### ISSUE TITLE
worksheet.getSheetValues all the first element is null

### ISSUE THREAD

**Issue by newghost** [exceljs/exceljs#100]
I make slightly change seems works fine:

exceljs\lib\doc\worksheet.js 

```
// return all rows as sparse array
getSheetValues: function() {
  var rows = [];
  this._rows.forEach(function(row) {
    rows[row.number - 1] = row.values;
  });
  return rows;
},
```

change to row.number - 1

exceljs\lib\doc\row.js

```
// return a sparse array of cell values
get values() {
  var values = [];
  _.each(this._cells, function (cell) {
    if (cell.type != Enums.ValueType.Null) {
      values[cell.col - 1] = cell.value;
    }
  });
  return values;
},
```

change to cell.col - 1

Since your row number and col number is start from 1.

**Comment by jacobopolavieja** [comment]
It seems this still happens? I receive an empty element in each row when calling row.values

Simple fix it seems... Would be nice to have it.

**Comment by termene7** [comment]
It s a bug from 2016, and nothing has been done about it?

**Comment by papandreou** [comment]
What's with the entitlement? If you're affected by this problem, and the fix is simple, why not submit a pull request with a regression test? That's the best way to get the attention of the maintainers.

**Comment by nathaliaspinula** [comment]
Hi there! I'm using exceljs@4.2.1 and I have the same issue. Here is my code:

`
await workbook.xlsx.load(buffer).then((wb) => {
      wb.eachSheet((sheet) => {
        sheet.eachRow((row, rowNumber) => {
          rows.push({ values: row.values });
        });
      });
    });
`

**Comment by aonamrata** [comment]
> Hi there! I'm using exceljs@4.2.1 and I have the same issue. Here is my code:
> 
> `await workbook.xlsx.load(buffer).then((wb) => { wb.eachSheet((sheet) => { sheet.eachRow((row, rowNumber) => { rows.push({ values: row.values }); }); }); });`
> 
> Did you find a solution?

From https://github.com/exceljs/exceljs/issues/698#issuecomment-453652089:

Hello @j0hnskot,
```
indexing in xlsx files starts from number 1 (eg. A1 point to row 1 and collumn 1)
setting null at the start is much easier than always recalculating from 0 based to 1 based indexing
```

**Comment by Tofandel** [comment]
You can always `.splice(0, 1)` the result, but yes given we get an array out of values and not an object, it's weird to get a null first element
