### ISSUE TITLE
Formula in R1C1 format

### ISSUE THREAD

**Issue by yashgt** [exceljs/exceljs#101]
Is there a way to make the generated XLSX file use R1C1 formulae instead of conventional formulae?

**Comment by Siemienik** [comment]
@yashgt 
```
Changing to R1C1 notation will not change the formulas. It will only change the view.
```
https://bettersolutions.com/excel/formulas/cell-references-a1-r1c1-notation.htm

 if you need use 'relative' mode to create file, the best way is counting addresses,
hack to map column number & row number to address is 
```
const addr1 = ws.getCell(colNo, rowNo).model.address
const addr2 = ws.getCell(colNo-3, rowNo).model.address
const formula = `${addr1}-${addr2}`
```
