### ISSUE TITLE
Problem exporting Excel with Angular in production 

### ISSUE THREAD

**Issue by ecaronPG** [exceljs/exceljs#1014]
Exprting data in Excel in developement environment work very well but in production silently error occur. This problem seem to be recurent from many version. Actually we are with ExcelJS version 3.1.0 We try ExcelJS 3.3.1 and we have the same problem. We can't rollback version to old version because we use fonctionnality contained in only new version. We expect correction soon. The problem seem to be with  **workbook.xlsx.writeBuffer()**.then

Thanks

**Comment by manuelblum** [comment]
Having the same problem here. Looks like the browser parameter in [package.json](https://github.com/exceljs/exceljs/blob/master/package.json) is wrong, or build/distribution configuration.  

**Problem:**
The [current package.json](https://github.com/exceljs/exceljs/blob/master/package.json#L19) points to `"browser": "./dist/exceljs.min.js",` but there is no such file in the distributed dist directory from version 3.4.0. 

<img width="226" alt="Screenshot 2019-11-27 at 10 13 05" src="https://user-images.githubusercontent.com/6098356/69709862-8823b300-10fe-11ea-9ea2-2eaeee17201f.png">

**Solution:**
I think this path should point to: `"browser": "./dist/exceljs.js",`


If i locally change this, and run a production build, i am able to get the `workbook.xlsx.writeBuffer()` work again

I already created a pull request #1038 

A temporary fix should be: change import to:
`import * as Excel from "exceljs/dist/exceljs.js";`

**Comment by Siemienik** [comment]
@manuelblum after update to `v3.5.0` is the issue still actual?

**Comment by guyonroche** [comment]
@ecaronPG , @manuelblum is there a nodejs script or an online page that exhibits this issue?
This might help getting to the bottom of the issue
