### ISSUE TITLE
Not happens by writeFile 

### ISSUE THREAD

**Issue by GELight** [exceljs/exceljs#1020]
Hi,

I try to use exceljs to manipulate an existing Excel file dynamically but I have a problem by writing a file. 
The problem is that nothing happens if I exec this code snippet from your documentation:
**... No file will be created ...**

```
let testPath = path.join(__dirname, 'test.xlsx');
let workbook = new Excel.Workbook();
workbook.xlsx.writeFile(testPath).then(() => {
    console.log('Written', testPath);
});
```

I hope you can give me a tipp what is wrong on my code example. :)

Best regards,
Mario

**Comment by b-asaf** [comment]
Hey @GELight,
I am encountering the same issue, How did you solved it?
I am getting `TypeError: T.createWriteStream is not a function` error.
My code is similar, I am writing in `ReactJS`:

```
import Excel from 'exceljs';

export default () => {
    const workbook = new Excel.Workbook();
    const worksheet = workbook.addWorksheet('My Sheet');

    worksheet.columns = [
        { header: 'Id', key: 'id', width: 10 },
        { header: 'Name', key: 'name', width: 32 },
        { header: 'D.O.B.', key: 'dob', width: 15 },
    ];

    worksheet.addRow({ id: 1, name: 'John Doe', dob: new Date(1970, 1, 1) });
    worksheet.addRow({ id: 2, name: 'Jane Doe', dob: new Date(1965, 1, 7) });

    // save under export.xlsx
    workbook.xlsx.writeFile('export.xlsx');
```

**Comment by GELight** [comment]
Hi @b-asaf ,

In my usecase I try to read multiple files from multiple directories.
Currently there is a problem in my recursion yet but anyway you can look at my code related your problem. 

**Write a new file is working so far. :)** 
Hope, I could help you.

Best regards,
Mario
