### ISSUE TITLE
合并单元格：找不到名称“expect”

### ISSUE THREAD

**Issue by jaling530** [exceljs/exceljs#1022]
egg ts 项目中
 const workbook = new Excel.Workbook();
const sheet = workbook.addWorksheet(fileName);
sheet.addRows(data);
想要合并单元格并保留所有值 sheet.mergeCells()满足不了，用以下方法报错：
expect(sheet.getCell('C2').value).toBe(sheet.getCell('C6').value);
提示：找不到名称“expect”

谢谢解答

**Comment by fghjfghj** [comment]
这里边的expect和toBe是单元测试框架的代码
你可以把这行删了
