### ISSUE TITLE
How do I merge cell with its' values ?

### ISSUE THREAD

**Issue by jaling530** [exceljs/exceljs#1023]
I used this way,
expect(worksheet.getCell('B5').value).toBe(worksheet.getCell('A4').value);
But it gived me tips 'don't have expect'.
Who can give me ways? Thank you

**Comment by Alanscut** [comment]
See [Merged Cells](https://github.com/exceljs/exceljs#merged-cells).

```
// merge a range of cells
worksheet.mergeCells('A4:B5');

// ... merged cells share the same style object
worksheet.getCell('B5').style.font = myFonts.arial;

// unmerging the cells breaks the style links
worksheet.unMergeCells('A4');

// merge by top-left, bottom-right
worksheet.mergeCells('G10', 'H11');
worksheet.mergeCells(10,11,12,13);  // top,left,bottom,right
```

**Comment by Siemienik** [comment]
after that
`worksheet.mergeCells('A4:B5');`

values from A5, B4, B5 will be removed, and all shape has a value from A4 (top-left corner).
If you need concat them You should do this before merging :)
