### ISSUE TITLE
Conditional formatting is lost after reading and writing

### ISSUE THREAD

**Issue by plynchnlm** [exceljs/exceljs#1024]
If I use workbook.xlsx.readFile to read in an Excel file that has conditional formatting rules, and then write the data back out with writeFile, the conditional formatting is not present in the newly written file.

**Comment by nerminator** [comment]
I have the same problem. 
After reading and writing the excel file, all the conditional formatting rules inside the excel file are cleared.

**Comment by Ola-Alkhateeb** [comment]
Same thing happens to me , Any updates on this issue?

**Comment by Siemienik** [comment]
https://github.com/exceljs/exceljs/issues/1057

**Comment by Alanscut** [comment]
@plynchnlm   Can you provide test code and versions used? I used the master branch to verify andAfter reading and writing the excel file, Did not clear conditional formatting rules in the excel file.

**Comment by gangadharingithub** [comment]
am also facing the same issue.  here is error whcih gets displayed while opening the XLSX file in windows. and supricingly it shows good in Mac.

`<?xml version="1.0" encoding="UTF-8" standalone="true"?>
​
-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
​
<logFileName>error166440_01.xml</logFileName>
​
<summary>Errors were detected in file 'C:\Users\lenovo\Downloads\worklog123.xlsx'</summary>
​
​
-<additionalInfo>
​
<info>Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.</info>
​
</additionalInfo>
​
​
-<removedParts summary="Following is a list of removed parts:">
​
<removedPart>Removed Part: /xl/styles.xml part with XML error. (Styles) Load error. Line 2, column 0.</removedPart>
​
</removedParts>
​
​
-<repairedRecords summary="Following is a list of repairs:">
​
<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet1.xml part</repairedRecord>`

**Comment by plynchnlm** [comment]
[cond_format.xlsx](https://github.com/exceljs/exceljs/files/4256900/cond_format.xlsx)

The attached test file shows the problem when the following is run on Windows:
```
node -e "const Excel = require('exceljs'); var workbook = new Excel.Workbook(); var data = workbook.xlsx.readFile('./cond_format.xlsx').then(()=>workbook.xlsx.writeFile('./test.xlsx').then(()=>console.log('Finished writing')))"
```

node version: v10.17.0
exceljs version: 3.3.1

**Comment by Alanscut** [comment]
@plynchnlm Thank you very much for providing relevant test code and files. In my verification, this problem does exist in version 3.3.1, but versions 3.5.0 and above work well, so it is recommended that you use the latest version 3.8.1.

@gangadharingithub Can you provide test code and versions used? This is very helpful for us to solve the problem.

**Comment by losper** [comment]
[cond_format.xlsx](https://github.com/exceljs/exceljs/files/4433109/cond_format.xlsx)

@Alanscut Hi,you can test this file.
An error occurs when opening the file
`node -e "const Excel = require('exceljs'); var workbook = new Excel.Workbook(); var data = workbook.xlsx.readFile('./cond_format.xlsx').then(()=>workbook.xlsx.writeFile('./test.xlsx').then(()=>console.log('Finished writing')))"`
node version: v12.16.1
exceljs version: 3.8.1

**Comment by plynchnlm** [comment]
I tried my test file I posted earlier with version 3.8.2, and it is working now.  Thank you!  (node version v10.17.0, Windows 10).
