### ISSUE TITLE
Identify cells are merge

### ISSUE THREAD

**Issue by soganideepak** [exceljs/exceljs#1025]
How we got the cells are merge and get the value of merge cell.

**Comment by Alanscut** [comment]
You can tell by the **`type`** and **`master`** fields.

```
ws.getCell('A2').value = 1;
ws.getCell('A3').value = 5;
ws.getCell('A4').value = 10;
ws.mergeCells('A3:A4');  // mergeCells
console.log('A2-Model', ws.getCell('A2').model); // A2-Model { address: 'A2', type: 2, value: 1, style: {} }
console.log('A4-Model', ws.getCell('A4').model); // A4-Model { address: 'A4', type: 1, master: 'A3', style: {} }
```


Get the value of a merged cell.

```
var mergeVal = ws.getCell('A4').value;
```

See  [cell.js](https://github.com/exceljs/exceljs/blob/master/lib/doc/cell.js#L666)  and   [enums.js](https://github.com/exceljs/exceljs/blob/master/lib/doc/enums.js#L6)
