### ISSUE TITLE
How to insert image FIT inside a cell ?

### ISSUE THREAD

**Issue by TranBaVinhSon** [exceljs/exceljs#1029]
Thanks for the great package. I want to insert image inside a cell. Currently, I'm using fixed width and height, but have no idea how to make image size fit inside a cell. How can I do that with `exceljs` ? Thanks in advance !
I want to 
```js
        const tmpWorkBook = new ExcelJS.Workbook();
        tmpWorkBook.xlsx.readFile(filePath)
            .then(function() {
              const worksheet = tmpWorkBook.getWorksheet("Sheet1");
              var imageID = tmpWorkBook.addImage({
                filename: imagePath,
                extension: 'png',
              });
              console.log("imageID", imageID);
              const relCol = cell.columnNumber() - 1;
              const relNum = cell.rowNumber() - 1;
              
              worksheet.addImage(imageID, {
                tl: { col: relCol, row: relNum },
                ext: { width: 100, height: 50 } // currently I'm using fixed width and height.
              });
              tmpWorkBook.xlsx.writeFile(outputPath);
            });
```

**Comment by TranBaVinhSon** [comment]
I noticed that I can insert image fit inside a range but wonder how I can do that with cell?
```js
worksheet.addImage(imageId2, 'B2:D6');
```

**Comment by Alanscut** [comment]
See the example of  [add image to a cell](https://github.com/exceljs/exceljs#add-image-to-a-cell).

```
worksheet.addImage(imageId2, {
  tl: { col: 0, row: 0 },
  ext: { width: 500, height: 200 }
});
```

**Comment by Alanscut** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
Best of luck.

**Comment by ibalaji777** [comment]
> See the example of [add image to a cell](https://github.com/exceljs/exceljs#add-image-to-a-cell).
> 
> ```
> worksheet.addImage(imageId2, {
>   tl: { col: 0, row: 0 },
>   ext: { width: 500, height: 200 }
> });
> ```

It doesn't  fit cell

**Comment by Knight-H** [comment]
Not sure if you still need this, but what I did was using the same `cellId` fits inside the cell. I think this works because the same cell is used for the top left (tl) and the bottom right (br). 

```typescript
sheet.addImage(imageId, `${cellId}:${cellId}`)
```

Example:
```typescript
sheet.addImage(imageId, `J13:J13`)
```

**Comment by elyohan14** [comment]
> Not sure if you still need this, but what I did was using the same `cellId` fits inside the cell. I think this works because the same cell is used for the top left (tl) and the bottom right (br).
> 
> ```ts
> sheet.addImage(imageId, `${cellId}:${cellId}`)
> ```
> 
> Example:
> 
> ```ts
> sheet.addImage(imageId, `J13:J13`)
> ```

Great, that is what I need! Thank you

**Comment by yogithesymbian** [comment]
how to fit but have margin ? because i have border of the row and make it gone when use fit ?

> > Not sure if you still need this, but what I did was using the same `cellId` fits inside the cell. I think this works because the same cell is used for the top left (tl) and the bottom right (br).
> > ```ts
> > sheet.addImage(imageId, `${cellId}:${cellId}`)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Example:
> > ```ts
> > sheet.addImage(imageId, `J13:J13`)
> > ```
> 
> Great, that is what I need! Thank you

how to fit but have margin ? because i have border of the row and make it gone when use fit ?

**Comment by IamMille** [comment]
> Not sure if you still need this, but what I did was using the same `cellId` fits inside the cell. I think this works because the same cell is used for the top left (tl) and the bottom right (br).
> 
> sheet.addImage(imageId, `${cellId}:${cellId}`)
> Example:
> 
> sheet.addImage(imageId, `J13:J13`)

Is this also supposed to anchor the image to the cell? 

My issue is still that upon sorting the rows, the images do not follow along with the sorting, unfortunately.

**Comment by Kombuchelada** [comment]
> > Not sure if you still need this, but what I did was using the same `cellId` fits inside the cell. I think this works because the same cell is used for the top left (tl) and the bottom right (br).
> > sheet.addImage(imageId, `${cellId}:${cellId}`)
> > Example:
> > sheet.addImage(imageId, `J13:J13`)
> 
> Is this also supposed to anchor the image to the cell?
> 
> My issue is still that upon sorting the rows, the images do not follow along with the sorting, unfortunately.

I think the issue here may be solved by exceljs adding in the ability to "Place in cell" as asked for in [this issue](https://github.com/exceljs/exceljs/discussions/2839)
