### ISSUE TITLE
Unable to get argb value from theme attribute

### ISSUE THREAD

**Issue by jclsn** [exceljs/exceljs#1035]
Is there a way to get the argb value from a color that was selected by using the standard palette? If I choose the color by using "custom color" in Excel, I can get the argb value, but not if it was chosen from the standard colors. It would be convenient, if a function to get this value existed!

**Comment by dwanda** [comment]
I have the same issue.. Hope this function will be added

**Comment by dwanda** [comment]
I find out that the theme was saved in workbook->_themes. Its format is xml. when I translate xml to json . I got two attributes format from different theme Setting . I didn't figure out why.

Here are the different attributes format
`
            <a:dk1>
                <a:sysClr val="windowText" lastClr="000000" />
            </a:dk1>
            <a:lt1>
                <a:sysClr val="window" lastClr="FFFFFF" />
            </a:lt1>
            <a:dk2>
`

`
            <a:dk1>
                <a:srgbClr val="2F2B20" />
            </a:dk1>
            <a:lt1>
                <a:srgbClr val="FFFFFF" />
            </a:lt1>
            <a:dk2>
`

**Comment by dwanda** [comment]
你好~我是宇达，已经收到你的来信啦。
