### ISSUE TITLE
horizontalCentered & verticalCentered in page not working

### ISSUE THREAD

**Issue by tinhnqjp** [exceljs/exceljs#1045]
Hi all, plz help me

**Template file:**
![image](https://user-images.githubusercontent.com/34364630/70420419-0bec8080-1aab-11ea-9e5e-c96268b91f32.png)
Center on page: 

- horizontally : Checked
- vertically : Checked

**Source coder:**

```
worksheet.pageSetup.horizontalCentered = true 
worksheet.pageSetup.verticalCentered = true
```

**File output:**
- horizontal : uncheck
- vertical : uncheck

![image](https://user-images.githubusercontent.com/34364630/70420596-6980cd00-1aab-11ea-8b30-7933fb9016b3.png)

**Comment by LiaoZhiyong** [comment]
worksheet-xform.js
line: 216
const printOptionsModel = {
      showRowColHeaders: model.pageSetup.showRowColHeaders,
      showGridLines: model.pageSetup.showGridLines,
      horizontalCentered: model.pageSetup.horizontalCentered,
      verticalCentered: model.pageSetup.verticalCentered,
    };

line: 238
this.map.printOptions.render(xmlStream, printOptionsModel);
this.map.pageMargins.render(xmlStream, pageMarginsModel);

**Comment by Siemienik** [comment]
I will be glad for pull request with fixation 😸
