### ISSUE TITLE
Save as CSV with UTF-16 format ?

### ISSUE THREAD

**Issue by energizer92** [exceljs/exceljs#1046]
Hi there,

i try to save a workbook as csv using [Filesaver](https://github.com/eligrey/FileSaver.js/) to provide a download. But the saved csv is Utf-8 and i want it to be Utf-16. Can someone help?

Here is some Code:
````
async function provideCsvDownload(workbook, title){
	// console.log("Building CSV...");
	const buf = await
	workbook.csv.writeBuffer();

	// console.log("Provide CSV Download...");
	saveAs(new Blob([ buf ]), title + '.csv');
}

**Comment by papandreou** [comment]
Try something like [iconv-lite](https://www.npmjs.com/package/iconv-lite) to convert it?

**Comment by energizer92** [comment]
Hmm ok, i thought there would be an option like
workbook.csv.writeBuffer({type: 'text/csv;charset=utf-16'});
