### ISSUE TITLE
file does not downloading in production

### ISSUE THREAD

**Issue by Abdykapar** [exceljs/exceljs#1051]
const wb = new ExcelJS.Workbook()

                const ws = wb.addWorksheet()

                const row = ws.addRow(['a', 'b', 'c'])
                row.font = { bold: true }

                wb.xlsx.writeBuffer()
                    .then(function(buffer) {
                        var blob=new Blob([buffer], {type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
                        var link = document.createElement('a');
                        link.href = window.URL.createObjectURL(blob);
                        var fileName = "test.xlsx";
                        link.download = fileName;
                        link.click();
                    });
i use vuejs, in localhost works fine, but in prod does not

**Comment by fghjfghj** [comment]
i use "file-saver" to download file
