### ISSUE TITLE
CSV with dateformats will fail because of dayjs

### ISSUE THREAD

**Issue by reyramos** [exceljs/exceljs#1059]
Pull Request 
	https://github.com/iamkun/dayjs/pull/756

has been submitted to correct the issue with dayjs

If match is null, match[0] will throw an exception error

**Comment by Siemienik** [comment]
@guyonroche should we do something here?

**Comment by reyramos** [comment]
No, this is just informational. I submitted a PR request for the fix on dayjs library that is causing the error.

**Comment by reyramos** [comment]
Closing will submit a PR when I solve the issue. The problem exist on CSV reader, where if a date string is a pass, it throws an exemption.
