### ISSUE TITLE
Excel complains about generated file being corrupt

### ISSUE THREAD

**Issue by AlexGustafsson** [exceljs/exceljs#1068]
When I try to open a file created by the package in Excel, it complains about it being corrupt and prompts me to ask if I want to repair it. The reperation always works and the document works as intended.

The code used to generate the document can be seen here: https://github.com/AlexGustafsson/timekeep/blob/master/src/utils/excel.js

An example file generated by the code can be found here:
[timekeep.xlsx](https://github.com/exceljs/exceljs/files/4042160/timekeep.xlsx)

**Comment by Siemienik** [comment]
@AlexGustafsson yes, that right, sometimes I had this bug too. 

https://github.com/exceljs/exceljs/issues/732
https://github.com/exceljs/exceljs/issues/745
#35 
https://github.com/exceljs/exceljs/issues/106
https://github.com/exceljs/exceljs/issues/739

If I have a good memory, the solution has been setting `model.result` in cells with a formula

**Comment by AlexGustafsson** [comment]
"Solved" by moving to https://www.npmjs.com/package/xlsx-populate which worked great right of the bat.

**Comment by Serj-M** [comment]
I solved the problem. Hope this helps you.
If you download this excel file from the server side (In my case Node JS). 
The problem is solved by one line on the client side:  **req.responseType = "arraybuffer";**

```
requestData(req, "exportToExcel")
            .then(resXHR => {
                // For the correct processing of data from the server, you must specify the format/structure of data transfer
                resXHR.responseType = "arraybuffer"
                // Wait until the data is downloaded from the server
                resXHR.onload = function () {
                    // Call a modal window for saving with type and file name 
                    saveAs(new Blob([resXHR.response], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), 'users.xlsx')
                }
            })
```

**Comment by Jigna-Rathod** [comment]
@Siemienik Could you please elaborate:what exactly to do in  by setting `model.result` in cells with a formula

**Comment by Siemienik** [comment]
> @Siemienik Could you please elaborate:what exactly to do in by setting model.result in cells with a formula

@Jigna-Rathod 
When a formula causes file corruption, the best workaround is set for this formula `result` to undefined, which tells Excel to recalculate the formula result.

However, there may be more reasons. So If your case makes the file is corrupt, please create a new issue ( or discussion ) and obviously attach code and, if possible, the output xlsx. I can't respond to all issues, so please tag me by using `@siemienik` there. Additionally, I might be caught on [Gitter](https://gitter.im/Siemienik) or mail hi@siemienik.pl .
