### ISSUE TITLE
What's meaning of tint in color attribute?

### ISSUE THREAD

**Issue by dwanda** [exceljs/exceljs#1070]
When I read color attribute from xlsx files，it has tint and theme attribute，I figure out that theme is the _theme xml read from xlsx，but tint still makes me feeling confuesd

**Comment by dwanda** [comment]
Oh I have found the solution。

**Comment by Siemienik** [comment]
what was that?

**Comment by lsby** [comment]
![111](https://github.com/lsby/tuchuang1/blob/master/2020%E5%B9%B42%E6%9C%8827%E6%97%A5125355.png?raw=true)
