### ISSUE TITLE
Add multiple rows to Sheet at once using key-value paired not working

### ISSUE THREAD

**Issue by euniceolaires** [exceljs/exceljs#1072]
Did a workbook and wrote an xlsx file using stream. Opened the download xlsx file and seen no values. I think adding array of objects (key-value paired) in (worksheet.addRows) currently not working.

// Add an array of rows
var rows = [
    [5,'Bob',new Date()], // row by array // WORKING
    {id:6, name: 'Barbara', dob: new Date()} // NOT WORKING
];
worksheet.addRows(rows);

**Comment by Siemienik** [comment]
Did you set columns? 
https://github.com/exceljs/exceljs#columns
