### ISSUE TITLE
Unable to read/write defaultColWidth attribute in <sheetFormatPr> node

### ISSUE THREAD

**Issue by kigh-ota** [exceljs/exceljs#1075]
`defaultColWidth` attribute can exist in `<sheetFormatPr>` node in worksheet.xml ([Link](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.sheetformatproperties?view=openxml-2.8.1)), but the library cannot read nor write this attribute.
As a result, for example, some column widths in an imported xlsx file can be unexpectedly altered after exporting.

**Comment by kigh-ota** [comment]
I opened a PR https://github.com/exceljs/exceljs/pull/1076 to fix this.
However, most of tests currently fail for some reason that I'm not sure.

**Comment by Siemienik** [comment]
@kigh-ota could You resolve problems during tests?
