### ISSUE TITLE
foreground and background when used at the same time not being respected

### ISSUE THREAD

**Issue by ras-miglesias** [exceljs/exceljs#1081]
First thanks for this package (and all contributors!). Its great and has gotten me out of a bind for the most part.

I am on the tail end of styling improvements and I can't figure out why if I want white text on a dark background its not giving me it.

No idea if I am doing something obviously wrong or what but the foreground/background colors appear to be either flipped or something else is going on I am not understanding. I see that fgColor appears to be required in the interface and bgColor is optional.

As an example, this should produce a cell with yellow text on a red solid background but i am seeing yellow cell with black text.
```
// Create workbook and worksheet
        const workbook = new Workbook()
        const worksheet = workbook.addWorksheet('SheetNameTest', {pageSetup:{paperSize: undefined, fitToPage: true, orientation:'landscape'}, views: [{ activeCell: 'A50', showGridLines: false }] })

        worksheet.addRow(['test'])
        worksheet.getCell('A1').fill = {
            type: 'pattern',
            pattern:'solid',
            fgColor:{argb:'FFFFFF00'},
            bgColor:{argb:'FFFF0000'}
        }
```

Any help addressing this or confirming if something is off would be appreciated thanks!

**Comment by Siemienik** [comment]
please use `font` property:
```javascript
worksheet.getCell('A1').font={color:XYZ}
```

more info here :)
https://github.com/exceljs/exceljs#fonts
