### ISSUE TITLE
Can not find namespace 'Nodejs'

### ISSUE THREAD

**Issue by sumit9664** [exceljs/exceljs#1085]
I am getting below error while "ng build" for Angular 7.

Can not find namespace 'Nodejs', i found this reference in index.ts ( Nodejs.TypeArray ).

I investigate this issue then i came to know that Exceljs internally using Node version more than 10 but angular has 7 has lower Node version 8.0.*
So, that cause to failure and I tried multiple solution but that didn't work for me.

Can you just check and update the package with angular 7 compatibility or suggest me the best way.

For now, i have just removed the reference of NodeJs.TypeArray from index.ts as temporary solution.

Note : Also i tried lower version 2.0 but it has also higher version of node as compare to angular 7.

**Comment by WonderfulOlanrewaju** [comment]
Try to use a much lower version like 1.0.1

**Comment by Alanscut** [comment]
Hi @sumit9664 
1. See #1191, Hope that can help you.
2.  Please look for help in [stackoverflow](https://stackoverflow.com).

**Comment by Alanscut** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
Best of luck.
