### ISSUE TITLE
Can you provide a bower component of the module.

### ISSUE THREAD

**Issue by SoniyaLadhani** [exceljs/exceljs#109]
Hi Team,
I tried to include the module in angular but was unable as i am facing issues while initializing the Excel variable in angular.Can you please provide the link of the bower component of the library or any documentation link in which the module is used with AngularJs.

**Comment by alabaki** [comment]
I am interested in a bower package too. @SoniyaLadhani any luck getting it to work with angular?

**Comment by michelmeeuwissen** [comment]
@alabaki  Did you found a solution to use Exceljs with Bower?

**Comment by yasinrose** [comment]
exceljs needs to be fixed to run in the browser before bower can support it.  See https://github.com/guyonroche/exceljs/issues/31
