### ISSUE TITLE
Won't recalculate formulas after duplicate rows.

### ISSUE THREAD

**Issue by richard07250** [exceljs/exceljs#1094]
Hi,

I am trying to duplicate rows that contain a cell with value like
`{ formula: 'ROW()-ROW($A$10)+1', result: 4 }`
using new duplicateRows function. 

And the result won't be recalculate after duplicated, seems like there's no other way to tell cells to recalculate them self, so i need to do something like:
`cell.value = { formula: cell.value.formula }`
to force the recalculate.

Is there any better way to approach this kind of use case?

**Comment by richard07250** [comment]
Maybe a extend issue for #24 ?

**Comment by Siemienik** [comment]
You should set result=undefined to force recalculate in Excel (after open file)

**Comment by Siemienik** [comment]
here we show the solution: :)
https://github.com/exceljs/exceljs/issues/230#issuecomment-455430539

another one:
https://github.com/exceljs/exceljs/issues/246
