### ISSUE TITLE
I want to split value in a column to multiple column

### ISSUE THREAD

**Issue by WonderfulOlanrewaju** [exceljs/exceljs#1096]
I have an excel sheet generated within my application, I need to split one of it's columns into 6columns unequal column in terms of width. There is no method for doing such in  yout application

**Comment by Siemienik** [comment]
There is no feature like this, but it's doesn't mean that is impossible :)

please use `worksheet.eachRow`

and later `row.values = row.getCell(1)split(";")`

it should work fine I think :)

docs:
https://github.com/exceljs/exceljs#rows

**Comment by WonderfulOlanrewaju** [comment]
Thank you @Siemienik  It is true that there is no such feature, your answer has given me an idea, I want to create a function that takes the cell value and the indexes at which I want to break it. Then returns an array of the broken strings which I can use on the inserted new column. 

something like this

```javascript
const splitStringAtIndex = (string, index) => {
    return [string.substring(0, index) , string.substring(index)]
}
```
