### ISSUE TITLE
add height property when duplicate line

### ISSUE THREAD

**Issue by anterta** [exceljs/exceljs#1101]
when you duplicate line the height property is forgotten. 

In function duplicateRow and in spliceRows
```
          rDst.style = rSrc.style;
+        rDst.height = rSrc.height;
```

**Comment by Siemienik** [comment]
@anterta Could I please you to make a pull request with fix?

**Comment by cbeltrangomez84** [comment]
Thanks @anterta. 

@Siemienik I just made the pull request with fix and new tests

**Comment by Siemienik** [comment]
@cbeltrangomez84 thank you :)
