### ISSUE TITLE
Null value results "Out of bounds. Excel supports columns from 1 to 16384"

### ISSUE THREAD

**Issue by jozsi** [exceljs/exceljs#111]
Hello,

If the first value in the pushed row is `null` or `undefined`, it throws the error `Out of bounds. Excel supports columns from 1 to 16384`:

``` javascript
// Fails
sheet.addRow([null, 'hello', 123]);
sheet.addRow([undefined, 'hello', 123]);

// Works
sheet.addRow(['', 'hello', 123]);
sheet.addRow(['hello', null, 123]);
```

I guess I should use `null` instead of an empty string for empty cells.

**Comment by barbalex** [comment]
yep, same happens to me
when I return `''` instead of `null` everything works fine
@jozsi thanks for finding the reason, I don't think I could have isolated it

**Comment by Alanscut** [comment]
This issue is fixed, I use the code from the master branch to verification and it works fine.

**Comment by Alanscut** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
Best of luck.
