### ISSUE TITLE
Release history not up-to-date

### ISSUE THREAD

**Issue by Tilogorn** [exceljs/exceljs#1111]
`npm update` offers excel.js `3.7.0`, but the release history in your [README](https://github.com/exceljs/exceljs#release-history) stops at `3.6.1`. Would you mind updating it? I really like it for getting information about breaking changes and new features.

**Comment by Siemienik** [comment]
https://github.com/exceljs/exceljs/compare/v3.6.1...v3.7.0

**Comment by Siemienik** [comment]
or, what new in next version: https://github.com/exceljs/exceljs/compare/v3.7.0...master
