### ISSUE TITLE
How to retrieve data from a pivot table?

### ISSUE THREAD

**Issue by samaslima** [exceljs/exceljs#1116]
I want to get the data from a database and export to excel, is there any way?

**Comment by Siemienik** [comment]
@samaslima that's quite simple:) I have 2 ways to do that:

1. The simplest way to get excel with data without any styles: 
```javascript
worksheet.columns = [
  { header: 'Id', key: 'id', width: 10 },
  { header: 'Name', key: 'name', width: 32 },
  { header: 'D.O.B.', key: 'DOB', width: 10, outlineLevel: 1 }
];

data.forEach(function(e){worksheet.addRow(e);});
```

2. More complex, with styles by using BETA version of my library (based on exceljs): https://github.com/Siemienik/xlsx-renderer/
```javascript
import Renderer from 'xls-renderer/lib/xls-renderer/Renderer';
import CellTemplatePool from 'xls-renderer/lib/xls-renderer/CellTemplatePool';
import {Workbook} from 'exceljs'

   const renderer = new Renderer(new CellTemplatePool()); 
 
    const data = itemService.getAll()

    const result = await renderer.render(async () => {
            const template = new Workbook();
            return await template.xlsx.readFile('./my-awesome-raport-template.xlsx');
        }, data);     
    
    await result.xlsx.writeFile('./my-awesome-raport.xlsx');
```

this solution get your template `my-awesome-raport-template.xlsx` what was made in excel, and render output based on them.

For example this template file:
![image](https://user-images.githubusercontent.com/2893099/74429118-9dd18a80-4e5a-11ea-8036-f90b96a2bda9.png)


gives:
![image](https://user-images.githubusercontent.com/2893099/74428769-f05e7700-4e59-11ea-877f-156a7f338eaa.png)
