### ISSUE TITLE
Content-Length from xlsx stream

### ISSUE THREAD

**Issue by dlcrista** [exceljs/exceljs#1117]
I'm planning to use exceljs to run a SQL query and stream it into excel for webusers to download it. These sql queries are going to be very large and cannot be kept in memory, hence why I am achieving this with streaming. 

How can I determine what the header **Content-Length** is? If I don't set this header, then I can't see the progress spinner during the download from my browser.

Here's a sample:
```javascript
app.get('/some/route', function(req, res) {
  res.writeHead(200, {
    'Content-Disposition': 'attachment; filename="file.xlsx"',
    'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    "Content-Length" : inf //this is what I want!!
  })
  var workbook = new Excel.stream.xlsx.WorkbookWriter({ stream: res })
  var worksheet = workbook.addWorksheet('some-worksheet')
  worksheet.addRow(['foo', 'bar']).commit()
  worksheet.commit()
  workbook.commit()
}
```

**Comment by Siemienik** [comment]
could you write it into temp file and send it after the rendering has been finished? It's maybe quite useful with cache system :)

**Comment by dlcrista** [comment]
I would like to do something like fs.createWriteStream("...") but I don't want to create files since I'll have to delete them after. Is there something where I can do this without creating a file?

**Comment by Siemienik** [comment]
there is no possibility to get the size of a stream before it has been rendered.

> When no Content-Length is received, the client keeps reading until the server closes the connection

 so your code should work without `content-length`

**Comment by yogithesymbian** [comment]
> [Crdzbird/flowder#2](https://github.com/Crdzbird/flowder/issues/2)
> i have issue with third package "flowder" downloader in flutter neede content-length .

solved 
```
    res.setHeader(
      "Content-Length",
      `${worksheet.toString().length}` + ""
    );
```
