### ISSUE TITLE
[BUG] Typescript error from getColumn.eachCell

### ISSUE THREAD

**Issue by weelillad** [exceljs/exceljs#1120]
## 🐛 Bug Report

Typescript error when using `Worksheet.getColumn().eachCell` - `TS2722: Cannot invoke an object which is possibly 'undefined'.`

Lib version: 3.8.0

## Steps To Reproduce

Code example

```javascript
const wb = new ExcelJS.Workbook();
const ws = wb.addWorksheet('XYZ');
...
ws.getColumn(1).eachCell((cell, rowNum) => {
  cell.fill = headerFill;
});
```

## The expected behaviour:

There should be no error.

## Possible solution (optional, but very helpful):

Is it possible to clearly define the functions and properties that are available from `getColumn`?

**Comment by Siemienik** [comment]
you have `.` before `(`

could you try do like below?:
```javascript
ws.getColumn(1).eachCell((cell, rowNum) => {
  cell.fill = headerFill;
});
```

**Comment by weelillad** [comment]
Sorry, there was a typo when copying the code. I checked and my code is like what you posted, and the TS error still shows. I have edited my original post to fix my code snippet.

**Comment by MetaMmodern** [comment]
Sorry, is this in latest version of your library? Cause I currently have the same problem.
@alubbe and @Siemienik do you have info about it?

Here is the code where I get error:
```typescript
const setColumnWidthForSheet = (ws: Worksheet) => {
	for (let i = 0; i < ws.columns.length; i++) {
		const column = ws.columns[i];
		let dataMax = 0;
		if (!column) {
			continue;
		} else {
			column.eachCell({ includeEmpty: true }, (cell) => {
				let columnLength = 0;
				if (cell.value instanceof Date) {
					columnLength = cell.value
						.toISOString()
						.slice(0, 10)
						.replace(/-/g, '.').length;
				} else {
					columnLength = String(cell.value).length;
				}
				if (columnLength > dataMax) {
					dataMax = columnLength;
				}
			});
			column.width = dataMax < 10 ? 15 : dataMax + 8;
		}
	}
};
```
And the error:
![image](https://user-images.githubusercontent.com/42899786/122118928-4d44b580-ce31-11eb-95af-d9d4c8172c7e.png)

**Comment by nywleswoey** [comment]
@MetaMmodern  `ws.columns[i]` return the type of `Partial<Column>` which just means that the properties are not guaranteed to be there. `!column` doesn't help since the object is present so it'll still return true.

You can try to use `ws.getColumn(i)` instead, which would return the `Column` type.

**Comment by MetaMmodern** [comment]
> @MetaMmodern  `ws.columns[i]` return the type of `Partial<Column>` which just means that the properties are not guaranteed to be there. `!column` doesn't help since the object is present so it'll still return true.
> 
> You can try to use `ws.getColumn(i)` instead, which would return the `Column` type.

Ok, thank you, I'm gonna try it later.

**Comment by MetaMmodern** [comment]
@nywleswoey Sorry, the thing you provided does not work in runtime. The types are somehow broken.
I've changed as you said to `getColumn(i)` but here what I het after that:
![image](https://user-images.githubusercontent.com/42899786/122191817-bb25c700-ce9b-11eb-8021-edc610e94271.png)

**Comment by nywleswoey** [comment]
@MetaMmodern column number starts from 1. From your above code you will try to access column 0.

**Comment by MetaMmodern** [comment]
> @MetaMmodern column number starts from 1. From your above code you will try to access column 0.

Oopsie, my bad😅
Thanks again

**Comment by nywleswoey** [comment]
No problem, glad to have been of help to you.
