### ISSUE TITLE
Can I fill the color to all columns

### ISSUE THREAD

**Issue by jaesungbong** [exceljs/exceljs#1123]
now I can only color cells with data. 

by using this

`WorkSheet.getRow().eachCell() or WorkSheet.getColumn().eachCell()`

```
cell.fill = {
    type: 'pattern',
    pattern: 'darkVertical',
    fgColor: { argb: 'FFFFFF00' },
    bgColor: { argb: 'FFFFFF00' }
}
```

but I want to color all columns

how can I do like this

![ex](https://user-images.githubusercontent.com/18666144/74392143-8a69f380-4e49-11ea-9ed8-d2ea650fe5fd.PNG)

**Comment by Alanscut** [comment]
please try:
```javascript
// fill a column
worksheet.getColumn('A').fill = {
  type: 'pattern',
  pattern: 'darkVertical',
  fgColor: {argb: 'FFFFFF00'},
  bgColor: {argb: 'FFFFFF00'},
};

// fill a row
worksheet.getRow('1').fill = {}
```
