### ISSUE TITLE
Dates are not recognized

### ISSUE THREAD

**Issue by raaymax** [exceljs/exceljs#113]
I created xlsx file in LibreOffice Calc but I cannot make dates work.
I'm setting rows formatting as Date -> YYYY-MM-DD
When I parse file I'm still getting raw numeric value.

When I generate file by exceljs and then load it everything works ok. I can even edit rows in file in LibreOffice but I cannot add new rows. New rows are parsed as numbers.

Is it possible to hardcode or define types of columns in code?

Edit:
Sometimes text columns are parsed as dates. result: Invalid Date.

**Comment by bayareahank** [comment]
I ran into similar issue that exceljs couldn't read Date types correctly from xslx file. Did some research and found out Excel's 1904 Date issue. So exceljs must simply read the raw value inside Dates type and turn that into a Date directly, which is incorrect. I did some more research and found the package xlsx, which can read date formats correctly, in Json, Csv and etc. formats. Would suggest you give it a try.

**Comment by jayflo** [comment]
This might be fixed in 2.11

**Comment by jayflo** [comment]
This is not fixed in 2.11... there are still times when dates are parsed as `Number` rather than `Date` and changing the structure of the workbook/worksheet can effect how the value is read.  I am trying to find out why this issue is happening in the code, but it is bit difficult to follow...

**Comment by lillyluminatus** [comment]
Excel usually stores dates as number dates.  Can you get the date if it's stored as a number?

**Comment by jayflo** [comment]
I made a PR here https://github.com/guyonroche/exceljs/pull/166 to fix along with an explanation.  May not be a complete solution and I can see this same kind of bug creeping up elsewhere.

**Comment by mouse9** [comment]
@Siemienik I faced this issue today,
DD/MM/YYYY form is not parsing properly and getting converted to raw string,
In the latest version can you help me with that?

**Comment by shivasrini** [comment]
I am having the same issue that @mouse9 mentioned

**Comment by mouse9** [comment]
@shivasrini https://github.com/exceljs/exceljs/pull/1328 I have created the PR for the same

**Comment by Siemienik** [comment]
Pr was merged, please wait for next release

**Comment by SangoYu** [comment]
Has it been fixed? I am still getting  raw numeric value when I read a date type value in version 4.11.1
