### ISSUE TITLE
How read a csv file take the first line as column header

### ISSUE THREAD

**Issue by Diluka** [exceljs/exceljs#1130]
Lib ver: 3.5.0

example file:
```csv
header1,header2
aaaa,bbbb
```

How read a csv file take the first line as column header

And make `row.getCell('header1').value` working

**Comment by Siemienik** [comment]
for similar purposes I implemented `xlsx-import` for you should work: (this is typescript, but it's works as well with js)

1. install package
`npm i xlsx-import --save`

2. type definition
```typescript

interface MyData{
    Header1: string;
    Header2: string;
}

```

3. import csv and data
```typescript
const workbook = new Excel.Workbook();
const ws = await workbook.csv.readFile(filename);
ws.name = "csv";

const importer = new Importer(workbook);
const data= importer.GetAllItems<MyData>( {
  type: 'list',
  worksheet: 'csv',
  columns: [
    { index: 1,  key: 'Header1' },
    { index: 2,  key: 'Header2' },
  ],
   rowOffset: 1, //offset header row
 }); 

console.log(data[0].header1);
```

**Comment by Diluka** [comment]
It's still depending on the `index`. If removed one or more rows in xlsx file, the program will not work.

**Comment by Siemienik** [comment]
@Diluka could I ask you for more explanation? I don't understand what is the problem.

**Comment by Diluka** [comment]
@Siemienik sorry, i mean no matter the index of `header1` is, i want to get its value by name

for example i want to both file works with the same code
```csv
header1,header2
aaaa,bbbb
```
```csv
header2,header1
bbbb,aaaa
```
