### ISSUE TITLE
headerFooter property doesn't work with WorksheetWriter

### ISSUE THREAD

**Issue by asivov** [exceljs/exceljs#1131]
Hi dear team,
I'm using the 3.8.0 version of exceljs and when I'm trying to set the headerFooter property for WorksheetWriter, it doesn't work. So it works perfectly when we are using Worksheet, but doesn't work for streams. I've investigated the code and found that there is no HeaderFooterXform using in WorksheetWriter.
I already prepared the fix for this issue. Could you be so kind to give me permissions to prepare the pull request with fix.

**Comment by Siemienik** [comment]
Hi @asivov , it's nice to read that you prepare fixation:smile: 
if could you, please fork this repo and later make there fix for this issue.
The last step will be to create a pull request, which we will merge after code review was done.
