### ISSUE TITLE
Get Row by value of column key

### ISSUE THREAD

**Issue by WonderfulOlanrewaju** [exceljs/exceljs#1132]
I am looking for a method to extract a row from my sheet where the column key/name has a particular value, I have read around the documentation haven't seen any method for accomplishing that.

1 | Age | Name | Class | Height
--|------|--------|-------|--------|
2 | 20  | Korede | Form 2 | 170
3 | 23  | Tayo | Form 2 | 180
4 | 23  | Titi | Form 1 | 183

Let's say I have my excel sheet in the format above, how do I get the row where the Age name is Tayo without hardcoding the row number and using the value of the name column index.

**Comment by Siemienik** [comment]
similar topic what I answered here:
https://github.com/exceljs/exceljs/issues/1130#issuecomment-587428831

ofc. You may use `ws.getColumn('name').getCell(1)`

**Comment by WonderfulOlanrewaju** [comment]
Thanks.

**Comment by consatan** [comment]
> similar topic what I answered here: [#1130 (comment)](https://github.com/exceljs/exceljs/issues/1130#issuecomment-587428831)
> 
> ofc. You may use `ws.getColumn('name').values[2]`

@Siemienik  not working on csv file
