### ISSUE TITLE
[BUG] 3.8.0 -- Breaking template border formatting

### ISSUE THREAD

**Issue by JLuboff** [exceljs/exceljs#1149]
## 🐛 Bug Report
After upgrading to 3.8.0, the formatting from within my template file is altered by exceljs, that is, borders that are part of the template are either cut off or missing all together.
[Outputted file (missing/broken borders)](https://github.com/exceljs/exceljs/files/4264781/output.xlsx)
Lib version: 3.8.0

## Steps To Reproduce

Use the following file [Template.xlsx](https://github.com/exceljs/exceljs/files/4264780/Template.xlsx) along with provided code.
```javascript
const Excel = require('exceljs');
const CreateExcel = async () => {
  const templateToUse = 'Template.xlsx';
  // ////////////////////////////////////////
  // Read template file and clone sheet to new sheet
  // ///////////////////////////////////////
  let templateWorkbook = new Excel.Workbook();
  templateWorkbook = await templateWorkbook.xlsx.readFile(templateToUse);
  const sheetToCopy = templateWorkbook.getWorksheet('template');
  const targetSheet = templateWorkbook.addWorksheet('temp');
  targetSheet.model = Object.assign(sheetToCopy.model, {
    mergeCells: sheetToCopy.model.merges
  });
  templateWorkbook.removeWorksheet(sheetToCopy.id);

  await templateWorkbook.xlsx.writeFile(`output.xlsx`);
};

CreateExcel();

```

## The expected behaviour:
I would expect for the output file to look the same as the input template file.

## Possible solution (optional, but very helpful):
Currently I have downgraded to 3.7.0, which works as expected

**Comment by TranBaVinhSon** [comment]
@JLuboff I have exactly same problem with 3.4.0 version but it works well with 3.8.0 version. 
But 3.8.0 has a problem with `Shape` and `Textbox` https://github.com/exceljs/exceljs/issues/1147
