### ISSUE TITLE
[Q] HOW TO REMOVE AUTO SET PRINT AREA ?

### ISSUE THREAD

**Issue by benamrou** [exceljs/exceljs#1151]
## 💬 HOW TO REMOVE AUTO SET PRINT AREA ?

With the actual API we can set the print area by adjusting the printArea properties in the Page Setup.
`ws.pageSetup.printArea='A1:L57'`

Additionally, we can add page Break by row to split the printing.
`ws.getRow(rowBreak).addPageBreak();`

I am getting my two print areas. Question is how to readjust the "Auto" set Print area (dotted area).

**Comment by Siemienik** [comment]
Lack of activity, I have to close it. 
For making new question, please use GH Discussion category Q&A: https://github.com/exceljs/exceljs/discussions/categories/q-a
