### ISSUE TITLE
[Q] How to remove cell comments

### ISSUE THREAD

**Issue by Komojo7** [exceljs/exceljs#1153]
I've added a comment to a cell as follows:

```
ws.getCell('A1').note = {
    texts: [
        {
            text: 'some comment',
        },
    ],
};
```

I'm then trying to completely remove the comment afterwards, but i couldn't see any obvious way to do this.

**Comment by Siemienik** [comment]
check this: https://github.com/exceljs/exceljs#cell-comments

**Comment by Siemienik** [comment]
ws.getCell('A1').note = {};

should works;

**Comment by dolbyzerr** [comment]
Seems that `ws.getCell('A1').note = {}` doesn't remove the note. It is still there but just empty, which results in having an empty note in the xlsx file.

The only workaround I found so far is
```
ws.getCell('A1')._comment = undefined
```
