### ISSUE TITLE
[Q] Get width/height of a Cell

### ISSUE THREAD

**Issue by TranBaVinhSon** [exceljs/exceljs#1156]
## 💬 Questions and Help

Is there any ways that I can get `width/height` of a cell by `exceljs` ?
For example
```js
const width = cell.width();
const height = cell.height();
```
I tried access width/height of cell through fullAddress but it always returrn undefined
```js
const width = cell.fullAddress.col.width; // undefined
const height = cell.fullAddress.row.height; // undefined
```
Any help is welcome !

**Comment by Alanscut** [comment]
@TranBaVinhSon `width` property is in `Column` and `height` property is in `Row`, get them by:
```
let width = worksheet.getRow(1).height;
let height = worksheet.getColumn(1).width;
```
but when you don't set `width` and `height` value manually, then the value is undefined.

**Comment by Siemienik** [comment]
`cell.fullAddress.col` is a string `.row` too
to get a Column please use @Alanscut`s instructions :)

**Comment by TranBaVinhSon** [comment]
> but when you don't set width and height value manually, then the value is undefined.

But when I open the excel file, the value isn't `undefined` ? 
I think it was default width and height.

**Comment by Siemienik** [comment]
Lack of activity, close
