### ISSUE TITLE
[BUG] Cannot set property 'marked' of undefined

### ISSUE THREAD

**Issue by cooperbrown9** [exceljs/exceljs#1157]
## 🐛 Bug Report

This error can be found at this path
`exceljs/lib/xlsx/xform/sheet/data-validations-xform.js:75:42`

It happens whenever I try to create a sheet. However, it doesn't seem too important because simply wrapping a try/catch around it fixes the problem. Literally, just wrapping it in try/catch works. But what gives? Has anyone else gotten this behavior?

           ```
            try {
             // originally, there is no try catch, just the line below
             // 
              dvMap[otherAddress].marked = true;  
            } catch(e) {
              console.log('cant set undefined marked blah blah', e)
            }
```

**Comment by Alanscut** [comment]
@cooperbrown9   I used the code from the master branch and didn't find the problem. Can you conveniently provide a version of the library and an example that can reproduce this problem? This will help us a lot in solving the problem.

**Comment by Alanscut** [comment]
I studied the source code and the corresponding xml file.  The error caused by different values of ``sqref`` attribute.

```xml
<dataValidation type="textLength" operator="greaterThan" showInputMessage="1" showErrorMessage="1" sqref="E1 E4">
   <formula1>2</formula1>
</dataValidation>

```
