### ISSUE TITLE
[BUG] readFile error

### ISSUE THREAD

**Issue by jshin07** [exceljs/exceljs#1168]
readFile gives ```TypeError: Cannot read property 'F_OK' of undefined```

I have 
```
import { Workbook } from "exceljs";
let workbook = new Workbook();
files.forEach((file) => {
const data = workbook.csv.readFile(file.name)
})
```

Tried with `workbook.xlsx.readFile` and this gives same error. 

I have version 3.8.1 installed.

**Comment by tonamson** [comment]
I have problem too

**Comment by KeyprodDev0** [comment]
Same error here :(

**Comment by Alanscut** [comment]
Upgrading your node version(above v 0.7) will wok.

**Comment by tonamson** [comment]
I use version 12.16.1

**Comment by KeyprodDev0** [comment]
Thank you for your quick response, but same here I use 12.16.1 (node -v)

**Comment by jshin07** [comment]
I'm using version 10.18.1

**Comment by Alanscut** [comment]
sorry, I veried it with old version. There does seem to be a bug in version 3.8, please try a old verison which below v3.8.0, that's ok in my pc.

**Comment by Alanscut** [comment]
BTW, if you using it in brower environment, then `fs` is not allowed, which violates the browser's security mechanism.

**Comment by dougleville** [comment]
I'm using from an Electron window with nodeIntegration: true and still getting this. 

I'm able to use other libraries that access the file system (and even fs itself), but I can't get around this error with exceljs.

![image](https://user-images.githubusercontent.com/30697943/77363785-57a4fc00-6d21-11ea-8dbd-0b877854bde9.png)

**Comment by dougleville** [comment]
Tried on Node v12.9 and 13.9

**Comment by SandeepBadawe** [comment]
I am getting the same error in browser env. How to get read of it. If not what is the alternative to read excel file.

**Comment by Shiko1st** [comment]
Same problem in browser (latest Chrome)

**Comment by evrardts** [comment]
Same here

**Comment by andreibuboi** [comment]
Workaround if using this in electron
`
        fs.promises.readFile(path)
            .then(data => {
                workbook.xlsx.load(data.buffer)
                    .then()
                    .catch();
            })
            .catch();
`

**Comment by mperu92** [comment]
same issue here

**Comment by Alanscut** [comment]
Hello guys, this `exceljs` uses different modules in the browser and node environment, you can refer to the following code.

## Demo
>index.vue
```vue
<template>
  <div class="excel">
    <div @click="generatorXlsx">generatorXlsx</div>
    <input type="file" @change="readXlsx" />
  </div>
</template>

<script>
import exceljs from "exceljs/dist/es5/exceljs.browser";
import { saveAs } from "file-saver";

export default {
  name: "ExcelPage",
  data() {
    return {};
  },
  methods: {
    downloadFile(wb, fileName) {
       wb.xlsx
        .writeBuffer()
        .then(buffer => {
          const blob = new Blob([buffer]);
          if (navigator.msSaveBlob) {
            navigator.msSaveBlob(blob, fileName);
          } else {
            console.log("writeFile ok");
            saveAs(blob, fileName);
          }
        })
        .catch(err => {
          console.log("writeFile Fail");
        });
    },
    generatorXlsx() {
      const workbook = new exceljs.Workbook();
      const worksheet = workbook.addWorksheet("sheet 1");
      worksheet.addRow(["a", "b", "c"]);

      // download the file
     this.downloadFile(workbook, 'abc.xlsx')
    },
    async readXlsx(obj) {
      if (!obj.target.files) {
        return;
      }
      const f = obj.target.files[0];
      const workbook = new exceljs.Workbook();
      var fileReader = new FileReader();
      fileReader.onload = (e) => {
        const buffer = e.target.result;
        workbook.xlsx.load(buffer).then(async (wb)=> {
          console.log("readFile success");
         this.downloadFile(wb, 'abcd.xlsx')
        }).catch((error)=> {
          console.log("readFile fail", error);
        })
      };
      fileReader.readAsArrayBuffer(f);
    }
  }
};
</script>
```
> main.js
```javascript
import 'core-js/modules/es.promise';
import 'core-js/modules/es.object.assign';
import 'core-js/modules/es.object.keys';
import 'regenerator-runtime/runtime';
// @ts-ignore
import rewritePattern from 'regexpu-core';
// @ts-ignore
import { generateRegexpuOptions } from '@babel/helper-create-regexp-features-plugin/lib/util';
try {
  new RegExp('a', 'u');
} catch (err) {
  // @ts-ignore
  global.RegExp = function (pattern, flags) {
    if (flags && flags.includes('u')) {
      return new RegExp(
        rewritePattern(
          pattern,
          flags,
          generateRegexpuOptions({ flags, pattern }),
        ),
      );
    }
    return new RegExp(pattern, flags);
  };
  // @ts-ignore
  global.RegExp.prototype = RegExp;
}
```

**Comment by DantSu** [comment]
With exceljs v4, `import { Workbook } from 'exceljs/excel'` fix the problem in Electron.

**Comment by ibalaji777** [comment]
same problem

**Comment by elementalPRESS** [comment]
save here. I know that `fs` doen't exist in browser, but something like is usually working - but NOT with csv. Why?

`	importCSV(file: File) {
		const wb = new this.Excel.Workbook();
		const reader = new FileReader();

		return new Promise((resolve, reject) => {
			// onerror
			reader.onerror = this.errorHandler;

			// onabort
			reader.onabort = e => {
				alert('File read cancelled');
			};

			// onload
			reader.onload = () => {
				const buffer = reader.result;

				console.log(buffer);

				wb.csv
					.read(buffer)
					.then(workbook => {
						console.log(workbook, 'workbook instance');
						let results = [];
						resolve(results);
					})
					.catch(err => {
						alert(err);
					});
			};

			reader.readAsArrayBuffer(file);
		});
	}
`

**Comment by zenxds** [comment]
in Electron
1. delete `browser` field in package.json
2. use `xlsx.load` `xlsx.writeBuffer` with `fs`

**Comment by Siemienik** [comment]
1. For a browser, `readFile` doesn't work. A better idea is to use the ArrayBuffer should be used, an example I implemented below:

https://github.com/Siemienik/XToolSet/blob/a8b00b46ffd6acec0254ac5b8b3c328b91641355/packages/xlsx-renderer/src/Renderer.ts#L36-L37

2. In responding to the original question:

<details>
<summary> First Question </summary>

> readFile gives `TypeError: Cannot read property 'F_OK' of undefined`
> 
> I have
> 
> ```
> import { Workbook } from "exceljs";
> let workbook = new Workbook();
> files.forEach((file) => {
> const data = workbook.csv.readFile(file.name)
> })
> ```
> 
> Tried with `workbook.xlsx.readFile` and this gives same error.
> 
> I have version 3.8.1 installed.

</details>

I would like to move `let workbook = new Workbook();` into lambda function. Because `readFile` mutates `workbook`.

3. This issue contains several different problems, that makes it impossible to resolve. If could I please you to create new ones with a clear description of how to reproduce a bug (if it is a bug) or reach an explanation what will resolve them. Thank you.
(I read only notification if I was mentioned).


---
_I'm contributing ExcelJS just for a fun, If want you to know something more go into #1500_
