### ISSUE TITLE
[BUG] TS Types wrong

### ISSUE THREAD

**Issue by MR4online** [exceljs/exceljs#1175]
## 🐛 Bug Report

Typescript Types are wrong in Cell environment.

Lib version: 3.8.1

## Detailed

index.d.ts line 406 says, that the Cell object has an property:

```javascript
readonly fullAddress: {
		sheetName: string;
		address: string;
		row: Row;
		col: Column;
	};
```

## current JS
when I do:
_console.log(myCell.fullAddress);_
I get:

```javascript
{
		sheetName: string;
		address: string;
		row: string;
		col: string
	};
```

**Comment by Siemienik** [comment]
@MR4online thank you for reporting this one:)
