### ISSUE TITLE
[BUG] exceljs throws an error "Invalid range in character set" in IE11 due to the lib "xmlchars"

### ISSUE THREAD

**Issue by JamesChenX** [exceljs/exceljs#1177]
## 🐛 Bug Report

Lib version: 3.8.2

## Steps To Reproduce

1. In IE11
```javascript
require('regenerator/runtime');
const Excel = require('exceljs/dist/es5/exceljs.bare');
```
2. Open the page that uses exceljs in IE11

## The expected behaviour:

exceljs should work fine in IE11

## Possible solution (optional, but very helpful):
The root cause is that exceljs uses saxes that uses xmlchars.
And xmlchars uses regular expressions with the unicode flag ("u") that cannot work in IE (so an error "Invalid range in character set" is thrown)

new RegExp("^["+t.NAME_START_CHAR+"]$","u")

```javascript

```

**Comment by tonchmx** [comment]
I'm trying to use this babel plugin: https://babeljs.io/docs/en/babel-plugin-proposal-unicode-property-regex

Actually, there's the same issue in the xmlchars package: https://github.com/lddubeau/xmlchars/issues/3

**Comment by tonchmx** [comment]
I've rolled back to the 3.8.0 version in my project and I am able to use the exceljs library again

**Comment by tonchmx** [comment]
I think that saxes isn't fully compatible with IE 11? I tested with 3.8.1 too and had the same error.

https://github.com/exceljs/exceljs/pull/1127

**Comment by alubbe** [comment]
Thanks for reporting this. As per https://github.com/exceljs/exceljs/pull/1193, you'll need to polyfill unicode support in IE11, for example like this (before requiring exceljs):

```js
const rewritePattern = require('regexpu-core');
const {generateRegexpuOptions} = require('@babel/helper-create-regexp-features-plugin/lib/util');

const {RegExp} = global;
try {
  new RegExp('a', 'u');
} catch (err) {
  global.RegExp = function(pattern, flags) {
    if (flags && flags.includes('u')) {
      return new RegExp(rewritePattern(pattern, flags, generateRegexpuOptions({flags, pattern})));
    }
    return new RegExp(pattern, flags);
  };
  global.RegExp.prototype = RegExp;
}
```

**Comment by alubbe** [comment]
The above fixed the issue on my windows laptop running IE11
