### ISSUE TITLE
[BUG] Error when try to compile depented lib

### ISSUE THREAD

**Issue by Siemienik** [exceljs/exceljs#1180]
## 🐛 Bug Report

Something, that works before, stop for now. 
I've developing xlsx-renderer, which use exceljs. After the latest update (`3.8.2`) compilation throws errors:
```
> xlsx-renderer@1.1.2 build /home/runner/work/xlsx-renderer/xlsx-renderer
> tsc

##[error]node_modules/exceljs/index.d.ts(1319,21): error TS2304: Cannot find name 'HeaderTransformFunction'.
##[error]node_modules/exceljs/index.d.ts(1319,47): error TS2304: Cannot find name 'HeaderArray'.
##[error]node_modules/exceljs/index.d.ts(1341,16): error TS2304: Cannot find name 'QuoteColumns'.
##[error]node_modules/exceljs/index.d.ts(1342,16): error TS2304: Cannot find name 'QuoteColumns'.
##[error]node_modules/exceljs/index.d.ts(1346,13): error TS2304: Cannot find name 'RowTransformFunction'.
```

## Steps To Reproduce

look here:
https://github.com/Siemienik/xlsx-renderer/pull/9/checks?check_run_id=535214873#step:4:473

## The expected behaviour:

build properly

## Possible solution (optional, but very helpful):

I have no research now, I'll try to check it tomorrow. I think its something with typings:
https://github.com/exceljs/exceljs/pull/1169/files#diff-b52768974e6bc0faccb7d4b75b162c99R1319

**Comment by irfanandratama** [comment]
#1179

**Comment by Siemienik** [comment]
Fixed in #1179, @guyonroche if I could ask you to publish v3.8.3 as soon as possible?

**Comment by Siemienik** [comment]
We have to publish v3.8.3 from current master first - 3.8.2 has bug inside - #1179 #1180 #1178

**Comment by ajmas** [comment]
Being a blocker for me, I replaced the version in my `package.json` for exceljs with:

`"git://github.com/exceljs/exceljs"`

**Comment by Siemienik** [comment]
@ajmas 
`"exceljs":"3.8.1" `


[here you are an example](https://github.com/Siemienik/xlsx-renderer/blob/master/package.json#L49)
