### ISSUE TITLE
[BUG] Typescript Error

### ISSUE THREAD

**Issue by MR4online** [exceljs/exceljs#1186]
## 🐛 Bug Report

With Version 3.8.2 there are Types in die index.d.ts file, which have not been defined.

Lib version: 3.8.2

## Error Message on Startup

```javascript
node_modules/exceljs/index.d.ts(1319,21): error TS2304: Cannot find name 'HeaderTransformFunction'.
node_modules/exceljs/index.d.ts(1319,47): error TS2304: Cannot find name 'HeaderArray'.
node_modules/exceljs/index.d.ts(1341,16): error TS2304: Cannot find name 'QuoteColumns'.
node_modules/exceljs/index.d.ts(1342,16): error TS2304: Cannot find name 'QuoteColumns'.
node_modules/exceljs/index.d.ts(1346,13): error TS2304: Cannot find name 'RowTransformFunction'.
```

## The expected behaviour:

no Typescript errors

## Possible solution:

type definitions

**Comment by Siemienik** [comment]
#1180 #1179 #1178 we are waiting for publishing the new version.

**Comment by Siemienik** [comment]
for now, I recommend use version 3.8.1

**Comment by Siemienik** [comment]
#1182 In the future, similar bugs should not happen again.
