### ISSUE TITLE
How can I write into the first empty cell of a column?

### ISSUE THREAD

**Issue by fhw-help** [exceljs/exceljs#1187]
Hello,
I am writing an application that adds values to a list in a xlsx-file.
I don't know the concrete Cell IDs, I just want to append the values at the end of the list (first free cell of the column).
How can I achieve this?

**Comment by Siemienik** [comment]
```javascript
dobCol.eachCell({ includeEmpty: true }, function(cell, rowNumber) {
  // ... some prediction here and some logic too
});
```
