### ISSUE TITLE
[BUG] TypeScript version doesn't have definition for Worksheet.addConditionalFormatting 

### ISSUE THREAD

**Issue by romanovma** [exceljs/exceljs#1194]
## 🐛 Bug Report

I cannot find the way to use addConditionalFormatting() method on a Worksheet in TypeScript.

Lib version: 3.8.1

## Steps To Reproduce

```typescript
    const wb = await workbook.xlsx.readFile(
      `./template.xlsx`
    );

    const mySheet: Worksheet = wb.getWorksheet(1);
    mySheet.addConditionalFormatting({})

    // error TS2339: Property 'addConditionalFormatting' does not exist on type 'Worksheet'.
```

## The expected behaviour:
Since it is supported in JS would be nice to have it in TS as well.

**Comment by Siemienik** [comment]
merged, available in v3.8.3 soon
