### ISSUE TITLE
[BUG] addConditionalFormatting method is not found in worksheet object

### ISSUE THREAD

**Issue by stackmanoj** [exceljs/exceljs#1197]
## 🐛 Bug Report
addConditionalFormatting method is not found. I am using below code that is given in documentation.

Lib version: 3.8.2

## Steps To Reproduce

import { Workbook, Worksheet, Cell, Fill, Row } from 'exceljs';

  private setErrorFormattingFont(worksheet:Worksheet) {
    worksheet.addConditionalFormatting({
      ref: 'A1:E7',
      rules: [
        {
          type: 'expression',
          formulae: ['MOD(ROW()+COLUMN(),2)=0'],
          style: {fill: {type: 'pattern', pattern: 'solid', bgColor: {argb: 'FF00FF00'}}},
        }
      ]
    })
  }

![Capture](https://user-images.githubusercontent.com/20141557/78246160-56848380-7506-11ea-8fa5-f08f2abfe487.PNG)

## The expected behaviour:

This should be work as documentation says

**Comment by Alanscut** [comment]
@stackmanoj  You can try the following code.
```javascript
import Excel from 'exceljs';

const workbook = new Excel.Workbook();
const ws = workbook.addWorksheet('Sheet1');
ws.addConditionalFormatting({
  ref: 'A1:E7',
  rules: [
    {
      type: 'expression',
      priority: 1,
      formulae: ['MOD(ROW()+COLUMN(),2)=0'],
      style: {fill: {type: 'pattern', pattern: 'solid', bgColor: {argb: 'FF00FF00'}}},
    }
  ],
});
```

**Comment by Alanscut** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
Best of luck.
