### ISSUE TITLE
[Q] Formula double quotes 

### ISSUE THREAD

**Issue by NeoForex** [exceljs/exceljs#1202]
Dear all,

I want to write a TEXT formula in my worksheet, but when i generate the file, i find that my double quotes was replaced to &quot;.  

- Here what i want: <f>TEXT("01/4/2020","mmm-aa")</f>

- Here what i get: <f>TEXT(& quot; 01/4/2020&quot;;& quot; mmm-aa&quot;)</f>

That formulas was extracted of the generated XML of sheet.

Thanks in advance!

The code: 

        const format = "\"mmm-aa\"";

        for(let i = 1; i <= 12; i++) {
            const date = "\"01/" + (startDate.getUTCMonth() + 1) + "/" + startDate.getUTCFullYear() + "\"";
            const formula: Excel.CellFormulaValue  =  { formula: 'TEXT("'+date+'";"+'+format+'")', date1904: false, result: '' };

            row.getCell(startCell).value = formula;

            startCell += 1;
            startDate = new Date(startDate.setMonth(startDate.getMonth()+1));
        }

**Comment by Siemienik** [comment]
Lack of activity, I have to close it. 
For making new question, please use GH Discussion category Q&A: https://github.com/exceljs/exceljs/discussions/categories/q-a
