### ISSUE TITLE
[BUG] Unlocked cells do not maintain their unlocked status after reading and writing a workbook.

### ISSUE THREAD

**Issue by Punknium** [exceljs/exceljs#1205]
## 🐛 Bug Report

If I read in an xlsx file and then write it back out any unlocked cell will become locked.

Lib version: 3.8.2

## Steps To Reproduce

Read and write an xlsx file.

Here is a before and after example, See E4 in the before and after.
[ExcelJS-FormattingLockedCellAndDatavalidation.xlsx](https://github.com/exceljs/exceljs/files/4445268/ExcelJS-FormattingLockedCellAndDatavalidation.xlsx)
[ExcelJS-AFTER-FormattingLockedCellAndDatavalidation.xlsx](https://github.com/exceljs/exceljs/files/4445269/ExcelJS-AFTER-FormattingLockedCellAndDatavalidation.xlsx)

```javascript
async load() {
  try {
    const wb = new ExcelJS.Workbook()
    await wb.xlsx.load(await this.file.arrayBuffer())
    const out = await wb.xlsx.writeBuffer()
    this.download(out)
  } catch (e) {
    console.error(e)
  }
}
```

## The expected behaviour:

Unlocked cells stay unlocked after reading and writing a file.

**Comment by Alanscut** [comment]
See PR #1210 .
