### ISSUE TITLE
[BUG] Unlocked cells lose their vertical and horizontal alignment after a read and write.

### ISSUE THREAD

**Issue by Punknium** [exceljs/exceljs#1206]
## 🐛 Bug Report

If I read in an xlsx file and then write it back out any unlocked cell will lose their vertical and horizontal alignments.

Lib version: 3.8.2

## Steps To Reproduce

Read and write an xlsx file.

Here is a before and after example. See cell E4
[ExcelJS-FormattingLockedCellAndDatavalidation.xlsx](https://github.com/exceljs/exceljs/files/4445268/ExcelJS-FormattingLockedCellAndDatavalidation.xlsx)
[ExcelJS-AFTER-FormattingLockedCellAndDatavalidation.xlsx](https://github.com/exceljs/exceljs/files/4445269/ExcelJS-AFTER-FormattingLockedCellAndDatavalidation.xlsx)

```javascript
async load() {
  try {
    const wb = new ExcelJS.Workbook()
    await wb.xlsx.load(await this.file.arrayBuffer())
    const out = await wb.xlsx.writeBuffer()
    this.download(out)
  } catch (e) {
    console.error(e)
  }
}
```

## The expected behaviour:

Unlocked cells should maintain their vertical and horizontal alignments.

**Comment by Alanscut** [comment]
See PR #1210 .
