### ISSUE TITLE
[BUG] All cells lose their data validation setting after reading and writing a file.

### ISSUE THREAD

**Issue by Punknium** [exceljs/exceljs#1207]
## 🐛 Bug Report

If I read in an xlsx file and then write it back out all data validation is lost.

Lib version: 3.8.2

## Steps To Reproduce

Read and write an xlsx file.

Here is a before and after example.
[ExcelJS-FormattingLockedCellAndDatavalidation.xlsx](https://github.com/exceljs/exceljs/files/4445268/ExcelJS-FormattingLockedCellAndDatavalidation.xlsx)
[ExcelJS-AFTER-FormattingLockedCellAndDatavalidation.xlsx](https://github.com/exceljs/exceljs/files/4445269/ExcelJS-AFTER-FormattingLockedCellAndDatavalidation.xlsx)

```javascript
async load() {
  try {
    const wb = new ExcelJS.Workbook()
    await wb.xlsx.load(await this.file.arrayBuffer())
    const out = await wb.xlsx.writeBuffer()
    this.download(out)
  } catch (e) {
    console.error(e)
  }
}
```

## The expected behaviour:

All cells should maintain their data validation.

**Comment by Alanscut** [comment]
See #1184. Same problem here.

**Comment by Punknium** [comment]
I missed that issue. My bad sorry. I'll wait for that one to be resolved.
