### ISSUE TITLE
[F] Convert each loops as asynchronous function

### ISSUE THREAD

**Issue by trenyture** [exceljs/exceljs#1212]
## 🚀 Feature Proposal

It could be super to have each loops (for example eachCell or in my case eachRow) as an asynchronous funtion...

## Motivation

I'm using KoaJs working with Promises and I try to make a script where everyRow should do a query to database ... But it do the job after I needed it ... Because eachRow is not an async function ...

## Example

For example I did : 
```javascript
let products = [];

worksheet.eachRow((row, rowNumber) => {
	if(rowNumber != 1) {
		let id = row.getCell('A');

		if(id) {
			let datas = await ProductManager.get(id);
			products.push(datas);
		}
		else {
			products.push({
				label: row.getCell('B'),
				price: row.getCell('C'),
			});
		}
	}
}

return ProductManager.save(products);
```

But as I said it's not waiting the DB call to do the save function ... 
So for the moment I did a second loop like that : 

```javascript
let products = [];

worksheet.eachRow((row, rowNumber) => {
	if(rowNumber != 1) {
		products.push({
			id    : row.getCell('A'),
			label : row.getCell('B'),
			price : row.getCell('C'),
		});
	}
});

for(let i = 0, length = products.length; i < length; i++) {
	if(products[i].id) {
		let datas = await ProductManager.get(products[i].id);
		products[i] = datas;
	}
	else {
		products[i] = {
			label: products[i].label,
			price: products[i].price,
		};
	}
}

return ProductManager.save(products);
``` 
So it would be great if we could have a **asyncEachRow** like this : 

```javascript
await worksheet.asyncEachRow(async (row, rowNumber) => {
```

**Comment by skineur** [comment]
Hello use async module

```javascript
async.eachLimit(worksheet._rows, 1, async function(row) {
      const values = row.values;
      const response = await saveInDB(values);
    }, (err) => { 
      if(err) {
        console.log(err);
      }
      console.log('finnish')
})

**Comment by alubbe** [comment]
Thank you for the feature proposal! I believe it coincides with something that I'm working on for version 4.0.0 - async iteration (https://github.com/exceljs/exceljs/pull/1135).
With it, you could just use this
```js
const workbook = new ExcelJS.stream.xlsx.WorkbookReader('./file.xlsx');
for await (const worksheetReader of workbookReader) {
  for await (const row of worksheetReader) {
    // ...
  }
}
```
Would that fit for your use case?

**Comment by trenyture** [comment]
That sounds great :) Thanks you

**Comment by alubbe** [comment]
you're right - fixed!
the async iteration branch is stable enough to be used in production (as we're using it at my own company), so feel free to try it out!

**Comment by alubbe** [comment]
This new API has been published in v4 - enjoy!
