### ISSUE TITLE
[Q] "Invalid range in character set" error on IE11 

### ISSUE THREAD

**Issue by cschwinderg** [exceljs/exceljs#1213]
## 💬 Questions and Help

I setup exceljs, in my React/TypeScript project, following the [es5 imports](https://github.com/exceljs/exceljs#importing) section and now I'm getting a "Invalid range in character set" error in IE11. I don't have any issues in Chrome or firefox. 

I setup a simple codesandbox here [https://codesandbox.io/s/elegant-sinoussi-m6ml0?file=/src/index.js](https://codesandbox.io/s/elegant-sinoussi-m6ml0?file=/src/index.js). The code below, is what I'm actually using in my app. 

In my index.tsx file I have
```
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import 'core-js/modules/es.promise';
import 'core-js/modules/es.object.assign';
import 'core-js/modules/es.object.keys';
import 'regenerator-runtime/runtime';
// @ts-ignore
import rewritePattern from 'regexpu-core';
// @ts-ignore
import { generateRegexpuOptions } from '@babel/helper-create-regexp-features-plugin/lib/util';
import React from 'react';
import ReactDOM from 'react-dom';
import * as serviceWorker from './serviceWorker';
// components
import App from 'components/App';

const { RegExp } = global as any;
try {
  new RegExp('a', 'u');
} catch (err) {
  // @ts-ignore
  global.RegExp = function (pattern: any, flags: any) {
    if (flags && flags.includes('u')) {
      return new RegExp(
        rewritePattern(
          pattern,
          flags,
          generateRegexpuOptions({ flags, pattern }),
        ),
      );
    }
    return new RegExp(pattern, flags);
  };
  // @ts-ignore
  global.RegExp.prototype = RegExp;
}

ReactDOM.render(<App />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

In the component that I'm using exceljs, I have.
```
/** @jsx jsx */

import { jsx, css } from '@emotion/core';
// @ts-ignore
import exceljs from 'exceljs/dist/es5/exceljs.browser';
import { saveAs } from 'file-saver';

// --- components (LabelValue) ---
// --- styles (Calculate) ---
const panelContainer = css`
  padding: 20px;
`;

// --- components (CalculateResults) ---
function CalculateResults() {
  async function downloadResults() {
    const workbook = new exceljs.Workbook();
    const worksheet = workbook.addWorksheet('sheet 1');
    worksheet.addRow(['a', 'b', 'c']);

    // download the file
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer]);
    if (navigator.msSaveBlob) {
      navigator.msSaveBlob(blob, 'abc.xlsx');
    } else {
      saveAs(blob, 'abc.xlsx');
    }
  }

  return (
    <div css={panelContainer}>
      <button onClick={() => downloadResults()}>Download</button>
    </div>
  );
}

export default CalculateResults;
```

**Comment by tonchmx** [comment]
Maybe https://github.com/exceljs/exceljs/issues/1177 can help you

**Comment by supriyamuppidi** [comment]
Facing the same issue in IE11 using create-react app application.
I have used Exceljs version 3.8.2

**Comment by Ryz0nd** [comment]
My solution is:

index.tsx
```
import "core-js/modules/es.promise";
import "core-js/modules/es.object.assign";
import "core-js/modules/es.object.keys";
import "regenerator-runtime/runtime";
import "react-app-polyfill/ie11";
import "react-app-polyfill/stable";
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

ReactDOM.render(<App />, document.getElementById("root"));
```

Component.tsx
```
import React from "react";

const rewritePattern = require("regexpu-core");
const {
  generateRegexpuOptions,
} = require("@babel/helper-create-regexp-features-plugin/lib/util");

const { RegExp } = global;
try {
  new RegExp("a", "u");
} catch (err) {
  // @ts-ignore
  global.RegExp = function(pattern, flags) {
    if (flags && flags.includes("u")) {
      return new RegExp(
        rewritePattern(
          pattern,
          flags,
          generateRegexpuOptions({ flags, pattern }),
        ),
      );
    }
    return new RegExp(pattern, flags);
  };
  // @ts-ignore
  global.RegExp.prototype = RegExp;
}

const ExcelJS = require("exceljs/dist/es5/exceljs.browser");

...
```

**Comment by alubbe** [comment]
Yes, for IE11 you'll need to teach IE about modern regex, like outlined here: https://github.com/exceljs/exceljs#es5-imports
Let us know if that doesn't work!

**Comment by zoltanbonus** [comment]
Using react-dom, I had to replace the last line to
` global.RegExp.prototype = RegExp.prototype;`

**Comment by ahilangopal** [comment]
> Yes, for IE11 you'll need to teach IE about modern regex, like outlined here: https://github.com/exceljs/exceljs#es5-imports
> Let us know if that doesn't work!

How do I, teach IE about modern regex in Angular 9 application

**Comment by ashishsharma229** [comment]
Hi @alubbe, i have the same question that @ahilangopal asked. How to get support of modern regex in angular 9 applications for IE11?

**Comment by nilebin10** [comment]
Hello @alubbe Tried using above polyfill in a angular app in diff ways. Still not able to use for angular application

**Comment by domehead100** [comment]
The "solutions" presented do not work, at least in a typical webpack setup.  The suggested polyfill imports two libs from node_modules, neither of which export es5 code, so es6 code ends up in the bundle and breaks IE because code from node_modules is typically not transpiled when using webpack.

I tried adding the folders for the two imported modules in the webpack.config to the rule that processes ts/js files, adding the absolute paths to the folders in the "include" setting to tell the loader to transpile anything from these folders to es5, but this doesn't work and after much hair pulling I'm still getting es6 in my bundle from these imports.  These modules import even more modules that also are not exported as es5.

There is no way that people are importing es6 as described, not transpiling it to es5, and having this work in IE.
