### ISSUE TITLE
[Q] How to get alignment info after reading an xlsx file ?

### ISSUE THREAD

**Issue by Gitturtle** [exceljs/exceljs#1214]
Is it possible to get the cell alignment info from the sheet object. As I found the alignment of the cell was always undefined.

**Comment by Alanscut** [comment]
@Gitturtle You can try the following code.
```javascript
const ExcelJS = require('exceljs');

const workbook = new ExcelJS.Workbook();
workbook.xlsx.readFile('./read/issue_1206.xlsx').then(function() {
  var ws = workbook.getWorksheet(1);
  const alignments = ws.getCell('A1').alignment;
  console.log('alignments==>', alignments);
});

```

**Comment by Gitturtle** [comment]
Thanks to @Alanscut , but the result was always undefined. Does the exceljs parsed alignment of cell correctly?

**Comment by Alanscut** [comment]
@Gitturtle Can you provide a file and example? This is more conducive to solving problems.

**Comment by Gitturtle** [comment]
@Alanscut you got the right alignment info? I used the code you provided before. File is very simple. Create a xlsx file by libreoffice, set a cell value and align the text whatever.

**Comment by Alanscut** [comment]
@Gitturtle In both cases, I can get the right information.You can try to change the suffix name of `xlsx` to` zip`, then unzip it, check the `style.xml` file.

```xml
// style.xml
  <cellXfs count="2">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" />
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1">
      <alignment horizontal="center" vertical="center" />
    </xf>
  </cellXfs>
```

**Comment by Alanscut** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
Best of luck.
