### ISSUE TITLE
[Q]Alignment and wrap-text

### ISSUE THREAD

**Issue by rafolmo** [exceljs/exceljs#1219]
## 💬 Questions and Help

Hi!

I have a doubt with the aligment property and the wrap text option.

When i do:

`worksheet.getRow(startRow).alignment = { wrapText: true };`

The cells auto-fit the height and work fine, the problem comes when i use this option and the cells
are merged. If the cells are merged the height is the default height..

Is there any way to use the option with merged cells? 

Thanks in advance!!

**Comment by JLuboff** [comment]
Are you applying the alignment before or after merging? I know unmerging will break any styles associated, which I would think merging would do the same.

**Comment by rafolmo** [comment]
The result of align, before of after, when merge are the same. Or i think so.
You can test in this fiddle:

[https://jsfiddle.net/q8o0ny73/1/](url)

**Comment by yrambler2001** [comment]
This is by design https://excel.tips.net/T003207_Automatic_Row_Height_For_Merged_Cells_with_Text_Wrap.html

**Comment by rafolmo** [comment]
Thanks so much!!

**Comment by banana618859** [comment]
I try to anthor way to resolve this problem.
just set row height，i will compute the word length and row count
`worksheet.getRow(i).height = word length / row contain length * 13.5 `
