### ISSUE TITLE
[Q] How to deal with fs.createReadStream with a new workbook

### ISSUE THREAD

**Issue by 64J0** [exceljs/exceljs#1238]
## 💬 Questions and Help

Hi, I'm trying to use ExcelJS to manipulate a xlsx file and then upload it to Google Drive, but I'm having problem with streams. Actually I'm very noob with streams and don't understand the very well.

When the program creates a new workbook where it is located? Like, if I have the path to a file I can user fs.createReadStream to access that file and then send it to the Google Drive API, but when I try to do that with a workbook (maybe in the memory of the process?) it sends me this error:
![error-message](https://user-images.githubusercontent.com/50725287/80518745-47ee8800-895d-11ea-995f-587edd1addbc.JPG)

The code of the example in Google Drive API tells me to do something like this: **fs.createReadStream(PATH_TO_THE_FILE)**, where I'm actually trying to send the workbook itself without saving in anywhere, so it doesn't have a path :(.

If anyone knows how to deal with this, and show me how, I would be very thankful.

**Comment by imrans110** [comment]
`      workbook.xlsx.write(res);
`

You can pipe down to any writable stream by using write method like above. The only requirement is that the place where you are piping down the data must a writable stream.
