### ISSUE TITLE
[Q] How can I set the width of a column based on the largest value in that column? 

### ISSUE THREAD

**Issue by awresolveio** [exceljs/exceljs#1242]
## 💬 Questions and Help

I have an excel that has merges. Like the following: 

wsJobs.mergeCells(row.getCell(1).$col$row + ':' + row.getCell(4).$col$row);

Row 1, Column 1-4 has values, all strings. 

I use this function to set the max width. 

wb._worksheets.forEach(ws => {
			if (ws._columns) {
				ws._columns.forEach(column => {
					let maxWidth = 5;
					column.values.forEach(value => {
						maxWidth = value.length > maxWidth ? value.length : maxWidth;
					});
					column.width = maxWidth + 3;
				});
			}			
		});

Which works great for the most part, except that it thinks that row 1 column 1 has a value and sets the column width of the column 1 to way bigger than it should (because the technically since the cells are merged , the same string value is in row 1, columns 1-4. 

I would like to know any tips and tricks I can use to merge cells but keep the value in only one column? 

Once again, if i merge row 1 , cells 1-4. and set the value to lets say 'example text' it sets the value of row1cell1 , row2cell2, etc.. to 'example text'. any way to not do that and still center and merge text between 1-4 cells?

**Comment by DanieleMar** [comment]
How did you solved @awresolveio ?
