### ISSUE TITLE
[BUG] WorkbookWriter  doesn't support headerFooter and rowBreaks.

### ISSUE THREAD

**Issue by master-maintenance1-peer-connect** [exceljs/exceljs#1248]
## 🐛 Bug Report

WorkbookWriter(WorkSheetWriter)  sheems that doesn't support headerFooter and rowBreaks.

Lib version: 3.9.0

## Steps To Reproduce

```javascript
  const workbookWriterOption1 = <ExcelJS.stream.xlsx.WorkbookWriterOptions>{
        stream: new stream.PassThrough(),
        filename: null,
        useStyles: true,
        useSharedStrings: true
    };
    const workBook1 = new ExcelJS.stream.xlsx.WorkbookWriter(workbookWriterOption1);
 const workSheet1 = workBook1.addWorksheet('ActionCorrespondencesViews',
        <ExcelJS.AddWorksheetOptions>{
            pageSetup: {
                printTitlesRow: "1:4",
                printTitlesColumn: "A:A",
                paperSize: 9, // A4
                orientation: 'landscape'
            },
            views:
                [<ExcelJS.WorksheetViewFrozen>{ state: 'frozen', xSplit: 5, ySplit: 4, topLeftCell: 'F5', activeCell: 'A1' }]
        });

const headerRow1 = workSheet1.addRow([.........]);
workSheet1.lastRow.addPageBreak(); 
```

## The expected behaviour:

TypeError Exception is  caused.

## Possible solution (optional, but very helpful):
The workaround for exception is the following code.
BUT, When printing the generated xlsx with MS-EXCEL, neither HeaderFooter nor rowBreaks was set.

```javascript
 //  Workaround : UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'oddFooter' of undefined

workSheet1.headerFooter = <ExcelJS.HeaderFooter>{ oddFooter: "&P/&N" }; // Set the footer (default centered) to bold, resulting in: "Page 2 of 16"


// Workaround : UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'rowBreaks' of undefined
 workSheet1.pageSetup["rowBreaks"] = workSheet1["rowBreaks"] = [];

```

**Comment by Alanscut** [comment]
@master-maintenance1-peer-connect See PR #1232 , Support 'rowbreaks' function, I will submit PR as soon as possible.

**Comment by master-maintenance1-peer-connect** [comment]
Fine!   is Pull-request version 4.0 ? And, When it can get by "npm install" ?

**Comment by Alanscut** [comment]
@master-maintenance1-peer-connect This requires the approval of members and authors. I don't have permission to merge code and release versions 😞 . I am working hard 😄 .

**Comment by master-maintenance1-peer-connect** [comment]
The "release versions" are incorrect.
There is a conflict between the versions of the files that could be installed from npmjs.com.
* The version of package.json is 3.9.0.
* The last modified version of readme.me is 3.8.2.
* No changes in lib / stream / xlsx / worksheet-writer.js. https://github.com/exceljs/exceljs/pull/1257/files
![exceljs-update-failed5](https://user-images.githubusercontent.com/64691446/83259498-1d5d4c80-a1f3-11ea-90e2-61bbe396ccf3.png)
