### ISSUE TITLE
[BUG] vulnerability 

### ISSUE THREAD

**Issue by Siemienik** [exceljs/exceljs#1250]
## 🐛 Bug Report

ExcelJs depends on vulnerability dependency.

## Steps To Reproduce

Details:
https://snyk.io/test/github/siemienik/xlsx-renderer#SNYK-JS-LODASH-567746
## The expected behaviour:

Should not depend on vulnerabilities

**Comment by Siemienik** [comment]
When this vulnerability was resolved https://github.com/Siemienik/xlsx-renderer/issues/24 could be closed

**Comment by Siemienik** [comment]
https://github.com/archiverjs/node-archiver/pull/420 has been merged, I am waiting for a new version was published in npm.

**Comment by ctalkington** [comment]
new version published

**Comment by Siemienik** [comment]
@ctalkington thank you

**Comment by Siemienik** [comment]
the vulnerability was resolved:
![image](https://user-images.githubusercontent.com/2893099/87235740-7ec22f00-c3df-11ea-90f9-4f254c95e13c.png)
