### ISSUE TITLE
Proposal to make alanscut a maintainer

### ISSUE THREAD

**Issue by alubbe** [exceljs/exceljs#1251]
I just found an email in my spam folder from @Alanscut that he would like to help out maintaining exceljs with us. He's produced a number of high quality PRs in the past months, helped with reviews and has answered some questions on our issue tracker. I think it would make sense - what do you think @guyonroche @Siemienik ?

**Comment by Alanscut** [comment]
Hi @alubbe , Thank you very much for your approval, I will do my best to keep up with your pace and contribute to exceljs 😄

**Comment by guyonroche** [comment]
I've just had the chance to log back in and - same here, email found in spam. Totally agree - Alan's contributions have been great! I've just sent the invite :-)

**Comment by Alanscut** [comment]
@guyonroche have received your invitation and joined, thank you very much! I willl try my best to maintain this lib with all of you :)

**Comment by Alanscut** [comment]
Hi @guyonroche, I just found that I have no permission to label or close the issue. Since the community has so many issues every day,  issue permission will help handle them, would you mind grant it to me?

**Comment by guyonroche** [comment]
Ah – it seems just adding you as a member was not enough.
I’ve now added you with Write access to exceljs/exceljs

Guyon

**Comment by Alanscut** [comment]
Thanks, already received !

**Comment by alubbe** [comment]
welcome aboard :)
