### ISSUE TITLE
[Q]limit column

### ISSUE THREAD

**Issue by ayushkumar9333** [exceljs/exceljs#1265]
i have 6 column fields in my code. i want only columns A to F be there when i export with rest columns hidden or locked so viewing the new created excel doesn't show any column beyond F.

how to do so. i am using angular 6 to create excel. and using excelsjs through npm

**Comment by rahuljoshi00794** [comment]
i am also trying to do same thing but not able to achieve this. i want only  6 columns and 2000 rows to be visible in exported excel rest of them should be hidden. how can we do it?. can anybody help me on this. 
thanks in advance

**Comment by Alanscut** [comment]
duplicate of #1284.
