### ISSUE TITLE
[BUG] Invalid regular expression: /^[	   -íŸ¿î€€-ï¿½ð€€-ô¿¿]$/: Range out of order in character class

### ISSUE THREAD

**Issue by Subhajitdas298** [exceljs/exceljs#1276]
## 🐛 Bug Report

exceljs.min.js:18 Uncaught SyntaxError: Invalid regular expression: /^[	

 -íŸ¿î€€-ï¿½ð€€-ô¿¿]$/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Object.508 (exceljs.min.js:18)
    at i (exceljs.min.js:3)
    at exceljs.min.js:3
    at Object.467.xmlchars/xml/1.0/ed5 (exceljs.min.js:10)
    at i (exceljs.min.js:3)
    at exceljs.min.js:3
    at Object.19.readable-stream (exceljs.min.js:3)
    at i (exceljs.min.js:3)
    at exceljs.min.js:3

Lib version: 3.9.0

## Steps To Reproduce

Just loading the page creates the error, with minified js. 

## The expected behaviour:

This error should not come

**Comment by Alanscut** [comment]
@Subhajitdas298 This problem does not appear in my project, you can try the following.

```javascript
yarn remove exceljs
yarn add exceljs -S
```

**Comment by Subhajitdas298** [comment]
> @Subhajitdas298 This problem does not appear in my project, you can try the following.
> 
> ```js
> yarn remove exceljs
> yarn add exceljs -S
> ```

No using yarn. Directly building from release sources. Then npm install. And then npm run clean-build.

**Comment by Alanscut** [comment]
> No using yarn. Directly building from release sources. Then npm install. And then npm run clean-build

Is your problem solved now 😄?

**Comment by Subhajitdas298** [comment]
> > No using yarn. Directly building from release sources. Then npm install. And then npm run clean-build
> 
> Is your problem solved now 😄?

No. As I explained, error is there. I just explained my process of building. How do you build?

**Comment by Subhajitdas298** [comment]
Fixed issue in pull request:[#1280 ](https://github.com/exceljs/exceljs/pull/1280)

**Comment by Subhajitdas298** [comment]
> > No using yarn. Directly building from release sources. Then npm install. And then npm run clean-build
> 
> Is your problem solved now 😄?

Please review my commit for the fix. Thanks

**Comment by xiaoliuzi955** [comment]
excuse me，should i rebuild the source code and replace exceljs/dist to solve the problem? expect for ur answer,thx

**Comment by SeoWooSoft** [comment]
"I've created a web page using exceljs, and it works fine in Korea, China, and Europe, but the same error occurs only in the US: exceljs.min.js:24 Uncaught SyntaxError: Invalid regular expression:." how can i solve?
