### ISSUE TITLE
4.0.0 mergefest

### ISSUE THREAD

**Issue by alubbe** [exceljs/exceljs#1285]
Hey @guyonroche @Siemienik @Alanscut 

I would like to finally release 4.0.0 - but I think we're blocked by @guyonroche having time for that. The async iteration PR also fixes a flaky test that we have on master.

So, to keep it simple, I propose that we have a mergefest: we all meet up on zoom, one of us (I volunteer) shares their screen, we merge as many PRs as we can, we then release the last 3.x version, we then merge async iteration and move node 8 to the transpiled files, and then release it - all together :)

What do you think? @Siemienik and I already did something like that to review the async iteration PR and it was really helpful.

@guyonroche how about you propose a time and place (let's take 60 minutes) and we try to make time for that? I'm happy to set up the zoom and send invitations.

**Comment by Alanscut** [comment]
great! it will make exceljs enter a new era. I'll take some time to review current PRs deeply again before this weekend.

**Comment by alubbe** [comment]
Or... if there aren't any urgent hotfixes for v3, how about we just merge the async iteration now?

**Comment by papandreou** [comment]
I would still really like to see a 3.x release with https://github.com/exceljs/exceljs/pull/1234 in it 🙏

**Comment by guyonroche** [comment]
Hey guys, this sounds great - as well, we'll be able to actually (well virtually) meet!
I think a last bash 3.x release is a good idea too...
I appreciate your understanding that my time is stretched, for me, the times that work best will be early evening tonight or tomorrow, in the range 18:00 to 21:00 BST (17:00 to 20:00 UTC) - or failing that, most of the British daytime over the weekend.

**Comment by alubbe** [comment]
@Alanscut would 17:00 - 18:00 UTC work for you? I imagine that will be quite late at night

**Comment by Alanscut** [comment]
sorry, it's too late for me... it's 01:00~3:00 in china.  British daytime over the weekend will work for me. Please don't mind my presence, I will list my opinions through email :)

**Comment by alubbe** [comment]
Weekends are bad for me :(
should we try next Tuesday 17:00 - 18:00 UTC?

**Comment by guyonroche** [comment]
Tuesday 17:00 UTC is good for me

**Comment by Siemienik** [comment]
> Tuesday 17:00 UTC is good for me

I will be available

**Comment by alubbe** [comment]
Ok I'm dialled in - does the url work for everyone else?

**Comment by alubbe** [comment]
join now or I'll just merge it myself :D

**Comment by guyonroche** [comment]
@alubbe @Siemienik v4.0.0 Published!!!
It was great to meet earlier :-)

**Comment by alubbe** [comment]
Thanks gentlemen! :)
