### ISSUE TITLE
[BUG] Workflows randomly failed by Babel error

### ISSUE THREAD

**Issue by Siemienik** [exceljs/exceljs#1292]
## 🐛 Bug Report

Lib version: 3.9.0 (current muster)

## Steps To Reproduce

Any push with any changes (even no code changes like README).
![image](https://user-images.githubusercontent.com/2893099/82742375-9e34c800-9d5d-11ea-8290-dded64e563d3.png)
https://github.com/exceljs/exceljs/runs/702800293?check_suite_focus=true

## The expected behaviour:

Deterministic behaviour of tests results.

**Comment by alubbe** [comment]
This is fixed by https://github.com/exceljs/exceljs/pull/1135
