### ISSUE TITLE
[BUG] Reading CSV file is giving error on browser console.

### ISSUE THREAD

**Issue by nitin-kapoor** [exceljs/exceljs#1296]
## 🐛 Bug Report

Reading CSV file is giving error on browser console. Below is the screenshot for same.

Please help with this issue. Can anyone share a proper example for reading data of CSV file.

![image](https://user-images.githubusercontent.com/34282001/82757927-0983a600-9e01-11ea-9636-60ff8baa832f.png)

**Comment by Alanscut** [comment]
duplicate of #1168 .
