### ISSUE TITLE
How to read CSV and XLS in browser?

### ISSUE THREAD

**Issue by grq** [exceljs/exceljs#1298]
It's easy to read XLSX, but how to use workbook.csv.read? What is this "Stream"? How to transform ArrayBuffer to this "Stream"?
Also read XLS doesn't work because you don't support it or there is just a bug? xlsx.load for .xls file returns a workbook with zero worksheets

**Comment by three-king** [comment]
> It's easy to read XLSX, but how to use workbook.csv.read? What is this "Stream"? How to transform ArrayBuffer to this "Stream"?
> Also read XLS doesn't work because you don't support it or there is just a bug? xlsx.load for .xls file returns a workbook with zero worksheets

do you resolve this problem?

**Comment by mmahalwy** [comment]
solution for this?
