### ISSUE TITLE
[F] Deno 1.0 support

### ISSUE THREAD

**Issue by mamiu** [exceljs/exceljs#1302]
## 🚀 Feature Proposal

Support for [Deno 1.0](https://github.com/denoland/deno).  
It shouldn't be that hard to make ExcelJS Deno compatible. The only thing which was failing in my test right now is the use of a buffer polyfill which is using the `__proto__` on `UInt8Array`. You can read more about it here: [https://github.com/denoland/deno/issues/4721](https://github.com/denoland/deno/issues/4721)

## Motivation

A lot of node developers are already trying Deno and some of them are already switching for new projects to Deno.

## Example

```ts
import ExcelJS from "https://deno.land/x/exceljs/mod.ts"
```

**Comment by alubbe** [comment]
That sounds interesting. I checked that our code does not contain any references to `__proto__`, and it looks like deno is not using our source files, but rather the compiled bundle for the frontend. Could you help us find out which of our dependencies is responsible for that? I assume it's happening somewhere in our build step.

**Comment by mamiu** [comment]
@alubbe Yes, I had the same assumption that it comes from the build process. In the meantime I managed to import ExcelJS into Deno. However, [Deno doesn't have a crypto module yet](https://github.com/denoland/deno/issues/1891) but ExcelJS relies on the one from Node or the browser. Since it's just a side project I don't want to search for a Crypto Polyfill and integrate it into the build process. I'll probably just switch back to Node.

If you want I can leave this feature request open until Deno has a crypto module otherwise I'll close it.

**Comment by alubbe** [comment]
I'd say let's close it for now until we deno has a crypto module and then let's see whether we are compatible with it. But thanks for trying out deno and posting your findings here!
