### ISSUE TITLE
[BUG] XYZ

### ISSUE THREAD

**Issue by Peyton-lee** [exceljs/exceljs#1304]
## 🐛 Bug Report

lib/doc/workbook.js 54

if (this._worksheets.find(ws => ws && ws.name.toLowerCase() === name.toLowerCase())) {
      throw new Error(`Worksheet name already exists: ${name}`);
 }

find => some

**Comment by Alanscut** [comment]
@Peyton-lee This is not a bug, both `Array.find()` and `Array.some()` can meet the requirements.

**Comment by Alanscut** [comment]
I don't think that exceljs needs to change this API.
Please re-open if you still hava thoughts.
