### ISSUE TITLE
How to make the cells in a column have drop-down options?

### ISSUE THREAD

**Issue by alonglive** [exceljs/exceljs#1306]
How to make the cells in a column have drop-down options? Now can only make the specified cells have drop-down options

**Comment by Alanscut** [comment]
@alonglive  I don't understand your purpose, can you provide a screenshot😄 ? 
If you want to add a drop-down list, https://github.com/exceljs/exceljs#data-validations-

**Comment by alonglive** [comment]
I want to make the whole column have drop down
for example：Now i can only do like this
```js
worksheet.getCell('A1').dataValidation = {
  type: 'list',
  allowBlank: true,
  formulae: ['"One,Two,Three,Four"']
}
```
I want to do this, but it's didn't work
```js
worksheet.getColumn('A').dataValidation = {
  type: 'list',
  allowBlank: true,
  formulae: ['"One,Two,Three,Four"']
}
```

**Comment by Alanscut** [comment]
Exceljs does not support this feature, and may not support it in the future, maybe you need to use the loop setting, good luck😄.

```
  for (let i = 0; i < length; i++) {
    worksheet.getColumn(`A${i}`).dataValidation = {
      type: 'list',
      allowBlank: true,
      formulae: ['"One,Two,Three,Four"']
    }
  }
```

**Comment by Alanscut** [comment]
Please re-open if you still hava thoughts.

**Comment by garvitjoshi** [comment]
Hey, Can we pass the Dynamic dataset in formulae:

I am trying to call it but it is throwing an error while opening the excel:

`let adb = Company_Code_Data.map((item) => {
                    var fullname = [item.Company_Code].join(" ");
                    return fullname;
                });

                let Company_Code_list = '\'\"'+adb.toString()+'\"\'';

                console.log(Company_Code_list);

                newSheet.getColumn('Company_Code').eachCell((cell) => {
                    cell.protection = {
                        locked: false
                    }
                    cell.dataValidation = {
                        type: 'list',
                        allowBlank: false,
                        operator: 'equal',
                        formulae: [adb.toString()],
                        showErrorMessage: true,
                        errorStyle: 'error',
                        errorTitle: 'Invalid value',
                        error: 'The value must be C&W, Pro Unlimited, Concur, AWS, Azure, Legal, Other'
                    }
                    cell.fill = {
                        type: "pattern",
                        pattern: "solid",
                        fgColor: {
                            argb: "FF85c8ff"
                        }
                    }
                }); `

**Comment by GALMelo** [comment]
@garvitjoshi You need to transform your array in a string with join let joineddropdownlist= '"'+adb.join(",")+'"'; and use joinedddropdownlist on formulae; formulae: [joineddropdownlist]. At least Worked for me

**Comment by kashyap-cephei** [comment]
any live code-sandbox example?

**Comment by GALMelo** [comment]
@kashyap-cephei I hope it helps, this is some old code, idk if it stills works, version: "exceljs": "^4.3.0",

```
let brandsArray = [];
    brands.forEach((brand) => {
      brandsArray.push(brand.attr_value + ' [' + brand.value_id + ']');
    });

let joineddropdownlistBrands = '"' + brandsArray.join(',') + '"';

const workbook = new ExcelJS.Workbook();
const sheet = workbook.addWorksheet('Brands');
sheet.columns = [
      { header: 'Brand', key: 'brand', width: 10 }
]

const length = 500;
for (let i = 2; i < length; i++) {
      sheet.getCell(`A${i}`).dataValidation = {
        type: 'list',
        allowBlank: true,
        formulae: [joineddropdownlistBrands],
      };
 }
```

**Comment by damatomos** [comment]
> [@kashyap-cephei](https://github.com/kashyap-cephei) I hope it helps, this is some old code, idk if it stills works, version: "exceljs": "^4.3.0",
> 
> ```
> let brandsArray = [];
>     brands.forEach((brand) => {
>       brandsArray.push(brand.attr_value + ' [' + brand.value_id + ']');
>     });
> 
> let joineddropdownlistBrands = '"' + brandsArray.join(',') + '"';
> 
> const workbook = new ExcelJS.Workbook();
> const sheet = workbook.addWorksheet('Brands');
> sheet.columns = [
>       { header: 'Brand', key: 'brand', width: 10 }
> ]
> 
> const length = 500;
> for (let i = 2; i < length; i++) {
>       sheet.getCell(`A${i}`).dataValidation = {
>         type: 'list',
>         allowBlank: true,
>         formulae: [joineddropdownlistBrands],
>       };
>  }
> ```

LGTM!
