### ISSUE TITLE
[BUG] JavaScript heap out of memory

### ISSUE THREAD

**Issue by charliewei-m** [exceljs/exceljs#1311]
## 🐛 Bug Report

Got error: JavaScript heap out of memory. Even just import it like: import * as Excel from ‘exceljs’
Tried to add max old space size, didn’t work for me.
Env:
Node v10.14.1
Npm 6.4.1
Antd 3.26.7
Exceljs 3.9.0

**Comment by sambhav2612** [comment]
@charliewei-m how did you fix it?

**Comment by charliewei-m** [comment]
> @charliewei-m how did you fix it?

node --max-old-space-size=4096 scripts/build.js
works for me
