### ISSUE TITLE
[Q] A way to set print quality?

### ISSUE THREAD

**Issue by irfanandratama** [exceljs/exceljs#1312]
## 💬 Questions and Help

Hi, i want to ask if there is a way to set the print quality of excel? We can set paper size and orientation but what about print quality? Thank you.

**Comment by balexandre** [comment]
just by looking into the source code, there is a `horizontalDpi` and a `verticalDpi`

https://github.com/exceljs/exceljs/blob/master/lib/xlsx/xform/sheet/page-setup-xform.js#L75-L76

maybe you can play with those properties...

**Comment by Alanscut** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
Best of luck.
