### ISSUE TITLE
[BUG] A problem with package.json main entry path

### ISSUE THREAD

**Issue by spectreqx** [exceljs/exceljs#1313]
## 🐛 Bug Report

Lib version: 4.0.0
The error is :

```
Error: Cannot find module 'C:\Users\Nasreddine\Desktop\lab\clean-install\node_modules\exceljs\excel.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:316:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:705:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:969:27)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Nasreddine\Desktop\lab\clean-install\index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\Nasreddine\\Desktop\\lab\\clean-install\\node_modules\\exceljs\\package.json',
  requestPath: 'exceljs'
}
```

## Steps To Reproduce

I did a clean install of the exceljs and ran it this way

```javascript
const Excel = require('exceljs');
const workbook = new Excel.Workbook();
const sheet = workbook.addWorksheet('My Sheet');
(async () => {
  await workbook.xlsx.writeFile('out.xlsx');
})();
```

## The expected behaviour:

I expected the package would export a file in the root directory of the project with the name "out.xlsx"

## Behaviour in previous version "3.10.0"

Works perfectly with the desired behaviour.

## Possible solution (optional, but very helpful):

Change this line in package.json
```package.json
...
135:    "main": "./excel.js",
...
```

To
```package.json
...
135:   "main": "./lib/exceljs.nodejs.js",
...
```

**Comment by alubbe** [comment]
@guyonroche the published npm package is missing a few files, most notably `excel.js`, but also `README_zh.md` and maybe `index.ts`

I can't see any npmignore file, how did you decide which files and folders to include?

**Comment by naholyr** [comment]
+1 here

**Comment by papandreou** [comment]
> Also, how did you decide which files and folders to include? If it was manual, should we maybe use an npmignore file instead?

That comes from the `files` key in `package.json`: https://github.com/exceljs/exceljs/blob/feb8e6b89cd1a20ca408fcdc2a27db98c48a0b99/package.json#L21-L27

(Personally I think it's better to use `files` (whitelist) than `.npmignore` (blacklist), but `files` clearly also has caveats 😅 )

**Comment by delcon** [comment]
editing package.json did it for me

```
"main": "./dist/exceljs.js",
```

**Comment by alubbe** [comment]
I'd recommend to use 
```
const Excel = require('exceljs/lib/exceljs.nodejs.js');
```
until the fix is released

**Comment by JLuboff** [comment]
Also experiencing this... how did this get released with such a breaking issue?

**Comment by alubbe** [comment]
It's because the final bundle is missing files - when you check out the repo and test things (locally or on CI) everything works. I guess to catch it we'd need a test run where the bundle is created and then imported. Happy to merge such a PR!

**Comment by deusama** [comment]
Not sure if this is related, but when I run 'jest' in my project it cannot import exceljs anymore and fails. Issue disappears when I switch from 4.0.0 back to 3.9.0 .. should I open a separate bug report?
