### ISSUE TITLE
[Q] client(express) download excel file

### ISSUE THREAD

**Issue by grant111924** [exceljs/exceljs#1315]
I tried this code, but I get the error
(node:30010) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object
why ?  I guess **workbook.xlsx.write(res)**  res is not string or buffer ? 

    app.get('/excel',(req,res)=>{
           var workbook = new Excel.Workbook();
           workbook.creator = 'Me';
           workbook.lastModifiedBy = 'Her';
           workbook.created = new Date(1985, 8, 30);
           workbook.modified = new Date();
           workbook.lastPrinted = new Date(2016, 9, 27);
           workbook.properties.date1904 = true;

           workbook.views = [
              {
                  x: 0, y: 0, width: 10000, height: 20000,
                   firstSheet: 0, activeTab: 1, visibility: 'visible'
              }
            ];
          var worksheet = workbook.addWorksheet('My Sheet');
         worksheet.columns = [
                      { header: 'Id', key: 'id', width: 10 },
                  { header: 'Name', key: 'name', width: 32 },
         ];

          worksheet.addRow({ id: 1, name: 'John Doe', dob: new Date(1970, 1, 1) });
          worksheet.addRow({ id: 2, name: 'Jane Doe', dob: new Date(1965, 1, 7) });

        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader("Content-Disposition", "attachment; filename=" + "Report.xlsx");
       workbook.xlsx.write(res).then(function (data) {
            res.end();
            console.log('File write done........');
        });

**Comment by fmenis** [comment]
I guess you must use the stream API.
`const workbook = new Excel.stream.xlsx.WorkbookWriter({ stream: res });`

**Comment by grant111924** [comment]
I know what happened
At the beginning I used 
> import Excel from 'exceljs/dist/exceljs is failed
and later I changed it 
> import Excel from 'exceljs/dist/es5/exceljs.browser'
so that it can be used
