### ISSUE TITLE
[Q] VALUE ON MERGED CELLS IS REPEATED INFINITE TIMES

### ISSUE THREAD

**Issue by XavierVicente** [exceljs/exceljs#1322]
Hi everyone,
I'm triying to merge cells before adding a unique value into them... my code is same as 

`
worksheet.mergeCells("B1:F1"); 
 const titleCell = worksheet.getCell("B1");
titleCell.value = 'Hello';
`

The problem appears when i'm triying to see the merged cell value.... 
(B1, C1, D1, E1, F1) the value printing is (Hello Hello Hello....)infinity times and not one time for all

I want to print only one time the value. 

Someone can help me? 
many thanks in advance.

**Comment by Alanscut** [comment]
@XavierVicente I dont't understand your purpose, How do you view the value of the merged cells?
Are you using the following method?
```javascript
console.log(worksheet.getCell('C1').value); // Hello
console.log(worksheet.getCell('D1').value); // Hello
```

**Comment by XavierVicente** [comment]
@Alanscut excuse my delay on answer you!
it's exact that i want to explain at the issue but i think that's the normal behavior of mergesCells.
my problem persist when I put an alignment same as:
  -  worksheet.getCell('B1').alignment = { vertical: 'middle', horizontal: 'fill' };
The conclusion of that, when I put value "fill" in horizontal property, i've a problem for render my "hello" value. The value "fill" take a special visibility on excel file as repeat the value infinite times on the merged cells
Using another alignment value on horizontal property same as: 
 -  worksheet.getCell('B1').alignment = { vertical: 'middle', horizontal: 'left' };
Everything works well and the value Hello is never repeated on the merged cells.

Finally I think that's solved, many thanks for the support!
