### ISSUE TITLE
[BUG] worksheet.insertRow is not a function

### ISSUE THREAD

**Issue by KazakovKirill** [exceljs/exceljs#1333]
## 🐛 Bug Report

When trying to use insertRow (or insertRows) method I getting error:
**TypeError: worksheet.insertRow is not a function**

Lib version: "4.0.1"

## Steps To Reproduce
```
const workbook = new Excel.Workbook()
const worksheet = workbook.addWorksheet('demo')
worksheet.insertRow(1, [3, 'Sam', new Date()])
```

## The expected behaviour:
https://github.com/exceljs/exceljs#insert-rows

**Comment by KazakovKirill** [comment]
Seems like this is a documentation issue: there is a deprecated methods published in documentation @ github.com/exceljs/exceljs

**Comment by wereHamster** [comment]
https://github.com/exceljs/exceljs/blob/master/UPGRADE-4.0.md doesn't mention anything about insertRow.

**Comment by Alek-S** [comment]
Getting this is well, so is `insertRow` depreciated in v4?

**Comment by Alek-S** [comment]
Looks like they had a PR recently for `insertRow` in #1324 that was merged, probably just haven't cut a new version tag yet to get it in since that went in 9 days ago, and the last version was 18 days.

**Comment by Subhajitdas298** [comment]
Yea, this method is new. Though, for Typescript users, there is a small bug, of missing optional operator in styleOptions. 
New version is released. You can use it. Just use 'n' in styleOptions parameter, until #1358 or alternative is merged.

**Comment by Subhajitdas298** [comment]
Also, I would suggest directly taking from source, rather than releases, if possible. As, it would contain latest features and fixes.

**Comment by alubbe** [comment]
Closing this, as we just need to wait for the release: https://github.com/exceljs/exceljs/issues/1362
