### ISSUE TITLE
[Q] Border style is not being reading from the excel.

### ISSUE THREAD

**Issue by andreperegrina** [exceljs/exceljs#1340]
## 🐛 Bug Report

When you read an Excel the border-style property is not available. 

Lib version: 4.0.1

## Steps To Reproduce

```javascript
const wb = await wb.xlsx.readFile(filePath);
wb.eachSheet((ws, sheetId) => {
  ws.eachRow((row, rowNumber) => {
     expect(row.getCell(2).style.border).to.equal({
        top: {style:'thin'},
        left: {style:'thin'},
        bottom: {style:'thin'},
        right: {style:'thin'}
     })
  })
})

```

## The expected behaviour:

`row.getCell(2).style.border` should get the whole style of the cell

**Comment by Alanscut** [comment]
@andreperegrina You can try the following code should achieve your purpose.

```javascript
row.getCell(1).border;
```

**Comment by andreperegrina** [comment]
I try to but I'm still getting `undefined`

**Comment by andreperegrina** [comment]
Already solve my problem. 

I just create a new excel. Looks like the old one has some troubles in the XML.
