### ISSUE TITLE
[BUG] Date loses 1 day

### ISSUE THREAD

**Issue by JacquelinaGarrido** [exceljs/exceljs#1343]
## 🐛 Bug Report

I imported an excel and parsed with ExcelJS.
I set workbook.properties.date1904 = true; and it is working ok but the problem is that it is substracting 1 day.
In my excel you can see that the date is: **5/17/2020**, but is is being imported as: **5/16/2020**.
Here is a sample of my excel:
[test.xlsx](https://github.com/exceljs/exceljs/files/4800719/test.xlsx)

**Comment by Alanscut** [comment]
@JacquelinaGarrido 
I did not reproduce this problem on the `master` branch, but I am not sure whether it is related to the time zone. Can you provide an example to reproduce this problem?
```javascript
const Excel = require('../../lib/exceljs.nodejs');
const wb = new Excel.Workbook();

wb.properties.date1904 = true;
wb.xlsx.readFile('./read/test.xlsx').then(() => {
  wb.xlsx.writeFile('./read/issue_1343.xlsx').then(() => {
    console.log('ok');
  }).catch((error) => {
    console.log('fail to write file', error);
  })
}).catch(() => {
  console.log('fail to read file');
})
```
<img width="560" alt="issue_1343" src="https://user-images.githubusercontent.com/21104054/85089704-e5579100-b215-11ea-9395-792d1255a606.png">

**Comment by Alanscut** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
Best of luck.
