### ISSUE TITLE
[Q] I am using exceljs package, My excel file gets corrupted after using writeFile method. Tried lot of solution but never got a fix for this..please help me.

### ISSUE THREAD

**Issue by MS2305** [exceljs/exceljs#1349]
<h3>When I tried to execute below code, my excel file gets corrupted, not able to view my modified data in xlsx file.</h3>

```var wb = require('../Packages/ExcelJs/node_modules/exceljs');

describe('Suite:7, Excel Demos', function () {
    it('spec:Test-Case-7.4, Edit Existing File', function () {
        async function editExistingFile(xlFilePath) {
            var workbook = new wb.Workbook();
            await workbook.xlsx.readFile(xlFilePath).then(async function () {
                var worksheet = await workbook.getWorksheet("TestData");
                await worksheet.eachRow(async function (row, rowID) {
                    console.log("Current Row:" + rowID);
                    await row.eachCell(function (cell, colID) {
                        console.log("Cell Value=" + cell.value + " for cell [" + rowID + "]" + "[" + colID + "]");
                        if (rowID >= 1 && colID == 3) {
                            cell.value = "New Result for OLD data";
                        }
                    });
                });
                await workbook.xlsx.writeFile(xlFilePath);
            });
        }

        var xlFilePath = "../test2.xlsx";

        editExistingFile(xlFilePath);
    })
});
```

**Comment by papb** [comment]
Please format your issue, see [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by Meenakshisundaram23** [comment]
var wb = require('../Packages/ExcelJs/node_modules/exceljs');

describe('Suite:7, Excel Demos', function () {
    it('spec:Test-Case-7.4, Edit Existing File', function () {
        async function editExistingFile(xlFilePath) {
            var workbook = new wb.Workbook();
            await workbook.xlsx.readFile(xlFilePath).then(async function () {
                var worksheet = await workbook.getWorksheet("TestData");
                await worksheet.eachRow(async function (row, rowID) {
                    console.log("Current Row:" + rowID);
                    await row.eachCell(function (cell, colID) {
                        console.log("Cell Value=" + cell.value + " for cell [" + rowID + "]" + "[" + colID + "]");
                        if (rowID >= 1 && colID == 3) {
                            cell.value = "New Result for OLD data";
                        }
                    });
                });
                await workbook.xlsx.writeFile(xlFilePath);
            });
        }
    });

    var xlFilePath = "../test2.xlsx";

    editExistingFile(xlFilePath);
});

**Comment by Meenakshisundaram23** [comment]
I tried formatting, but the code looks like that after save.

**Comment by papb** [comment]
You must have done something wrong. I assure you, if you format it correctly, the odds of you getting help will increase drastically

**Comment by Meenakshisundaram23** [comment]
**<h2>Tried formatting, Please help to resolve my issue**

**Comment by MS2305** [comment]
**_###Hi @papb , Any solution for my issue?_**

**Comment by MS2305** [comment]
<h3> Solved. Thanks for your support.  

**<h4>Root cause for the issue:**</h4> callback for writeFile method is written inside the user-defined (editexistingfile) function which is defined inside the IT function. </h3>

**<h4>Solution:**</h4> Removed the user-defined function inside the it function. now it works successfully. please find the below code.
```
var Excel =require('../Packages/ExcelJs/node_modules/exceljs');
 
describe('Suite:7, Excel Demos', function () {
    it('spec:Test-Case-7.4, Edit Existing File', async function () {
       var xlFilePath="../test2.xlsx";
            var workbook = new Excel.Workbook();
            await workbook.xlsx.readFile(xlFilePath).then(async function () {
                var worksheet = await workbook.getWorksheet("TestData");
                await worksheet.eachRow(async function (row, rowID) {
                    console.log("Current Row:" + rowID);
                    await row.eachCell(function (cell, colID) {
                        console.log("Cell Value=" + cell.value + " for cell [" + rowID + "]" + "[" + colID + "]");
                        if (rowID >= 1 && colID == 3) {
                            cell.value = "New Result for OLD data";
                        }
                    });
                });
                await workbook.xlsx.writeFile(xlFilePath);
            });
       })
});
```
