### ISSUE TITLE
[BUG] ExcelJS throws an error "Invalid range in character set" in IE11

### ISSUE THREAD

**Issue by EugeniyKiyashko** [exceljs/exceljs#1352]
## 🐛 Bug Report

I'm getting a "Invalid range in character set" error in IE11. I don't have any issues in Chrome or firefox.

Lib version: 4.0.1

## Steps To Reproduce

Open the [test page](https://eugeniykiyashko.github.io/DevExtreme-Demos/demos/IE11-testpage/index.html) that uses ExcelJS library in IE11

The code below, is what I'm actually using on my page.

```javascript
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.10.1/polyfill.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.0.1/exceljs.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.2/FileSaver.min.js"></script>

var workbook = new ExcelJS.Workbook();
var worksheet = workbook.addWorksheet('SheetName');

workbook.xlsx.writeBuffer().then(function(buffer) {
   saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'FileName.xlsx');
});
```

## The expected behaviour:

ExcelJS should work fine in IE11.

I've rolled back to the 3.8.0 version and I am able to use the ExcelJS library again. Could you explain to me using ExcelJS library with version 4.0.1 on my page?

**Comment by novsstation** [comment]
I faced the same problem. Could you please provide a working example?

**Comment by Alanscut** [comment]
@EugeniyKiyashko Please see issue #1213 .

**Comment by Alanscut** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
Best of luck.

**Comment by EugeniyKiyashko** [comment]
The "solutions" presented do not work, at least in the my simple html page. I have a issues with this and don't know what polyfill I should add on the page. Do you have any ideas or samples how it should works?
