### ISSUE TITLE
[BUG] 4.1.0 causes TypeScript compilation errors - addRows styleOption should be optional?

### ISSUE THREAD

**Issue by cduff** [exceljs/exceljs#1357]
## 🐛 Bug Report

Upgrading to 4.1.0 results in TypeScript compilation errors for previously working code like:

`sheet.addRows(rows);`

It looks like the problem was introduced in [Added insert rows functionality with new style inherit options](https://github.com/exceljs/exceljs/pull/1324). The new TypeScript definition is:

`addRows(rows: any[], styleOption: string): void;`

Shouldn't styleOption be optional with a default value?

**Comment by Subhajitdas298** [comment]
Sorry for the mishap. And thanks for quick response @sdg9670.
For the code, @cduff, If you are in hurry for release, you can use 'n' in styleOptions parameter.

**Comment by alubbe** [comment]
Closing this, as we just need to wait for the release: #1362
