### ISSUE TITLE
[F] + Possible Implementation - AutoFilter: Support the filterColumn tag

### ISSUE THREAD

**Issue by remzh** [exceljs/exceljs#1363]
## 🚀 Feature Proposal

Although AutoFilter support has been implemented since 2017, there is currently no way to exclude specific columns within the range. While this works completely fine in most scenarios, it primarily causes trouble with merged cells - as a filter will show up under each individual cell despite the "merge" (which we may not want). 

Adding an AutoFilter with merged cells with Excel:
![image](https://user-images.githubusercontent.com/20567781/86170086-da371780-bad7-11ea-886c-979c6dbd087f.png)

Adding an AutoFilter with merged cells with ExcelJS:
![image](https://user-images.githubusercontent.com/20567781/86170171-f3d85f00-bad7-11ea-9553-91107d6e3b9f.png)

## Motivation/Use Cases
By supporting column exclusions, users can further customize how autoFilter is implemented as well as properly handling merged cells (resulting in the top image instead of the bottom image). 

## Example/Possible Implementation 

From comparing the xlsx files between ones created by ExcelJS and Excel, it appears that ExcelJS is simply missing support for the filterColumn tag. 

```XML
<autoFilter ref="A1:G1"><filterColumn colId="1" showButton="0"/><filterColumn colId="2" showButton="0"/><filterColumn colId="3" showButton="0"/><filterColumn colId="5" showButton="0"/></autoFilter>
```

I've tweaked ExcelJS locally to work around this issue by adding an `exclude` property under `worksheet.autofilter`, so columns can be excluded like this: 
```JavaScript
sheet.autoFilter = {
    from: 'A10', 
    to: 'G10', 
    exclude: [1, 2, 3, 5]
}; 
```

If this solution looks viable, I'd be more than happy to submit it as a pull request along with updating the documentation to reflect it, just let me know!

**Comment by NiklasPor** [comment]
Is this closed because it's **completed**, because it won't be implemented or because or for what reason? I can't find anything in the docs or in the TS types.
