### ISSUE TITLE
[BUG] Incorrect Worksheet Name on Streaming XLSX Reader

### ISSUE THREAD

**Issue by whizdummy** [exceljs/exceljs#1364]
## 🐛 Bug Report

I am having problems getting correct worksheet name when using streaming xlsx reader (async iteration). The first worksheet always defaults to *Sheet1* regardless of name.

Lib version: 4.1.0

![excel](https://user-images.githubusercontent.com/12737833/86193024-7ff09200-bb7d-11ea-8fac-bf30eee6dac9.png)
![sheet-name](https://user-images.githubusercontent.com/12737833/86193212-f2fa0880-bb7d-11ea-9494-b2648a0445fc.png)

## Steps To Reproduce

[Sample Template.xlsx](https://github.com/exceljs/exceljs/files/4855135/Sample.Template.xlsx)

```javascript
const workbook = new stream.xlsx.WorkbookReader('path/to/Sample Template.xlsx', {});

for await (const worksheetReader of workbook) {
    console.log('sheet name:', worksheetReader.name); // It always outputs Sheet1
}
```

## The expected behaviour:

Worksheet name should be _Sum Worksheet_ instead of Sheet1.

**Comment by Alanscut** [comment]
@whizdummy  I found that there is indeed something unreasonable in the `XLSX` reader.
@alubbe  Do you have time to answer these questions?

## Source Code
We should use the function of `sheet-xform.js` to parse the worksheet name.

```javascript
// sheet-xform.js
 parseOpen(node) {
    if (node.name === 'sheet') {
      this.model = {
        name: utils.xmlDecode(node.attributes.name),
        id: parseInt(node.attributes.sheetId, 10),
        state: node.attributes.state,
        rId: node.attributes['r:id'],
      };
      return true;
    }
    return false;
  }
```
The following code will build an instance of `worksheet-reader`, including the name of the worksheet, such as `Sheet1` and `Sheet2`, etc.

```javascript
// workbook-reader.js
  *_parseWorksheet(iterator, sheetNo) {
    this._emitEntry({type: 'worksheet', id: sheetNo});
    const worksheetReader = new WorksheetReader({workbook: this, id: sheetNo, iterator, options: this.options});
    if (this.options.worksheets === 'emit') {
      yield {eventType: 'worksheet', value: worksheetReader};
    }
  }
```
I think that workbook-xform.js should be used to parse the workbook.xml file.
```javascript
// const WorkbookPropertiesManager = require('../../xlsx/xform/book/workbook-properties-xform');
const WorkbookManager = require('../../xlsx/xform/book/workbook-xform');
```

**Comment by alubbe** [comment]
@Alanscut that looks reasonable. Could you put together a PR with a potential fix (or an attempt of it) and with a test using the provided xlsx?

**Comment by colinroemer** [comment]
Do you plan on addressing this any time soon?

**Comment by vksonagara1996** [comment]
Is there a workaround other than not using the stream interface? @Alanscut @alubbe
