### ISSUE TITLE
When use IE 11 download Excel , meet the error 

### ISSUE THREAD

**Issue by zxforben** [exceljs/exceljs#1372]
`   // https://github.com/exceljs/exceljs#writing-xlsx
                        workbook.xlsx.writeBuffer().then(function (buffer) {

                            if (navigator.msSaveBlob) {
                                navigator.msSaveBlob(new Blob([buffer], {type: 'application/octet-stream'}), $scope.configName + '.xlsx');
                            } else {
                                saveAs(new Blob([buffer], {type: 'application/octet-stream'}), $scope.configName + '.xlsx');
                            }
                        }, function (error) {
                            console.error(error);
                        });`

![image](https://user-images.githubusercontent.com/5674472/86427549-098a9600-bd1d-11ea-88e4-aa0b9b725e16.png)

**Comment by Subhajitdas298** [comment]
The error is not in the shared code. Have to see generation code, as promise is rejected.
Also, in a side note, excel mime type type is 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'.

**Comment by zxforben** [comment]
This issue should use the babel polyfill js to fix that. It is works for me now.
