### ISSUE TITLE
[Q] XYZ

### ISSUE THREAD

**Issue by FsqXXX** [exceljs/exceljs#1373]

**Comment by anusha801** [comment]
` workbook.xlsx.writeBuffer().then(data => {
          const blob = new Blob([data], { type: this.blobType });
          FileSaver.saveAs(blob, 'Export');
        });`

this might help you

**Comment by Subhajitdas298** [comment]
Pure JS (es5) solution:

`
// Function to download data to a file
        function download(data, filename, type) {
            var file = new Blob([data], { type: type });
            if (window.navigator.msSaveOrOpenBlob) // IE10+
                window.navigator.msSaveOrOpenBlob(file, filename);
            else { // Others
                var a = document.createElement("a"),
                    url = URL.createObjectURL(file);
                a.href = url;
                a.download = filename;
                document.body.appendChild(a);
                a.click();
                setTimeout(function () {
                    document.body.removeChild(a);
                    window.URL.revokeObjectURL(url);
                }, 0);
            }
        }
        const MIMETypeXLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

`

`
workbook.xlsx.writeBuffer().then(function (buffer) {
        download(buffer, "test-" + Date.now() + ".xlsx", MIMETypeXLSX);
});
`

**Comment by Subhajitdas298** [comment]
@FsqXXX  please use proper query name (instead of XYZ)
