### ISSUE TITLE
[Q] Add row with color

### ISSUE THREAD

**Issue by theprobugmaker** [exceljs/exceljs#1382]
## 💬 Questions and Help

Is it possible to add a row with a color? For example, I have a few columns and one of them is `percentage`. I wanted to add that but with a background color based on the percentage... bellow `50%` would be red and above would be green.
I can't find in the docs something that helps with that. In resume, I need to change the individual color of a cell when adding a row.

**Comment by Subhajitdas298** [comment]
You can change the cell colour, after adding. While adding, option is not there, yet.

**Comment by zefexdeveloper** [comment]
That is the problem, I'm adding as a loop, it wouldn't be easy to do that later I guess haha. I would need to loop on each cell and so on.

**Comment by Subhajitdas298** [comment]
while you are calling addRow in a loop right?
Then in same loop you can set the cell colour

**Comment by zefexdeveloper** [comment]
@Subhajitdas298 Does addRow returns the current added row? If yes then it's the best way for sure. I will try it out.

**Comment by Subhajitdas298** [comment]
@zefexdeveloper yes, it returns the added row. addRows does not return anything (and calls addRow in a loop). So, efficiency wise, if you are already running a loop, best would be to, add a row, store returned row reference, and update by getting getCell(col), and set fill property.
