### ISSUE TITLE
Saved file is too big in size

### ISSUE THREAD

**Issue by yashgt** [exceljs/exceljs#139]
Hi,

Using, exceljs I have created a file with formulae. The xlsx file when saved is 44MB in size. When I open it and try to close it, it prompts me to Save the file, even though I have not made any changes to it after opening. Once i save it, the size becomes 9MB.

What might be causing the file to be generated with larger size the first time?

Thanks

**Comment by pablonm3** [comment]
hello @yashgt  i am having exactly the same problem here, could you solve it?

**Comment by geraldotomaz** [comment]
Hello @yashgt could you solve it?

**Comment by xwu-alterdomus** [comment]
Hello @Siemienik , I have the same issue. when I use exceljs to export to some files, it has a large size. but when I open the excel file and saved it is shrinked to a small size.
In my case, I have hundreds of thousands rows exported (only simple text), the original size is 40MB+, but when I open and save it it is shrinked to 3MB+.

My version is 4.4.0
