### ISSUE TITLE
Cannot read property 'cells' of undefined

### ISSUE THREAD

**Issue by ghost** [exceljs/exceljs#145]
Hi ! 
I just want to try before coding and it's not working ... 
I have this code : 

```
var Excel = require('exceljs');
var filename = './test.xlsx';

var workbook = new Excel.Workbook();
workbook.xlsx.readFile(filename)
    .then(function() {
        // use workbook
        var worksheet = workbook.getWorksheet('Dataset1');
        worksheet.eachRow(function(row, rowNumber) {
            console.log('Row ' + rowNumber + ' = ' + JSON.stringify(row.values));
        });
    });
```

But I have this error : 

> Cannot read property 'cells' of undefined

**Comment by lassmann** [comment]
can you put an image of the excel file?

**Comment by shrimpwagon** [comment]
I am getting a very similar issue. My code is almost exactly the same as @ghost

My error:

Cannot read property 'Target' of undefined

**Comment by hazemsamoaa** [comment]
for me I apply exactly the same APIs within the following code 

`var Excel = require('exceljs');
var inboundWorkbook = new Excel.Workbook();
inboundWorkbook.xlsx.readFile("Data/DataSet.xls").then(function() {
   var inboundWorksheet = inboundWorkbook.getWorksheet(1); //or name of the worksheet
   inboundWorksheet.eachRow({ includeEmpty: true }, function(row, rowNumber) {
	console.log("Row " + rowNumber + " = " + JSON.stringify(row.values));
   });
});`

but I got the error TypeError: Cannot read property 'eachRow'
I work in version exceljs@1.5.0, so I update eachrow function exactly like the documentation but still doesn't work

**Comment by xang555** [comment]
i have same issue! but i can solved it

i create new workbook and copy content from old excel file to new workbooks and save it to `.xlsx`

i think my issue occur from older version of excel  (you can not convert from xls to xlsx by using 
`save as` or online convert because i tried it! not work). my issue same like #652 

maybe help!

**Comment by CJSoldier** [comment]
hi, @hazemsamoaa .
`inboundWorkbook.getWorksheet(1);`
This is probably where the problem lies, try to replace id with sheet name.
Step into `inboundWorkbook.getWorksheet(1)` and wath `this._worksheets`, you'll find that you have several sheets but no one's id is 1.

**Comment by Siemienik** [comment]
see https://github.com/exceljs/exceljs/issues/2190#issuecomment-1498388491

> `getWorksheet` will search by index or name, but some workbooks can have worksheet's indexes started from any number - in that case, you will receive `undefined` for `workbook.getWorksheet(1)`. It's better to use `workbook.worksheets[0]` or `workbook.getWorksheet()`
