### ISSUE TITLE
[BUG] Columns only available from A-Z

### ISSUE THREAD

**Issue by MeisterBerg** [exceljs/exceljs#1450]
## 🐛 Bug Report

When I want to access a cell behind the Z-column for example with `worksheet.getCell('AA9')` I get an error message: `../exceljs/lib/doc/cell.js:15
      throw new Error('A Cell needs a Row');
` 
Same is for the array in `worksheet.columns`: If I add more than 26 entries into this array, I get the same error-message.

So at the moment its not possible to have more columns than 26, which makes my usecase impossible to implement.

Lib version: 4.1.1

## Steps To Reproduce

```javascript
const wb = new ExcelJS.Workbook();
const ws = wb.addWorksheet('XYZ');

ws.getCell('AA1').value = 7;
expect(ws.getCell('AA1').value).to.equal(7);

or

ws.columns = [
      {header: 'HEADER1', key: 'KEY1' ..}
       ...
      {header: 'HEADER27', key: 'KEY27' ..}
];

```

## The expected behaviour:

I would expect the same behavior like in all columns from A-Z.

## Possible solution (optional, but very helpful):
I guess it has something to do with colCache._dictionary in col-cache.js.

**Comment by zhaozhoa** [comment]
Can you tell me how to solve this problem

**Comment by zhaozhoa** [comment]
Oh ! I solved it!

```js

const fills = {
  solid: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'cccccc' }},
  border: { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' }},
  alignmentCenter: { vertical: 'middle', horizontal: 'center' },
  alignmentMiddleLeft: { vertical: 'middle', horizontal: 'left' },
  titleFont: { name: 'Helvetica Neue', size: 18 },
  orgFont: { name: '微软雅黑', size: 14 },
  mainFont: { name: '微软雅黑', size: 12 }
};


for (let i = 0; i < headerList.length; i++) {
      const coord = String.fromCharCode(65 + i) + 1; // That's the problem
      sheet.getCell(coord).fill = fills.solid;
      sheet.getCell(coord).border = fills.border;
      sheet.getCell(coord).alignment = fills.alignmentCenter;
    }
```

**Comment by aminnabiyev** [comment]
> Oh ! I solved it!
> 
> ```js
> const fills = {
>   solid: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'cccccc' }},
>   border: { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' }},
>   alignmentCenter: { vertical: 'middle', horizontal: 'center' },
>   alignmentMiddleLeft: { vertical: 'middle', horizontal: 'left' },
>   titleFont: { name: 'Helvetica Neue', size: 18 },
>   orgFont: { name: '微软雅黑', size: 14 },
>   mainFont: { name: '微软雅黑', size: 12 }
> };
> 
> 
> for (let i = 0; i < headerList.length; i++) {
>       const coord = String.fromCharCode(65 + i) + 1; // That's the problem
>       sheet.getCell(coord).fill = fills.solid;
>       sheet.getCell(coord).border = fills.border;
>       sheet.getCell(coord).alignment = fills.alignmentCenter;
>     }
> ```

Hi. Can you please tell me how did you solve it ?

**Comment by aminnabiyev** [comment]
@zhaozhoa Hi. Can you please tell me how did you solve it ?

**Comment by ingagudelob** [comment]
Hola chicos, saludos.
Quizas estoy un poco desfasado en el tiempo, pero me gustaria aportar algo de la solución que le pude encontrar.
Efectivamente el impase se encuentra en esta linea: **const coord = String.fromCharCode(65 + i) + 1;** // That's the problem
Esta linea lo que hace es: ir generando los codigos ASCII desde la A a la Z para la fila 1, que hacen referencia al nombre de las columnas del excel. Cuando vas a utilizar la columna AA o AB, este no corresponde a la secuencia que lleva esa linea de codigo. Es decir, cunod el (65 + i) es igual a 91, el caracter que aparece ya no es una letra sino un caracter especial "[" y este simbolo no es un nombre para la columna. 
Para utilizar esas columnas lo que hice fué: Concatenar la letra "A", en mi caso. Para contar con 25 columnas mas.

for (let i = 0; i < headerList.length; i++) {
      const coord = "A"+String.fromCharCode(65 + i) + "1"
      console.log("A"+String.fromCharCode(65 + i) + "1")
      sheet.getCell(coord).fill = fills.solid;
      sheet.getCell(coord).border = fills.border;
      sheet.getCell(coord).alignment = fills.alignmentCenter;
    }
// resultado: AA1
                     AB1
                     AC1
                     AD1
                     ...
                     AZ1
