### ISSUE TITLE
Add type for property of worsheet.lastcolumn 

### ISSUE THREAD

**Issue by Jigna-Rathod** [exceljs/exceljs#1453]
## 🚀 Feature Proposal
Similar to worsheet.lastRow worksheet.lastColumn should be added 

## Motivation
Doing so will facilitate the creation of multiple tables in same sheet and adding address for next table

## Example

Please provide an example for how this feature would be used.

**Comment by masterzeus05** [comment]
Was this added to the typescripts types? It does not appear on index.d.ts

**Comment by Siemienik** [comment]
@masterzeus05 good catch, thanks


---
_I'm contributing ExcelJS just for. If you want you to know something more, go into #1500. 
I accept orders for the resolve of issues._

**Comment by Siemienik** [comment]
Thank you @masterzeus05
