### ISSUE TITLE
[Q] formula creation for IF method

### ISSUE THREAD

**Issue by PetroTsapei** [exceljs/exceljs#1467]
## 💬 Questions and Help

Hello there, I have a question about `formula` creation.

After inserting a row for cell.
I try to use `IF` method but it doesn’t work:

`
row.getCell('D').value = {
    formula: 'IF(TRUE;1;2)'
};
`

The code above with a formula like - `1+2` works well.

Could you please give any suggestions?

**Comment by PetroTsapei** [comment]
I successfully resolved this issue, In such cases, you just need to replace `;` sign to `,`.

Hopefully, this information will help someone. 😊

**Comment by hppod** [comment]
Thank you very much, it helped me a lot. I had been looking for a solution to this problem for a few hours.
