### ISSUE TITLE
[BUG] Row.actualCellCount and Row.cellCount values are reversed if empty column present

### ISSUE THREAD

**Issue by kiba-d** [exceljs/exceljs#1472]
## 🐛 Bug Report

Row.actualCellCount and Row.cellCount are reversed if empty column present
Input:
A|B|C
1|   |1

Lib version: 4.1.1

## Steps To Reproduce

```typescript
  const workbook = new Excel.Workbook()
  await workbook.xlsx.load(input)
  workbook.eachSheet(sheet => {
     const row = sheet.getRow(2)
     console.log(`columnCount ${sheet.columnCount}`) //columnCount 3
     console.log(`actualCellCount ${row.actualCellCount}`) //actualCellCount 2
     console.log(`cellCount ${row.cellCount}`) //cellCount 3
  })
```

## The expected behaviour:

`actualCellCount` must return actual cells count including empty cells, i.e. 3 in described above example

**Comment by nandakumardtc** [comment]
https://github.com/exceljs/exceljs#worksheet-metrics

As per the document actualCellCount, actualRowCount and actualColumnCount will return count of the number of rows or cells or column that have values. If a mid-document row or cell or column is empty, it will not be included in the count.

**Comment by kiba-d** [comment]
Thx. But it is the opposite in the [code comments](https://github.com/exceljs/exceljs/blob/49a58750131485caf431034b55670630f4fa6555/index.d.ts#L557-L565)

**Comment by nandakumardtc** [comment]
@kiba-d  yeah, you are right.

**Comment by kiba-d** [comment]
I have a fix for it in local branch, but I do not have permission to access remote.
```
ERROR: Permission to exceljs/exceljs.git denied to kiba-d.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kiba-d** [comment]
How to receive access rights?

**Comment by nandakumardtc** [comment]
You can contribute by a pull request
https://github.com/exceljs/exceljs#contributions

**Comment by alubbe** [comment]
Thanks!
