### ISSUE TITLE
[Q] How to create an Excel array formula?

### ISSUE THREAD

**Issue by awn70** [exceljs/exceljs#1479]
Can You tell me how to create an Excel array formula with ExcelJS?
I want to create a formula like this:
![_Shot-000169](https://user-images.githubusercontent.com/1712315/94654616-98e41d00-02fd-11eb-8acf-6e170ea1a15a.png)

D4 formula is created by typing "=SUM( ROUND( D1:D3, 0 ))" and then CTRL+SHIFT+ENTER.

In ExcelJS I've tried this:
```
            cell.value = {
                formula: "SUM( ROUND( D1:D3, 2 ))",
                shareType: "array",
                ref: "D1:D3",
                result: 0
            };
```

Can anyone give me an example or tell me what's wrong?

**Comment by skypesky** [comment]
Hi, awn70, It might help you!

my exceljs version is 4.1.1.

```html
 "exceljs": "4.1.1",
```
usage

```ts
    const workbook: Workbook = new Workbook();
    const worksheet: Worksheet = workbook.addWorksheet('test_sheet');

    worksheet.getCell('D1:D1').value = '1.2';
    worksheet.getCell('D2:D2').value = '2.3';
    worksheet.getCell('D3:D3').value = '5.6';
    worksheet.getCell('D4:D4').value = {
      formula: "SUM(ROUND(D1:D3, 0))",
      result: 0,
      date1904: false,
    };
    // export to excel
    this.excelJsUtilsService.exportExcel('test', workbook);
```

**Comment by awn70** [comment]
Thanks for the example! 
Have you tried to open the xlsx with Excel from Office365?
Excel365 has a formula update which inserts "@" (Implicit intersection operator) in such CSE formulas, this "feature" destroys the formula and I haven't found an option to disable this feature. :-(

**Comment by skypesky** [comment]
@awn70 

When I use my syntax above and hold down Ctrl + Shift + enter, the formula works normally
I'm very sorry, I didn't show up what you said

**Comment by awn70** [comment]
The insert of the "@" (Implicit intersection operator) happens when Excel opens the generated sheet. 
Which Excel version do you have, I'm on "Excel for Microsoft 365 MSO (16.0.13127.20266)"?

**Comment by skypesky** [comment]
@awn70 
I did this test on my other computer (the notebook is not with me, so I can't tell you the version for the time being). The computer on my hand doesn't have Excel software.
For your situation, maybe you can take screenshots or videos so that other people know about the problem. Maybe someone finds out that the same can help you solve it.

**Comment by awn70** [comment]
Thanks, I'll open another question...

**Comment by hbt272** [comment]
@awn70 I have problem with CSE function too.
I'd like CSE automatic generated. If you have any idea please help!
