### ISSUE TITLE
[Q] How do I get access to the list of merged cells

### ISSUE THREAD

**Issue by Den2016** [exceljs/exceljs#1501]
## 💬 Questions and Help

Worksheet contains private property "_merges". In JS i can just write 
`
let m = workbook.getWorksheet(0)._merges
`
and get all merged cells in sheet. But in TS i get error "Property '_merges' does not exist on type 'Worksheet'".
If i try 
`
let m = workbook.getWorksheet(0).model.merges
`
i`m get a similar error - merges does non exist on WorksheetModel. 
at the same time everything works in JS, but result are different.

**Comment by skypesky** [comment]
@Den2016 hi,den2016.
If your excel has only one sheet, the code you should use to get this sheet is:
```ts
const justOneWorksheet = workbook.getWorksheet(1); // can work!
```
So the following code can work in TS without error.
```ts
const merges = (workbook.getWorksheet(1) as any)._merges;
console.log(merges);
```

**Comment by Den2016** [comment]
not a very nice solution, but apparently there is no other solution yet. Thanks

**Comment by skypesky** [comment]
Because _merge is a private property, which is not defined in the index.d.ts _merge property, so TS will report an error.

**Comment by Den2016** [comment]
this is understandable, but where is the guarantee that someday this property will not be renamed

**Comment by StephenChips** [comment]
I think it should make it public, the `_merge` property, or there should be some alternative method to access all merged cell.
