### ISSUE TITLE
[Q] How to encode/decode cell address

### ISSUE THREAD

**Issue by Den2016** [exceljs/exceljs#1506]
## 💬 Questions and Help

How do decode cell address, like "AB2" into {row:2, col:28} and encode 2, 28 back to AB2 ?

**Comment by skypesky** [comment]
@Den2016 hi,Den2016, This file contains two ways to solve your problem.  [open colCache.js](https://github.com/exceljs/exceljs/blob/master/lib/utils/col-cache.js)
usage:
```js
// {address: "AB2", col: 28, row: 2, $col$row: "$AB$2"}
console.log(colCache.decodeAddress('AB2'));

// AB2
console.log(colCache.encodeAddress(2, 28));
```

**Comment by Den2016** [comment]
thank you very much!
