### ISSUE TITLE
Insert a column

### ISSUE THREAD

**Issue by koldka** [exceljs/exceljs#1508]
Hi, 
I was looking for a way to insert a column in an existing xlsx file with exceljs.
Let's say I have 4 columns. I want to insert a column at 2nd position.
My new column would be the new B column and the other would shift to the right so the new C, D, E are the old B, C, D

From
   A  B  C  D
1 1  1   1  1
2 1  1   1  1
3 1  1   1  1
4 1  1   1  1

to

  A  B  C  D E
1 1     1  1  1
2 1     1  1  1
3 1     1  1  1
4 1     1  1  1

Is there a way to properly do that ?

**Comment by koldka** [comment]
I found the method  called "spliceColumns". It works perfectly.
For my example => workbook.spliceColumns(2, 0, [])

**Comment by aksharj** [comment]
hi @koldka, can you please share you code as to how to use `spliceColumns`, do you need to commit the worksheet after using spliceColumns?
