### ISSUE TITLE
[BUG] TypeScript  Excel.Column[] type check error

### ISSUE THREAD

**Issue by nshusr** [exceljs/exceljs#1517]
## 🐛 Bug Report

Lib version: 4.2.0

## Steps To Reproduce

```javascript

sheet1.columns = [
      { key: 'account', width: 20, style: { font: tableFontStyle, alignment: alignCenter } },
      { key: 'time', width: 16, style: { font: tableFontStyle, alignment: alignCenter } }
]

/*

error msg:

type "{ key: string; width: number; style: { font: Partial<Font>; alignment: Partial<Alignment>; }; }" lack type Column props: outlineLevel, hidden, values, letter... ts(2740)

*/
```

## The expected behaviour:

Optional parameters, not required option

**Comment by JaehyunLee-B2LiNK** [comment]
I get the same error.
After updating from version 4.1.1 to 4.2.0.

**Comment by anhphantien** [comment]
I found the difference between the two versions (which caused this bug). This is version 4.1.1:
![Screenshot from 2020-10-28 15-10-42](https://user-images.githubusercontent.com/54684536/97409239-da351000-192f-11eb-9ff0-2d6e49b40a12.png)
And this is version 4.2.0:
![Screenshot from 2020-10-28 15-09-40](https://user-images.githubusercontent.com/54684536/97409236-d903e300-192f-11eb-8188-ad832d6d0ab3.png)
It seems that reverting is needed here.

**Comment by Hesamp** [comment]
I also had a problem with this, the update

**Comment by seahindeniz** [comment]
A temporary solution would be downgrading to version 4.1.1

**Comment by Hesamp** [comment]
I think a hot fix is needed for this issue

**Comment by nshusr** [comment]
After I re-npm install, the wrong type file is still in the v4.2.0 version, I hope to fix it as soon as possible

![image](https://user-images.githubusercontent.com/45023042/103126758-4763e800-46ca-11eb-89c3-1bcea180d055.png)

**Comment by thoys** [comment]
Just ran into the same issue myself

**Comment by rahulgopinathan** [comment]
A workaround will be like this:

`sheet.columns = [
            { header: 'Id', key: 'id', width: 10},
            { header: 'Name', key: 'name', width: 32 },
            { header: 'Work Date.', key: 'DOB', width: 10, outlineLevel: 1, style: { numFmt: 'dd/mm/yyyy' } },
            { header: 'Meal 1 Out', key: 'meal1', width: 32 },
            { header: 'Meal 2', key: 'meal2', width: 32 }
          ] as ExcelJS.Column[];`
