### ISSUE TITLE
[Q] How to change orderNo of a Work Sheet?

### ISSUE THREAD

**Issue by amcs99** [exceljs/exceljs#1521]
Hello, I'm opening this issue because I did not find other discussions about that, please redirect me on the proper issue if you are already discussing it.
I want to move the last sheet(which was added latest) to the top, I've read some issues and found that there is a property call 'orderNo' which define the order of sheet, but how to change it? please help me!

**Comment by skypesky** [comment]
@amcs99  I want to move the last sheet(which was added latest) to the top.  ------------ 
I can't understand you. Can you give me an example? Maybe I can help you

**Comment by mfahmirukman** [comment]
Are you asking how you can exchange places of, for example: Sheet 5 with Sheet 1?

**Comment by amcs99** [comment]
> @amcs99 I want to move the last sheet(which was added latest) to the top. ------------
> I can't understand you. Can you give me an example? Maybe I can help you

Ah, one workbook can have many sheets and each sheet has it own place when open with Microsoft Excel. 
![image](https://user-images.githubusercontent.com/45377610/98885990-ab896e80-24c5-11eb-9bf2-79e7023f5917.png)
As you can see, the original order is : Sheet1, Sheet2, Sheet3, now I want to reorder it: Sheet3, Sheet1, Sheet2. How to do this?
Thanks for being mindful of my question !

**Comment by skypesky** [comment]
@amcs99 This may help you!
```javascript
      const workbook: Workbook = new Workbook();
      workbook.addWorksheet('sheet1');
      workbook.addWorksheet('sheet2');
      workbook.addWorksheet('sheet3');

      const _worksheets: any[] = (workbook as any)._worksheets;

      // In particular, the _worksheets[0] element is not available and index access should start at 1
      console.log(_worksheets); // look at me

      // Modification order
      _worksheets[3].orderNo = 1;
      _worksheets[1].orderNo = 2;
      _worksheets[2].orderNo = 3;

      // export excel
      this.excelJsUtilsService.exportExcel('1521.xlsx', workbook);
```

**Comment by amcs99** [comment]
Thanks @skypesky  very much, my problem was solved!

**Comment by FabienDehopre** [comment]
how could this possibly be fixed using "any" and accessing private members? at best, it can be considered as a workaround... not a fix.

**Comment by elpenao** [comment]
yes this is a bigger issue that needs to be solved

**Comment by icharge** [comment]
> how could this possibly be fixed using "any" and accessing private members? at best, it can be considered as a workaround... not a fix.

I agree with that.

@skypesky Thank you, This workaround save my life.

BTW. I can't hide the first worksheet (OrderNo = 1) unless its state is 'veryHidden'. So, I have to reorder it.

and I can't find the method that can set active sheet. It looks like it would set default as the first sheet.

**Comment by johnnyoshika** [comment]
Yeah, pretty crazy that we need to access private members for this. Hopefully this doesn't break in a future release 😬

Thanks @skypesky for the workaround.

Here's a more general approach:

```typescript
const moveSheetToFirstPosition = (
  workbook: ExcelJS.Workbook,
  sheetName: string,
) => {
  const targetSheet = workbook.getWorksheet(sheetName);
  if (!targetSheet) return;

    // Get current order of target sheet
  const currentOrderNo = (targetSheet as any).orderNo ?? 0;

  // Only increment sheets that are currently before the target
  workbook.worksheets.forEach(ws => {
    if (ws.name === sheetName) return;

    const wsOrderNo = (ws as any).orderNo ?? 0;
    if (wsOrderNo < currentOrderNo)
      (ws as any).orderNo = wsOrderNo + 1;
  });

  // Set target sheet to first position
  (targetSheet as any).orderNo = 0;
};
```
