### ISSUE TITLE
[BUG] Cell value returns undefined instead of 0

### ISSUE THREAD

**Issue by htorjmen** [exceljs/exceljs#1528]
## 🐛 Bug Report

Hello, 

I was using exceljs 1.12.1 and i upgraded it to 4.1.1 and everything works fine but there is a problem and I don't know if it is Bug issue or not but when i want to get value '0' it returns undefined but the other number positive or negative works fine.

This is my code That I'm using : 

`private static getCellValue(cell: Cell): any {
        if (cell.formula) {
            const value: CellFormulaValue = <CellFormulaValue>cell.value;
            return value.result !== '' ? value.result : null;
        } else {
            return cell.model.value !== '' ? cell.model.value : null;
        }
    }`

does anyone knows why only for number 0 it returns undefined ?

**Comment by abdulbasit1149** [comment]
Why was this closed?
