### ISSUE TITLE
Alignement on empty cell

### ISSUE THREAD

**Issue by TheoSabattie** [exceljs/exceljs#153]
Hi, 

We can not set alignment on empty cell.
Writing is wrong, alignment is broken when we open the written xlsx file.

Thanks,

Théo Sabattié

**Comment by haoliangyu** [comment]
I think we have to at least set an empty string in order to add cell styles and formatting. The same issue happened when I tried to set the background color of an empty cell. I solved by add an empty string:

```
cell.value = '';
```

**Comment by TheoSabattie** [comment]
Ok, thanks for tip haoliangyu! :)
