### ISSUE TITLE
[BUG] error after build 

### ISSUE THREAD

**Issue by lph666** [exceljs/exceljs#1551]
## 🐛 Bug Report

Lib version: ^4.2.0
react: ^16.13.1

In dev env, everything is ok. In prod env, it throw an error. 

react-dom.production.min.js:5058 
TypeError: Super expression must either be null or a function
    at exceljs.min.js:19876
    at exceljs.min.js:19875
    at Object.e.exports.119.../../utils/xml-stream (exceljs.min.js:19874)
    at a (exceljs.min.js:23)
    at exceljs.min.js:24
    at Object.e.exports.134.../../../doc/enums (exceljs.min.js:22566)
    at a (exceljs.min.js:23)
    at exceljs.min.js:24
    at Object.<anonymous> (exceljs.min.js:24001)
    at Object.e.exports.141.../utils/browser-buffer-decode (exceljs.min.js:25136)

similar issue #1342

**Comment by brandonlenz** [comment]
Seeing this as well with "react": "^16.6.3" and "exceljs": "^4.2.0".

**Comment by ctwizz1e** [comment]
@lph666 for what it's worth, we encountered this too. We were able to get around it by importing directly from "exceljs/dist/exceljs". We use typescript, and we were able to keep our type declarations intact by defining our own types.d.ts file with the classes we needed. Hopefully that helps!

**Comment by lph666** [comment]
> @lph666 for what it's worth, we encountered this too. We were able to get around it by importing directly from "exceljs/dist/exceljs". We use typescript, and we were able to keep our type declarations intact by defining our own types.d.ts file with the classes we needed. Hopefully that helps!

Thanks you, after these two steps, it works in prod env.

**Comment by NgocSon159** [comment]
> @lph666 for what it's worth, we encountered this too. We were able to get around it by importing directly from "exceljs/dist/exceljs". We use typescript, and we were able to keep our type declarations intact by defining our own types.d.ts file with the classes we needed. Hopefully that helps!

Thanks you so muchhhhh.

**Comment by dkun9039** [comment]
I've troubled with this too. 
Temporarily it is solved by changing the path of it, but it is not good to see... :)
I hope it to fix ASAP~!

for Korean who is like me,
일단 경로를 바꿔서 import {..} from 'exceljs/dist/exceljs'로 해서 빌드하면 해결은됩니다~~

**Comment by hinchley2018** [comment]
@alubbe would you be open to reopening this issue? We ran into the same issue in prod env as well, this issue should be reopened IMO since it is not fixed. Our team could help update the docs at least so others can find this issue faster.

**Comment by Alixhan** [comment]
Hope the authorities fix it.

**Comment by aliaksei-lyzo** [comment]
Also faced this issue on Angular prod build. Turning "optimization: false" in angular.json seems to have fixed it. Also somewhere seen that removing Uglify plugin for React also helped.

**Comment by huntbao** [comment]
My solution：

Project tech stack: React + TypeScript

Add an `exceljs.d.ts` file in directory where the file import `exceljs`, the `exceljs.d.ts` file content is

```
declare module 'exceljs/dist/exceljs';
```

in the file which import `exceljs`, code is:

```
import ExcelJS from 'exceljs/dist/exceljs';
```

these above save my build problem

**Comment by catofly** [comment]
> 일단 경로를 바꿔서 import {..} from 'exceljs/dist/exceljs'로 해서 빌드하면 해결은됩니다~~

we are not using Typescript.  In this case, wHere do we need to change the path ?

**Comment by chenop** [comment]
Experience that as well
on dev everything ok.
on prod build got: `"Super expression must either be null or a function"`

Changing:
`const Excel = require("exceljs");`
to 
`const Excel = require("exceljs/dist/exceljs");`
Solved it

**Comment by LanceMoe** [comment]
Have the same problem.
When the import is switched from `exceljs` to `exceljs/dist/exceljs` the problem disappears.
Looking forward to resolution.

**Comment by Pruiz05** [comment]
> My solution：
> 
> Project tech stack: React 16.12.0 + TypeScript 3.8.3 + exceljs4.2.1
> 
> Add an `exceljs.d.ts` file in directory where the file import `exceljs`, the `exceljs.d.ts` file content is
> 
> ```
> declare module 'exceljs/dist/exceljs';
> ```
> 
> in the file which import `exceljs`, code is:
> 
> ```
> import ExcelJS from 'exceljs/dist/exceljs';
> ```
> 
> these above steps save my build problem

Excelent. Thanks 🥇
