### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by dec87** [exceljs/exceljs#156]
Is it possible to add and write iamges with exceljs?

**Comment by haoliangyu** [comment]
This question was asked last year #34 and there is no `yes` answer yet. To add image into a new xlsx, there is an alternative [excel4node](https://github.com/natergj/excel4node).

**Comment by dec87** [comment]
I care about this library because it has a writing of stream which uses less RAM

**Comment by muuvmuuv** [comment]
Is there a update, that provides adding images?

**Comment by kachkaev** [comment]
@dec87 can this issue be closed now? See https://github.com/guyonroche/exceljs#images
