### ISSUE TITLE
Excel file contains {"sharedString":0} instead of actual value

### ISSUE THREAD

**Issue by aksharj** [exceljs/exceljs#1565]
Hi,

I am trying to read from a excel file, manipulate and create another excel file from it, i am using stream support for this. Most of it is working fine but i see resultant excel file containing `{"sharedString":0}` instead of actual values.

Below is my relevant code

```
let ws = fs.createWriteStream(fpath);
const writerOptions = {
fileName: fpath
};
const workbook = new ExcelJS.stream.xlsx.WorkbookWriter({stream: ws, useStyles: true, useSharedStrings: true});
const myworksheet = workbook.addWorksheet('sheet1');
const workbookReader = new ExcelJS.stream.xlsx.WorkbookReader(sheet.path, options);
workbookReader.read();

workbookReader.on('worksheet', worksheet => {
    worksheet.on('row', row => {
        myworksheet.addRow(row.values);
     });
});

workbookReader.on('shared-strings', sharedString => {
    console.log('not coming here');
});

workbookReader.on('end', async () => {
  console.log('processing done...');
  await workbook.commit();
});
```

Please see the attached file for your reference.

Any help on how to fix this will be really great, Thanks.

<img width="209" alt="shared_strings" src="https://user-images.githubusercontent.com/8026629/102232489-7a9ac000-3eef-11eb-9573-f98745910d04.png">

**Comment by aksharj** [comment]
Hi,

Once i created the WorkbookReader with below options, it worked

```
        const options = {
          sharedStrings: 'cache',
          hyperlinks: 'cache',
          worksheets: 'emit',
          styles: 'cache',
        };

```

**Comment by nainabbas007** [comment]
I am still getting this issue, even I say,

        const options = {
          sharedStrings: 'cache',
          hyperlinks: 'cache',
          worksheets: 'emit',
          styles: 'cache',
        };
