### ISSUE TITLE
Simply reading a xlsx file and saving it as a new file changes styles

### ISSUE THREAD

**Issue by victorbadila** [exceljs/exceljs#157]
I have an xlsx file, in which all strings in cells are of color black and non bold, which I read:

```
workbook.xlsx.readFile(filename)
        .then(function() {
            console.log('Done reading file');
            done();
        });
```

Then I simply write it to a new file

```
workbook.xlsx.writeFile(filename)
        .then(function() {
            console.log('Finished writing file');
            done();
        });
```

When I open the resulting file a lot of the previously black and non-bolded strings have become grey and bolded.

**Comment by Skilsar** [comment]
@Siemienik  Can you tell me, were you able to find a solution?
