### ISSUE TITLE
How to convert string to number using an excel worksheet?

### ISSUE THREAD

**Issue by shvamabps** [exceljs/exceljs#1582]
Can anyone please help me with how to convert the string values that are float numbers to float values in the excel sheet ??

**Comment by Den2016** [comment]
may be https://github.com/exceljs/exceljs#number-formats

**Comment by shvamabps** [comment]
Actually, I am importing the bulk of excel files and the column values format is a string. I am trying to convert the value of that column but the values are multiple and I can't afford to use  a loop.

**Comment by Akxe** [comment]
You must loop over it. Every cell must set its style

**Comment by shvamabps** [comment]
Thanks @Akxe

**Comment by alfizo** [comment]
You need to convert your json object that contains string values to numbers.
Exceljs will do the rest.
I used this js method to do that. 

```
  convertStringToNumber(objects) {
    for (var i = 0; i < objects.length; i++) {
      var obj = objects[i];
      for (var prop in obj) {
        if (obj.hasOwnProperty(prop) && obj[prop] !== null && !isNaN(obj[prop])) {
          obj[prop] = +obj[prop];
        }
      }
    }
    return objects;
  }
```
