### ISSUE TITLE
[BUG] Conditional Formatting with Font Style causes it to break styles on excel 

### ISSUE THREAD

**Issue by ywadi** [exceljs/exceljs#1583]
## 🐛 Bug Report
#1410 
When an excel files has a conditional format defined, and the conditional formatting specifically has font styles to it, if you read it into exceljs and write it back with no changes, excel finds the styles corrupt and removes all styles 

Lib version: Latest to date

## Steps To Reproduce
Create an excel that has conditional formatting and has _font styles for the conditional format_. 
Read the file by exceljs , do no changes, write it back to xlsx. The file results in a corrupted style and excel removes all styles. 
 [Template with conditional formating font style](https://github.com/exceljs/exceljs/files/4980773/template.xlsx)
 [Same template without the font style in conditional format](https://gofile.io/d/5WbsQs)

```
node -e "const Excel = require('exceljs'); var workbook = new Excel.Workbook(); var data = workbook.xlsx.readFile('./template.xlsx').then(()=>workbook.xlsx.writeFile('./test.xlsx').then(()=>console.log('Finished writing')))"
```

## The expected behaviour:

The file styles should not break if a conditional format has font styles. 

## Possible solution (optional, but very helpful):
Can not pinpoint where the issue is

**Comment by ywadi** [comment]
@Siemienik would you be able to help identify in code where the issue is ? I might be able to help if I just know how this is happening as I managed to reproduce it on multiple templates of xlsx

**Comment by rolandostar** [comment]
Might be related to #1305 which is fixed in PR #1574

**Comment by Siemienik** [comment]
@rolandostar Thank you for the information,
@ywadi I've added this issue to my personal to-do list. Recently I have limited time resources and all my free time spend working on [XToolset](https://github.com/Siemienik/XToolset). If want you to help me spend more time on Open Source activities and will you want to have more impact on my priorities, It is able to support me by [GH Sponsors](https://github.com/sponsors/Siemienik)

**Comment by Siemienik** [comment]
Done in #1574 by @rolandostar. Thank you a lot!
