### ISSUE TITLE
[SyntaxError: Invalid flags supplied to RegExp constructor 'u' ] exceljs/dist/exceljs.min.js:52421

### ISSUE THREAD

**Issue by dkun9039** [exceljs/exceljs#1593]
## 💬 Help me

- version
  - exceljs: 4.2.0
  - webpack: 4.44.1
  - react : 17.0.1
 
## Problem
> it works well in modern browsers.

but, I'm trying to run this web application on windows XP(Chrome v.49) ; it seems not good but I should try that..

when I launch it on Chrome v.49, it shows this error.

[SyntaxError: Invalid flags supplied to RegExp constructor 'u' ] exceljs/dist/exceljs.min.js:52421

SyntaxError: Invalid flags supplied to RegExp constructor 'u'
n.541
node_modules/exceljs/dist/exceljs.min.js:52421
```
  52418 | 
  52419 | Object.defineProperty(r, "__esModule", {
  52420 |   value: !0
> 52421 | }), r.CHAR = "\t\n\r -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF", r.S = " \t\r\n", r.NAME_START_CHAR = ":A-Z_a-z\xC0-\xD6\xD8-\xF6\xF8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD\uD800\uDC00-\uDB7F\uDFFF", r.NAME_CHAR = "-" + r.NAME_START_CHAR + ".0-9\xB7\u0300-\u036F\u203F-\u2040", r.CHAR_RE = new RegExp("^[" + r.CHAR + "]$", "u"), r.S_RE = new RegExp("^[" + r.S + "]+$", "u"), r.NAME_START_CHAR_RE = new RegExp("^[" + r.NAME_START_CHAR + "]$", "u"), r.NAME_CHAR_RE = new RegExp("^[" + r.NAME_CHAR + "]$", "u"), r.NAME_RE = new RegExp("^[" + r.NAME_START_CHAR + "][" + r.NAME_CHAR + "]*$", "u"), r.NMTOKEN_RE = new RegExp("^[" + r.NAME_CHAR + "]+$", "u");
        | ^  52422 | 
  52423 | function n(t) {
  52424 |   return t >= 65 && t <= 90 || t >= 97 && t <= 122 || 58 === t || 95 === t || 8204 === t || 8205 === t || t >= 192 && t <= 214 || t >= 216 && t <= 246 || t >= 248 && t <= 767 || t >= 880 && t <= 893 || t >= 895 && t <= 8191 || t >= 8304 && t <= 8591 || t >= 11264 && t <= 12271 || t >= 12289 && t <= 55295 || t >= 63744 && t <= 64975 || t >= 65008 && t <= 65533 || t >= 65536 && t <= 983039;
```

How Can I solve it? 
I tried your options on README.md. 
- import Exceljs from 'exceljs/dist/es5';
- import core-js before importing exceljs

is there any methods to solve it?

**Comment by Akxe** [comment]
You need to polyfill the regexp `u` flag too, it is at the beginning of the readme.

**Comment by dkun9039** [comment]
Thanks to @Akxe ,
I've solved this problem for your help. 

But, I should used another solution.
I added `excel.js`

```javascript
require("core-js/modules/es.string.includes");
require("core-js/modules/es.promise");
require("core-js/modules/es.object.assign");
require("core-js/modules/es.object.keys");
require("core-js/modules/es.symbol");
require("core-js/modules/es.symbol.async-iterator");
require("regenerator-runtime/runtime");

const rewritePattern = require("regexpu-core");
const {
  generateRegexpuOptions,
} = require("@babel/helper-create-regexp-features-plugin/lib/util");

const { RegExp } = global;
try {
  new RegExp("a", "u");
} catch (err) {
  global.RegExp = function (pattern, flags) {
    if (flags && flags.includes("u")) {
      return new RegExp(
        rewritePattern(
          pattern,
          flags,
          generateRegexpuOptions({ flags, pattern })
        )
      );
    }
    return new RegExp(pattern, flags);
  };
  global.RegExp.prototype = RegExp;
}

export const Excel = require("exceljs/dist/es5");

export default Excel;

```
but it makes an error at
> Object../node_modules/exceljs/dist/es5/stream/xlsx/workbook-reader.js

So, I changed a source a little.
```javascript
...
export const Excel = require("exceljs"); // here I changed
...

```

I know, this is very rare case, and I don't wanna use this on my project... but, there are still user used IE10... :(

Anyway, Thanks to solved it.
I hope this issue and solution help to other people who struggling like me :)

**Comment by betterthanyestoday** [comment]
> Thanks to @Akxe ,
> I've solved this problem for your help.
> 
> But, I should used another solution.
> I added `excel.js`
> 
> ```js
> require("core-js/modules/es.string.includes");
> require("core-js/modules/es.promise");
> require("core-js/modules/es.object.assign");
> require("core-js/modules/es.object.keys");
> require("core-js/modules/es.symbol");
> require("core-js/modules/es.symbol.async-iterator");
> require("regenerator-runtime/runtime");
> 
> const rewritePattern = require("regexpu-core");
> const {
>   generateRegexpuOptions,
> } = require("@babel/helper-create-regexp-features-plugin/lib/util");
> 
> const { RegExp } = global;
> try {
>   new RegExp("a", "u");
> } catch (err) {
>   global.RegExp = function (pattern, flags) {
>     if (flags && flags.includes("u")) {
>       return new RegExp(
>         rewritePattern(
>           pattern,
>           flags,
>           generateRegexpuOptions({ flags, pattern })
>         )
>       );
>     }
>     return new RegExp(pattern, flags);
>   };
>   global.RegExp.prototype = RegExp;
> }
> 
> export const Excel = require("exceljs/dist/es5");
> 
> export default Excel;
> ```
> 
> but it makes an error at
> 
> > Object../node_modules/exceljs/dist/es5/stream/xlsx/workbook-reader.js
> 
> So, I changed a source a little.
> 
> ```js
> ...
> export const Excel = require("exceljs"); // here I changed
> ...
> ```
> 
> I know, this is very rare case, and I don't wanna use this on my project... but, there are still user used IE10... :(
> 
> Anyway, Thanks to solved it.
> I hope this issue and solution help to other people who struggling like me :)

It really works, thank you very much!!!!!!!!!!!!!!
