### ISSUE TITLE
workbook.xlsx.writeBuffer() function extremely slow

### ISSUE THREAD

**Issue by wb-123456** [exceljs/exceljs#1609]
## 🚀 Feature Proposal

When there is a large amount of data，workbook.xlsx.writeBuffer() function extremely slow in Google browser

## Motivation

Download more than ten trillion Excel files

## Example

Please provide an example for how this feature would be used.
![image](https://user-images.githubusercontent.com/64052665/106839615-888fe480-66d9-11eb-8949-11d796f30d5a.png)

**Comment by alex0598** [comment]
@Siemienik  The mentioned bug is not related to WriteBuffer. Why is this bug closed ?

**Comment by Siemienik** [comment]
It was inactive

**Comment by mavyfaby** [comment]
> @Siemienik The mentioned bug is not related to WriteBuffer. Why is this bug closed ?

`closed as completed` but without a fix 😒
