### ISSUE TITLE
[Q] Read a xlsx file syncrronuously

### ISSUE THREAD

**Issue by raahed** [exceljs/exceljs#1620]
I'm trying to read a excel file into a csv-like looking array [ArrayLine1,ArrayLine2,..] with exceljs in nodejs. Exceljs has probably no solution to read a file synchronuously, so I have to build a solution around that. But all my attempts with async functions around the exceljs code doesn't work with the synchronuous frontend.
```

const workbook = new Excel.Workbook()

var raw = []
var line
workbook.xlsx.readFile(filename).then(() => {

    workbook.eachSheet((sheet, sid) => {

       sheet.eachRow((row, rid) => {

           line = []
           row.eachCell((cell, cid) => {
               
               line.push(cell.value)
           })
           
           raw.push(line)
       })
    })
})

//use raw / write the raw to another file
console.log(raw) //echo's: []
```
Is there any solution to read files syncrronuously?

**Comment by skypesky** [comment]
Maybe you can use async / await .
