### ISSUE TITLE
Error: Unexpected xml node in parseClose: filters

### ISSUE THREAD

**Issue by wjdgusfb11** [exceljs/exceljs#1633]
workbook.xlsx.load() occured error.

![image](https://user-images.githubusercontent.com/23116160/110913633-c1fee400-8358-11eb-8746-c595ef84d56b.png)

what is problem?

**Comment by shaozj** [comment]
> workbook.xlsx.load() occured error.
> 
> ![image](https://user-images.githubusercontent.com/23116160/110913633-c1fee400-8358-11eb-8746-c595ef84d56b.png)
> 
> what is problem?

do you know how to fix this problem, I came up with the same error

**Comment by tyler-pohl** [comment]
I found that I received this error when a column had a filter applied to it and it was saved that way. For example, column A has a filter and the options are `One, Two, and Three`. If only `One` is selected in the filter and the file is saved this way, reading the file with exceljs results in this error.

**Comment by andyyapwl** [comment]
for time's sake, i added the customFilters into new tag at auto-filter-xform.js neaar line 76 switch case:
switch (name) {
      case this.tag:
        return false;
	  case "customFilters":
		return false;
      default:
        throw new Error(`Unexpected xml node in parseClose: ${name}`);
    }

**Comment by jgranduel** [comment]
What's the state with this issue due to auto filters which prevents communicating about ExcelJS currently? (which is great BTW).
