### ISSUE TITLE
There's no support for .xls?

### ISSUE THREAD

**Issue by antunezz** [exceljs/exceljs#165]
If that's the case, you should make it very clear in the specification.

**Comment by sbahrain** [comment]
I agree, "Excel Workbook Manager" should support the XLS Excel Workbook.  NPM description does say "XLSX and CSV" but Github description doesn't.

**Comment by roccomuso** [comment]
+1

**Comment by sbahrain** [comment]
@antunezz @roccomuso I switched to https://github.com/sheetjs/js-xlsx, great support for .xls!

**Comment by gvnc** [comment]
Sheetjs does not support styles and formatting in their community edition, they support it only in pro version. I wish exceljs supported xls too.

**Comment by 19992077** [comment]
2021, still no support?

**Comment by Alamonall** [comment]
> 2021, still no support?

i guess not

**Comment by Siemienik** [comment]
> > 2021, still no support?
> 
> i guess not

Is anyone how want's to payout the development process? It is quite a lot of work to do, and as ExcelJS is MIT open-source library, no one covers the cost of maintaining it and development. Even if I have a lot of motivation and much more ideas, I may only spend some of my spare time.
