### ISSUE TITLE
[BUG] Quotes & apostrophes are escaped in formulas making Excel file unreadable

### ISSUE THREAD

**Issue by mortiy** [exceljs/exceljs#1650]
## 🐛 Bug Report

Formulas with quotes are escaped by `utils.xmlEncode`, so Excel cannot open the file.

Lib version: 4.2.1

## Steps To Reproduce

```javascript
const wb = new ExcelJS.Workbook();
const ws = wb.addWorksheet('XYZ');

ws.getCell('A1').value = {formula: 'FIND("WORD"; A2)'}
```
Resulting sheet1.xml will contain `&quot;` and `&apos;` instead of `"` & `'` in formula.

## The expected behaviour:

Quotes & apostrophes shouldn't be escaped during formula XML serialization

## Possible solution (optional, but very helpful):

```javascript

```

**Comment by mortiy** [comment]
Never mind.
Looks like locale specific issue.
In my UI formula separator is semicolon (`;`), while XML requires comma (`,`).

**Comment by flogvit** [comment]
Not sure this is a locale issue. I get the same:

```javascript
sheet.getCell('B3').value = { formula: `COUNTIF(D:D,">"&B2)`, result: undefined, date1904: false};
```

This result in a xml formula, and Excel complains then opening it (and removes it)

```xml
<f>COUNTIF(D:D,&quot;&gt;&quot;&amp;B2)</f>
```

But excel will make this file:
```xml
<f>COUNTIF(D:D,"&gt;"&amp;B2)</f>
```
