### ISSUE TITLE
[BUG] TypeScript: set properties company, title, description, etc. to Workbook class

### ISSUE THREAD

**Issue by kaoths** [exceljs/exceljs#1655]
## 🐛 Bug Report

properties added to `Workbook` class does not have TS declarations.  

Mentioned in version `0.2.30` as this following
- Merged Fix issue #178 #201. Adds the following properties to workbook:
    - title
    - subject
    - keywords
    - category
    - description
    - company
    - manager

Lib version: 4.2.1

## Steps To Reproduce

```typescript
const workbook = new ExcelJS.Workbook();
workbook.title = 'some title'
workbook.subject = 'any desc'
//... and rest
```
When trying to set these properties, I get `Property 'title' does not exist on type 'Workbook'.ts(2339)`
## The expected behaviour:
Able to set the properties (TS types should be declared)

## Possible solution (optional, but very helpful):

```javascript

```

**Comment by Siemienik** [comment]
Done in #1656 . Thanks
