### ISSUE TITLE
Is it possible to read an excel file stored in cloud or any remote url?

### ISSUE THREAD

**Issue by saravmajestic** [exceljs/exceljs#167]
I have a nodejs app which stores uploaded excel files in cloud and I will have public url for accessing the file. Is it possible to use the remote url in `readFile` method? Documentation shows we can readfile from local system only.

**Comment by ilya-payrange** [comment]
Use XHR to grab the file from URL (use proper flags for binary transfer), convert it to a data Buffer, and then feed to:

    var workbook = new Excel.Workbook();
    workbook.xlsx.load(data).then(function() { ... } );
