### ISSUE TITLE
[F] support output xlsx from template xlsx file 

### ISSUE THREAD

**Issue by voderl** [exceljs/exceljs#1691]
## 🚀 Feature Proposal
tabBar( the first line) maybe complex, hard to configure, like filter, annotate
but data is simple, regular
maybe like: 
https://www.yuque.com/easyexcel/doc/fill

template
```
name   |   age
{name} |   {age}  (fill with red)
```
output
```
name   | age
hello  |   18     (red)
hello  |   19     (red)
```

## Motivation
use office to generate xlsx template with style and use exceljs to fill formatted data

**Comment by Siemienik** [comment]
Hi @voderl, I already did it as another package: [XLSX-Renderer](https://github.com/Siemienik/XToolset/tree/master/packages/xlsx-renderer#xlsx-renderer)

**Comment by voderl** [comment]
awesome, thank you
