### ISSUE TITLE
Trying to get started by get error....

### ISSUE THREAD

**Issue by SPlatten** [exceljs/exceljs#171]
I want to get started with this module, I have node v6.4.0 installed, I tried this code:

```
    var excel = require("exceljs");
    var workbook = new excel.Workbook();    
    workbook.lastModifiedBy = workbook.creator = "Me";
    workbook.modified = workbook.created = new Date();
```

But when I start node running I get:

```
    (node:9220) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

I search on the site but I couldn't find any hjelp with this.

**Comment by SPlatten** [comment]
Found this and trying:

http://stackoverflow.com/questions/37346512/how-to-fix-fs-re-evaluating-native-module-sources-is-not-supported-graceful

**Comment by SPlatten** [comment]
Still does it...

**Comment by SPlatten** [comment]
This warninng doesn't appear to present me with an problems and I have successfully created a workbook, well done!!! hours of fun ahead.

**Comment by guyonroche** [comment]
@SPlatten - did you try with the latest version? There was a PR a while back that fixed an issue related to graceful-fs

**Comment by SPlatten** [comment]
I'll take a look, thank you.
