### ISSUE TITLE
[BUG] Uncaught ReferenceError: Excel is not defined

### ISSUE THREAD

**Issue by fuxingjun** [exceljs/exceljs#1794]
## 🐛 Bug Report

readme需要更新，还有几个地方用的Excel.Workbook,在浏览器中会报Uncaught ReferenceError: Excel is not defined
Lib version: latest

## Steps To Reproduce

```javascript
const workbook = new Excel.Workbook();
```

## Possible solution (optional, but very helpful):

```javascript
const workbook = new ExcelJS.Workbook();
```

**Comment by mlstoppa** [comment]
Hi,
Did you import the library?
`const Excel = require('exceljs')`

**Comment by fuxingjun** [comment]
> Hi,
> Did you import the library?
> `const Excel = require('exceljs')`

I used script tag in browser
```
<script src="../static/js/exceljs/exceljs.min.js"></script>
```
