### ISSUE TITLE
Apply styles or data validators to a range of cells

### ISSUE THREAD

**Issue by pp611** [exceljs/exceljs#180]
It seems styles or data validators can only be applied to a single cell. I could not find a way to apply them to a range of cells, e.g. A1..E10. 

Is it possible? Or we can only do it by iterating each cell in the range? Any difference in efficiency when rendered by Excel for applying a style to a range of cells or applying the style to each cell one by one in the range?

**Comment by efeminella** [comment]
Any updates on this one? I am trying to determine how one can enforce a list of values for all cells within a given column. The documentation doesn't appear to indicate how this is to be done.

**Comment by Siemienik** [comment]
Class `Range` has getters `top`, `bottom`, `left`, `right`, just use them to iterate through cells
