### ISSUE TITLE
[BUG] Worksheet name already exists

### ISSUE THREAD

**Issue by wellyal** [exceljs/exceljs#1809]
## 🐛 Bug Report

Error: Worksheet name already exists: My Sheet 
It was reported on #910 but it's still happening even though it was closed 

Lib version: exceljs@4.2.1

## Steps To Reproduce

```javascript
const sheet = workbook.addWorksheet('My Sheet');
```

**Comment by baguse** [comment]
are yau have another sheet with that name with different case?? Cause sheet name is not case sensitive when creating

**Comment by Siemienik** [comment]
The steps to reproduce are not enough in detail to reproduce the error.
The error is typically thrown when a worksheet with the same name exists. To check that you can iterate through `workbook.worksheets`
