### ISSUE TITLE
[BUG] Image position is wrong when adding to the row specific point and row height is not default.

### ISSUE THREAD

**Issue by faradaytrs** [exceljs/exceljs#1820]
## 🐛 Bug Report

I am trying to insert images in the row, first cell of the row and the second cell.
It's alright, but because images have different height, I wanted to put a smaller image to the centre.
I use the following syntax: 
```javascript
sheet.getRow(row).height = rowHeight;
sheet.addImage(preview, {
    tl: {
      col: col - 1,
      row: row - 1 + (1 - (imageHeight / rowHeight)) / 2,
   },
    ext: {width: fitTo, height: imageHeight},
    editAs: "oneCell",
});
```

The problem is when we add the image to a specific place in the cell, for example, 2.34 we expect it to re that .34 as 34% of the row height, but it only moves the image a little, and our best guess is it counts height from the original row height and not from the height we set.

Lib version: exceljs 4.3.0

## Steps To Reproduce
Described above

For example we have two images, one is 100 units of height, another one is 80, so we set row height to 100, and after that we want to put the second one to the row middle. So when (100 - 80) / 2 is 10, so in order to put it to that position we specify 2.1 (where 2 is row number, and .1 is how many % we want to move the image inside of row), but it doesn't work expected way.

## The expected behaviour:

We expect it to respect the new row height and put the image (if we specify 2.34) to the second row, 34% of the row height position.

**Comment by yulduck** [comment]
Any workaround for this bug?

**Comment by imatwork** [comment]
Same issue here

**Comment by GaryHyland** [comment]
Also finding this an issue. Gather I will have to do extra work and calc the intended position based off the initial row sizes, not the actual row sizes?

**Comment by joshvarun** [comment]
> Also finding this an issue. Gather I will have to do extra work and calc the intended position based off the initial row sizes, not the actual row sizes?

Were you able to do this?
