### ISSUE TITLE
I want to use the hyperlink only to a specific word in the string. Is this possible?

### ISSUE THREAD

**Issue by juteh** [exceljs/exceljs#1823]
Hi guys!

I want to use the hyperlink only to a specific word in the string. Is this possible?

```
const footerRow = worksheet.addRow(f);
        footerRow.eachCell((cell, number) => {
          cell.value = {
            text: "Klick on this link", //  only the word "link" should be a hyperlink
            hyperlink: 'https://www.google.com',
          };
          cell.font = {
            color: { argb: '000000' },
            size: 9,
            name: 'Helvetica',
          };
});
```

**Comment by dugokontov** [comment]
I was looking for the same feature, but it looks like that is not possible in excel:

 - https://superuser.com/questions/428299/hyperlinking-a-piece-of-text-in-excel
 - https://www.reddit.com/r/excel/comments/93eyj0/how_to_hyperlink_one_word_in_a_cell/

**Comment by juteh** [comment]
Thanks for your feedback! 

I will then close this issue. Maybe the topic will be resumed if that is possible in excel
