### ISSUE TITLE
[F] Specify row index for `columns` property

### ISSUE THREAD

**Issue by vicary** [exceljs/exceljs#1914]
## 🚀 Feature Proposal

Add a new `Worksheet.columnsHeaderRow` to hint where `Worksheet.columns.header` should apply its value, defaulting to `0` for backward compatibility.

## Motivation

Currently, specifying `header` value for the `Worksheet.columns` array mutates the values of the first row, there are legit use cases which multiple rows of metadata/legends are prepended to the actual column headers.

## Example

```typescript
const worksheet = workbook.addWorkheet("Sheet 1");

worksheet.addRow(["Total:", 123]);
worksheet.addRow(["Average:", 56.2]);
worksheet.columnsHeaderRow = 3;
worksheet.columns = [{ header: "No." }, { header: "Name" }, ...];
```

**Comment by sebastienbarre** [comment]
Was this ever implemented in a different way, I definitely have a use case for having a preamble before the header row. Thanks

**Comment by wilmanbarrios** [comment]
For anyone looking for a solution https://github.com/exceljs/exceljs/issues/433#issuecomment-343955264
