### ISSUE TITLE
Corrupted XLSX file when using stream writer with lots of data. No Error is thrown.

### ISSUE THREAD

**Issue by brunoargolo** [exceljs/exceljs#1916]
I have narrow down the issue a bit and seems related to transpilation. Unfortunately I cant reproduce this on a small repo. This happens on and off in prod and dev envs but I cant reproduce locally.

Issue:
XLSX file with multiple sheets and large volume of data often generates an XLSX file in a corrupt state.
When Opening the xlsx file the workbook.xml is missing and only half the sheets were written.
No errors on the logs and the process finishes "successfully", so the error is silent.

First I thought archive was not propagating the error event from the input stream to the archive streams.
So I checked out Exceljs and uploaded it to a private npm repo to test this hypothesis, but I didnt run npm run build (no transpilation).
This version consistently works and never presents an issue.

When I upload the built version I'm back to receiving errors. I'm using this on AWS Lambda and I cant reproduce the issue on ubuntu even with the same data.

Posting this here as a possible solution for people with the same issue, you can use the code stright from github instead of npm. I dont have a great suggestion on how to properly fix this as I imagine transpilation is needed for backwards compatibility on older versions of node. I dont have great knowledge on transpilation settings as well but if any ideas please let me know and I can explore it.

**Comment by slaveofcode** [comment]
I also facing this issue, try to generate 1 million rows with stream, but the file is corrupt when opened

**Comment by brunoargolo** [comment]
closing the issue as there is no point on keeping it open. Many updates since and this might no longer be a problem.
Still using non transpiled code so I cant say for sure if its no longer an issue.
