### ISSUE TITLE
How to get empty string when the cell is empty and sits at the last column

### ISSUE THREAD

**Issue by kmorte** [exceljs/exceljs#1924]
### Discussed in https://github.com/exceljs/exceljs/discussions/1921

<div type='discussions-op-text'>

<sup>Originally posted by **kmorte** December  3, 2021</sup>
Hi

I'm trying to build a json object per row. But rows with an empty cell as the last onw don't get parsed be the library and then values don't match with headers.

Thanks.

```
const book = new ExcelJS.stream.xlsx.WorkbookReader(fileRoute, {
        sharedStrings: 'cache',
        hyperlinks: 'emit',
        worksheets: 'emit',
        entries: 'emit'
    });
for await (const sheet of book) {

        const headers = {};
        const values = {};
        for await (const row of sheet) {

            const model = row.model;
            const cells = model.cells;

            if(model.number === 1) {
                cells.forEach((c, i)=> {

                    headers[i] = c.value;
                });
            };

            if(model.number !== 1) {
                cells.forEach((c, i)=> {

                     // if the last cell is empty, it does not appear here

                    values[i] = c.value;
                });
            };

            const item = {};
            Object.keys(headers).forEach(h=> {

                Object.keys(values).forEach(v => {

                    if(h === v) {
                        item[headers[h]] = values[v]

                    };
                });
            });

            // console.log('item ', item );

        };

    };
```</div>

**Comment by skypesky** [comment]
@kmorte 
hello kmorte, Is this question important to you?
Can you provide test files and test code?(If you want to solve your problem as quickly as possible.)

**Comment by kmorte** [comment]
Hi Skypesky, well, I found a way arround, but since it's a important library I'd say I'd be worth the fix. I think

He it is the code and file to reproduce the error.

As you'll see, there a 4 rows, they (represent invoices) and none of them have a value on the last cell (column L) There is already a console.log, and you'll see it's not on the callback argument of the row.eachCell function. If there were a value to 
any cell on the L column, it would appear the object.

Thanks!
```
import ExcelJS from 'exceljs';
import path from 'path';

const excel = path.join(path.resolve() + '/kelly/TFM/excel/copy.xlsx');


(async () => {

    const book = await new ExcelJS.stream.xlsx.WorkbookReader(excel, {
        sharedStrings: 'cache',
        hyperlinks: 'ignore',
        worksheets: 'emit',
        entries: 'ignore',
        styles: 'ignore'
    });

    for await (const sheet of book) {

        for await (const row of sheet) {

            const model = row.model;

            if(model.number !== 1) {
                row.eachCell({includeEmpty: true}, (c, n) => {

                    console.log('■■■■■ THIS IS A CELL ■■■■■', c);

                });

            };

        };

    };

})();

```

[copy.xlsx](https://github.com/exceljs/exceljs/files/7667008/copy.xlsx)
;

**Comment by skypesky** [comment]
Is the result of the following code running what you expect?
```typescript
    for await (const sheet of book) {

      const headers = [];

      for await (const row of sheet) {

        const values = [];
        const model = row.model;

        if (model.number === 1) {
          row.eachCell({includeEmpty: true}, (c, i) => {
            i && headers.push(c.value);
          });
        };

        if (model.number > 1) {
          row.eachCell({includeEmpty: true}, (c, i) => {
            i && values.push(c.value);
          });
        };

        const item = {};

        for (let i = 0; i < headers.length; ++i) {
          item[headers[i]] = values[i];
        }

        console.log(headers, values, item);

      };

    };

```

**Comment by kmorte** [comment]
YES, IT DOES.
For a second it seemed to me there were no bug, but it is an you fixed it as  good pianists fix a bad note, ie. seemlessly.
You're solution is better than mine, because I did an extra loop, so, yes thanks!

**Comment by skypesky** [comment]
Thank you for your approval. Due to time, there can be a better way to write.
```typescript
    for await (const sheet of book) {

      const headers = [];

      for await (const row of sheet) {

        const item = {};

        if (row.model.number === 1) {
          row.eachCell({includeEmpty: true}, (c, i) => {
            i && headers.push(c.value);
          });
        };

        if (row.model.number > 1) {
          const rowValues = row.values;
          headers.forEach((header, i) => {
            item[header] = rowValues[i + 1];
          })
        };

        console.log(headers, item);

      };

    };
```

**Comment by kmorte** [comment]
Well, yeah, this one removes a whole loop. I take it! Thanks.
I just don't understand the syntax i && headers.push(c.value); i is not actually being pushed to what I see in the console.log, so what is doing here...?

**Comment by skypesky** [comment]
@kmorte 
```typescript
i && headers.push(c.value)
```
Equivalent to
```typescript
if(i) {
  headers.push(c.value)
}
```
Equivalent to
```typescript
if(i > 0) {
  headers.push(c.value)
}
```

**Comment by kmorte** [comment]
Awkay... Couldn't google it. Thank you very much,skypesky!

**Comment by skypesky** [comment]
> Awkay... Couldn't google it. Thank you very much,skypesky!

No problem. You can refer to the documentation for more information...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND

**Comment by sukharev-deel** [comment]
will there actually be a fix to the library?

when a cell is empty in the last column, csv is parsed incorrectly: https://github.com/exceljs/exceljs/issues/1456

**Comment by JonathanLangton1** [comment]
I came up with a simple solution for this without any crazy workaround: https://github.com/exceljs/exceljs/issues/1456#issuecomment-1847468078 👍Hope it helps.
