### ISSUE TITLE
[PATTERN STYLE] how to know name of pattern

### ISSUE THREAD

**Issue by yogithesymbian** [exceljs/exceljs#1944]
```ts
row.getCell(cell).fill = {
            type: 'pattern',
            pattern:'darkTrellis',
            // fgColor:{argb:'FFC7C7C7'},
            bgColor:{argb:'FFD3D3D3'},
          };
```
i just only know three name from documentation **fill** on **readme.md**

but can you more describe about all pattern style name on documentation ???
<img width="557" alt="Screen Shot 2021-12-25 at 9 25 54 AM" src="https://user-images.githubusercontent.com/28316296/147375465-25080533-2d51-4156-909b-7acde4caa4cf.png">
i need the pattern style look like on above . 
i am bad on searching google 😅for the name of pattern style.

**Comment by skypesky** [comment]
@yogithesymbian 
Maybe this can help you.[view the value range of pattern](https://github.com/exceljs/exceljs/blob/2ab468b8bae2c8d5844f922d61ac7d960fee26be/index.d.ts#:~:text=export%20type%20FillPatterns,%7D)
```typescript
      const workbook: Workbook = new Workbook();
      const worksheet = workbook.addWorksheet('test_sheet');
      const patterns: FillPatterns[] = ['darkGrid', 'darkTrellis', 'darkHorizontal', 'darkGray', 'lightDown', 'lightGray', 'solid', 'lightGrid', 'gray125', 'lightHorizontal', 'lightTrellis', 'darkDown', 'mediumGray', 'gray0625', 'darkUp', 'darkVertical', 'lightVertical', 'lightUp'];

      for (let i = 0; i < patterns.length; ++i) {
        worksheet.getCell(i + 1, 1).fill = {
          type: 'pattern',
          pattern: patterns[i],
          fgColor: { argb: 'FFFF0000' }
        };
        worksheet.getCell(i + 1, 2).value = patterns[i];
      }

      // export excel ....
```

**Comment by Siemienik** [comment]
thanks @skypesky
