### ISSUE TITLE
[Q] 页面导出，excel中添加图片 会报错 提示 fs.readFile is not a function

### ISSUE THREAD

**Issue by taoqingfeng** [exceljs/exceljs#1973]
## 💬 Questions and Help
在浏览器端测试excelJs导出。 添加图片时，会报错，提示 **fs.readFile is not a function**！
以下为demo代码：

const workbook = new ExcelJS.Workbook();

  const fileName = '表格数据导出至Excel';

  const worksheet = workbook.addWorksheet('sheet1');
 
    worksheet.columns = [
    { header: 'Id', key: 'id', width: 10 },
    { header: 'Name', key: 'name', width: 32 },
    { header: 'D.O.B.', key: 'DOB', width: 10, outlineLevel: 1 }
    ];

    worksheet.addRow({id: 1, name: 'John Doe', dob: new Date(1970,1,1)});
    worksheet.addRow({id: 2, name: 'Jane Doe', dob: new Date(1965,1,7)});

    const img1 = workbook.addImage({filename: './1.jpeg', extension: 'jpeg'})
    worksheet.addImage(img1, 'A1:A1')

    workbook.xlsx.writeBuffer().then(buffer => {
        saveAs(
        new Blob([buffer], { type: 'application/octet-stream' }),
        fileName + '.' + 'xlsx'
        );
    });
![image](https://user-images.githubusercontent.com/16682430/153570430-1bac24b9-ef58-46aa-b75a-a92a3704ca17.png)

**Comment by skypesky** [comment]
@taoqingfeng 
你可以先得到(通过发送http请求)文件的buffer,再添加到image,具体写法可以参考: #1224 .

**Comment by taoqingfeng** [comment]
thank you~
![image](https://user-images.githubusercontent.com/16682430/153799422-811a6587-a541-48c3-ac74-cbbeffeb14ba.png)
我现在尝试先用http请求读取excel文件，拿到buffer，并用 workbook.xlsx.load(buffer)方式来读取。但总是读取不成功。
![image](https://user-images.githubusercontent.com/16682430/153799559-8230e0ea-7b7d-477f-b637-bc00849af52e.png)

**Comment by skypesky** [comment]
@taoqingfeng 
试试这个.
```typescript
    this.http.get('assets/1962.xlsx', {
      responseType: 'arraybuffer',
    }).subscribe(async (arrayBuffer) => {
      const workbook = new Workbook();
      // use async + await
      await workbook.xlsx.load(arrayBuffer);
      workbook.xlsx.writeBuffer()
        .then(buffer => saveAs(new Blob([buffer]), `abc.xlsx`));
    });
```

**Comment by taoqingfeng** [comment]
> @taoqingfeng 试试这个.
> 
> ```ts
>     this.http.get('assets/1962.xlsx', {
>       responseType: 'arraybuffer',
>     }).subscribe(async (arrayBuffer) => {
>       const workbook = new Workbook();
>       // use async + await
>       await workbook.xlsx.load(arrayBuffer);
>       workbook.xlsx.writeBuffer()
>         .then(buffer => saveAs(new Blob([buffer]), `abc.xlsx`));
>     });
> ```

我试着加了async/await   ,但还是一样的问题
![image](https://user-images.githubusercontent.com/16682430/153803511-fc51f2fe-032e-4189-bb9a-c01c7e1e8712.png)

**Comment by taoqingfeng** [comment]
大佬，您那是可以的嘛，能否发一份demo代码呢。

**Comment by skypesky** [comment]
我这边是可以的.
![image](https://user-images.githubusercontent.com/33124160/153803771-91b1df04-01c4-4462-beea-0342e262f1ab.png)

**Comment by skypesky** [comment]
如果还是不行,你加我qq,我给你看一下,上面就是demo代码.确保你正确读取了(正确的)xlsx文件.

**Comment by taoqingfeng** [comment]
> 

大佬您的qq是多少？我加一下您

**Comment by skypesky** [comment]
![image](https://user-images.githubusercontent.com/33124160/153804235-411c36b9-a5a2-4ff1-8328-3c298fed7e60.png)

**Comment by taoqingfeng** [comment]
thank you
