### ISSUE TITLE
Is it possible to add comment on a cell?

### ISSUE THREAD

**Issue by dinfer** [exceljs/exceljs#202]
I need add comment on some cell when exporting data, is there a method to do sth like this?

![image](https://cloud.githubusercontent.com/assets/11496403/19555749/c93c715a-96f0-11e6-893b-561e5cee8182.png)

**Comment by LogansUA** [comment]
:+1: Looking for this feature

**Comment by Lekmaby** [comment]
Any update on this?
There are 3 more similar feature requests: #529, #503, #451.

**Comment by guyonroche** [comment]
Comments (aka Notes) added to v1.12.0
