### ISSUE TITLE
[BUG] it report Cannot read property 'name' of undefined while i try to copy a sheet with image

### ISSUE THREAD

**Issue by nmnmtttt** [exceljs/exceljs#2033]
## 🐛 Bug Report

it report "Cannot read property 'name' of undefined" while i try to copy a sheet with image

Lib version: 4.2.1

## Steps To Reproduce

```javascript

  const _sheet = await mergeWorkBook.addWorksheet(`Sheet${index}`);
   _sheet.model = Object.assign(sheet.model, {
        mergeCells: sheet.model.merges,
    });
    _sheet.name += `_Sheet${index}`;
    index++;

```

## The expected behaviour:

get a backUp from sheet

but some error occured
like this:
![image](https://user-images.githubusercontent.com/34001432/163788203-53532264-f264-45d0-a7d2-7a44f996902f.png)

the media of  variabble e is an empty array. 
![image](https://user-images.githubusercontent.com/34001432/163789112-0a465162-2904-4008-a064-1596cd37f69a.png)

any solution?

**Comment by roscioli** [comment]
Seeing this too :/

**Comment by dingtwo** [comment]
How was this problem finally solved?

**Comment by dingtwo** [comment]
搞定了，复制 sheet 的时候媒体的源是挂在 workbook 上的，所以也得复制一份
Done, when copying the sheet, the media source is hung on the workbook, so you also need to copy it.
``` typescript
 if (!targetWorkbook.media) {
    targetWorkbook.media = [];
  }
  const sourceWorkbook = sourceSheet.workbook as exceljs.Workbook & {
    media?: exceljs.Media[];
  };
  targetWorkbook.media = targetWorkbook.media.concat(sourceWorkbook.media);
```
