### ISSUE TITLE
Columnwidth of 0 zero when setting numFmt

### ISSUE THREAD

**Issue by Sjonnie2nd** [exceljs/exceljs#204]
First thanks for the great work.

I'm new to this project so perhaps I miss some experience but..
When setting numFmt of a column: sheet.getColumn(3).numFmt = '0.00', the formatting works as expected but the column gets invisible. (using MS Office Excel 2010). 
Only if also the width is explicitely set: sheet.getColumn(3).width = 10 the column gets visible again.

Is this by design? Wouldn't it be good to warn for this issue in the docs?

**Comment by LukevdPalen** [comment]
@Sjonnie2nd i'm having the same issue. The problem also occurs when applying styles on columns.

**Comment by Alanscut** [comment]
@Siemienik I have researched the code and found that this width attribute is missing from the col tag in **sheet1.xml**. I think we should give a default value when then user does not set the width value. If you agree with this proposal, I would be happy to submit a PR.

### sheet1.xml
```xml
<cols>
    <col min="3" max="3" style="1" customWidth="1" />
</cols>
```

### Source Code
```javascript
  static toModel(columns) {
    // Convert array of Column into compressed list cols
    const cols = [];
    let col = null;
    if (columns) {
      columns.forEach((column, index) => {
        if (column.isDefault) {
          if (col) {
            col = null;
          }
        } else if (!col || !column.equivalentTo(col)) {
          col = {
            min: index + 1,
            max: index + 1,
            width: column.width || 8,   // it's here
            style: column.style,
            isCustomWidth: column.isCustomWidth,
            hidden: column.hidden,
            outlineLevel: column.outlineLevel,
            collapsed: column.collapsed,
          };
          cols.push(col);
        } else {
          col.max = index + 1;
        }
      });
    }
    return cols.length ? cols : undefined;
  }
```

**Comment by Siemienik** [comment]
Is the default value set for worksheet/workbook?
