### ISSUE TITLE
[F] Deno support

### ISSUE THREAD

**Issue by ddosakura** [exceljs/exceljs#2045]
## 🚀 Feature Proposal

I have read #1302 , but [deno](https://deno.land/) is more perfect than it was two years ago.

## Motivation

A similar Library——[sheetjs](https://github.com/SheetJS/sheetjs) already supports deno, see https://deno.land/x/sheetjs

But its support for styles is not good

## Example

In my [fork](https://github.com/ddosakura/exceljs), I did two things to make exceljs can run in deno:

1. [Use a new version of buffer](https://github.com/jspm/jspm-core/issues/2#issuecomment-612554467)
2. [fix a bug in `lib/xlsx/xlsx.js`](https://github.com/ddosakura/exceljs/commit/d00369d1edceeb8e3b6684d657a27b8e7fa4c02f#diff-a0e509d87e1082ae1c7e58dbde58d06a841574a23545cb78d311f5c582da093fR287-R331)

I didn't submit PR because I didn't clear why ` stream write(await entry.async('nodebuffer'));` causes errors and why you need to use it here.

Then, it can be used in deno by cdn. You can read more about it here: https://deno.land/manual@v1.21.0/node/cdns; https://esm.sh/

```js
export * from "https://esm.sh/@sakura-fork/exceljs@4.3.0-deno.0";
```

**Comment by bombillazo** [comment]
Hey! Was this merged into the codebase? Im getting a buffer error when using exceljs in deno :/
