### ISSUE TITLE
[Q] How to set the width and height of the annotation?

### ISSUE THREAD

**Issue by frankbuf** [exceljs/exceljs#2051]
## 💬 Questions and Help

I didn't find the relevant configuration in the documentation.
![image](https://user-images.githubusercontent.com/55173820/167093870-11b2b39b-7ddc-46c2-b730-1ee9dde54cc9.png)

Hope to export the following effect: 
![image](https://user-images.githubusercontent.com/55173820/167094177-52266a01-d08d-4b02-a665-8d9334f77bf6.png)

### How to make a question?
this my code
```javascript
const texts = [
    {
        font: {
            size: 12,
            color: { argb: 'FF000000' },
            name: 'Calibri',
            family: 2,
            scheme: 'minor'
        },
        text: item.name
    }
]
cell.note = {
    texts,
    margins: {
        insetmode: 'custom',
        inset: [0.25, 0.25, 0.35, 0.35]
    },
    editAs: 'twoCells'
}
```

Thanks for your guidance and help!

**Comment by relaxyel** [comment]
exceljs version: 3.6.0

**Comment by pietersv** [comment]
@frankbuf This public fork extends the library to specify the size of the comment box as rows and columns 

```js
cell.note = {
    texts,
    size: {rows:  10, cols: 4}
}
```

https://github.com/protobi/exceljs.git

**Comment by frankbuf** [comment]
@pietersv Thanks a lot, but we're already using the backend export.

**Comment by mazaxaka** [comment]
> @frankbuf This public fork extends the library to specify the size of the comment box as rows and columns
> 
> ```js
> cell.note = {
>     texts,
>     size: {rows:  10, cols: 4}
> }
> ```
> 
> https://github.com/protobi/exceljs.git

this function still not working in main release. Will it be added?
