### ISSUE TITLE
[F] Threaded Comments

### ISSUE THREAD

**Issue by ChrisSimoniMBT** [exceljs/exceljs#2070]
## 🚀 Feature Proposal

Support for new threaded comments.

## Motivation

Excel Parity

## Example

Threaded comments. I want to use them to store additional data but have it "hidden". Note comments aren't modern excel.

It appears for threaded comments there are a few changes, first in the `comments##.xml` file:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<comments
	xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
	xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="xr"
	xmlns:xr="http://schemas.microsoft.com/office/spreadsheetml/2014/revision">
	<authors>
		<author>tc={E722680E-88F9-4806-84CE-A0C8E0F639CB}</author>
	</authors>
	<commentList>
		<comment ref="A1" authorId="0" shapeId="0" xr:uid="{E722680E-88F9-4806-84CE-A0C8E0F639CB}">
			<text>
				<t>[Threaded comment]

Your version of Excel allows you to read this threaded comment; however, any edits to it will get removed if the file is opened in a newer version of Excel. Learn more: https://go.microsoft.com/fwlink/?linkid=870924

Comment:
    Hey
Hi
Reply:
    Whats up</t>
			</text>
		</comment>
	</commentList>
</comments>
```
This seems like its purely for legacy support. It adds a comment stating incompatibilities with the version of excel that loads the comment this way and has a "sloppy" overview of the thread.

The `threadedComment##.xml`:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ThreadedComments
	xmlns="http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments"
	xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
	<threadedComment ref="A1" dT="2022-06-01T13:24:40.86" personId="{8D9DB2FF-51B5-4863-B4CB-D5001D7B3245}" id="{E722680E-88F9-4806-84CE-A0C8E0F639CB}">
		<text>Hey
Hi</text>
	</threadedComment>
	<threadedComment ref="A1" dT="2022-06-01T13:25:12.54" personId="{8D9DB2FF-51B5-4863-B4CB-D5001D7B3245}" id="{D0285282-5A03-4F7B-8130-876841640E88}" parentId="{E722680E-88F9-4806-84CE-A0C8E0F639CB}">
		<text>Whats up</text>
	</threadedComment>
</ThreadedComments>
```

The `person.xml`:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<personList
	xmlns="http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments"
	xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
	<person displayName="My Name" id="{8D9DB2FF-51B5-4863-B4CB-D5001D7B3245}" userId="S:email@myad.domain.com::UUID-UUID-UUID-UUID" providerId="AD"/>
</personList>
```

I do not believe I'm missing anything here for threaded comments to work.

Proposing:
- Rename the current comment functions to `note`
- Add `person` items to the sheet
- Add threaded comments to sheet with person as author
- Add replies to threaded comments with author
- Read all

I don't have time to implement myself at the moment. If I find time, this is not done and is desired by the devs I can look into adding support myself. Otherwise, anyone else feel free to pick up and mark as started if you can.

**Comment by ZinoKader** [comment]
Hi @Siemienik! I see that you have closed this issue as completed, but I cannot find any documentation about how to use threaded comments with ExcelJS.
