### ISSUE TITLE
[BUG] Cannot read property 'style' of undefined when adding table to sheet

### ISSUE THREAD

**Issue by sentientmachin3** [exceljs/exceljs#2073]
## 🐛 Bug Report
`addTable` method throws an exception `Cannot read property 'style' of undefined`.

Lib version: 4.3.0

## Steps To Reproduce
- Generate a sheet in a workbook
- Append some table in a cell
  ```javascript
  sheet.addTable({ ref: 'C1', columns: scheduleHeadings, name: '', rows: serializableSchedule }
  ```

`scheduleHeadings` and `serializableSchedule` are two lists of elements. The size of the lists does not appear to affect the error.

## The expected behaviour:
Generate a table without errors

**Comment by risalfajar** [comment]
How do you solve it? I also encounter this problem

**Comment by sentientmachin3** [comment]
Sorry, it has been two years and I was working for another company. I don't have access to the code anymore.

**Comment by risalfajar** [comment]
I've found the problem. It's because the number of columns and rows in `addTable` doesn't match.
