### ISSUE TITLE
[BUG] spliceRows doesn't work on the last row

### ISSUE THREAD

**Issue by ak99372** [exceljs/exceljs#2125]
## 🐛 Bug Report
Removing rows in worksheet with spliceRows works except for the last row.

Lib version: 4.3.0

## Steps To Reproduce

```javascript
worksheet.spliceRows(worksheet.rowCount, 1)

```

## The expected behaviour:

Last row to be removed

## 
Is there another way to delete/remove (last) row than using spliceRow?

**Comment by MCSulphate** [comment]
Hey! I've been having this issue among others recently, I have found/developed a workaround for this. You can use this function to delete rows from a worksheet:

```js
function deleteRows(worksheet, start, count, rowCount) {
	for (let i = 0; i < count; i++) {
		if (rowCount && start + i === rowCount) {
			// Workaround fix for deleting the last row.
			worksheet.spliceRows(start, 1, []);
		}
		else {
			worksheet.spliceRows(start, 1);
		}
	}
}
```

With this, `rowCount` is optional, pass it in if you may be deleting the last row - it will detect when the last row is being deleted; the workaround is to insert a blank row in place of the last row (which works!). I found that deleting multiple rows at once doesn't usually work, so my function deletes them one at a time.

Hope this helps.

**Comment by k8w** [comment]
Still exists at `exceljs@4.3.0`

**Comment by blue32a** [comment]
I have the same problem. `exceljs@4.3.0`

**Comment by blue32a** [comment]
This code has allowed me to work around the problem.
Note, however, that `worksheet.rowCount` will not be reduced because a blank row is inserted at the end.

> ```js
> function deleteRows(worksheet, start, count, rowCount) {
> 	for (let i = 0; i < count; i++) {
> 		if (rowCount && start + i === rowCount) {
> 			// Workaround fix for deleting the last row.
> 			worksheet.spliceRows(start, 1, []);
> 		}
> 		else {
> 			worksheet.spliceRows(start, 1);
> 		}
> 	}
> }
> ```
