### ISSUE TITLE
Unicorn Is Displayed on exceljs GitHub Main Project Page

### ISSUE THREAD

**Issue by sotarules** [exceljs/exceljs#2133]
## 🐛 Bug Report

There seems to be something wrong with:

https://github.com/exceljs/exceljs

When I try to navigate to this page, I get the dreaded Unicorn (too long to load):

![image](https://user-images.githubusercontent.com/5454239/189739485-99543a71-b106-4786-8425-bccb5b1407c4.png)

I have tried multiple browsers and VPN and I get the same issue.  It is possible to navigate to the issues, however, as evidenced by this bug report.  This has been an issue over several days so it is not transitory.

More information in Chrome DevTools Console:

![image](https://user-images.githubusercontent.com/5454239/189740035-d34e24f1-027f-4046-a772-d4b658c4dcd6.png)

**Comment by MetaSeth** [comment]
Looks like it's somehow solved.
