### ISSUE TITLE
[BUG] writeFile not working in AWS ec2 instance

### ISSUE THREAD

**Issue by nikhilkhot46** [exceljs/exceljs#2141]
## 🐛 Bug Report

File is created with 0KB with xlsx extension but no data added, when we download this file and open it in windows excel it shows "excel cannot open the file sample.xlsx because the file format or extension is not valid"

Also we given the 777 permission to folder
Also changed group owner to ubuntu

Lib version: "exceljs": "^4.3.0",

## Steps To Reproduce

```nodejs
const Excel = require('exceljs');

        const fileName = process.cwd()+'simple.xlsx';

        const wb = new Excel.Workbook();
        const ws = wb.addWorksheet('My Sheet');

        ws.getCell('A1').value = 'John Doe';
        ws.getCell('B1').value = 'gardener';
        ws.getCell('C1').value = new Date().toLocaleString();

        const r3 = ws.getRow(3);
        r3.values = [1, 2, 3, 4, 5, 6];

        wb.xlsx
        .writeFile(fileName)
        .then(() => {
            console.log('file created');
        })
        .catch(err => {
            console.log(err.message);
        });
```

## The expected behaviour:
It should write data into the file and also need to open in windows system excel application

**Comment by devwhisper** [comment]
sir may i know what's the solution for this?
