### ISSUE TITLE
[BUG] worksheet.spliceRows() unexpected behavior

### ISSUE THREAD

**Issue by Quartzbell** [exceljs/exceljs#2163]
## 🐛 Bug Report

The result of worksheet.spliceRows() is inconsistent.
We know the horrendous bug of worksheet.spliceRows() that unable to remove the last row has been reported repeatedly.

But we have another bug regarding this method.

## Steps To Reproduce

```javascript
// Let's remove a sheet with 2000 rows
excelAuto.worksheet.getSheetValues().length
// print 2000 


excelAuto.worksheet.spliceRows(100, 2000)
excelAuto.worksheet.getSheetValues().length
// print 2000
// expected result : 100
// we know this bug, when we tried to remove rows greater or equal than the row length, it does nothing

excelAuto.worksheet.spliceRows(100, 1900)
excelAuto.worksheet.getSheetValues().length
// expected result : 100
// print 2000, ouch!


excelAuto.worksheet.spliceRows(100, 1899)
excelAuto.worksheet.getSheetValues().length
// expected result : 101
// print 1999
// now this is getting weirder and weirder

excelAuto.worksheet.spliceRows(100, 1100)
excelAuto.worksheet.getSheetValues().length
// expected result : 900
// print 1200
// Yeah, this method is definitely weird.

```

Aparently the method will mess your worksheet if the second argument is greater than (the first argument + number of the row of the spreadsheet)/2

**Comment by fansOnly** [comment]
> ## 🐛 Bug Report
> The result of worksheet.spliceRows() is inconsistent. We know the horrendous bug of worksheet.spliceRows() that unable to remove the last row has been reported repeatedly.
> 
> But we have another bug regarding this method.
> 
> ## Steps To Reproduce
> // Let's remove a sheet with 2000 rows
> excelAuto.worksheet.getSheetValues().length
> // print 2000 
> 
> 
> excelAuto.worksheet.spliceRows(100, 2000)
> excelAuto.worksheet.getSheetValues().length
> // print 2000
> // expected result : 100
> // we know this bug, when we tried to remove rows greater or equal than the row length, it does nothing
> 
> excelAuto.worksheet.spliceRows(100, 1900)
> excelAuto.worksheet.getSheetValues().length
> // expected result : 100
> // print 2000, ouch!
> 
> 
> excelAuto.worksheet.spliceRows(100, 1899)
> excelAuto.worksheet.getSheetValues().length
> // expected result : 101
> // print 1999
> // now this is getting weirder and weirder
> 
> excelAuto.worksheet.spliceRows(100, 1100)
> excelAuto.worksheet.getSheetValues().length
> // expected result : 900
> // print 1200
> // Yeah, this method is definitely weird.
> Aparently the method will mess your worksheet if the second argument is greater than (the first argument + number of the row of the spreadsheet)/2

This problem hasn't been resolved, why has it been closed
