### ISSUE TITLE
[BUG] Lock Image in a Cell Using just OneCell

### ISSUE THREAD

**Issue by sriharshAmur** [exceljs/exceljs#2196]
## 🐛 Bug Report

To add an image to a worksheet, the following function can be used:
```javascript
worksheet.addImage(imageID, {
       tl: { col: 1, row: 2 },
       br: { col: 2. row: 3 }
});
```

If the image has to be added with specific dimensions, then the `ext` property can be used instead of `br`
```javascript
worksheet.addImage(imageID, {
        tl:  { col: 1, row: 2 },
        ext: { width: width, height: height },
});
```

To lock the image within a cell and to make it "move & size with the cell", the `editAs` property can be set to `twoCell`. 

```javascript
worksheet.addImage(imageID, {
        tl:  { col: 1, row: 2 },
        ext: { width: width, height: height },
        editAs: 'twoCell'
});
```

However, this does not result in the image being locked inside the cell. The image still behaves as a `oneCell` or "Move but don't size with the cells"

Lib version: 4.3.0

## Steps To Reproduce

```javascript
const wb = new ExcelJS.Workbook();
const ws = wb.addWorksheet('images');

// get an image in base64
const anyBase64Image = getBase64Image();

// add the image to the workbook
const imageID = wb.addImage({
    base64: anyBase64Image,
    extension: 'png'
})

// add the image to a worksheet
// assuming the width and height of the image are 100px
ws.addImage(imageID, {
    tl: { col:  1, row: 2 },
    ext: {width: 100, height: 100},
    editAs: 'twoCell'
})

// download the workbook
workbook.xlsx.writeBuffer().then(function (data) {
    const blob = new Blob([data], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    const url = window.URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'excelJS.xlsx';
    anchor.click();
    window.URL.revokeObjectURL(url);
  });
```

## The expected behaviour:

When you open the Excel file and resize the cell, the image SHOULD resize with the cell. However, this is NOT the case.

To know for certain
1. Right-click on the image
2. Click on "Size and Properties"
3. Open the Properties tab

"Move but don't size with cells" is selected rather than "Move and size with cells".

## Possible solution (optional, but very helpful):

In `exceljs/lib/xlsx/xform/drawing/drawing-xform.js`, there is a `getAnchorType` function

```javascript
function getAnchorType(model) {
  const range = typeof model.range === 'string' ? colCache.decode(model.range) : model.range;

  return range.br ? 'xdr:twoCellAnchor' : 'xdr:oneCellAnchor';
}
```

It is checking if `range.br` exists and only then makes a `twoCellAnchor`. However, as seen above from the given example, It should be possible to make `twoCellAnchor` using the `ext` property as well.

In case this is not possible, is there a way to lock an Image within a cell while just specifying the `tr` and `ext` and not the `br`?

**Comment by ChrisJamesC** [comment]
Following what you described and fiddling a bit around, it seems like the following does the trick: 
```
worksheet.addImage(imageID, {
       tl: { col: 1, row: 2 },
       br: { col: 2. row: 3 }, 
       editAs: "twoCell"
});
```
