### ISSUE TITLE
I can't using excel.stream.xlsx

### ISSUE THREAD

**Issue by jasuil** [exceljs/exceljs#2219]
### Discussed in https://github.com/exceljs/exceljs/discussions/2168

<div type='discussions-op-text'>

<sup>Originally posted by **wansoon** November  9, 2022</sup>
I am trying to use Excel.stream.xlsx.WorkbookWriter, 
but I am getting the error 'Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'xlsx')'. 
Maybe it has something to do with the node version? I am using v12.16.3
I installed exceljs with npm i exceljs.</div>

**Comment by datapolitical** [comment]
How did you fix this?

**Comment by jasuil** [comment]
I tried to run it in browser, that is my mistake.
with node server, it works well. But...
I didn't know it does not write response directly.
And it seems that downloaded file is incorrect type of xlsx.
I think it does not related with this issue.

my code.
```javascript

const Excel = require("exceljs");
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader(
    'Content-Type',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  );
  res.setHeader(
	'Content-Disposition',
    'attachment; filename=' + 'test.xlsx',
  );
	
  downloadWorkbook(res);
  res.end();
  
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});


async function downloadWorkbook(res) {
	const options = {
  filename: 'test.xlsx',
  useStyles: true,
  useSharedStrings: true,
  stream: res
};
const workbook = new Excel.stream.xlsx.WorkbookWriter(options);
let  worksheet = workbook.addWorksheet('work-sheet');

 for (i = 0 ; i < 1000000; i++) {
  worksheet.addRow([i,i+2]).commit();
 }

  worksheet.commit();
  await workbook.commit();
}
```

and you can see simlliar issue #209
