### ISSUE TITLE
[Q] How to use addConditionalFormatting function with dataBar type

### ISSUE THREAD

**Issue by gianam65** [exceljs/exceljs#2229]
I have an excel sheet with percentages, i want to add formatting data to render progress like below image but it seem to be not working.

<img width="116" alt="Screen Shot 2023-03-22 at 10 16 48 AM" src="https://user-images.githubusercontent.com/64204862/226793166-e2f29494-1822-4668-87f1-f5bbe85edafd.png">

This is my code.
`worksheet.addConditionalFormatting({
      ref: 'H:H',
      rules: [
        {
          type: 'dataBar',
          priority: 1,
          cfvo: [
            { type: 'num', value: 0 },
            { type: 'num', value: 1 },
          ],
        },
      ],
    })
`

Any help will be appreciated.

**Comment by jybleau** [comment]
Did you find a solution?

**Comment by gianam65** [comment]
I found a solution using chatGPT but I don't remember how I did it, because I quit my job at my old company so I can't give you a solution.

**Comment by jybleau** [comment]
ok :)
Worked fine like that:

```
  worksheet.addConditionalFormatting({
    ref: `A2:A10`,
    rules: [
      {
        type: 'dataBar',
        maxLength: 100,
        color: { argb: "71c6de" },
        cfvo: [
          { type: "num", value: 0 },
          { type: "num", value: 10 }
        ]
      }
    ]
  })
```
