### ISSUE TITLE
Xlsx styles/colors are completely changed after opening and writing

### ISSUE THREAD

**Issue by adrien-candiotti** [exceljs/exceljs#223]
<img width="906" alt="screen shot 2016-11-09 at 11 48 40" src="https://cloud.githubusercontent.com/assets/13977967/20135902/886fecc4-a672-11e6-8e14-24639c4c17bb.png">

**Comment by Siemienik** [comment]
It currently looks it working properly. @adrien-candiotti please reopen if iam wrong

**Comment by kasrak** [comment]
Hi, I'm seeing the same issue on v4.4.0

Here's a sample file:

[sample.xlsx](https://github.com/exceljs/exceljs/files/13291903/sample.xlsx)

When I open and re-save it the background and border colors are changed:

![image](https://github.com/exceljs/exceljs/assets/331454/e86cab80-e260-41f1-bf99-33adf545d740)

**Comment by shimonacarvalho** [comment]
I see the same thing as well 4.3.0

**Comment by shimonacarvalho** [comment]
Oh I think the issue was that the file was last saved in Numbers app on mac.
