### ISSUE TITLE
Add stop if true boolean settings in Conditional formatting

### ISSUE THREAD

**Issue by paweenwat-man** [exceljs/exceljs#2233]
I see the Python Excel library has this option, but I needed to use to get the same result as my Python code do in my client side.

## Example

```
worksheet.addConditionalFormatting({
  ref: `${startColumnLetter}${this.worksheet.rowCount}:${endColumnLetter}${this.worksheet.rowCount}`,
  rules: [
    {
      type: 'expression',
      formulae: [`$E${this.worksheet.rowCount} < ${this.missDistance * 1000}`],
      style: {
        font: { color: { argb: 'FFFFFFFF' } },
        fill: { type: 'pattern', pattern: 'solid', bgColor: { argb: 'FFFF0000' } },
      },
      stopIfTrue: true,
    },
    {
      type: 'expression',
      formulae: [`$D${this.worksheet.rowCount} > ${this.probability}`],
      style: {
        font: { color: { argb: 'FF000000' } },
        fill: { type: 'pattern', pattern: 'solid', bgColor: { argb: 'FFFFD966' } },
      },
      stopIfTrue: true,
    }
  ]
})
```

**Comment by Blackhol3** [comment]
Why has this issue been marked as completed? `stopIfTrue` is still not available.

**Comment by paweenwat-man** [comment]
I don't know, because I've been inactive too long. First, I used ExcelJS to export the data from the client side, but my server is running with Python, so I could implement API to export the data from the server using `openpyxl` instead.

The problem still exists on the server running with Node.js

**Comment by guillaumeduboc** [comment]
thanks @Blackhol3 for the fix 😁 
can we reopen the issue ?

**Comment by Arvid-L** [comment]
I'd really appreciate this feature as well. Can someone with write-access review @Blackhol3's fix?

**Comment by Azbesciak** [comment]
@Siemienik Could you take a look at the MR, as you closed the issue :)?
