### ISSUE TITLE
[BUG] Typescript error 

### ISSUE THREAD

**Issue by JBarzdo** [exceljs/exceljs#2250]
## 🐛 Bug Report

Simple problem with TS and lib itself. 
I have no typings at all when installed it in pure node.js TS project.
![image](https://user-images.githubusercontent.com/79201655/233848534-23d540d0-d342-4933-adab-414c87af8e1f.png)

Lib version: 4.3.0

## Steps To Reproduce

Added it by 

```javascript
yarn add exceljs
```

Then used as below:

```javascript
import ExcelJS from 'exceljs';
const workbook = new ExcelJS.Workbook();
```

**Comment by Siemienik** [comment]
Please try this import statement
```
import * as ExcelJS from 'exceljs';
const workbook = new ExcelJS.Workbook();
```

**Comment by Siemienik** [comment]
This solution was proposed during our last Merge Fest. We regularly organize such meetings on our Discord server. Join us to have a greater influence on the future of ExcelJS and receive direct support through chat on [Discord](htpps://discord.gg/siema).
