### ISSUE TITLE
[BUG] File created with stream.xlsx.WorkbookWriter can not be opened

### ISSUE THREAD

**Issue by mravey** [exceljs/exceljs#2274]
## 🐛 Bug Report

I'm trying to create a file with stream.xlsx.WorkbookWriter, but the created file can not be opened by Excel then.

Lib version: 4.3.0

## Steps To Reproduce

```javascript
 const w = new Excel.stream.xlsx.WorkbookWriter({
    filename: 'test.xlsx'
});
const s = w.addWorksheet('membres');

s.addRow(['one', 'two']).commit();

await w.commit();
```

When I try to open `test.xlsx` I get an error message from Excel. I unzipped the file created at `workbook.xml` is empty.

**Comment by matchdav** [comment]
I'm experiencing a similar issue where commits appear to not be carried out.

**Comment by benrcrane** [comment]
I was having this issue and updating [archiver](https://www.npmjs.com/package/archiver) to the latest version (5.3.1) which is a dependency of `exceljs` fixed it.

**Comment by zurmokeeper** [comment]
@mravey Can you please see what the archiver version is in your exceljs?

**Comment by mravey** [comment]
In exceljs dependencies I have `"archiver": "^5.0.0"` and the installed version is `5.2.0`

**Comment by zurmokeeper** [comment]
@mravey Receive an upgrade to the latest and try again?

**Comment by zurmokeeper** [comment]
@mravey Update `archiver`, you can try npm i exceljs, reload the dependencies, exceljs should not lock the version of `archiver`, reinstallation should automatically install the latest version of `archiver`, if not installed to the latest version of `archiver`, you can try again after deleting the node_modules reinstallation. Make sure `archiver `is up to date and try again.

**Comment by mravey** [comment]
It works with the latest version of archiver. Thanks.

**Comment by zurmokeeper** [comment]
@mravey Since it seems that exceljs is no longer releasing new versions, you can pay attention to this [project](https://github.com/zurmokeeper/excelize). [@zurmokeeper/exceljs](https://www.npmjs.com/package/@zurmokeeper/exceljs)
