### ISSUE TITLE
[BUG] Table gets destroyed after loading the Excel that is included in

### ISSUE THREAD

**Issue by GeorgePals** [exceljs/exceljs#2277]
## 🐛 Bug Report

I'm trying to load and modify an Excel file (.xlsx) with ExcelJS, that has a table in it. However, the table is not loaded properly.

In my scenario, the Excel has 3 sheets. One of them (e.g. Sheet_1), has a table in it.
The issue is that every time that I'm loading the Excel, ExcelJS breaks the table. Even if I don't modify it, or even if I do not load the sheet that includes it, the table gets "destroyed".

When I'm trying to open the file with Excel, it tells me that the Workbook got repaired and under the technical details I see:
`Removed Records: AutoFilter from /xl/tables/table1.xml part (Table)`

I've tried everything I could think of. I also tried creating the Excel file with the Web/Desktop version (and even with LibreOffice! lol).
When I'm trying to get the table's parameters and data with:

```
  const worksheet = workbook.getWorksheet("sheet1");
  const table = worksheet.getTable("table1");
  console.log({ table });
```
I get:

```
{
  table: Table {
    worksheet: undefined,
    table: {
      name: 'table1',
      displayName: 'table1',
      tableRef: 'D28:G29',
      totalsRow: false,
      headerRow: false,
      columns: [Array],
      autoFilterRef: 'D28:G29',
      style: [Object]
    }
  }
}
```
Of course, the table has its headers already set and is inside a worksheet, so the "undefined" values are totally wrong.

Lib version: 4.3.0

## Steps To Reproduce

Just try to load (I'm using a buffer) and modify an Excel, that has a table inside it.

Any ideas on this?
I've found this: https://github.com/exceljs/exceljs/issues/1615, but it didn't really help.
Also, I do not want to use a fork.

Thank you!

**Comment by hyperliskdev** [comment]
I am still having this issue and am wondering why this issue was closed without any futher discussion.

**Comment by opgbaudouin** [comment]
This seems to resolve this issue:

I.e. Add, then commit()

```
 const table = homeSheet.addTable({
        name: `MyTable`,
        ref: 'A4',
        headerRow: true,
        totalsRow: false,
        style: {
            theme: 'TableStyleDark3',
            showRowStripes: true,
        },
        columns: [
            {name: 'Programme', filterButton: true}
        ],
        rows: [
            ['Hello']
        ]
    });


    table.commit();
```
