### ISSUE TITLE
Unable to read cell value is time

### ISSUE THREAD

**Issue by hohnworld** [exceljs/exceljs#2287]
# Unable to read cell value is time
## Here are the code and attachments
```javascript
const Excel = require("exceljs");
const excelfile = "a.xlsx";
var workbook = new Excel.Workbook();
workbook.xlsx.readFile(excelfile).then(function () {
  var worksheet = workbook.getWorksheet(1); //获取第一个worksheet
  worksheet.eachRow(function (row, rowNumber) {
    row.eachCell(function (cell, colNumber) {
      if (cell.type == 4) {
        console.log(cell.value); //Sat Dec 30 1899 18:11:43 GMT+0805 (中国标准时间)
        console.log(cell.style.numFmt); //'h:mm'
        // how to get the right value 10:06
      }
    });
  });
});
```
[a.xlsx](https://github.com/exceljs/exceljs/files/11806006/a.xlsx)

**Comment by hohnworld** [comment]
[Edit in StackBlitz](https://stackblitz.com/edit/stackblitz-starters-2bwwrp?file=index.js)

**Comment by zurmokeeper** [comment]
@hohnworld 你只是要格式化时间吗？如果是的话，用moment.js或者day.js或者是其他库就能做到了？

**Comment by hohnworld** [comment]
> @hohnworld 你只是要格式化时间吗？如果是的话，用moment.js或者day.js或者是其他库就能做到了？

获取到的不是时间，而是日期，并且还没有找到转换的规律：譬如Sat Dec 30 1899 18:11:43 GMT+0805 (中国标准时间)怎么转时间10:06

**Comment by zurmokeeper** [comment]
@hohnworld 
```
const Excel = require('exceljs');
const moment = require('moment');
const excelfile = 'a.xlsx';
var workbook = new Excel.Workbook();
workbook.xlsx.readFile(excelfile).then(function () {
  var worksheet = workbook.getWorksheet(1); //获取第一个worksheet
  worksheet.eachRow(function (row, rowNumber) {
    row.eachCell(function (cell, colNumber) {
      if (cell.type == 4) {
        console.log(cell.value); //Sat Dec 30 1899 18:11:43 GMT+0805 (中国标准时间)
        console.log(cell.style.numFmt); //'h:mm'
        console.log(moment(cell.value).format('h:mm'));
        console.log(moment(cell.value).format('H:mm'));
        // how to get the right value 10:06
      }
    });
  });
});

控制台输出：
1899-12-30T10:06:00.000Z
h:mm
6:11 （这个是你想要的吗？）
18:11 （这个是你想要的吗？）
```

**Comment by hohnworld** [comment]
> @hohnworld
> 
> ```
> const Excel = require('exceljs');
> const moment = require('moment');
> const excelfile = 'a.xlsx';
> var workbook = new Excel.Workbook();
> workbook.xlsx.readFile(excelfile).then(function () {
>   var worksheet = workbook.getWorksheet(1); //获取第一个worksheet
>   worksheet.eachRow(function (row, rowNumber) {
>     row.eachCell(function (cell, colNumber) {
>       if (cell.type == 4) {
>         console.log(cell.value); //Sat Dec 30 1899 18:11:43 GMT+0805 (中国标准时间)
>         console.log(cell.style.numFmt); //'h:mm'
>         console.log(moment(cell.value).format('h:mm'));
>         console.log(moment(cell.value).format('H:mm'));
>         // how to get the right value 10:06
>       }
>     });
>   });
> });
> 
> 控制台输出：
> 1899-12-30T10:06:00.000Z
> h:mm
> 6:11 （这个是你想要的吗？）
> 18:11 （这个是你想要的吗？）
> ```
不是，我读取的那个单元格内容是10:06

**Comment by zurmokeeper** [comment]
@hohnworld 

1899-12-30T10:06:00.000Z 表示的是一个日期和时间，使用了 UTC（协调世界时）作为参考。这个时间戳实际上对应于 Sat Dec 30 1899 18:11:43 GMT+0805。

具体的转换过程如下：

首先，根据时间戳中的 "Z"，可以确定这个时间戳是使用的 UTC 时间（协调世界时）。

然后，在计算机中，时间戳是相对于特定的基准时间进行计算的，通常使用的是 Unix 时间（1970 年 1 月 1 日 00:00:00 UTC）作为基准点。而微软 Excel 在保存日期和时间时采用了不同的基准时间，即 1899 年 12 月 30 日 00:00:00 UTC。
因此，当将这个时间戳转换为本地时间时，需要考虑计算机系统所使用的时区。在您提供的情况下，假设您的计算机位于中国标准时间（GMT+0805）时区。

根据 UTC 时间和时区的差异，将 UTC 时间调整为本地时间。对于中国标准时间（GMT+0805），需要将时间增加 8 小时又 5 分钟，以获得正确的本地时间。

最终，将时间戳转换为本地日期和时间，即为所得结果。

所以这应该是不是exceljs的bug，可能就是一个时区的转换吧。

```
const Excel = require('exceljs');
const excelfile = 'a.xlsx';
const moment = require('moment');
var workbook = new Excel.Workbook();
workbook.xlsx.readFile(excelfile).then(function () {
  var worksheet = workbook.getWorksheet(1); //获取第一个worksheet
  worksheet.eachRow(function (row, rowNumber) {
    row.eachCell(function (cell, colNumber) {
      if (cell.type == 4) {
        console.log(cell.value); //Sat Dec 30 1899 18:11:43 GMT+0805 (中国标准时间)
        console.log(cell.text);
        console.log(cell.style.numFmt); //'h:mm'
         how to get the right value 10:06
        console.log(moment(cell.value).utc().format('h:mm'));   // 手动设置下时区就好了 .utc()
        console.log(moment(cell.value).utc().format('H:mm'));
      }
    });
  });
});
```

**Comment by hohnworld** [comment]
> @hohnworld
> 
> 1899-12-30T10:06:00.000Z 表示的是一个日期和时间，使用了 UTC（协调世界时）作为参考。这个时间戳实际上对应于 Sat Dec 30 1899 18:11:43 GMT+0805。
> 
> 具体的转换过程如下：
> 
> 首先，根据时间戳中的 "Z"，可以确定这个时间戳是使用的 UTC 时间（协调世界时）。
> 
> 然后，在计算机中，时间戳是相对于特定的基准时间进行计算的，通常使用的是 Unix 时间（1970 年 1 月 1 日 00:00:00 UTC）作为基准点。而微软 Excel 在保存日期和时间时采用了不同的基准时间，即 1899 年 12 月 30 日 00:00:00 UTC。 因此，当将这个时间戳转换为本地时间时，需要考虑计算机系统所使用的时区。在您提供的情况下，假设您的计算机位于中国标准时间（GMT+0805）时区。
> 
> 根据 UTC 时间和时区的差异，将 UTC 时间调整为本地时间。对于中国标准时间（GMT+0805），需要将时间增加 8 小时又 5 分钟，以获得正确的本地时间。
> 
> 最终，将时间戳转换为本地日期和时间，即为所得结果。
> 
> 所以这应该是不是exceljs的bug，可能就是一个时区的转换吧。
> 
> ```
> const Excel = require('exceljs');
> const excelfile = 'a.xlsx';
> const moment = require('moment');
> var workbook = new Excel.Workbook();
> workbook.xlsx.readFile(excelfile).then(function () {
>   var worksheet = workbook.getWorksheet(1); //获取第一个worksheet
>   worksheet.eachRow(function (row, rowNumber) {
>     row.eachCell(function (cell, colNumber) {
>       if (cell.type == 4) {
>         console.log(cell.value); //Sat Dec 30 1899 18:11:43 GMT+0805 (中国标准时间)
>         console.log(cell.text);
>         console.log(cell.style.numFmt); //'h:mm'
>          how to get the right value 10:06
>         console.log(moment(cell.value).utc().format('h:mm'));   // 手动设置下时区就好了 .utc()
>         console.log(moment(cell.value).utc().format('H:mm'));
>       }
>     });
>   });
> });
> ```

学到了，谢谢

**Comment by zurmokeeper** [comment]
@hohnworld 由于exceljs后续可能不会发新版本，可以关注下这个项目 [project](https://github.com/zurmokeeper/excelize). [@zurmokeeper/exceljs](https://www.npmjs.com/package/@zurmokeeper/exceljs)
