### ISSUE TITLE
[BUG] Reading accented characters cause problem from Excel file

### ISSUE THREAD

**Issue by bahadirarslan** [exceljs/exceljs#2288]
## 🐛 Bug Report

I am trying to read a file containing Polish-accented characters. Everything seems normal, but JavaScript cannot match it when I check with the equal operator, `indexOf`, or `includes` function.

Lib version: 4.3.0

## Steps To Reproduce

For example, the word is dzień.

```javascript
const columns = ["dzień","and so on"];
const workbook = new excelJs.Workbook();
await workbook.xlsx.readFile(filePath);
const dataSheet = workbook.getWorksheet('Sheet');
var row = dataSheet.getRow(1);
var rowColumn = row.values[1];
console.log(MD5(rowColumn.toString()).toString());
console.log(MD5(columns[0]).toString());
console.log(MD5('dzień').toString());
console.log(rowColumn == columns[0]);
console.log('#' + rowColumn + '#')
console.log('#' + columns[0] + '#');
```

Here is the console output of the code above

```
47b1c8910533a68444a574ca2907ec29
b46f08c14c441ac65c75d15457f63db4
b46f08c14c441ac65c75d15457f63db4
false
#dzień#
#dzień#
```

**Comment by zurmokeeper** [comment]
@bahadirarslan Can you provide your excel file and add the MD5 specific code?

**Comment by bahadirarslan** [comment]
> @bahadirarslan Can you provide your excel file and add the MD5 specific code?

For MD5, I used crypto-js library

`var MD5 = require("crypto-js/md5");`
A sample excel file is attached.

[polish.xlsx](https://github.com/exceljs/exceljs/files/11826801/polish.xlsx)

**Comment by zurmokeeper** [comment]
@bahadirarslan  Your excel cell 'dzień' has an extra space in front of it，remove the space is correct


![image](https://github.com/exceljs/exceljs/assets/25943604/01d476b7-0275-4b71-8109-9e0705b291a8)

```
(async ()=>{
    const columns = ["dzień","and so on"];
    const workbook = new excelJs.Workbook();
    await workbook.xlsx.readFile('polish.xlsx');
    const dataSheet = workbook.getWorksheet('Sheet');
    var row = dataSheet.getRow(1);
    var rowColumn = row.values[1];
    console.log(MD5(rowColumn.toString()).toString());
    console.log(MD5(columns[0]).toString());
    console.log(MD5('dzień').toString());
    console.log(rowColumn == columns[0]);
    for (let index = 0; index < rowColumn.length; index++) {
        const element = rowColumn[index];
        console.log('#index-->' + element + '<--#')
    }
    console.log('#' + rowColumn.length + '#' + columns[0].length)
    console.log('#' + rowColumn + '#')
    console.log('#' + columns[0] + '#');
})()
```

**Comment by bahadirarslan** [comment]
This is unbelievable.
Thank you, I've never thought such a thing.

**Comment by zurmokeeper** [comment]
@bahadirarslan Since it seems that exceljs is no longer releasing new versions, you can pay attention to this [project](https://github.com/zurmokeeper/excelize). [@zurmokeeper/exceljs](https://www.npmjs.com/package/@zurmokeeper/exceljs)

**Comment by bahadirarslan** [comment]
I will have a look, thank you.
