### ISSUE TITLE
Update moment library to >2.15.1 (fixes a security bug)

### ISSUE THREAD

**Issue by parmentf** [exceljs/exceljs#229]
BitHound signal exceljs as being unsecure due its moment version: https://www.bithound.io/github/Inist-CNRS/lodex/master/dependencies/npm/exceljs

Here are the attached advisory details: https://snyk.io/vuln/npm:moment:20161019

Thanks in advance!

**Comment by Siemienik** [comment]
currently it is `"moment": ">=2.19.3"`
