### ISSUE TITLE
[BUG] No Workbooks found in xls Buffer

### ISSUE THREAD

**Issue by ingodahn** [exceljs/exceljs#2292]
## 🐛 Bug Report

When I read the attached xls file, I get an empty list of worksheets. The code works well with data read from xlsx files.

Lib version: ^4.3.0

## Steps To Reproduce

```javascript
import * as Excel from 'exceljs'

var reader = new FileReader();
 reader.onload = e => {
  dataBuffer = e.target.result;
   console.log('dataString Bytes', dataBuffer.length)
    this.handleData(dataBuffer);
};
reader.readAsArrayBuffer(f);

handleData(dataBuffer) {
  const workbook = new Excel.Workbook();
  workbook.xlsx.load(dataBuffer).then(() => {
   console.log('loaded',workbook.worksheets.length,'worksheets')
}
```
This prints on the console the number of bytes of the buffer and reports 0 found worksheets. No other error is flagged.

## The expected behaviour:

The reported number of worksheets should be 1.

## Possible solution (optional, but very helpful):

File to be read in:

[TestdatenOpal.xls](https://github.com/exceljs/exceljs/files/11859463/TestdatenOpal.xls)

**Comment by zurmokeeper** [comment]
@ingodahn exceljs does not support reading excel files with xls suffix, change[ xlsx](https://www.npmjs.com/package/xlsx) this library it

**Comment by ingodahn** [comment]
Thanks for the info.

**Comment by zurmokeeper** [comment]
@ingodahn Since it seems that exceljs is no longer releasing new versions, you can pay attention to this [project](https://github.com/zurmokeeper/excelize). [@zurmokeeper/exceljs](https://www.npmjs.com/package/@zurmokeeper/exceljs)
