### ISSUE TITLE
[BUG] Large data set creates corrupt Excel file with "we found a problem with some content" error

### ISSUE THREAD

**Issue by morganp-dev** [exceljs/exceljs#2299]
## 🐛 Bug Report

A large data set is causing a corrupt Excel file to be created that displays this error when opened: 
"we found a problem with some content".

The excel report is generated on the server. With real data, it works fine for ~45,000 rows, but creates a corrupt file for 47,500+ rows. 

I believe the issue has to do with the total size of the data rather than the actual number of rows, since if all the values are set to "1", the report is generated without issues for 50,000+ rows.

Lib version: 4.3.0

## Steps To Reproduce

1. A request is sent from the client.
2. Data is fetched from an SQL database.
3. The Excel report is generated with the ExcelJS library.
4. The report is streamed back to the client.

```javascript
async function exportReport(req, res, next) {
  const workbook = new Excel.Workbook();
  const worksheet = workbook.addWorksheet('My Sheet');

  worksheet.columns = [
    { key: 'a' },
    { key: 'b' },
    { key: 'c' },
    { key: 'd' },
    { key: 'e' },
    { key: 'f' },
    { key: 'g' },
    { key: 'h' },
    { key: 'i' },
    { key: 'j' },
    { key: 'k' },
    { key: 'l' },
    { key: 'm' },
    { key: 'n' },
    { key: 'o' }
  ];

  worksheet.addRow({
    a: 'Column A',
    b: 'Column B',
    c: 'Column C',
    d: 'Column D',
    e: 'Column E',
    f: 'Column F',
    g: 'Column G',
    h: 'Column H',
    i: 'Column I',
    j: 'Column J',
    k: 'Column K',
    l: 'Column L',
    m: 'Column M',
    n: 'Column N',
    o: 'Column O',
  });

  const mockObject = {
    propA: 'A',
    propB: 'B',
    propC: 'C',
    propD: 'D',
    propE: 'E',
    propF: 'F',
    propG: 'G',
    propH: 'H',
    propI: 'I',
    propJ: 'J',
    propK: 'K',
    propL: 'L',
    propM: 'M',
    propN: 'N',
    propO: 'O',
  };

  let mockObjects = [];

  for (let i = 0; i < 100000; i++) {
    mockObjects.push(mockObject);
  }

  for (let i = 0; i < mockObjects.length; i++) {
    const data = mockObjects[i];
    const row = worksheet.addRow({
      a: data.propA,
      b: data.propB,
      c: data.propC,
      d: data.propD,
      e: data.propE,
      f: data.propF,
      g: data.propG,
      h: data.propH,
      i: data.propI,
      j: data.propJ,
      k: data.propK,
      l: data.propL,
      m: data.propM,
      n: data.propN,
      o: data.propO,
    });

    row.commit();
  }

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename=report.xlsx`);

  await workbook.xlsx.write(res);
}
```

## The expected behaviour:

The Excel report generated by ExcelJS should be a valid file even for a large number of rows (100,000+).

## Possible solution (optional, but very helpful):

I believe this might have to do with a memory issue or an issue compiling an Excel sheet when the data is over a certain size.

- I tried using "row.commit()" after adding each row in order to release the Row object from memory.
- I also tried streaming the data back to the client in different ways, but none of these other options worked.
- When the values for all the cells is set to "1", it is possible to generate 50,000+ rows without issue, but with real data, the file is corrupt.

**Comment by morganp-dev** [comment]
The problem does not seem to be related to the ExcelJS library after all.

**Comment by shenX-2021** [comment]
@morganp-dev Hi, I suffer from this problem too. How did you fix this problem? What is the problem relative?

**Comment by morganp-dev** [comment]
@shenX-2021 if I remember correctly, the problem was that we were streaming the request. This means that a small file would be sent in a single chunk, but a large file would be sent in multiple chunks. So I just needed to handle processing multiple chunks in the front-end before trying to use the data.
