### ISSUE TITLE
cannot read propeety getcell of undefined while writing in to the workbook

### ISSUE THREAD

**Issue by sandeepSathish** [exceljs/exceljs#23]
var workbook = new Excel.Workbook();
workbook.xlsx.readFile(filename)
  .then(function() {
    // edit worksheet
    var worksheet = workbook.getWorksheet("My Sheet");
    worksheet.getCell("A1") = new Date();
  })
  .then(function() {
   return workbook.xlsx.writeFile(filename)
  })
  .then(function() {
    console.log("Done");
  });
![capture](https://cloud.githubusercontent.com/assets/13032708/8516951/77e9a052-23d8-11e5-846a-1a234bef8483.PNG)

**Comment by guyonroche** [comment]
Sorry it's taken me so long to reply, I've been v.focussed on other work lately.
looking at your code I can see a problem with the line 
```javascript
worksheet.getCell("A1") = new Date();
```
This line is trying to assign a value to the return result of a function call (not possible). You probably meant:
```javascript
worksheet.getCell("A1").value = new Date();
```
