### ISSUE TITLE
Formula not applied!

### ISSUE THREAD

**Issue by ilijaveselica** [exceljs/exceljs#230]
In Excel Viewer C6 cell will not be displayed at all:
`sheet.getCell("C6").value = {formula:"SUM(C2:C5)"};`
But Libre Office (Linux) will display cell and apply formula correctly.
If I put it this way it will be displayed in Excel also:
`sheet.getCell("C6").value = {formula:"SUM(C2:C5)", result: 5};`
But in this case result field needs to be calculated programatically instead in Excel. Is it even possible to apply formula to a cell so that Excel makes a calculation?

**Comment by konstantinvlasenko** [comment]
It doesn't show the calculation's result in a cell in VIEW mode w/o a result property. But it will show if you enable edit mode.

**Comment by guyonroche** [comment]
I don't think there's much I can do about that - that's behaviour in Excel itself. Modifying the document while not in edit-mode is probably against Excel's principles so I'm afraid unless you know the actual value when you create the document then there's not much that can be done.

**Comment by benbroadley** [comment]
I'm replying to this quite a while after it was asked but in case anyone else runs into this difficulty:

I got Excel to use the formula by setting the `result` of the cell to undefined. When Excel opens the file, it can see that there is no result for that cell and this prompts a recalculation. In the example above, you would do the following:

`sheet.getCell("C6").result = undefined`

**Comment by nkagarw** [comment]
Hi, I tried to set the result to undefined :

`workbook.getWorksheet(1).getCell('N6').result = undefined;
`

But i'm getting this error :

` (node:6392) UnhandledPromiseRejectionWarning: TypeError: Cannot set property result of [object Object] which has only a getter`

Looks like cell.result is just a getter. How can I set the result to undefined ?

**Comment by Siemienik** [comment]
@nkagarw 
1. [`result` is getter](https://github.com/exceljs/exceljs/blob/master/lib/doc/cell.js#L227)
2. to set result please access by `workbook.getWorksheet(1).getCell('N6').value.result = undefined`
3. It's recommended to check condition `cell.type ===Cell.Types.Formula' before

**Comment by nkagarw** [comment]
Unfortunately, setting cell.value.result to undefined is not causing excel to recalculate the formula automatically when I open the output in excel. I'm forced to do Ctrl+Alt+Shift+F9 to recalculate the formula. 

I simply have A1 set to value 'Hello' and A2 set to '=A1' in the original sheet. I read it using exceljs and update A1.value='Hi' and A2.value.result=undefined. Then, I write it using exceljs and open the resultant file in excel. Excel still shows 'Hello' in A2 instead of 'Hi' until I hit Ctrl+Alt+Shift+F9.

**Comment by Siemienik** [comment]
@nkagarw thanks

**Comment by mercmobily** [comment]
I know this issue is closed and I am late to the party, but please allow me to leave my 2c:

* this precious, priceless hint should be documented
* there should be a method to set a cell as "To recalculate", to be used if exceljs modifies a cell that should trigger a recalculation
