### ISSUE TITLE
[BUG] Out-of-memory with lots of cells

### ISSUE THREAD

**Issue by hfhchan-plb** [exceljs/exceljs#2303]
## 🐛 Bug Report

node crashes with cryptic error messages like:

```
#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0x17ccb4f08
 1: 0x100acbc2c node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/Users/user/Library/Application Support/fnm/node-versions/v18.14.2/installation/bin/node]
 2: 0x1019fdd24 V8_Fatal(char const*, ...) [/Users/user/Library/Application Support/fnm/node-versions/v18.14.2/installation/bin/node]
 3: 0x100d3f1e8 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/Users/user/Library/Application Support/fnm/node-versions/v18.14.2/installation/bin/node]
 4: 0x100ecb4d0 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2>>::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/user/Library/Application Support/fnm/node-versions/v18.14.2/installation/bin/node]
 5: 0x1010cb2f0 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/Users/user/Library/Application Support/fnm/node-versions/v18.14.2/installation/bin/node]
 6: 0x10142104c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/user/Library/Application Support/fnm/node-versions/v18.14.2/installation/bin/node]
```

Lib version: 4.3.0

## Possible solution:

It appears that commenting out the following code in styles-xform.js resolves the issue.

```
if (this.weakMap) {
  this.weakMap.set(model, styleId);
}
```

**Comment by hfhchan-plb** [comment]
See also: https://github.com/exceljs/exceljs/issues/2041.

It seems weak maps cause more issues than they solve.

**Comment by hfhchan-plb** [comment]
Code to disable the weakMap via monkey patching each instance:

```

/**
 * Disables the weak map on the style object.
 *
 * See https://github.com/exceljs/exceljs/issues/2041 and https://github.com/exceljs/exceljs/issues/2303.
 */
function disableWeakMap(xlsx: any) {
  const prepareModel = xlsx['prepareModel'];
  xlsx['prepareModel'] = (model: any, options: any) => {
    // Clear out model.styles.weakMap when model.styles is set
    Object.defineProperty(model, 'styles', {
      get() {
        return this._styles;
      },
      set(styles) {
        styles.weakMap = null;
        this._styles = styles;
      },
    });

    prepareModel.call(xlsx, model, options);
  };
}
```

Call on `disableWeakMap(workbook.xlsx);` before calling `workbook.xlsx.write` / `workbook.xlsx.writeFile`.

**Comment by zurmokeeper** [comment]
@hfhchan-plb Can you provide me with an excel file?

**Comment by hfhchan-plb** [comment]
This happens when writing out a file.

We are generating a workbook with 8 sheets in the following configuration:

```
sheet 0: {rows: 97, maxColLength: 19}
sheet 1: {rows: 18527, maxColLength: 31}
sheet 2: {rows: 18527, maxColLength: 272}
sheet 3: {rows: 18527, maxColLength: 46}
sheet 4: {rows: 18527, maxColLength: 62}
sheet 5: {rows: 18527, maxColLength: 26}
sheet 6: {rows: 42, maxColLength: 25}
sheet 7: {rows: 41, maxColLength: 2}
```

V8 crashes subsequently after we call `workbook.xlsx.write()`.

**Comment by hfhchan-plb** [comment]
OK this fix worked once but then it stopped working. I'm still not sure how 8,099,274 cells can cause on OOM, which is well under 256 M items per array limit on V8. Will investigate more.

**Comment by hfhchan-plb** [comment]
I tried setting a breakpoint at the start and end of in `worksheet-xform.js` `render()`. Here are my results:

Sheet 0 [start]: model.dimensions: `A1:S97`
Sheet 0 [end]: xmlStream._xml.length: `44834`
Sheet 1 [start]: model.dimensions: `A1:AG18527`
Sheet 1 [end]: xmlStream._xml.length: `13267361`
Sheet 2 [start]: model.dimensions: `A1:KS18527`
[crash]

**Comment by hfhchan-plb** [comment]
After patching `pushAttribute()` in `xml-stream.js` to generate only one item instead of multiple:

Sheet 0 [start]: model.dimensions: `A1:S97`
Sheet 0 [end]: xmlStream._xml.length: `26370`
Sheet 1 [start]: model.dimensions: `A1:AG18527`
Sheet 1 [end]: xmlStream._xml.length: `8480265`
Sheet 2 [start]: model.dimensions: `A1:KS18527`
Sheet 2 [end]: xmlStream._xml.length: `84042137`
[no more crash, but OOM]
