### ISSUE TITLE
How to get  picture blob ？i need to upload for mutil

### ISSUE THREAD

**Issue by pengcheng433** [exceljs/exceljs#2307]
example:
const worksheet = workbook.getWorksheet( 'Sheet1' )
const images = worksheet.getImages()
console.log( worksheet )
console.log( images )

![image](https://github.com/exceljs/exceljs/assets/49235483/7b8f8947-d358-44b9-872e-6bab981ece56)
![image](https://github.com/exceljs/exceljs/assets/49235483/e66d4b10-4a7d-42ce-bb75-6861e93a29cf)

but i need imageFile type to upload image。

**Comment by zurmokeeper** [comment]
@pengcheng433  That's good.

```
const worksheet = workbook.getWorksheet( 'Sheet1' )
const images = worksheet.getImages()
console.log( worksheet )
console.log( images )
  for (const { imageId } of images) {
    const image = workbook.getImage(imageId);
    console.log('image-->', image);
  }

{
  type: 'image',
  name: 'image1',
  extension: 'png',
  buffer: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 01 77 00 00 02 9b 08 06 00 00 00 0e ae ca 9a 00 00 00 01 73 52 47 42 00 ae ce 1c e9 00 00 00 04 ... 33633 more bytes>,
  index: 0
}
```

**Comment by pengcheng433** [comment]
thanks bro， and yes i also reslove this 

   const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.readFile(filePath);
    const worksheet = workbook.getWorksheet("Sheet1");
    const images = worksheet.getImages();
    console.log("images", images).length;
    var image = workbook.getImage(0);
    console.log("image", image);
    console.log(image.buffer);

**Comment by zurmokeeper** [comment]
@pengcheng433 Interested in keeping an eye on [this program](https://github.com/zurmokeeper/excelize), which after all has been largely unmaintained.
