### ISSUE TITLE
[F] add support for “Center Across Selection”

### ISSUE THREAD

**Issue by amitm02** [exceljs/exceljs#2314]
## 🚀 Feature Proposal

Add support in excelJS to define “center across selection” for a group of cells. 

## Motivation

Center Across Selection: This Excel feature allows you to center text across a selection of cells without merging them. It gives a similar visual effect to merging cells, but without the negative side effects. Each cell in the selection remains a separate, individual cell, so there’s no loss of data and no problems with sorting, filtering, or cell navigation. This makes it a good alternative to cell merging for creating headers or labels that span multiple columns.

In general, if you need to center text across a range of cells, it’s usually better to use “Center Across Selection” rather than merging cells. And if you’re trying to organize your data or create a complex model, outlines can be a very useful tool.

**Comment by zurmokeeper** [comment]
@amitm02 Do other js excel libraries have this or similar functionality you are talking about? Or is there a library in another language that implements it? Can I go for reference or can I record the screen? In office or other excel software operation process? I don't really understand what kind of functionality you are looking for.

**Comment by amitm02** [comment]
I do not know if other library support this functionality.
I know it is an existing feature of  Microsoft Excel.
e.g
https://kb.wisc.edu/helpdesk/page.php?id=119089
https://www.youtube.com/watch?v=1KP901eZcpg

**Comment by zurmokeeper** [comment]
@amitm02 

This` "Center Across Selection"` feature is a bit questionable:
1: It seems that only a single row of merged cells, selected multiple rows is only the value of those rows can be merged successfully?
2: When 2 columns each have a cell with a value, but I `'Center Across Selection'` when I chose 3 columns, the last 2 rows of that cell will be merged, the first row of that does not merge, which may be confusing.

So this `" Center Across Selection"` function may be convenient in some cases, but in the program operation may be merged function will be better to use.

**Comment by amitm02** [comment]
Got it. Thanks

**Comment by zurmokeeper** [comment]
@amitm02 exceljs doesn't look like it's maintained by many people, if you're interested, you can follow this project（[@zurmokeeper/exceljs](https://github.com/zurmokeeper/excelize)）, issue still has quite a few features to be improved, and you can mention any new ideas. Welcome to join!
