### ISSUE TITLE
Typescript type declarations for exceljs

### ISSUE THREAD

**Issue by madoar** [exceljs/exceljs#238]
I want to use exceljs in a typescript project of mine. When using exceljs in a typescript project, it would be nice if there is a type declaration file (d.ts file) out there for exceljs to prevent programming errors.

Is there a typescript type declaration file for exceljs?

**Comment by Rycochet** [comment]
I've started putting together a .d.ts for this - https://gist.github.com/Rycochet/ebd8521c56059ec440339098b18a58c7

Please note that it's still a WIP - I've grabbed comments from the README or the source where possible, and tried to make sure types are correct as much as is needed (so there may be some placeholder "any" types around).

Quite happy for this to join the repo - but want to get it a bit more filled out first, putting it out there for people to use (and hopefully feedback on stuff I've missed). My needed target is browser - so it'll almost definitely be missing Node related bits.

**Comment by ilya-payrange** [comment]
Having .d.ts file will be really great!

Meanwhile I used this method (presented in #335)

In project tree:
`npm install exceljs --save`

In the component.ts:
`import * as ExcelJs from 'exceljs/dist/exceljs.min.js';`

Do not try to do dependency injection into constructor() (it requires proper .d.ts). Instead just grab the ExcelJs:

`var workbook = new ExcelJs.Workbook();`

Works for me. 

P.S. When I was trying `var workbook = new ExcelJs.Workbook();` with `import ExcelJs from 'exceljs;`, app crashed.

**Comment by Rycochet** [comment]
@ilya-payrange My [gist](https://gist.github.com/Rycochet/ebd8521c56059ec440339098b18a58c7) *is* a .d.ts file for it, probably about 90% complete - moved on to other projects at work so don't know if I'll get a chance to update it at all any time soon though...
