### ISSUE TITLE
Add title to worksheet

### ISSUE THREAD

**Issue by NandoMB** [exceljs/exceljs#240]
Hi man, first of all, I'd like to congratulate you for your **awesome** project!

I'd like to know if is possible to insert an "title" for my worksheet, above of columns headers?
Something like the green cell on image bellow:

<img width="1440" alt="screen shot 2016-12-09 at 15 51 54" src="https://cloud.githubusercontent.com/assets/5796053/21059000/a696ac8e-be27-11e6-93c0-3fcd59779018.png">

Thank you for your attention 😃

**Comment by AdamInTheOculus** [comment]
Hey @NandoMB, if I understand your issue correctly do the following to give your worksheets a title:

I would store the worksheet title in a variable ...

`
const wsTitle = 'Nando Title'; // Store our title in a variable
const ws = workbook.addWorksheet(wsTitle); // Create our worksheet
...
ws.getCell(`A1`).value = wsTitle; // Assign title to cell A1 -- THIS IS WHAT YOU'RE LOOKING FOR.
ws.mergeCells('A1:G1'); // Extend cell over all column headers
ws.getCell(`A1`).alignment = { horizontal: 'center' }; // Horizontally center your text
... 
`

Let me know if that helps at all.

**Comment by kurt343** [comment]
Note for anyone reading this. Microsoft Excel has a max length on worksheet titles of 30 chars, and, the following chars are invalid:

`\ / ? * [ ] :`

**Comment by jwmann** [comment]
This doesn't work. 
If you do this before columns are defined then columns overwrite these cells.
If you do this after columns are defined, then it overwrites the columns.

The problem is needing to shift/ set a start row line to start the columns at or something.
This is something I'm also trying to figure out.

**Comment by jwmann** [comment]
#433 Solves this for me.

The trick is to not set a `header` properties for the columns themselves.
You add a row with the values of columns where you want them to start and add the data after that row.

As long as you set the columns with the correct `key` it will map out accordingly.

```
sheet.columns = [ {key: 'myFull'}, {key: 'displayedValues'}, {key: 'goHere'} ]
sheet.addRow(5).values = [ 'My Full', 'Displayed Values', 'Go Here']
sheet.addRows( [
  { myFull: 'Text', displayedValues: 1234, goHere: 'Foobar' },
  { myFull: 'Text', displayedValues: 1234, goHere: 'Foobar' },
  { myFull: 'Text', displayedValues: 1234, goHere: 'Foobar' },
  { myFull: 'Text', displayedValues: 1234, goHere: 'Foobar' }
]);
```
