### ISSUE TITLE
Formula based cell not updating

### ISSUE THREAD

**Issue by soates** [exceljs/exceljs#246]
Hey, fantastic library.

I am having a few issues with formulas, just wondering if this is a bug or I am doing something stupid...

Basically, if I open a spreadsheet manually and update a cell then save and reopen the file - everything is as expected,

but If I do the same with exceljs the cell that should have changed is the original value?

my code;

 workbook.xlsx.readFile(__dirname + '/circles-test.xlsx')
                .then(function (worksheet) {
                    if (worksheet) {

                        var worksheet = workbook.getWorksheet(1);

                        if (worksheet) {

                            //I5 is 71 by default

                            worksheet.getCell('H5').value = 750;

                            workbook = new Excel.Workbook()

                            workbook.xlsx.writeFile(__dirname + '/circles-test.xlsx').then(function () {

                                workbook.xlsx.readFile(__dirname + '/circles-test.xlsx')
                                    .then(function (worksheet) {
                                        if (worksheet) {
                                            var worksheet = workbook.getWorksheet(1);
                                             //I5 should now be 91
                                            console.log(worksheet.getCell('I5').value);
                                        }
                                    });

                            });

                        }

                    }
                });

any help would be fantastic..

**Comment by ensignsystems** [comment]
@soates you are being stupid.  exceljs does not do the math for you.  You need something like https://github.com/sutoiku/formula.js to do the math

**Comment by soates** [comment]
do you have any examples of this? it looks good but absolutely nothing on the github page on how to use it

**Comment by ensignsystems** [comment]
@soates I am not sure.  All i kno is that the exceljs just changes the stored formula but does not do the rest of the math

**Comment by soates** [comment]
What about the fact that I am not expecting exceljs to do the calculation BUT saving my workbook and reopening it? still not possible?

**Comment by ensignsystems** [comment]
@soates If you make a change to the formula, save with exceljs and open with Excel you should see the new values show up.  Excel should recalculate.  If you make a change to the formula, save with exceljs, then reopen with exceljs I think it will give you the old values.  If you make a change in excel then reopen in exceljs it should give you new values.

**Comment by patrick-motard** [comment]
@soates were you able to resolve this issue? If so, what was your solution?

**Comment by crash83k** [comment]
I found a solution to this issue. I don't use MS Excel. I use LibreOffice, and I figured this was mostly an issue stemming from not using MS software. 

In the cell model, there's a `result` key that contains the calculated value of the formula.
`{
	address : 'I19',
	styleId : undefined,
	formula : '\'cash flow\'!C8',
	value : undefined,
	type : 6,
	result : 900,
	style : {
		numFmt : '_(* #,##0_);_(* (#,##0);_(* "-"??_);_(@_)'
	}
}`

What I did to get the sheets to recalculate the values was set `result` to `undefined`. 
`model.result = undefined;`
Then I saved the book to a new file. I found that after I open the workbook, all the values of the formulas that have `result` reset to `undefined` get recalculated.

I don't know if this is the best way to do it, but it does seem to work. I haven't tested on Excel though. Can someone confirm this works for them in Excel?

**Comment by benbroadley** [comment]
I recently ran into the same issue but working with generating for MS Excel and I solved this the same way as @crash83k.

So for anyone still looking at this issue, set the `result` property of your cell to `undefined`.

**Comment by KaranLala** [comment]
Setting the result to undefined works. However, After saving the values only get recalculated when you open the workbook in excel but not when open it in exceljs. Any idea on how to force recalculate an excel file from JS, so that the results will be populated when opened in exceljs?

**Comment by crash83k** [comment]
This library doesn't perform any of the calculation tasks. That's why setting the results to `undefined` forces Excel to recalculate when you open the file again in Excel.

If you want to get calculation results without using Excel, you'll either need a different library, or you'll need to run through the calculations manually. My team ended up creating a Java library to handle manipulating Excel files and data. There isn't any out-of-the-box JS solutions out there that I've found for that.

**Comment by nkagarw** [comment]
Hi, I tried to set the result to undefined :

`workbook.getWorksheet(1).getCell('N6').result = undefined;
`

But i'm getting this error :

` (node:6392) UnhandledPromiseRejectionWarning: TypeError: Cannot set property result of [object Object] which has only a getter`

Looks like cell.result is just a getter. How can I set the result to undefined ?

**Comment by Siemienik** [comment]
#230

**Comment by borismih** [comment]
> Hi, I tried to set the result to undefined :
> 
> `workbook.getWorksheet(1).getCell('N6').result = undefined; `
> 
> But i'm getting this error :
> 
> ` (node:6392) UnhandledPromiseRejectionWarning: TypeError: Cannot set property result of [object Object] which has only a getter`
> 
> Looks like cell.result is just a getter. How can I set the result to undefined ?

`workbook.getWorksheet(1).getCell('N6').model.result = undefined; `
