### ISSUE TITLE
Creating and opening files in linux

### ISSUE THREAD

**Issue by Adidi** [exceljs/exceljs#250]
I am working on CentOS 7 and trying to generate and save simple excel file.
When I am saving it with **xls** the file is open as corrupt on linux (using LibreOffice): #129 
changing it to **xlsx** solves the probelm - so I guess this is a really small issue to solve:
```javascript
const Excel = require('exceljs');

const workbook = new Excel.Workbook();

const sheet = workbook.addWorksheet('sheet');

sheet.columns = [
    { header: 'Id', key: 'id' },
    { header: 'Name', key: 'name' }
];

sheet.addRow({id: 1, name: 'John Doe'});

workbook.xlsx.writeFile('sample.xls')
    .then(function() {
        console.log('done');
    }).catch( ex =>{
        console.log(ex);
});
```

Like explianed changing line 14 ```workbook.xlsx.writeFile('sample.xls')``` to ```workbook.xlsx.writeFile('sample.xlsx')``` make the file works fine.

**Comment by paomoca** [comment]
I think exceljs only supports writing in .xlsx and .csv formats

**Comment by Siemienik** [comment]
https://github.com/exceljs/exceljs/issues/165
