### ISSUE TITLE
Remove the '@' symbol from a dynamically generated formula

### ISSUE THREAD

**Issue by MattePug** [exceljs/exceljs#2582]
**Premise: It's my first question on github, but I really can't find an answer anywhere else, so I'll try.**

I have this problem, I have to create a fairly complex formula (on my own) in generating an excel.

This below is my code:

```
worksheet.getCell(`$N${currentRow}`).value = {
          // Assicurati di non includere il simbolo `@` e usa la virgola come separatore di argomenti
          formula: `(${this.calculateHWPrice(worksheet.getCell(`E${currentRow}`).value)}) / 12 * L${currentRow}`,
          result: undefined
};
```

And this is my calculatHWPrice function : 

`calculateHWPrice(modello: any): string {
    const modeltype = this.modelDetails.find(t => t.modello === modello).gruppo
    return `CERCA.VERT("${modeltype}", $M$13:$N${12 + this.countModel}, 2, FALSO)`;
 }`
 
 
 Now, the problem is that when i open my excel, this is what i found in front of me (covered the string to search just for privacy ):
 
 
![issue](https://github.com/exceljs/exceljs/assets/150263753/0a3c766d-b1bc-4fd4-938b-a258c296bda5)

Here, the only thing that doesn't make the formula work is that '@' symbol placed in front of the formula, as once removed everything works perfectly.

I've tried everything so far but nothing worked.

Does anyone know the solution to this problem?

Without that formula my excel is meaningless

**Comment by Arun6121143** [comment]
@MattePug  is there any solution for this 
i am facing the same issue i am creating a copy of my original excel sheet 
and for some of the formulas i am getting the error 
  originalWorkbook.eachSheet((originalSheet) => {
        const newSheet = copiedWorkbook.addWorksheet(originalSheet.name);
        newSheet.model = Object.assign({}, originalSheet.model);;
        // newSheet.model = Object.assign({}, originalSheet.model);
      });
      
      this is my code to craete a copy from original excel sheet by adding each sheet along with their formulas and style
