### ISSUE TITLE
[BUG] AddImage is not working

### ISSUE THREAD

**Issue by Ilkhomjon2002** [exceljs/exceljs#2606]
## 🐛 Bug Report

I am downloading image and storing it  and reading with fs.fileReadSync and trying to insert it into xlsx but image is not showing up there isn`t any error
Lib version: 4.4.0

## Steps To Reproduce

```javascript
axios({
		method: "get",
		url: imageUrl,
		responseType: "stream",
	})
		.then((response) => {
	
			const fileStream = fs.createWriteStream(downloadPath);

			response.data.pipe(fileStream);

	
			fileStream.on("finish", () => {
				console.log("finished");
				const imageId2 = workbook.addImage({
					buffer: fs.readFileSync(downloadPath),
					extension: "png",
				});
				const imageId3 = workbook.addImage({
					filename: downloadPath,
					extension: "png",
				});
				console.log(imageId3);
				worksheet.addImage(imageId2, {
					tl: { col: 3, row: 21 },
					ext: { width: 500, height: 200 },
				});
			});
```

## The expected behaviour:

Process is finishing but when I open xlsx it is not showing an image

**Comment by imingyu** [comment]
@Ilkhomjon2002  @baolongt 
I used AI to enable Excel JS to support streaming I/O and add images. You can refer to this answer:  https://github.com/exceljs/exceljs/issues/322#issuecomment-3026225724
