### ISSUE TITLE
xlsx file gets corrupted when tried to update xlsx file using ExcelJS in Protractor

### ISSUE THREAD

**Issue by akothuru** [exceljs/exceljs#263]
I was trying to read data from xlsx file and then tried to write update data in it. When I executed the code, it was able to read data but after updating the value in same file through code, it corrupted xlsx file.

Code used for it:
            var Excel = require(GlobalVariables.gPluginsExcelJSPath);
            var workbook = new Excel.Workbook();
            var strCellValue = "";
            workbook.xlsx.readFile(FilePath).then(function () {
                var worksheet = workbook.getWorksheet("Sheet1");                
                var Row = 2;
                var Col = 2;
                var row = worksheet.getRow(Row);
                strCellValue = row.getCell(Col).value;
                console.log("Cell Value for Cell(" + Row + "," + Col + "): " + strCellValue);
                var today = new Date();
                var sToday = today.getDate().toString();                
                row.getCell(Col).value = sToday ;                        
                workbook.xlsx.writeFile(strTempFile)
                            .then(function() {
                                // done
                            });
           });

Please correct the code if anything is missing? I heard that other folks as well have the similar issues.
If so, please provide fix ASAP which helps us a lot.

**Comment by ybatsiun** [comment]
Faced the same issue

**Comment by mahdinaija** [comment]
i have the same issue too, did u find a solution

**Comment by akothuru** [comment]
I switched to xlsx-style package and it too had limitations.
