### ISSUE TITLE
Out of bounds. Excel supports columns from 1 to 16384

### ISSUE THREAD

**Issue by KIRUBASHANKAR26** [exceljs/exceljs#2654]
## 🐛 Bug Report

Out of bounds. Excel supports columns from 1 to 16384. While getColumn by using the key.

Lib version: 4.4.0

## Steps To Reproduce

Instead of describing it here, I have shared the Stackblizt to reproduce 

[Stackblizt](https://stackblitz.com/edit/stackblitz-starters-mg2vqb?file=src%2FApp.js)

1. Click the download and upload the same file

## The expected behaviour:

The column key should return the result.

**Comment by guptaarpit** [comment]
Does someone started working on this

**Comment by FadiShak3r** [comment]
Did you get this figured out?
