### ISSUE TITLE
Typeerror: i.constants is undefined

### ISSUE THREAD

**Issue by sam1946** [exceljs/exceljs#2677]
Hi, I am using excelJS in a NextJS application:

```
import exceljs from 'exceljs'
  const wb = new exceljs.Workbook();
  const dd = "/tmp/testHL.xlsx";

  await wb.xlsx.readFile(dd)
```

---> and this is where the error occurs. I use different spreadsheets, different locations and it is the same. 

A search through excelJS.min.js shows that "i.constants" is in the code itself - is this a bug?

I'm using the latest excelJS with npm.

**Comment by avner-sapiens** [comment]
Try to import like this:  `import * as ExcelJS from 'exceljs';`

**Comment by sam1946** [comment]
Hi, thanks for your help. I used it and still the error.

I am wondering if the error is coming because I am calling the function from a client component in NextJS, and it maybe that excelJS needs to run on the server components. I will test and  report back.....

**Comment by sam1946** [comment]
Yes, that was the problem. I had the code running in a client component, and I needed to shift it to the server! Issue solved.
