### ISSUE TITLE
Client-side download from server

### ISSUE THREAD

**Issue by m0ngr31** [exceljs/exceljs#269]
I'm using exceljs to modify an Excel file I have saved on S3. The modification seems to work fine, but I'm having issues saving the file back to the browser.

Here's the meteor code:

    var ExcelJS = require('exceljs');
    var StreamBuf = require('exceljs/lib/utils/stream-buf');
    import { request } from 'meteor/froatsnook:request';

    Meteor.methods({
      createExcel: function(planObj) {
        var result = request.getSync("https://<S3URL>/public/excel-export.xlsx", {encoding: null});
        var base64 = 'data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,' + new Buffer(result.body).toString('base64');

        var wb = new ExcelJS.Workbook();
        return wb.xlsx.load(base64, {base64: true}).then(() => {
          let ws = wb.getWorksheet('Recommended Plans');
          ws.getCell('D1').value = 'Test';
        }).then(() => {
          var outStream = new StreamBuf();

          return wb.xlsx.write(outStream).then(function() {
            var b = outStream.read();
            var s = b.toString('base64');

            return s;
          });
        });
      }
    });

And on the front-end:

    function b64toBlob(b64Data, contentType, sliceSize) {
      contentType = contentType || '';
      sliceSize = sliceSize || 512;

      var byteCharacters = atob(b64Data);
      var byteNumbers = new Array(byteCharacters.length);
      for (var i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
      }
      var byteArray = new Uint8Array(byteNumbers);

      var blob = new Blob([byteArray], {type: contentType});
      return blob;
    }

    $meteor.call('createExcel', data).then((returnedFile) => {
      let fileBlob = b64toBlob(returnedFile, 'vnd.openxmlformats-officedocument.spreadsheetml.sheet')
      saveAs(fileBlob, 'test.xlsx');
    });

The file actually saves, but the issue is that there is nothing in the worksheets (Although the sheets are still there and named the same thing).

Any suggestions?

**Comment by Siemienik** [comment]
#37
