### ISSUE TITLE
how to set Header in a different row?

### ISSUE THREAD

**Issue by ntorres144** [exceljs/exceljs#276]
Is there a way to set the headers on a diferent row, other than the first?

I'm trying to do this
```
`var Excel = require('exceljs');
    var workbook = new Excel.Workbook();
    var headers = [
      {header:'Cliente',key:'client_name'  ,width: 18}, // i need something like headerRow:2
      {header:'N° Visitas',key:'visits'  ,width: 10},
      {header:'Visitas Periodo Anterior',key:'visits_old'  ,width: 10},
      {header:'Ultima visita',key:'last_visit',style: { numFmt: 'DD/MM/YYYY HH:mm:ss' },width: 22},
      {header:'Ultima Persona en Visitarlo',key:'device_name'  ,width: 18}
    ];
    var libro  = workbook.xlsx.readFile(template_file)
      .then(function() {
        var worksheet = workbook.getWorksheet(1);
        worksheet.properties.defaultRowHeight = 15;
        worksheet.columns = headers;
        worksheet.addRows(data);


        //row.height=40;
        worksheet.getRow(1).hidden=false;
        worksheet.getRow(2).hidden=false;

        //row.height=40;
        workbook.xlsx.writeFile(output)
          .then(function() {
            callback(null,output);
          });`

**Comment by dsdjolence** [comment]
I also have same issue.

**Comment by sevenstories** [comment]
I've managed to offset the header row by using splice rows set to remove 0 rows and giving it an empty array of the desired amount of rows, just place it after all rows have been added. A similar technique could be applied to columns.
Anything you want to add above the header rows will need to be set directly (not using addRow or addRows, so presumably wont work for a streamed file if the rows are already committed?) Or you could specify it in the array parameter of splice in place of the `new Array(offset)` parameter
```javascript
let offset = 3; // to offset by 3 rows
worksheet.spliceRows(1,0,new Array(offset))
```

**Comment by Siemienik** [comment]
#268 276

**Comment by yoyo837** [comment]
```js
let offset = 3; // to offset by 3 rows
worksheet.spliceRows(1,0,new Array(offset))
```

The style of the columns does not move after splice.

**Comment by andrewkittredge** [comment]
The syntax in typescript is
`worksheet.spliceRows(1, 0, ...new Array(5))`

**Comment by abyss-kp** [comment]
I wanted my headers to start from 3rd row and 1st-row 1st cell had some metadata,so what I did was:

1. Duplicated my headers in 3 rows (1,2,3).
`worksheet.duplicateRow(1, 2, true); //duplicate header row 2 times with values and style; in row2 and row3` 

2. Added metadata in 1st row
` worksheet.getRow(1).values = ['Some meta data'] //Replace row1 headers with "Berry Type";here we pass an array where each index denotes a cells`

3. Removing duplicated headers from 2nd row
`worksheet.getRow(2).values = [] //Delete row2 duplicated above in step 1`

**Comment by abyss-kp** [comment]
> ```js
> let offset = 3; // to offset by 3 rows
> worksheet.spliceRows(1,0,new Array(offset))
> ```
> 
> The style of the columns does not move after splice.

I wanted my headers to start from 3rd row and 1st-row 1st cell had some metadata,so what I did was:

1. Duplicated my headers in 3 rows (1,2,3).
`worksheet.duplicateRow(1, 2, true); //duplicate header row 2 times with values and style; in row2 and row3` 

2. Added metadata in 1st row
` worksheet.getRow(1).values = ['Some meta data'] //Replace row1 headers with "Berry Type";here we pass an array where each index denotes a cells`

3. Removing duplicated headers from 2nd row
`worksheet.getRow(2).values = [] //Delete row2 duplicated above in step 1`

And here's my output:

Metadata |   |   |   |  
-- | -- | -- | -- | --
  |   |   |   |  
header1 | Header2 | header3 | header4 | header5
1 | 2 | 3 | 4 | 5

**Comment by abyss-kp** [comment]
I wanted my headers to start from 3rd row and 1st-row 1st cell had some metadata,so what I did was:

1. Duplicated my headers in 3 rows (1,2,3).
`worksheet.duplicateRow(1, 2, true); //duplicate header row 2 times with values and style; in row2 and row3` 

2. Added metadata in 1st row
` worksheet.getRow(1).values = ['Some meta data'] //Replace row1 headers with "Berry Type";here we pass an array where each index denotes a cells`

3. Removing duplicated headers from 2nd row
`worksheet.getRow(2).values = [] //Delete row2 duplicated above in step 1`

And here's my output:

Metadata |   |   |   |  
-- | -- | -- | -- | --
  |   |   |   |  
header1 | Header2 | header3 | header4 | header5
1 | 2 | 3 | 4 | 5

**Comment by gbhipolitoglyph** [comment]
mfahmirukman's answer here https://github.com/exceljs/exceljs/issues/433 worked for me! w/ 1 minor tweak as I commented there too.

**Comment by michaelparkadze** [comment]
@abyss-kp I get a workseet.duplicateRow is not a function error.

**Comment by baolongt** [comment]
> @abyss-kp I get a workseet.duplicateRow is not a function error.

Think because you use the WorkbookWriter which implement for stream

try this code instead

```
// add n row before header
 for (let i = 1; i <= n; i++) {
    worksheet.addRow({});
  }
  
   worksheet.columns = [
    { header: "ID", key: "id" },
    { header: "NAME", key: "name" },
    { header: "AGE", key: "age" },
  ];
  
  //remove the defaul header
  // should remove hear before commit data with stream
  worksheet.getRow(1).values = [];

  worksheet.addRow({
    id: "ID",
    name: "NAME",
    age: "AGE",
  });
```

**Comment by IvanSereginGitHub** [comment]
Sorry for necro..ing (?) the issue, but since spliceRows now accepts rest parameter inserts, new code should look like this:
`
let offset = 3; // to offset by 3 rows
worksheet.spliceRows(1,0,...new Array(offset))
`
