### ISSUE TITLE
Is there a way to set width of columns "automatically" based on the size of context in cells?

### ISSUE THREAD

**Issue by ZlatyChlapec** [exceljs/exceljs#277]
In excel you can do this by clicking on icon in top left corner between A and 1 followed up with double click on border between A and B or any other border in between alphabets.

Is there a way to do this from code?

**Comment by Rycochet** [comment]
You'd need to render the text somehow - ideally in a browser with the correct font metrics. Failing that you can just estimate it. From quick tests, one unit of width is 7px.

**Comment by Siemienik** [comment]
#83 #450 #583
