### ISSUE TITLE
[Q] 如何正确读取图片？或者如何解析DISPIMG函数的图片（嵌入单元格图片）

### ISSUE THREAD

**Issue by palxiao** [exceljs/exceljs#2786]
在 wps 中嵌入单元格的图片是自定义函数的形式：

![image](https://github.com/exceljs/exceljs/assets/21021314/f293bd2f-11fb-4618-af3d-1dc0a6ccd04a)

这种图片无法被 `worksheet.getImages()` 函数读取出来，只能识别出自定义函数的值：

![image](https://github.com/exceljs/exceljs/assets/21021314/ec07d132-faab-436c-9960-5a0e8ec8138b)

如果采用浮动式图片的话，就可以读取，但是只要修改图片那么读取顺序就会有问题（因为每次图片都是push进去的）

所以应该如何才能正确获取图片？

**Comment by humbass** [comment]
我的需求跟你相反，需要将浮动图片转成 embed （嵌入）的形式

**Comment by palxiao** [comment]
已额外实现方法实现解析关系，图片可从media中获取，该问题关闭。

**Comment by aliwumi** [comment]
@palxiao 请教下这个问题如何解决的呢？

**Comment by fcl999** [comment]
> @palxiao 请教下这个问题如何解决的呢？

在workbook的media里

**Comment by jim-tian** [comment]
> > @palxiao 请教下这个问题如何解决的呢？
> 
> 在workbook的media里

workbook的media里获取的图片如何与对应的 单元格关联起来呢，这个media又有浮动图片又有嵌入图片，而且是所有sheet的集合

**Comment by fcl999** [comment]
> > > @palxiao 请教下这个问题如何解决的呢？
> > 
> > 
> > 在workbook的media里
> 
> workbook的media里获取的图片如何与对应的 单元格关联起来呢，这个media又有浮动图片又有嵌入图片，而且是所有sheet的集合

我这边是先拿到所有图片的名称,然后遍历图片单元格,如果有嵌入函数就能匹配到.同时有浮动的单元格是没有函数的,互不干扰
下面的 allRows 是对应行数所属的对象, 这样处理改对象的适合就能直接从索引拿到图片数据

```js
// wps 嵌入式
                    let isWPSEmbed = false;
                    // {id: imageObject}
                    const result = {};
                    const zip = await JSZip.loadAsync(data);
                    const cellimagesRels = zip.files['xl/_rels/cellimages.xml.rels'] || zip.files['/xl/_rels/cellimages.xml.rels'];
                    const cellimages = zip.files['xl/cellimages.xml'] || zip.files['/xl/cellimages.xml'];
                    if (cellimagesRels && cellimages) {
                      const cellimagesRelsData = await parseStringPromise(await cellimagesRels.async('text'));
                      const cellimagesData = await parseStringPromise(await cellimages.async('text'));
                      const cellimagesNameRidMap = {};
                      cellimagesData['etc:cellImages']['etc:cellImage'].forEach((pic) => {
                        const rid = pic['xdr:pic'][0]['xdr:blipFill'][0]['a:blip'][0].$['r:embed'];
                        const imageId = pic['xdr:pic'][0]['xdr:nvPicPr'][0]['xdr:cNvPr'][0].$.name;
                        cellimagesNameRidMap[rid] = imageId;
                      });
                      for (const relationship of cellimagesRelsData['Relationships']['Relationship']) {
                        const data = relationship.$.Target.match(/media\/([a-zA-Z0-9]+[.][a-zA-Z0-9]{3,4})$/)
                        if (!data) continue;
                        const fullName = data[1];
                        const [name, extension] = fullName.split('.');
                        result[cellimagesNameRidMap[relationship.$.Id]] = workbook.media.find(v => v.name === name);
                        isWPSEmbed = true;
                      }
                    }


if (isWPSEmbed) {
                      let _rowIndex = null;
                      let diff = 2;
                      let i = 2;
                      if (worksheet.getCell('A2').value === this.i('msg175')) {
                        i = 3;
                        diff = 3;
                      }
                      for(let len = worksheet._rows.length + 1; i < len; i++) {
                        const index = allRows[i - diff];
                        if (index === _rowIndex) continue;
                        _rowIndex = index;
                        if (typeof index === 'undefined') continue;
                        if (!images.has(index)) {
                          images.set(index, []);
                        }
                        const rows = images.get(index);
                        const spans = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
                        // todo 排除多行数据
                        [
                          worksheet.getCell(spans[imageIndex] + i).value,
                          worksheet.getCell(spans[imageIndex + 1 ] + i).value,
                          worksheet.getCell(spans[imageIndex + 2] + i).value,
                          worksheet.getCell(spans[imageIndex + 3] + i).value
                        ].forEach((value, index) => {
                          if(value && value.result && value.result.indexOf('=DISPIMG(') === 0) {
                            const id = value.result.match(/ID_[0-9A-F]{32}/i)[0];
                            if (result[id]) {
                              if (rows.length < 4) {
                                rows.push(Object.assign({ nativeCol: index + imageIndex }, result[id]));
                              }
                            }
                          }
                        })
                      }
                    }




```

**Comment by jim-tian** [comment]
> > > > @palxiao 请教下这个问题如何解决的呢？
> > > 
> > > 
> > > 在workbook的media里
> > 
> > 
> > workbook的media里获取的图片如何与对应的 单元格关联起来呢，这个media又有浮动图片又有嵌入图片，而且是所有sheet的集合
> 
> 我这边是先拿到所有图片的名称,然后遍历图片单元格,如果有嵌入函数就能匹配到.同时有浮动的单元格是没有函数的,互不干扰 下面的 allRows 是对应行数所属的对象, 这样处理改对象的适合就能直接从索引拿到图片数据
> 
> ```js
> // wps 嵌入式
>                     let isWPSEmbed = false;
>                     // {id: imageObject}
>                     const result = {};
>                     const zip = await JSZip.loadAsync(data);
>                     const cellimagesRels = zip.files['xl/_rels/cellimages.xml.rels'] || zip.files['/xl/_rels/cellimages.xml.rels'];
>                     const cellimages = zip.files['xl/cellimages.xml'] || zip.files['/xl/cellimages.xml'];
>                     if (cellimagesRels && cellimages) {
>                       const cellimagesRelsData = await parseStringPromise(await cellimagesRels.async('text'));
>                       const cellimagesData = await parseStringPromise(await cellimages.async('text'));
>                       const cellimagesNameRidMap = {};
>                       cellimagesData['etc:cellImages']['etc:cellImage'].forEach((pic) => {
>                         const rid = pic['xdr:pic'][0]['xdr:blipFill'][0]['a:blip'][0].$['r:embed'];
>                         const imageId = pic['xdr:pic'][0]['xdr:nvPicPr'][0]['xdr:cNvPr'][0].$.name;
>                         cellimagesNameRidMap[rid] = imageId;
>                       });
>                       for (const relationship of cellimagesRelsData['Relationships']['Relationship']) {
>                         const data = relationship.$.Target.match(/media\/([a-zA-Z0-9]+[.][a-zA-Z0-9]{3,4})$/)
>                         if (!data) continue;
>                         const fullName = data[1];
>                         const [name, extension] = fullName.split('.');
>                         result[cellimagesNameRidMap[relationship.$.Id]] = workbook.media.find(v => v.name === name);
>                         isWPSEmbed = true;
>                       }
>                     }
> 
> 
> if (isWPSEmbed) {
>                       let _rowIndex = null;
>                       let diff = 2;
>                       let i = 2;
>                       if (worksheet.getCell('A2').value === this.i('msg175')) {
>                         i = 3;
>                         diff = 3;
>                       }
>                       for(let len = worksheet._rows.length + 1; i < len; i++) {
>                         const index = allRows[i - diff];
>                         if (index === _rowIndex) continue;
>                         _rowIndex = index;
>                         if (typeof index === 'undefined') continue;
>                         if (!images.has(index)) {
>                           images.set(index, []);
>                         }
>                         const rows = images.get(index);
>                         const spans = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
>                         // todo 排除多行数据
>                         [
>                           worksheet.getCell(spans[imageIndex] + i).value,
>                           worksheet.getCell(spans[imageIndex + 1 ] + i).value,
>                           worksheet.getCell(spans[imageIndex + 2] + i).value,
>                           worksheet.getCell(spans[imageIndex + 3] + i).value
>                         ].forEach((value, index) => {
>                           if(value && value.result && value.result.indexOf('=DISPIMG(') === 0) {
>                             const id = value.result.match(/ID_[0-9A-F]{32}/i)[0];
>                             if (result[id]) {
>                               if (rows.length < 4) {
>                                 rows.push(Object.assign({ nativeCol: index + imageIndex }, result[id]));
>                               }
>                             }
>                           }
>                         })
>                       }
>                     }
> ```

昨天把源码扫了下，发现exceljs确实没有去读取 cellimages 文件，想着要解决这个问题，得手动去解压excel文件，遍历两个文件，自己建立映射表了，看到你已经实现了 太棒了👍
