### ISSUE TITLE
[BUG] Polyfill Supply Chain Attack

### ISSUE THREAD

**Issue by Sarsewar** [exceljs/exceljs#2787]
As per below Link, there were Polyfill supply chain attack embeds malware in JavaScript CDN assets
https://dev.to/snyk/polyfill-supply-chain-attack-embeds-malware-in-javascript-cdn-assets-55d6

Would like to know if there is any implicit dependency on exceljs? Can we use it without polyfill.js?

**Comment by akomm** [comment]
How do you come to the conclusion that it depends on it? Or do you just ask for others to look up the dependencies?

You can look this up yourself easy... Example yarn berry in your project with exceljs: `yarn info -R exceljs` (-R = recursive)

Here is what I get at 4.4.0:
![grafik](https://github.com/exceljs/exceljs/assets/2409779/6b01e3f9-3855-49dd-bf1c-69cc95fcfee5)

**Comment by Sarsewar** [comment]
Thanks @akomm Closing the issue.
