### ISSUE TITLE
4.4.0 导出excel 添加图片在单元格 无法直接在office excel中显示  

### ISSUE THREAD

**Issue by Birdyqaq** [exceljs/exceljs#2788]
## 💬 Questions and Help
多张图片添加在单元格 wps 可以直接打开查看   使用office excel 打开提示导出的内容格式有问题  下面是部分代码逻辑
和wps显示的效果
<img width="981" alt="image" src="https://github.com/exceljs/exceljs/assets/53514645/75639f19-d48e-4770-b13f-d9debf08388b">
excel 打开的报错
<img width="260" alt="image" src="https://github.com/exceljs/exceljs/assets/53514645/865df9fc-397f-4933-9668-db5f0f986e8d">
<img width="260" alt="image" src="https://github.com/exceljs/exceljs/assets/53514645/c6f93e18-cb72-4c53-97bc-68025405d523">

### How to make a question?
import * as XLSX from 'xlsx';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';

// 获取图片尺寸
function getImageDimensions(base64Image) {
    return new Promise((resolve) => {
        const img = new Image();
        img.onload = () => {
            resolve({ width: img.width, height: img.height });
        };
        img.src = base64Image;
    });
}

// 等比例缩放图片
function scaleImage(dimensions, maxHeight) {
    const scale = maxHeight / dimensions.height;
    return {
        width: dimensions.width * scale,
        height: maxHeight + 20
    };
}

// 导出 Excel 文件，并将图片嵌入到 Excel 中
export async function exportExcelWithImages(data, headersMap, filename, imageFields = [], maxHeight = 220) {
    // 1. 使用SheetJS创建基础的Excel文件并设置列宽
    const sheetData = data.map(item => {
        const row = {};
        Object.keys(headersMap).forEach(key => {
            if (!imageFields.includes(key)) {
                row[headersMap[key]] = item[key];
            }
        });
        return row;
    });
    const sheetHeaders = Object.keys(headersMap).map(key => headersMap[key]);
    const ws = XLSX.utils.json_to_sheet(sheetData, { header: sheetHeaders });

    // 自动调整列宽
    const colWidths = sheetHeaders.map(header => {
        // 根据内容的最长宽度来设置列宽
        const maxLength = Math.max(
            header.length,
            ...sheetData.map(row => (row[header] ? row[header].toString().length : 0))
        );
        return { wch: maxLength + 5 }; // 添加额外的宽度以确保显示
    });
    ws['!cols'] = colWidths;

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
    const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });

    // 2. 使用ExcelJS加载SheetJS生成的文件并插入图片
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(wbout);
    const worksheet = workbook.getWorksheet('Sheet1');

    // 添加图片到单元格并调整图片大小以适应列宽和行高
    for (let rowIndex = 0; rowIndex < data.length; rowIndex++) {
        const item = data[rowIndex];
        for (const field of imageFields) {
            const imageKeys = item[field] || []; // Default to empty array if imageKeys is null or undefined
            console.log(imageKeys, "imageKeys");
            // 如果 imageKeys 数组为空，则插入占位图片
            // if (imageKeys.length === 0 && placeholderImage) {
            //     imageKeys.push(placeholderImage)
            // }
            for (let imageIndex = 0; imageIndex < imageKeys.length; imageIndex++) {
                let imageData = imageKeys[imageIndex];

                if (imageData && imageData.length > 100) {
                    const dimensions = await getImageDimensions(imageData);
                    const colIndex = Object.keys(headersMap).indexOf(field) + imageIndex;

                    // 获取列宽和行高
                    const columnWidth = worksheet.getColumn(colIndex + 1).width || 10;
                    const rowHeight = worksheet.getRow(rowIndex + 2).height || 15;

                    // 计算缩放后的图片尺寸
                    const scale = Math.min(columnWidth * 7.5 / dimensions.width, rowHeight * 1.333 / dimensions.height);
                    const scaledDimensions = {
                        width: dimensions.width * scale,
                        height: dimensions.height * scale
                    };

                    const id = workbook.addImage({
                        base64: imageData, // 去掉前缀
                        extension: 'png', // 假设图片格式为 png，根据实际情况调整
                    });

                    // 插入图片到单元格中
                    worksheet.addImage(id, {
                        tl: { col: colIndex, row: rowIndex + 1 },
                        ext: { width: scaledDimensions.width, height: scaledDimensions.height }
                    });
                }
            }
        }
    }

    // 保存文件
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    saveAs(blob, `${filename}.xls`);
}

1. First, try to find it by using search bar - anware what are you looking for was be done before.
2. Push the `New discussion` button.
3. Select `Q&A` category.

**Comment by Birdyqaq** [comment]
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';

// 获取图片尺寸
function getImageDimensions(base64Image) {
    return new Promise((resolve) => {
        const img = new Image();
        img.onload = () => {
            resolve({ width: img.width, height: img.height });
        };
        img.src = base64Image;
    });
}

// base64转换为Blob对象
function base64ToBlob(base64, mime) {
    const byteString = atob(base64.split(',')[1]);
    const ab = new ArrayBuffer(byteString.length);
    const ia = new Uint8Array(ab);
    for (let i = 0; i < byteString.length; i++) {
        ia[i] = byteString.charCodeAt(i);
    }
    return new Blob([ab], { type: mime });
}

// 导出 Excel 文件，并将图片嵌入到 Excel 中
export async function exportExcelWithImages(data, headersMap, filename, imageFields = [], maxHeight = 150, maxWidth = 150) {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Sheet1');

    // 设置列宽
    const columns = Object.keys(headersMap).map(key => ({
        header: headersMap[key],
        key: key,
        width: 20 // 默认宽度，可根据需要调整
    }));
    worksheet.columns = columns;

    // 添加数据到工作表中
    data.forEach(item => {
        const row = {};
        Object.keys(headersMap).forEach(key => {
            if (!imageFields.includes(key)) {
                row[key] = item[key];
            }
        });
        worksheet.addRow(row);
    });

    // 添加图片到单元格并调整行高和列宽
    for (let rowIndex = 0; rowIndex < data.length; rowIndex++) {
        const item = data[rowIndex];
        let scaledHeight = maxHeight; // 设置行高为固定的最大高度
        for (const field of imageFields) {
            const imageKeys = item[field] || []; // Default to empty array if imageKeys is null or undefined

            for (let imageIndex = 0; imageIndex < imageKeys.length; imageIndex++) {
                let imageData = imageKeys[imageIndex];

                if (imageData && imageData.length > 100) {
                    const dimensions = await getImageDimensions(imageData);
                    const colIndex = Object.keys(headersMap).indexOf(field);

                    // 获取列宽和行高
                    const columnWidth = worksheet.getColumn(colIndex + 1).width || 10;
                    const rowHeight = worksheet.getRow(rowIndex + 2).height || 15;

                    // 计算缩放后的图片尺寸
                    const scaleWidth = maxWidth / dimensions.width;
                    const scaleHeight = maxHeight / dimensions.height;
                    const scale = Math.min(scaleWidth, scaleHeight);
                    const scaledDimensions = {
                        width: dimensions.width * scale,
                        height: dimensions.height * scale
                    };

                    // 将base64转为Blob对象
                    const mime = imageData.split(',')[0].match(/:(.*?);/)[1];
                    const blob = base64ToBlob(imageData, mime);
                    const url = URL.createObjectURL(blob);

                    const imageId = workbook.addImage({
                        base64: imageData.split(',')[1],
                        extension: mime.split('/')[1], // 例如 'png', 'jpeg'
                    });

                    // 插入图片到单元格中
                    worksheet.addImage(imageId, {
                        tl: { col: colIndex + imageIndex, row: rowIndex + 1 },
                        ext: { width: scaledDimensions.width, height: scaledDimensions.height }
                    });
                    worksheet.getColumn(colIndex + 1).width = Math.max(worksheet.getColumn(colIndex + 1).width || 0, scaledDimensions.width / 7.5); // 更新列宽
                }
            }
        }
        worksheet.getRow(rowIndex + 2).height = scaledHeight * 0.75; // 设置行高度，0.75 为点到像素的转换因子
    }

    // 保存文件
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    saveAs(blob, `${filename}.xlsx`);
}
问题已解决。   把base64转换一下就好了。  office excel就可以直接打开了 图片也正常显示

**Comment by kuangxiaowang** [comment]
请问楼主是怎么解决的，base64转成blod以后怎么处理的？office版本是多少？
