### ISSUE TITLE
[BUG] RangeError: Invalid array length with large amount of rows

### ISSUE THREAD

**Issue by jHabjanMXP** [exceljs/exceljs#2792]
## 🐛 Bug Report

Lib version: 4.3.0

## Steps To Reproduce
Created 300k rows with 20 properties

## Stack
```
Error: Uncaught (in promise): RangeError: Invalid array length
RangeError: Invalid array length
    at Array.push (<anonymous>)
    at a (exceljs.min.js:3:96081)
    at t.value (exceljs.min.js:3:96786)
    at a.value (exceljs.min.js:3:224568)
    at exceljs.min.js:3:330724
    at Array.forEach (<anonymous>)
    at u.value (exceljs.min.js:3:330701)
    at exceljs.min.js:3:216299
    at Array.forEach (<anonymous>)
    at u.value (exceljs.min.js:3:216274)
```
Inner:
![image](https://github.com/exceljs/exceljs/assets/60509445/c2fbfb5f-0bf1-4247-b9bc-808586193d04)
![image](https://github.com/exceljs/exceljs/assets/60509445/d407e967-c664-4390-8b20-11e06235b1fc)
outer:
![image](https://github.com/exceljs/exceljs/assets/60509445/6be5a125-3a7c-44ec-9335-7aace566a1f6)

## Possible temp workaround
- split exports to multiple sheets

**Comment by Yumitoya8569** [comment]
fix on: #2320
update to v4.4.0+

**Comment by ChandanChainani** [comment]
@Yumitoya8569 If the issue is resolved, Please can we close this issue.

**Comment by Yumitoya8569** [comment]
> @Yumitoya8569 If the issue is resolved, Please can we close this issue.

@jHabjanMXP Is this issue confirmed to be resolved? If so, can we close it? Thanks.

**Comment by jHabjanMXP** [comment]
I havent tested 4.4.0. It can be closed. Thanks
