### ISSUE TITLE
Reading binary format instead of base64 for browser version

### ISSUE THREAD

**Issue by poushy** [exceljs/exceljs#287]
I am trying to use this in the browser.  When I try to read, if I try to convert to base64, it works fine.  I can get it to work in the base64 format using option {base64: true} , but if I try to use plain binary, it throws error.  I don't think passing {'binary' : true} in options does anything.

**Comment by Rycochet** [comment]
Can confirm that binary didn't do anything for me either - so I switched over to base64 too (but deadlines meant I didn't have time to follow up, then forgot).

**Comment by guyonroche** [comment]
@poushy - 'binary' is the default mode, and you're right... passing {'binary': true} will have no effect. What to do depends on the type of data you have. If you've made an xhr request to a server to pull down a spreadsheet, it's most likely you're dealing with base64 - so you can just pass {base64: true} as the options and it should work.
This simple example demonstrates sending and receiving spreadsheets to/from a node service: [Manual Test](https://github.com/guyonroche/exceljs/tree/master/spec/manual)
