### ISSUE TITLE
Issue with copying cells

### ISSUE THREAD

**Issue by muscapades** [exceljs/exceljs#298]
See pull request https://github.com/guyonroche/exceljs/pull/297 with three failing tests.

We see a problem where cells that are copied as a block does not appear to have formulas, only values.

I suspect that Excel has some way of saving "similar cells" that exceljs does not understand?

The attached [fibonacci.xlsx](https://github.com/guyonroche/exceljs/files/889651/fibonacci.xlsx) has the problem. Rows 1-3 where created by hand.
Rows 4 to 19 where created by copying A3:B3 in one copy-paste operation.

The first row in the new block, A4:B4, is fine.

All the rest of the rows, A5:B19, appear in exceljs to have only values, not formulas.

I can reproduce this problem by copying blocks of cells in other spreadsheets too. The first row is okay, the rest shows the problems.
Copying the rows one by one is a workaround, but not reliable. (A sheet created like this worked, but then when I added a range name to a cell, many cells now start showing the problem again.)

**Comment by nehakseth** [comment]
Was working on something similar and got stuck here. Few cells with formula just turn out to be an object which has formula which messes my calculations. Early help is appreciated.

**Comment by muscapades** [comment]
I have submitted a suggested fix with a new ValueType.SharedFormula and information about what cell to adapt the formula from.
Another angle would be to create the adapted formula and let exceljs pretend that the formula was there all along.
