### ISSUE TITLE
Cannot resolve module 'fs' on client side

### ISSUE THREAD

**Issue by whatya** [exceljs/exceljs#299]
Module not found: Error: Cannot resolve module 'fs'

**Comment by dmr** [comment]
I think I have a similar issue:

```Module not found: 'module' in /~/natives/index.js```

@whatya did you solve your issue?

**Comment by sangwell** [comment]
Me too:Module not found: Error: Can't resolve 'fs' in...... @dmr

**Comment by lrecknagel** [comment]
Did you use it it in the Browser?

**Comment by hlehmann** [comment]
same error: `Module not found: Error: Can't resolve 'fs' in '/home/hugo/work/optimyo/node_modules/fast-csv/lib/parser'`

even with `import Excel from "exceljs/dist/es5/exceljs.browser.js";`

**Comment by dmr** [comment]
I tried to use it in a browser, yes.
But we ended up pushing the exceljs-part to the serverside to solve the issue.

**Comment by jalembke** [comment]
Any work towards getting this to work?  I just started using this library client side (in a browser).  Ran into this issue with no idea how to fix it.  I'm including the exceljs.browser.js as specified but still getting the error.

**Comment by ryarasi** [comment]
I'm also having this issue. I'm trying to use this on my React app and I get this error while compiling:-
```
Failed to compile.

./node_modules/natives/index.js
Module not found: Can't resolve 'module' in '~/node_modules/natives'
```
All I'm doing is this:-
`import Excel from exceljs;`

I'm on exceljs 0.7.1

**Comment by jwmann** [comment]
I have a similar error
```
ERROR in ./~/natives/index.js
Module not found: Error: Cannot resolve module 'module' in /Users/jwmann//app/node_modules/natives
 @ ./~/natives/index.js 2:13-30
```

I'm using webpack if that helps

**Comment by jwmann** [comment]
I managed to resolve this using [this comment](https://github.com/guyonroche/exceljs/issues/335#issuecomment-307645129)
```
import * as Excel from 'exceljs/dist/exceljs.min.js';
```
but I'm getting a new error when using `.writeFile`
```
Uncaught TypeError: e.createWriteStream is not a function  exceljs.min.js?5b90:formatted:9227
```

Anyone else getting this?

**Comment by jwmann** [comment]
So yea I think were back with the original issue of it trying to use `fs` module
Except `fs` is a native node.js module and nowhere does it say on this module's docs that node.js is a dependency.

**Comment by Ahmad19860** [comment]
@jwmann I am also getting the same issue **'TypeError: e.createWriteStream is not a function'** . How did you resolve this issue?

**Comment by jwmann** [comment]
@Ahmad19860 So `.writeFile` relies on node.js libraries in order to function. So we can't actually use that unless they change the way it works.

Fortunately there's a function _specifically_ for xlsx worksheets called `.writeBuffer()` and using this we can use an alternative file saving package to do our work.

Here's some example code.

```
import saveAs from 'file-saver';

workbook.xlsx.writeBuffer().then( data => {
  const blob = new Blob( data, {type: "application/octet-stream"} );
  saveAs( blob, 'myexcel.xlsx');
});
```

**Comment by Ahmad19860** [comment]
@jwmann Thanks for your suggestion. I used ionic File package which worked for me.

**Comment by dovk** [comment]
Thank you - for me I had to make it **saveAs**.saveAs (not saveAs)

**Comment by jwmann** [comment]
@dovk Oh yea, I just remembered, specifically for `file-saver` you need to import the non-default function `saveAs`.

This should make your life a little easier.
````
import { saveAs } from 'file-saver';
````

I'll edit my original comment to reflect this.

**Comment by dovk** [comment]
It looks like this is a brilliant piece of work. Now all I need is to save it as a PDF. Does anyone have an idea how to do that ?

**Comment by jwmann** [comment]
I use [jsPDF](https://github.com/MrRio/jsPDF) with the [jsPDF Autotable plugin](https://github.com/simonbengtsson/jsPDF-AutoTable) and it worked great for me.

I recall their doc.save() method worked out of the box for me.
Would recommend 👍

**Comment by dovk** [comment]
OK, I'm looking at it. Since I created the output as XML spreadsheet, I was hoping for something that would take that and convert to PDF (directly or via a conversion to XLSX), in other words I preferred converting from one source (XML) instead of writing the whole thing over. But it looks promising, so I'll check it out. Thanks!

**Comment by weelillad** [comment]
An alternative solution that worked for me:

In my `.ts` files: `import * as exceljs from 'exceljs';`

In `webpack.config.js`:
```
module.exports = {
    resolve: {
        alias: {
            exceljs: path.resolve(__dirname, 'node_modules/exceljs/dist/exceljs.min')
        }
    }
}
```

**Comment by aallvviinn** [comment]
@jwmann Thanks for the solution. Only issue I have is when i process large data for eg: (20 cols x 100k rows) chrome gives **Aw snap!** error. Any workaround?
@guyonroche Any suggestion?

**Comment by Jaguar1** [comment]
Hi, this is what works for me, but I am not sure this is the best solution:
```
import * as Excel from 'exceljs/dist/exceljs.min.js';
import { saveAs } from 'file-saver';
```
..and then:
```
workbook.xlsx.writeBuffer().then( data => {
   const blob = new Blob( [data], {type: "application/octet-stream"} );
   saveAs( blob, 'MyFile.xlsx');
});
```

**Comment by swamy-m-s** [comment]
> If you are having issues with importing regarding the `fs` module.
> Try adding:
> 
> ```js
> node: {
>       fs: "empty"
> },
> ```
> 
> to your `webpack.config.js` this fixed it for me. And I can import the library via:
> 
> ```js
> import ExcelJS from "exceljs/dist/es5/exceljs.browser";
> ```

where can I find webpack.config.js
