### ISSUE TITLE
Open xlsx file that have chart

### ISSUE THREAD

**Issue by kathawut** [exceljs/exceljs#307]
This image is template file that have chart.
![1493019403669](https://cloud.githubusercontent.com/assets/675592/25328582/9285b82a-2902-11e7-91f0-f515bd21b41e.jpg)

After I written it, I open it. Chart is disappear.
![1493019432196](https://cloud.githubusercontent.com/assets/675592/25328583/9285c086-2902-11e7-96d3-80e4fa5b820b.jpg)

Hi, I have chart in my xlsx file. I write some data with exceljs and then I opened file.My chart is disappear. How can I solved?

**Comment by Toub** [comment]
Unfortunately, it is not supported yet.

Duplicate of https://github.com/guyonroche/exceljs/issues/141

**Comment by ArkhipovK** [comment]
Does the problem still there?

**Comment by yvzkr** [comment]
I guess not yet.

**Comment by felix25** [comment]
there is already the integration for excelljs??
