### ISSUE TITLE
cannot work with exceljs using angular-cli (1.1.1)

### ISSUE THREAD

**Issue by marc0olo** [exceljs/exceljs#335]
I always get the following error when trying to use exceljs within my angular-application (created and running with angular-cli 1.1.1)
```
ERROR in ./~/natives/index.js
Module not found: Error: Can't resolve 'module' in 'C:\XXX\node_modules\natives'
 @ ./~/natives/index.js 2:13-30
 @ ./~/unzip2/~/graceful-fs/fs.js
 @ ./~/unzip2/~/graceful-fs/graceful-fs.js
 @ ./~/unzip2/~/fstream/lib/file-writer.js
 @ ./~/unzip2/~/fstream/fstream.js
 @ ./~/unzip2/lib/extract.js
 @ ./~/unzip2/unzip.js
 @ ./~/exceljs/dist/es5/stream/xlsx/workbook-reader.js
 @ ./~/exceljs/dist/es5/index.js
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```
anybody else running in this issue? am I doing wrong something? I added the library by running `npm install exceljs --save` and imported it ultimately in various ways and always ended up with the error above.

would be great you could help me out to get this lib used in my project. thanks! :-)

**Comment by marc0o-** [comment]
well as I read in other issues this has something to do with typescript ... got it working now by importing the lib as follows:
`import * as ExcelJs from 'exceljs/dist/exceljs.min.js';`

**Comment by ryanpm40** [comment]
@marc0o- where did you make this import? In app.module, or in the component using it? 

When I try to import ExcelJs (0.4.12) in an app component, or within <script> tags in index.html, the page does not render at all, but no errors appear in the console. Were there other steps needed from your end, aside from installing and saving to package.json?

**Comment by marc0o-** [comment]
the import-statement above was made in the component.ts (NOT in the index.html or elsewhere)

when using angular-cli the command "npm install exceljs --save" should add the package automatically to the package.json and the package-lock.json

**Comment by ryanpm40** [comment]
@marc0o- Ok, thanks! Very odd, the application still fails to load without any console errors. I have it installed in package.json, as well. You didn't need to find a ".d.ts" typings file, did you?

Guess I'll be trying out js-xlsx from SheetJs. Quite a bummer since Exceljs seems to be a bit easier to follow.

**Comment by ilya-payrange** [comment]
I used this method (presented above)

In project tree:
`npm install exceljs --save`

In the component.ts:
`import * as ExcelJs from 'exceljs/dist/exceljs.min.js';`

Do not try to do dependency injection into constructor() (it requires proper .d.ts). Instead just grab the ExcelJs:

`var workbook = new ExcelJs.Workbook();`

Works for me. 

P.S. When I was trying `var workbook = new ExcelJs.Workbook();` with `import ExcelJs from 'exceljs;`, app crashed.

**Comment by bryannbarbosa** [comment]
I'm trying to open the excel file in ReadFile method in ExcelJS, but I can not, how to fix it?

**Comment by jwmann** [comment]
I cannot use `.writeFile` method, using the minified import technique.
See #299

**Comment by timratha** [comment]
Is there any update from exceljs team to have properly import exceljs to app:
ex:  "import ExcelJs from 'exceljs;"

**Comment by fidoogle** [comment]
@marc0olo ```import * as ExcelJs from 'exceljs/dist/exceljs.min.js';``` worked for me in CodeSandbox.io
Thanks!

**Comment by jmac-slash0** [comment]
In [this comment](https://github.com/guyonroche/exceljs/issues/511#issuecomment-391140701) I showed how I added it in Angular 5 with nice types (should work in 4 too).
