### ISSUE TITLE
Stream Reader Documentation Lack

### ISSUE THREAD

**Issue by nickykln** [exceljs/exceljs#340]
Hello,
Your API is pretty cool. I manage to make it works very easily. But I am struggling with Stream Reader
Could you please provide a quite example in the documentation of how to read basic data rows using this method.

Thank you very much, 

Nicolas

**Comment by FrankAst** [comment]
+1

**Comment by techsavyravi** [comment]
+1

**Comment by kapilpjain1** [comment]
I am also waiting for same

**Comment by vimutti77** [comment]
+1

**Comment by danielcastill0** [comment]
+1 Hey there guys! I need this feature ASAP!

**Comment by fmenis** [comment]
+1 Me too!!

**Comment by alubbe** [comment]
If you can wait a little bit longer, this exceljs 4.0.0 will have more documentation (https://github.com/exceljs/exceljs/pull/1135/files#diff-04c6e90faac2675aa89e2176d2eec7d8R2253) and this new usage:
```js
const workbookReader = new ExcelJS.stream.xlsx.WorkbookReader('./file.xlsx');
for await (const worksheetReader of workbookReader) {
  for await (const row of worksheetReader) {
    // do something with row...
  }
}
```
https://github.com/exceljs/exceljs/pull/1135

**Comment by alubbe** [comment]
Published as v4 - enjoy!

**Comment by DrecDroid** [comment]
Wow, thanks for that feature!. I want to use it on Typescript but It looks like typings where not generated for WorkbookReader. Thank you anyways, I think there will be not problems using it without typings.
