### ISSUE TITLE
Does a Minified Version of the Library exist?

### ISSUE THREAD

**Issue by johnrileybjss** [exceljs/exceljs#346]
This library is perfect for a use case I need to accomplish for a project, but unfortunately the person who architected the project architected it in a strange fashion, such that I can't simply import the node module. Our dependencies are all in minified js form, and using dependencies which don't match this format would required overhauling our build process in a way that's not feasible for my current development cycle. 

Is there somewhere I can find an all-in-one minified version of exceljs?

**Comment by spacem** [comment]
node_modules/exceljs/dist/exceljs.min.js

**Comment by johnrileybjss** [comment]
That was simple. Thank you!

**Comment by johnrileybjss** [comment]
I'm re-opening the issue because I while I man

**Comment by shivavelingker** [comment]
@johnrileybjss Did the minified file work for you? When I include only it, my code can't recognize the basic keywords like `Excel` or `Workbook`

**Comment by johnrileybjss** [comment]
@shivavelingker No, I'm having the same problem. Is the minified library designed for browsers? Maybe we need to minify the excel.browser.js file?

**Comment by Siemienik** [comment]
one of this should work
```
node_modules/exceljs/dist/exceljs.min.js
node_modules/exceljs/dist/es5/exceljs.browser.js
````
