### ISSUE TITLE
TypeError : Excel file that contains charts

### ISSUE THREAD

**Issue by miniil** [exceljs/exceljs#347]
Hi,

I have this error Type Error: Cannot read property 'rId' of null when à try to use an Excel file that contains charts.  If I remove charts no error.

Is it possible to fix this?

Thanks for your response.

**Comment by alandoyle95** [comment]
also getting this error, no charts though.

**Comment by vukanac** [comment]
Is this patched to some release?

**Comment by Jaloko** [comment]
Also getting this error after adding a chart to a worksheet.

**Comment by papandreou** [comment]
This was fixed in 0.6.0 (dfd12e80f24d922a20007243619e2f4850dcaa13)
