### ISSUE TITLE
ExcelJS with Angular and Typescript

### ISSUE THREAD

**Issue by johnrileybjss** [exceljs/exceljs#348]
I'm working on integrating ExcelJS into a browser based node.js client built using the angular framework and typescript (and grunt). I previously tested the library in a separate project and was able to get it working using grunt with browserify, but this required me to bundle my own app.js script with a 'require' on the exceljs dependency.

My current project is designed to reference minified libraries by declaring script tags in index.html, and type definitions in a separate typings folder. I've done both for exceljs, but when I attempt to run my code (which declares a new Workbook via new Excel.Workbook()), I get the following error:

`ReferenceError: Can't find variable: Excel in app/src/myScript.js (line 56)`

Also Note: When I try and add a require statement on exceljs in the file that needs it, I get another ReferenceError:

`ReferenceError: Can't find variable: require`

What steps am I missing in integrating the library such that Excel will be recognized as the correct namespace? Or is there another way I should be declaring a Workbook?

**Comment by Gargamil** [comment]
In which way you import exceljs? 

I use ExcelJs in Angular (4) and TS too, with the following import:

`import * as Excel from 'exceljs';`

after that, you can use Exceljs:

` const myWorkbook = new Excel.Workbook();`

**Comment by johnrileybjss** [comment]
I've tried adding that line as it is into my angular service responsible for exporting xlsx. I get the following error when I run my unit tests:

`ReferenceError: Can't find variable: define`

**Comment by Gargamil** [comment]
Check your environment and unit tests. This is no error in context of Exceljs.

**Comment by johnrileybjss** [comment]
I see. I'll do some more leg work and see if I'm missing something crucial. I know I've seen some things regarding angular mocks, perhaps I've not configured my project correctly to mock Excel.

As a quick question though, where do you place that import statement in your angular project? Do you place it in the class which requires it? Or do you place it in one of your module declarations?

**Comment by Gargamil** [comment]
>As a quick question though, where do you place that import statement in your angular project? Do you place it in the class which requires it? Or do you place it in one of your module declarations?

i've created an service, in which the import of exceljs takes place and works with it. Nowhere else.

**Comment by IRCraziestTaxi** [comment]
@Gargamil I am trying to use exceljs in Angular 4 but my app fails to compile when I try to import and use it. I am importing and using it exactly as you've said: `import * as Excel from "exceljs";` and `let workbook = new Excel.Workbook();`. The webpack errors I get are:

```
WARNING in ./~/natives/index.js
44:17-28 Critical dependency: the request of a dependency is an expression
```

and

```
ERROR in ./~/natives/index.js
Module not found: Error: Can't resolve 'module' in '...\node_modules\natives'
 @ ./~/natives/index.js 2:13-30
 @ ./~/unzip2/~/graceful-fs/fs.js
 @ ./~/unzip2/~/graceful-fs/graceful-fs.js
 @ ./~/unzip2/~/fstream/lib/reader.js
 @ ./~/unzip2/~/fstream/fstream.js
 @ ./~/unzip2/lib/extract.js
 @ ./~/unzip2/unzip.js
 @ ./~/exceljs/dist/es5/stream/xlsx/workbook-reader.js
 @ ./~/exceljs/dist/es5/index.js
 @ ./~/client.common/src/app/pages/landing/landing.component.ts
 @ ./~/client.common/src/app/app.module.ts
 @ ./~/client.common/module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4202 ./src/main.ts
```

Removing the import and the code that uses it mitigates all errors. I have also tried including dist/exceljs.min.js and dist/es5/exceljs.browser.js in the scripts section of .angular-cli.json but got exactly the same results. Does any of that ring any bells? I'm stumped.

**Comment by IRCraziestTaxi** [comment]
I got it working by using:

```
import * as Excel from "exceljs/dist/exceljs.min.js";
```

rather than

```
import * as Excel from "exceljs";
```

**Comment by IRCraziestTaxi** [comment]
However, now I have the issue that type definitions are not being picked up for exceljs. This is pretty annoying.

**Comment by IRCraziestTaxi** [comment]
I have found a workaround for no type definitions:

```typescript
import * as Excel from "exceljs/dist/exceljs.min.js";
import * as ExcelProper from "exceljs";

let workbook: ExcelProper.Workbook = new Excel.Workbook();
```

As long as you just use the import from `exceljs` for type definitions and only use the import from `exceljs/dist/exceljs.min.js`, the app will run just fine and you still get type safety.

**Comment by jmac-slash0** [comment]
No workaround needed anymore: [example](https://github.com/guyonroche/exceljs/issues/511#issuecomment-391140701).

**Comment by visrey** [comment]
After wasting an hour time found this workaround working for me instead of the above 

`import * as ExcelJS from "exceljs/dist/exceljs.min.js";`

`let workbook = new ExcelJS.Workbook();`

Accessing it with name ExcelJS solved issue.
Hope this helps.

**Comment by askumar17** [comment]
Team,

I am using Angular 5 and i need to use Exceljs in my aplication. Could you please what is the exact version for accessing exceljs in angular 5. 

page is not rendering if i use work book in excel.service file.

FYI.
I  am using Angular 5 with "exceljs": "^1.6.2",.

Kindly help me any one.

**Comment by askumar17** [comment]
> After wasting an hour time found this workaround working for me instead of the above
> 
> `import * as ExcelJS from "exceljs/dist/exceljs.min.js";`
> 
> `let workbook = new ExcelJS.Workbook();`
> 
> Accessing it with name ExcelJS solved issue.
> Hope this helps.

Hi,

Can you tell me which exceljs version you used in angular application. Help me plse.

**Comment by Outdoorsmanedit-in-place** [comment]
> However, now I have the issue that type definitions are not being picked up for exceljs. This is pretty annoying.





https://oracle-apex-51.github.io/source/
