### ISSUE TITLE
New line in richText cell

### ISSUE THREAD

**Issue by bpryer** [exceljs/exceljs#353]
Take the following code:

    let excel = require('exceljs')
    let wb = new excel.Workbook()
    let ws = wb.addWorksheet('test')

    ws.getCell('B2').value = {
      richText: [
        {
          font: {
            color: {
              argb: `99E391`
            }
          },
          text: `Chuck Norris' tears cure cancer,\n`
        },
        {
          font: {
            color: {
              argb: `FF6565`
            }
          },
          text: `too bad Chuck Norris has never cries.`
        }
      ]
    }

    wb.xlsx.writeFile('./test.xlsx').then(err => {
      if (!err) {
        console.log(`file written successfully.`)
      } else {
        console.log(`error writing file: ${err}`)
      }
    })

The result will be a string resembling the following (Ignoring the line break):

> Chuck Norris' tears cure cancer,too bad Chuck Norris never cries.

It seems as though the line break is being stripped from the ends of the text property when the file is being written.

By simply adding a character after the \n the line break does not get removed.  Is there a setting somewhere to turn this functionality on or off?

**Comment by t1hk** [comment]
It works for me, if I change the code in the 3 modules

node_modules\exceljs\dist\es5\xlsx\xform\strings\text-xform.js
node_modules\exceljs\dist\exceljs.js
node_modules\exceljs\dist\exceljs.min.js

from:
if (model[0] === ' ' || model[model.length - 1] === ' ') {
      xmlStream.addAttribute('xml:space', 'preserve');
 }

into:
if (model[0] === ' ' || model[0] === '\n' || model[model.length - 1] === ' ' || model[model.length - 1] === '\n') {
      xmlStream.addAttribute('xml:space', 'preserve');
 }

**Comment by MikeZyatkov** [comment]
Try add space in line with '\n'. Like this:
```
  {
      'richText': [
        {font: {underline: true}, text: ' °C \n'},
        {font: {underline: false}, text: 'м'}
      ]
    };
```

**Comment by TrevorJamesH** [comment]
@t1hk You should make a PR, I'm still seeing this issue.

**Comment by ilimei** [comment]
load some xlsx file and save , the richText will missing in save file

**Comment by Siemienik** [comment]
anyone could open PR for that?

**Comment by Ahmad-Abo-Saa** [comment]
> @bpryer
> Try add space in begin line with '\n'. Like this:
> 
> ```
>   {
>       'richText': [
>         {font: {underline: true}, text: ' °C \n'},
>         {font: {underline: false}, text: 'м'}
>       ]
>     };
> ```

or you can add the space at the end of the line that contains the "\n"

**Comment by Alanscut** [comment]
@Siemienik This bug has been fixed by **guyonroche**, See https://github.com/exceljs/exceljs/commit/493bf3f6b627ed3bbdd0c9ef58f0479c411cc4cc
