### ISSUE TITLE
Download multiple xlsx files as zip in the client

### ISSUE THREAD

**Issue by gtskaushik** [exceljs/exceljs#357]
Use Case:-

1. Create multiple xlsx files
2. Do not write them to server
3. Zip all the files. Again in-memory
4. Push it to client for downloading

Please help me to solve this issue. As this is a blocker for my deliverable.

**Comment by achraf-boussaada** [comment]
Looking for the same thing! @gtskaushik did you manage to get it working?

**Comment by gtskaushik** [comment]
Nope :-( I did a workaround
1. Write all the xlsx files to temp location
2. Create a zip out of it
3. stream the zip file to client
