### ISSUE TITLE
getWorksheet does not work after piping into input stream rather than using workbook.xlsx.read

### ISSUE THREAD

**Issue by IRCraziestTaxi** [exceljs/exceljs#371]
I actually am having several issues trying to use this library in an Angular 4 application.  I'll focus on the one in the title, but I'll mention the others for context.

The first problem is that using `import * as Excel from "exceljs";` produces errors regardless of the scripts I include in .`angular.cli`.  See my comments on issue [348](https://github.com/guyonroche/exceljs/issues/348).  As you can see, I must import from `exceljs/dist/exceljs.min.js` instead.  The problem with that is that type definitions are no longer picked up by VS Code.  That, however, is a minor inconvenience.

The main problem is with reading a file from a stream.  Using `workbook.xlsx.read(stream)` works, but `.read()` is not in the type definitions for `exceljs`, so I must cast it as `any` in order to use it.

I looked at the docs and found the suggested method of using `stream.pipe(workbook.xlsx.createInputStream())`.  It does read the file and makes my code cleaner, so I want to use that method instead, but when I do that, `.getWorksheet()`, `.worksheets`, and `.eachSheet()` all fail to find any worksheets even though I can see in the console from logging `workbook` that the sheets are indeed on the workbook and have the correct properties.

**Comment by mor-o** [comment]
i am having the same problem. 
i read the stream like the docs suggested (with stream.pipe(workbook.xlsx.createInputStream()))
and the resulting workbook has no worksheets for some reason.
any idea why?

**Comment by buddythumbs** [comment]
+1 on this - can someone please help out here?

**Comment by Siemienik** [comment]
is this issue actual?
