### ISSUE TITLE
Require/Import Exceljs

### ISSUE THREAD

**Issue by johnrileybjss** [exceljs/exceljs#375]
I'm trying to integrate ExcelJS v0.4.4 into my browser client which uses the AngularJS framework. I don't have access to require statements in this project, and trying to get requirejs to work has been a nightmare, so I'd prefer if I didn't need that.

What is the recommended way to get the browser version of the library to work properly in an Angular setting? I've been struggling with this issue for weeks and can't seem to get this to work at all.

Here's some of my code for my test project (not using angular here, just trying to get the browser version to load properly):

index.html
```
<!DOCTYPE html>
<head>
  <title>Test Excel JS</title>
  <meta charset="utf-8">
  <meta name="description" content="">
</head>
<body>
  <div>
    <label>Test</label>
    <button onclick="writeTestExcelFile()">Test this Stuff and Check your console log</button>
  </div>

  <script src="node_modules/requirejs/require.js" type="text/javascript"></script>
  <script src="node_modules/exceljs/dist/exceljs.min.js" type="text/javascript"></script>
  <script src="node_modules/exceljs/lib/exceljs.browser.js" type="text/javascript"></script>
  <!--<script src="node_modules/exceljs/excel.js" type="text/javascript"></script>-->

  <script src="src/vendor/FileSaver.min.js" type="text/javascript"></script>
  <script src="src/js/app.js" type="text/javascript"></script >
</body>
</html>

```

app.js
```
'use strict';

var isRowBold = function(excelRow){
    return excelRow.getCell('name').value === "Jeff";
};

var getRowColor = function(excelRow){
    return { argb: excelRow.getCell('colorCode').value };
};

var getCellColor = function(excelRow, cell){
    return (excelRow.getCell('name').value === 'John' && cell.value === 0)? { argb: 'FFFFFF00' } : getRowColor(excelRow);
};

var getFont = function(isBold, color){
    return {
        name: 'Arial Black',
        color: color,
        family: 2,
        size: 14,
        bold: isBold
    };
};

var getTestHeader = function(){
    return [
        {key: "id", header: "Id"},
        {key: "name", header: "Name", width: 32},
        {key: "color", header: "Color", width: 10},
        {key: "colorCode", header: "Color Code", width: 10}
    ];
};

var getTestData = function(){
    return [
        {
            id: 0,
            name: "John",
            color: "green",
            colorCode: "FF00FF00"
        },
        {
            id: 1,
            name: "Rehan",
            color: "red",
            colorCode: "FFFF0000"
        },
        {
            id: 2,
            name: "Jeff",
            color: "purple",
            colorCode: "FFFF00FF"
        }
    ];
};

var generateTestFile = function(){
    var workbook = new ExcelJS.Workbook();

    // Set Workbook Metadata
    workbook.creator = "Generated";
    workbook.lastModifiedBy = "Generated";
    workbook.created = new Date();
    workbook.modified = new Date();

    // Create Worksheet
    var worksheet = workbook.addWorksheet('Sheet 1');

    //Set Column Headers
    worksheet.columns = getTestHeader();

    //Add Rows
    var testData = getTestData();
    var length = testData.length;
    for(var i = 0; i < length; i++){
        worksheet.addRow(testData[i]);
    }

    //Format Rows
    worksheet.eachRow(function(row, rowNumber){
        var isBold = isRowBold(row);
        row.eachCell(function(cell, colNumber){
            var cellColor = getCellColor(row, cell);
            cell.font = getFont(isBold, cellColor);
            console.log(cell);
            console.log(cell._column._key);
        });
    });

    return workbook;
};

var writeTestFile = function (){
    var path = "test.txt";
    var data = "Test Content\n";

    var blob = new Blob([data], { type : 'text/plain' });

    /*
     fs.writeFile(path, data, "binary", function(e){
     if(e){
     console.log('Error has occurred');
     console.log(e);
     }
     else{
     console.log('Success!');
     }
     });
     */
    console.log('Writing Test File');
    saveAs(blob, path);
    console.log('Test File Written');
};

var writeTestExcelFile = function(){
    var path = "testExcel.xlsx";
    var mimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    var workbook = generateTestFile();
    workbook.xlsx.writeBuffer()
        .then(function(data) {
            console.log('Binary Buffer Opened');
            console.log(data);

            console.log('Creating blob');
            var blob = new Blob([data], { type : mimeType });

            console.log('Writing file to output/test.xlsx');

            saveAs(blob, path);
            console.log('File written!');
        });
};
```

Currently the require statement is supposed to work with requirejs, but it doesn't. Instead I get the following error from the exceljs.browser file:

```
Uncaught Error: Module name "config/set-value" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:168)
    at Object.localRequire [as require] (require.js:1436)
    at requirejs (require.js:1797)
    at exceljs.browser.js:2
```

**Comment by brucejo75** [comment]
Did you look at the description here: https://github.com/guyonroche/exceljs#browser

[`excel-spec.js`](https://github.com/guyonroche/exceljs/blob/master/spec/browser/exceljs.spec.js) is the example file to guide you on how to use `Exceljs` in the browser.

**Comment by jethik** [comment]
browserify ExcelJSTest.js -o bundle.js

ExcelJSTest.js

>
   ```
var Excel = require('./lib/exceljs.browser');
   window.ExcelJS = Excel;
```

index.html
`<html>
<body>
<h2>Hello friends</h2>
<script type="text/javascript" src="bundle.js"></script>
<script type="text/javascript" src="FileSaver.min.js"></script>
<script>
    // create workbook & add worksheet
	var workbook = new ExcelJS.Workbook();
	var worksheet = workbook.addWorksheet('Discography');

	// add column headers
	worksheet.columns = [
	    { header: 'Album', key: 'album'},
	    { header: 'Year', key: 'year'},
	    { header: 'Age', key: 'age'}
	];

	// add row using keys
	worksheet.addRow({album: "Taylor Swift", year: 2006, age : 20});

	// add rows the dumb way
	worksheet.addRow(["Fearless", 2008, 22]);

	// add an array of rows
	var rows = [
	  ["Speak Now", 2010, 30],
	  {album: "Red", year: 2012, age: 35}
	];
	worksheet.addRows(rows);

	// edit cells directly
	worksheet.getCell('A6').value = "1989";
	worksheet.getCell('B6').value = 2014;
	worksheet.getCell('C6').value = 23;

	worksheet.autoFilter = {
	    from: {
	        row: 1,
	        column: 1
	    },
	    to: {
	        row: 5,
	        column: 2
	    }
	}

	console.warn("create workbook###", workbook.xlsx);
	// save workbook to disk
	console.warn("savving###");

	var path = "assets.xlsx";
	var mimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
	workbook.xlsx.writeBuffer()
	.then(function(data) {
	    console.log('Binary Buffer Opened');
	    console.log(data);

	    console.log('Creating blob');
	    var blob = new Blob([data], { type : mimeType });

	    console.log('Writing file to output/test.xlsx');

	    saveAs(blob, path);
	    console.log('File written!');
	});
</script>
</body>
</html>`
