### ISSUE TITLE
Apply fill to range of cells

### ISSUE THREAD

**Issue by dnshr** [exceljs/exceljs#379]
we can apply fill to a particular cell. But is there a way to apply fill to a range of cells like below?
```
    worksheet.getCell('A1:C3').fill = {
                type: 'pattern',
                pattern:'solid',
                fgColor:{argb:'FFFF0000'}
            };
```

**Comment by Rycochet** [comment]
Internally it would need extending the Array returned - not particularly hard (and I'm adding that for VelocityJS for the same reason) - however it does potentially mean overriding an actual built in function (we don't know what method names are going to be used in the future).

For now it's pretty easy to do (ES6 / Typescript) -

```typescript
worksheet.getCell('A1:C3').forEach(cell => cell.fill = {
   type: 'pattern',
   pattern:'solid',
   fgColor:{argb:'FFFF0000'}
});
```

or (ES5 / JavaScript) -

```javascript
worksheet.getCell('A1:C3').forEach(function(cell) {
   cell.fill = {
      type: 'pattern',
      pattern:'solid',
      fgColor:{argb:'FFFF0000'}
   }
});
```

**Comment by dnshr** [comment]
that 2nd example throws forEach is not a function error.

**Comment by gigaga** [comment]
+1

**Comment by chenop** [comment]
Confirm that forEach throw exception.

Here is how I've implment it:
```
['A1', 'B1', 'C1', 'D1', 'E1', 'F1', 'G1'].map(key => {
        sheet.getCell(key).fill = {
            type: 'pattern',
            pattern:'solid',
            fgColor:{argb:'cccccc'}
        };
    });
```

**Comment by Siemienik** [comment]
#339 #180  #441
