### ISSUE TITLE
CSV does not support writeBuffer

### ISSUE THREAD

**Issue by Quantumplation** [exceljs/exceljs#383]
xlsx parsing provides a convenience wrapper for writing to a buffer:

https://github.com/guyonroche/exceljs/blob/3623df4522b390a84b4eda34aab56e9bbefce571/lib/xlsx/xlsx.js#L659

CSV, however, has no such wrapper, meaning the interfaces of these two objects is different:

https://github.com/guyonroche/exceljs/blob/3623df4522b390a84b4eda34aab56e9bbefce571/lib/csv/csv.js#L102

We can achieve the same by constructing and passing in our own buffer, but having a consistent interface would be nice.

**Comment by jathanasiou** [comment]
Is there any update for this? I tried implementting `writeBuffer` for the csv lib but it seems like the results are comma(`,`) separated instead of semicolon(`;`) separated as one would expect in CSV.

**Comment by Linpter** [comment]
> 
> 
> Is there any update for this? I tried implementting `writeBuffer` for the csv lib but it seems like the results are comma(`,`) separated instead of semicolon(`;`) separated as one would expect in CSV.

I'm also hoping for a way to do the same. Does anyone know how i can do it even it means dig a bit in the code ?

**Comment by Quantumplation** [comment]
Uh, not sure I understand the previous two comments.

First, @jathanasiou CSV stands for Comma Separated Values, so I would expect them to be comma separated ;)

Second, @Linpter looks like this has since been added, as of this PR:

https://github.com/exceljs/exceljs/pull/549

Closing this issue since it's been addressed.

**Comment by Quantumplation** [comment]
(As a side note, it looks like the library used to support custom separators, but no longer does: https://github.com/exceljs/exceljs/blob/3623df4522b390a84b4eda34aab56e9bbefce571/lib/csv/csv.js#L106)
