### ISSUE TITLE
workbook.xlsx.writeFile ==> no such file or directory 

### ISSUE THREAD

**Issue by love8587** [exceljs/exceljs#390]
I tried to write xlsx with writeFile(). But it was failed and when I checked the reason I realized there was no dir. But When I use another s3 NPM module, the module creates directory automatically.

Of course, I can resolve it easily as creating the directory  before writing a file, but I hope writeFile() works with creating dir when there is no dir.
```

{ Error: ENOENT: no such file or directory, open '/tmp/new_dir/file_name.xlsx'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/new_dir/file_name.xlsx' }
```

**Comment by Siemienik** [comment]
I don't think it's fine as a default behavior

**Comment by QingNeng** [comment]
I get same in Windows

**Comment by papandreou** [comment]
This suggestion seems to pop up in many libs that write files, eg. https://github.com/lovell/sharp/issues/1052#issuecomment-349401421

I'd personally find it too surprising, and it's really no trouble to just `mkdirp` the directory beforehand. Doesn't make sense for every library to onboard this complexity.

**Comment by gaspan** [comment]
you must know that folder name or file name can not write with special carachter, you can change the name.
