### ISSUE TITLE
{ properties: { showGridLines: false } } not working

### ISSUE THREAD

**Issue by JacobWeisenburger** [exceljs/exceljs#408]
I am trying to not show the grid lines with this code:
```
var sheet1 = workbook.addWorksheet( 'sheet1', { properties: { showGridLines: false } } )
```
But it is still showing the grid lines. Am I doing something wrong?

Here is the rest of my code:
```
const Excel = require('exceljs')
var workbook = new Excel.Workbook()
var sheet1 = workbook.addWorksheet( 'sheet1', { properties: { showGridLines: false } } )
sheet1.columns = [
  { header: 'Mark', key: 'Mark', width: 20 }
  ,{ header: 'QTY', key: 'QTY', width: 10 }
  ,{ header: 'Description', key: 'Description', width: 50 }
  ,{ header: 'Thickness', key: 'Thickness', width: 10 }
  ,{ header: 'Width', key: 'Width', width: 10 }
  ,{ header: 'Depth', key: 'Depth', width: 10 }
  ,{ header: 'Length', key: 'Length', width: 10 }
  ,{ header: 'Remarks', key: 'Remarks', width: 25 }
]
sheet1.getRow(1).alignment = { horizontal: 'center' }

sheet1.addRow({
  Mark: 'D6x12-4x7'
  ,QTY: 2
  ,Description: 'Column Assembly'
  ,Thickness: '1/2'
  ,Width: 10
  ,Depth: 6
  ,Length: 145
  ,Remarks: 'A992'
}).alignment = { horizontal: 'center' }
```

**Comment by Blakey** [comment]
I had same issue and played around for hours until I worked it out. Do it using views like this instead. The below will create a sheet names "test", colour it blue, remove the grid-lines, freeze the top 5 rows and make the active cell A1:

workbook.addWorksheet('test',{properties:{tabColor:{argb:'FF00FF00'}},views:[
        {state: 'frozen', ySplit: 5, activeCell: 'A1', showGridLines:false}
    ]})

**Comment by offg777** [comment]
that worked, thanks.

**Comment by Amittrexoglobal** [comment]
> I had same issue and played around for hours until I worked it out. Do it using views like this instead. The below will create a sheet names "test", colour it blue, remove the grid-lines, freeze the top 5 rows and make the active cell A1:
> 
> workbook.addWorksheet('test',{properties:{tabColor:{argb:'FF00FF00'}},views:[ {state: 'frozen', ySplit: 5, activeCell: 'A1', showGridLines:false} ]})

Thanyou so much dudde, it worked !!
