### ISSUE TITLE
Read a Cell from a Worksheet Currently Being Built

### ISSUE THREAD

**Issue by sfreeman422** [exceljs/exceljs#413]
I am in need of the ability to read the cells of a worksheet as it is being built. Essentially, I want to check if something exists in a specific cell then do something based on that information. I can't seem to find an easy answer to this in the documentation as it appears `worksheet.getCell('C2').value` is only used to set a value but not to read the value. 

Any guidance on this one?

**Comment by Siemienik** [comment]
`Cell` class has defined a lot of getters, for example `model` is very useful:)
https://github.com/exceljs/exceljs/blob/master/lib/doc/cell.js#L289
