### ISSUE TITLE
eachCell includeEmpty not working as expected

### ISSUE THREAD

**Issue by tribakzero** [exceljs/exceljs#432]
Using 0.6.2 (but updated from 0.5.1 hoping it fixed the issue)
I can't get eachCell to loop over all the empty cells, it gets only the cells with content (in this case A2)

```
worksheetData.eachRow({ includeEmpty: true }, (row, rowNumber) => { // Tried adding and removing includeEmpty here even when I think it's not needed but on eachCell
  console.log(row.cellCount) // 1 (outputs 35 for the headers row)
  row.eachCell({ includeEmpty: true }, (item, colNumber) => {
    console.log(item.worksheet.columnCount) // 35
  }) // eachCell runs only once since cellCount == 1
})
```

I expect it to get the full column count used on worksheet.columnCount and let eachCell loop over every cell.

**Comment by cris391** [comment]
eachCell also doesn't work as intended, includeEmpty property doesn't skip empty cells

**Comment by sandeep-bhaskar** [comment]
empty cells are replacing with the next cell, **includeEmpty** is not working
