### ISSUE TITLE
Range for .fill method

### ISSUE THREAD

**Issue by ZaeemR** [exceljs/exceljs#441]
Hello,

Can we give a range to colour the columns? For examples, I want to assign colour #CECEEC to columns A, B, ... , Z. Is there any way to do this in one line through some plugin functionality or do I have to handle it some different way? Is there any .Range method? Further, is there any method to colour the header differently than the whole column, like header in grey and column in yellow?

Thanks.

Zaeem

**Comment by Siemienik** [comment]
resolved in #339
