### ISSUE TITLE
Example of using browser version

### ISSUE THREAD

**Issue by james-boswell** [exceljs/exceljs#443]
Hi. Could someone show an example of using the browser version of this library? I have been unable to get it to work as I am getting "require is not defined" errors.

**Comment by rob2d** [comment]
second. I am also seeing when I use browserify that it attempts to use packages such as `fs` which are not set as explicit dependencies.

**Comment by zgriesinger** [comment]
First do: `npm install exceljs` or `yarn add exceljs` to your project.

Then at the top of the file: `import ExcelJS from "exceljs/dist/es5/exceljs.browser";`

Now to fix the import errors you must put this in your `webpack.config.js`

```javascript
node: {
      fs: "empty"
},
```

I'm not sure if this will work with Browserify but the solution is probably along similar lines

**Comment by i365** [comment]
[exceljs.js usage example on web browser](https://jstool.gitlab.io/demo/exceljs/?g2)
