### ISSUE TITLE
Is dd/mm/yyyy numFmt not supported?

### ISSUE THREAD

**Issue by amitbeck** [exceljs/exceljs#445]
I read a cell containing a date from some workbook, and copied it to another workbook's cell.
When reading it, the cell's numFmt was `'mm-dd-yy'` even though the value was 03/08/2017 (`'dd/mm/yyyy'` format). How come the numFmt does not match?

Anyway, I tried setting `'dd/mm/yyyy'` as the numFmt of the copied cell and instead it displayed `#######` in my generated worksheet.
Are not all numFmt formats for dates supported?

**Comment by zgriesinger** [comment]
Try widening the column width of the cell, sometimes they don't show up right away for me.
