### ISSUE TITLE
Is it not possible to add image using the WorkbookWriter?

### ISSUE THREAD

**Issue by mfahmirukman** [exceljs/exceljs#446]
Previously I tried using the excel file writing method. Works fine, but as the data grows so does the memory consumption. Hence the changing of writing method to streaming method.

Tried doing this on WorkbookWriter

```
var sheet = workbook.addWorksheet('Data');
        var base64Data = req.body.img.toString().replace(/^data:image\/png;base64,/, "");
        fs.writeFile('Tagihan/img.png', base64Data, 'base64', function(err) {
            console.log(err);
        })
var img1 = workbook.addImage({
            filename: 'Tagihan/img.png',
            extension: 'png'
        });

        sheet.addImage(img1, 'A1: H25');
```

got this error

`TypeError: workbook.addImage is not a function`

**Comment by ritesh-nitw** [comment]
This issue is a major release blocker. Surprised that, its not being addressed.. 
Right now, its impossible to use addImage using the WorkbookWriter. Any work around won't work.

**Comment by ritesh-nitw** [comment]
Are you planning to support this in future?

**Comment by Siemienik** [comment]
@mfahmirukman @ritesh-nitw 
I am really sad to say that, but probably here is bug with handling `.png` file.

@mfahmirukman could you test this one with `.jpg` and give me a confirmation?

**Comment by mfahmirukman** [comment]
I'm sorry that I can't help anymore because I'm currently not working on the NodeJS project anymore

**Comment by kkor** [comment]
@Siemienik does closing this issue mean you plan on never supporting images in the workbook writer? Or had this been fixed?

**Comment by mtawara** [comment]
I tried using both png and jpg. Both are not working.

**Comment by chdh** [comment]
Duplicate of #322
