### ISSUE TITLE
AutoWidth and/or AutoHeight on cols/rows

### ISSUE THREAD

**Issue by mdissel** [exceljs/exceljs#450]
Any tips how to implement an autoheight and/or autowidth function?

Thanks

**Comment by mah110020** [comment]
This is an often requested features, but I do not expect this feature to be supported in the near future. I get the impression that exceljs just wraps a width value into the excel workbook for excel to interpret, and thus it may be a matter of figuring out how exactly excel renders those texts. But that is speculation.

I would like to share with you my own code, which has worked quite well for me. I use it in all my workbooks to auto-size column widths. It handles the default font and size, richText, bold text, and new lines. It's based on the official excel documentation which states that excel width is a character width length of the default font.

`static eachColumnInRange(ws, col1, col2, cb){
    for(let c = col1; c <= col2; c++){
        let col = ws.getColumn(c);
        cb(col);
    }
}

// not sure on units; width seems to follow offical excel documentation,
// which is the number of default font's characters which fit into a cell.
// default font is Arial 10, which is used here and in the guidelines reference document
// observation: (column width) ~= (column pixel width)/7
// (column width) = ((exceljs width) - 0.71) when (exceljs width) is an integer
// bolding increases width by ~5-9%

static autofitColumns(ws){ // no good way to get text widths
    ExcelUtils.eachColumnInRange(ws, 1, ws.columnCount, column => {
        
        let maxWidth=10;
        column.eachCell( cell => {
            if( !cell.isMerged && cell.value ){ // doesn't handle merged cells or richText objects
                
                let text = "";
                if( typeof cell.value != "object" ){ // string, number, ...
                    text = cell.value.toString();
                } else if( cell.value.richText ){ // richText
                    text = cell.value.richText.reduce( (text, obj) => text + obj.text.toString() , "");
                }
                    
                let values = text.split(/[\n\r]+/); // handle new lines -> don't forget to set wrapText: true
                
                for( let value of values ){
                    let width = value.length;
                    
                    if(cell.font && cell.font.bold){
                        width *= 1.08; // bolding increases width
                    }
                    
                    maxWidth = Math.max(maxWidth, width);
                }
            }
        });
        
        maxWidth += 0.71; // compensate for observed reduction
        maxWidth += 1; // buffer space
        
        column.width = maxWidth;
    });
}`

**Comment by Siemienik** [comment]
#83

**Comment by AllanBontempo** [comment]
You can do something like this:
Foreach on your data and get the desired row through the index
 

    const row = worksheet.getRow(index);
        row.height = row.height * 20 / row.width;


*NOTE:
 - I fixed the number '20', but you can also make it a variable
 - In my excel, my data data starts at line four onwards, so I do:

        const row = worksheet.getRow(index + 4);
