### ISSUE TITLE
Add comment to cell

### ISSUE THREAD

**Issue by jpv** [exceljs/exceljs#451]
Excellent job BTW. Thank you so much !

How can i add a comment to a cell ?

**Comment by Rhuaer** [comment]
Maybe it's not supported yet. I can't find any about comment in the document.

**Comment by jgoris** [comment]
Any update on this?  I agree that this feature would be very helpful.

**Comment by hewford** [comment]
Please answer- thanks!

**Comment by guyonroche** [comment]
Comments (aka Notes) added to v1.12.0
