### ISSUE TITLE
No method / module for converting xlsx into json 

### ISSUE THREAD

**Issue by manojkhadoliya** [exceljs/exceljs#461]
Did not find any method or module for converting xlsx into json directly 
Please suggest if i m missiong something.

**Comment by Martin-Pitt** [comment]
Hi @manojkhadoliya,

It's easy to do this yourself, I mean it really depends on your data and what you need to do, but here is a very rough piece of code:
```
var sheet = workBook.model.sheets[0];
var headerRow = sheet.rows[0];
var dataRows = sheet.rows.slice(1);

var json = dataRows.map(row =>
	headerRow.cells.reduce((map, header, index) => {
		if(header.value) map[header.value] = row.cells[index]? row.cells[index].value : undefined;
		return map;
	}, {})
);
```

Adjust headerRow, for which row contains your headings, and the slice for dataRow for which row that your data starts at.

This code is very simple, my real implementation actually handles cell types and building an in-memory representation.
