### ISSUE TITLE
ECMA-376 formats with numFmt

### ISSUE THREAD

**Issue by amkoehler** [exceljs/exceljs#469]
Hello,

The documentation for numFmt was a little unclear on exactly how the number formats should look for various data types. I'm coming over from sheetjs (mainly because styling is so easy with this library), and the data types there rely on the ECMA-376 format. It appears that same standard works here for determining commas, decimal places, date formats, etc. but I see nothing formally written about it. Am I correct that we can use that standard for setting the number formats? 

Info on the standard:

https://support.office.com/en-us/article/Create-or-delete-a-custom-number-format-78f2a361-936b-4c03-8772-09fab54be7f4

https://github.com/SheetJS/ssf

**Comment by msillz** [comment]
Thank you for your post! To add onto the post above, this website explains it well in my opinion:

http://polymathprogrammer.com/2011/02/15/built-in-styles-for-excel-open-xml/
