### ISSUE TITLE
workbook.eachSheet is not a function

### ISSUE THREAD

**Issue by Abouyer20** [exceljs/exceljs#473]
I Have the following part of code;
`function addLegalRow(){
  console.log("worksheet test");
  workbook.eachSheet(function(worksheet, sheetId) {
    console.log("sheet id", sheetId)
  });
}`
But when I try and run to get the file I get the following error;
TypeError: workbook.eachSheet is not a function.

I have version v0.8.1 .

Is anyone getting this problem? is thier a way round it

Thanks

**Comment by Lehani** [comment]
I have the same issue. As I understand, it this happens when you use 'new Excel.stream.xlsx.WorkbookWriter' instead of 'new Excel.Workbook'. But I have to use the stream.
