### ISSUE TITLE
Issue with AzureApp insights

### ISSUE THREAD

**Issue by RenePingen** [exceljs/exceljs#483]
When the Microsoft azure app insights extension is enabled, the excel workbook writer starts failing. Root cause seems to be related to the Promishlib. For example:
The function:
```
addThemes: function addThemes() {
    var self = this;
    return new PromishLib.Promish(function (resolve) {
      self.zip.append(theme1Xml, { name: 'xl/theme/theme1.xml' });
      resolve();
    });
  },
```
Normally returns an object of type [Object Promise];  When app insights is enabled it returns [Object object] and therefore fails.

There seems to be some sort of conflict but im not sure what the exact conflict is.

**Comment by spacem** [comment]
We used appInsights.setup().setAutoDependencyCorrelation(**false**) and the problem went away.

I am not sure what that does exactly but other people seem to have similar problem eg:
https://github.com/Microsoft/ApplicationInsights-node.js/issues/409

**Comment by markwolff** [comment]
This was probably caused by app insight's usage of zone.js, which patches Promise. It has since then been updated to not use zone.js anymore in the latest version `1.1.0`.
