### ISSUE TITLE
writeFile works on localhost but not on my remote VPS

### ISSUE THREAD

**Issue by razaviv** [exceljs/exceljs#492]
```
workbook.xlsx.writeFile("src/excelUploads/mySheet.xlsx")
    .then(function() {
      console.log("Success");
    }).catch(function(err) {
      console.log("Errored");
    });
```

The above code works on localhost but not on my VPS.
On my VPS either the .then and the .catch functions not responding BUT the file is actually created BUT the file is corrupt and cannot be opened by the excel program itself.

Someone familier with this?

Thanks.

**Comment by Siemienik** [comment]
I'm not sure but this issue may be similar to:
#732
#745
#35
#106
#739

**Comment by Serj-M** [comment]
I solved the problem. Hope this helps you.
If you download this excel file from the server side (In my case Node JS). 
The problem is solved by one line on the client side:  **req.responseType = "arraybuffer";**

```
requestData(req, "exportToExcel")
            .then(resXHR => {
                // For the correct processing of data from the server, you must specify the format/structure of data transfer
                resXHR.responseType = "arraybuffer"
                // Wait until the data is downloaded from the server
                resXHR.onload = function () {
                    // Call a modal window for saving with type and file name 
                    saveAs(new Blob([resXHR.response], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), 'users.xlsx')
                }
            })
```
