### ISSUE TITLE
Specify range of cells for eachCell

### ISSUE THREAD

**Issue by richlewis14** [exceljs/exceljs#493]
Hi All,

Firstly apologies if this is not in the correct place but i had a question around the use of the `eachCell` function. Is it possible to specify a range of cells anywhere? So in my scenario i would like to update cells `E6:E25` using the values from an array

Any help appreciated 

Thank You

**Comment by Siemienik** [comment]
The simplest solution will be best,
```javascript
for(var i =6;i<26;i++){
    ws.getCell(`E${i}`)
}
```
