### ISSUE TITLE
Unable to read excel file using xlsx.readFile method

### ISSUE THREAD

**Issue by ashankasr** [exceljs/exceljs#499]
I created a electron application with AngularJS. I'm currently working on functionality where I'm tryng to manipulate an excel file. But using exceljs I'm I cannot read the file. What am I doing wrong?

```
import { Component, OnInit } from '@angular/core';
import * as Excel from "exceljs/dist/exceljs.min.js";
import * as stream from 'stream';
import { forEach } from '@angular/router/src/utils/collection';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  constructor() { 
    var remote = require('electron').remote;// Load remote compnent that contains the dialog dependency    
    var fs = require('fs') // Load the File System to execute our common tasks (CRUD)     
    const dialog = require('electron').remote.dialog;

    dialog.showOpenDialog({ properties: ['openFile', 'multiSelections'] }, fileNames => {

      console.log(fileNames)
      var inputFilePath = fileNames[0]
      var workbook = new Excel.Workbook()

      console.log('Run')

      workbook.xlsx.readFile(inputFilePath)
        .then(function (zz) {
          console.log('Success')
        });

        console.log('End trigger')
    });
  }

  ngOnInit() {
    // Parse a file
  }
}

```

**Comment by timratha** [comment]
I am facing the same problem.... When I use this statement :  
workbook.xlsx.readFile(filename.xlsx)
        .then(function (zz) {
          console.log('Success')
        });

Then i get this error: TypeError: d.exists is not a function
Is there anyone solve this problem?

**Comment by josocial** [comment]
@ashankasr, @timratha Did you manage to get this resolved ? I am facing the same issue and from another thread seems like the .readFile is a server side function and could not be used on UI. 
https://github.com/guyonroche/exceljs/issues/336
