### ISSUE TITLE
Why showGridLines don`t work in my code?

### ISSUE THREAD

**Issue by acsel1985** [exceljs/exceljs#502]
Hello! Why 'showGridLines' and 'horizontalCentered' don`t work in my code when i try print excel file? 

`let ws = wb.addWorksheet('sheetName', {
            pageSetup:{
                paperSize: 9,
                orientation: 'landscape',
                fitToPage: true,
                fitToWidth: 1,
                fitToHeight: 0,
                showGridLines: true,
                horizontalCentered: true         
            }
        });`

**Comment by Siemienik** [comment]
it should work properly:
https://github.com/exceljs/exceljs#page-setup
