### ISSUE TITLE
Possible Defect - Column Insert Affects Initial Row Only

### ISSUE THREAD

**Issue by rpattcorner** [exceljs/exceljs#504]
There may be a problem with the column insert function -- or I may be misunderstanding it.

We have a set of documents we're inserting into rows.  The documents vary in shape, so eventually we'll encounter a document with a new field, and need to insert a column in our worksheet (a sparse matrix).  Prior and subsequent rows should have no value for that column.

According to the documentation this should be no problem ... it says:

```// Also: If the worksheet has more rows than values in the colulmn inserts,
//  the rows will still be shifted as if the values existed
```

Exactly the desired behaviour ... if we insert at column 2 the former column 2 gets shifted to the right.

But ... what we find is that the columns (and values if supplied) are inserted only up to (but not including) the row where the insert is invoked.  The new column does not apply to subsequently added rows.  

So if we have this:
```
               header1  header2 header3
rowA         val1       val2        val3
rowB         val4       val5        val6
rowC         val7       val8        val9
```
and we splice when finding a new value in processing data for rowB:

```
    worksheet.spliceColumns(2, 0, ["headerx"]);
```
We get the following once all 3 rows are processed:
```
               header1  headerx header2 header3
rowA         val1               val2        val3
rowB         val4      val5     val6
rowC         val7      val8     val9
```

As you see, row B and the subsequent rows make no note of the new column.  It looks like the function alters the existing static structure of rowdata without altering the actual column structure of the underlying sheet.

Is this functionality broken, or am I applying it incorrectly?  I suppose we could keep track of each insert as it occurs and apply it to all subsequent rows as processed with a reinvocation of the spliceColumns, but that just doesn't seem right.

**Comment by Siemienik** [comment]
lack of activity
