### ISSUE TITLE
how to use exceljsin angular 5?

### ISSUE THREAD

**Issue by SudeendraG** [exceljs/exceljs#511]
tried following ways, but not working,  any idea how to use this in angular 5?

1.import * as Excel from 'exceljs/dist/exceljs.min.js';
 const workbook =  new Excel.workbook();

2.import * as Excel from 'exceljs/dist/exceljs.min.js';
import * as ExcelProper from 'exceljs';

 const workbook: ExcelProper.Workbook = new Excel.Workbook();

**Comment by jloveridge** [comment]
I have submitted a pull request that allows us to use `exceljs` in our Angular application. In our case we had to also add the following to the `compilerOptions` section of our `tsconfig.json`:

```
"paths": {
    "*": ["*", "../bower_components/*/index"]
},
```

If you are not using bower you will need to adapt the above to your environment. Once we did the above we can now do the following in our Angular code:

```
import * as Excel from 'exceljs';
const workbook = new Excel.Workbook();
```

Until the PR is merged you can install a fork of the repository with our changes from `@gradecam/exceljs`.

Cheers!

**Comment by jloveridge** [comment]
The PR has now been merged.

**Comment by smoke** [comment]
@jloveridge can you point the PR you are referring to? I am having difficulties using `exceljs` with typescript (angular) also.

**Comment by jmac-slash0** [comment]
**Angular 5 with types & exceljs 1.4.6:**

tsconfig.json in paths property (your path to node_modules may vary depending on the baseUrl property):
```
...
"exceljs": [
    "../node_modules/exceljs/dist/es5/exceljs.browser"
]
...
```
Usage:
```
// Add or remove types from here as needed
import { Borders, FillPattern, Font, Workbook, Worksheet } from 'exceljs';

let workbook: Workbook = new Workbook();
```

**Comment by jgoris** [comment]
I updated my Angular 5 setup to attempt to follow your example.  VS Code and the compilation was all happy, but when I deployed (we use webpack to build/package and 'ng serve' to deploy), I got these browser console errors when I attempted to access my app's starting page in the browser:

Uncaught TypeError: Cannot read property 'prototype' of undefined
    at patch (graceful-fs.js:166)
    at Object.eval (graceful-fs.js:27)
    at eval (graceful-fs.js:262)
    at Object.../../../../graceful-fs/graceful-fs.js (vendor.bundle.js:4618)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.eval (index.js:8)
    at eval (index.js:156)
    at Object.../../../../archiver-utils/index.js (vendor.bundle.js:2308)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.eval (core.js:14)

**Comment by jmac-slash0** [comment]
Those errors mean you're not using the browser version of exceljs in your deployed version. I don't use webpack in my workflow, but I suspect somewhere in your webpack configuration you need to make a change similar to the one in tsconfig.json. Basically, tell webpack when it sees 'exeljs' to grab the browser file.

**Comment by jgoris** [comment]
Reading is Fundamental.  I realized that you said to add it to the "paths" property, which I was not doing.  I have now added that into my tsconfig file and it is working!!  THANKS!!

    "paths": {
        "exceljs": [
        "../node_modules/exceljs/dist/es5/exceljs.browser"
        ]
    }

**Comment by shridhar-tl** [comment]
Hi @jmac-slash0 , @jgoris ,

I am using Angular 6 and added paths property in tsconfig.json and used the import similar way mentioned above. But I am getting the following compilation errors. Any idea what I was missing?

/*********   Error starts ****************************/
WARNING in ./node_modules/exceljs/node_modules/sax/lib/sax.js
Module not found: Error: Can't resolve 'stream' in 'E:\Projects\test-app\node_modules\exceljs\node_modules\sax\lib'

ERROR in ./node_modules/exceljs/dist/es5/csv/csv.js
Module not found: Error: Can't resolve 'fs' in 'E:\Projects\test-app\node_modules\exceljs\dist\es5\csv'
ERROR in ./node_modules/exceljs/dist/es5/utils/utils.js
Module not found: Error: Can't resolve 'fs' in 'E:\Projects\test-app\node_modules\exceljs\dist\es5\utils'
ERROR in ./node_modules/exceljs/dist/es5/xlsx/xlsx.js
Module not found: Error: Can't resolve 'fs' in 'E:\Projects\test-app\node_modules\exceljs\dist\es5\xlsx'
ERROR in ./node_modules/fast-csv/lib/index.js
Module not found: Error: Can't resolve 'fs' in 'E:\Projects\test-app\node_modules\fast-csv\lib'
ERROR in ./node_modules/fast-csv/lib/formatter/index.js
Module not found: Error: Can't resolve 'fs' in 'E:\Projects\test-app\node_modules\fast-csv\lib\formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter_stream.js
Module not found: Error: Can't resolve 'fs' in 'E:\Projects\test-app\node_modules\fast-csv\lib\formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter.js
Module not found: Error: Can't resolve 'fs' in 'E:\Projects\test-app\node_modules\fast-csv\lib\formatter'
ERROR in ./node_modules/fast-csv/lib/parser/parser_stream.js
Module not found: Error: Can't resolve 'fs' in 'E:\Projects\test-app\node_modules\fast-csv\lib\parser'
ERROR in ./node_modules/fast-csv/lib/parser/index.js
Module not found: Error: Can't resolve 'fs' in 'E:\Projects\test-app\node_modules\fast-csv\lib\parser'
ERROR in ./node_modules/fast-csv/lib/extended.js
Module not found: Error: Can't resolve 'os' in 'E:\Projects\test-app\node_modules\fast-csv\lib'
ERROR in ./node_modules/exceljs/dist/es5/utils/stream-buf.js
Module not found: Error: Can't resolve 'stream' in 'E:\Projects\test-app\node_modules\exceljs\dist\es5\utils'
ERROR in ./node_modules/exceljs/node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream' in 'E:\Projects\test-app\node_modules\exceljs\node_modules\jszip\lib'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter.js
Module not found: Error: Can't resolve 'stream' in 'E:\Projects\test-app\node_modules\fast-csv\lib\formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/formatter_stream.js
Module not found: Error: Can't resolve 'stream' in 'E:\Projects\test-app\node_modules\fast-csv\lib\formatter'
ERROR in ./node_modules/fast-csv/lib/formatter/index.js
Module not found: Error: Can't resolve 'stream' in 'E:\Projects\test-app\node_modules\fast-csv\lib\formatter'
ERROR in ./node_modules/fast-csv/lib/parser/index.js
Module not found: Error: Can't resolve 'stream' in 'E:\Projects\test-app\node_modules\fast-csv\lib\parser'
ERROR in ./node_modules/fast-csv/lib/parser/parser_stream.js
Module not found: Error: Can't resolve 'stream' in 'E:\Projects\test-app\node_modules\fast-csv\lib\parser'

/***************** Error Ends ***************************/

**Comment by funkizer** [comment]
Same error as @shridhar-tl, added exceljs.browser to tsconfig paths, it's still trying to import fs, os, stream, ...
My tsconfig.json, which is in the same app root folder as node_modules:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {
      "exceljs": [
        "./node_modules/exceljs/dist/es5/exceljs.browser"
      ]
    }
  }
}
```

Component:
```
import { Workbook, Worksheet } from 'exceljs';
// ...
const workbook = new Workbook();
```

**Comment by funkizer** [comment]
Back to the workaround until there's a proper way to get it working with Angular 6 (credits: https://github.com/guyonroche/exceljs/issues/348#issuecomment-320690232 ). Remove the path from `tsconfig` and import exceljs like this:

```
import * as Excel from "exceljs/dist/exceljs.min.js";
import * as ExcelProper from "exceljs";
let workbook: ExcelProper.Workbook = new Excel.Workbook();
```

**Comment by jmac-slash0** [comment]
For Angular 6, I swapped _exceljs.browser_ for _exceljs.min_ and it seems to be working. I'm not sure why the browser file doesn't work.

```
"compilerOptions": {
    "paths": {
        "exceljs": [
            "../node_modules/exceljs/dist/exceljs.min"
        ]
    }
}
```

**Comment by JohannesHoppe** [comment]
https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814 explains why it's not any longer possible to import some node-modules with Angular-CLI 6.

**Comment by Siemienik** [comment]
#348
