### ISSUE TITLE
How to add Cell comment 

### ISSUE THREAD

**Issue by runslow917** [exceljs/exceljs#529]
I have requirement where i need to show comment on hover the cell in excel .i've read the document, it is said that In Page Setup ->cellComments setting is there. But I am not understanding how to use that for adding cell comment.
i am adding row information like this
`worksheet.addRow([3, 'Sam', new Date()]);`
now i want to add a comment for the cell Sam like when a user hovers on that cell , it should show "Sam Winchester " in a small note comment
If you could explain with code that would be very much appreciated
![commentissue](https://user-images.githubusercontent.com/26476288/38127075-1cc01dd0-3412-11e8-9aaf-272ba9d09018.PNG)

**Comment by hewford** [comment]
someone please answer this

**Comment by Siemienik** [comment]
similar issues:
https://github.com/guyonroche/exceljs/issues/451
https://github.com/guyonroche/exceljs/issues/707
https://github.com/guyonroche/exceljs/issues/202
https://github.com/guyonroche/exceljs/issues/503

**Comment by guyonroche** [comment]
Comments (aka Notes) added to v1.12.0

**Comment by kfmasthan-syed** [comment]
ws.getCell(cellRef).note = 'Note';

**Comment by Pintiboy** [comment]
Even 6 years later this is still not really working... 

Even a simple
ws.getCell("A1").note = "Hello world" breaks the whole file.
