### ISSUE TITLE
Slow and high memory readFile for some xlsx

### ISSUE THREAD

**Issue by salterok** [exceljs/exceljs#535]
I'm using this lib to read xls files to gather some useful information from them.
At some time i have noticed that process sometimes crash. While investigating this issue i have found that some files (with noticeable amount of rows are very slow or failed to parse by `workbook.xlsx.readFile(file)`).

A'm using version 0.6.2 before and now upgrade to 1.1.1 and this issue reproducible on both.

Attaching example file that while parsing crash node process with out of memory.
[1523272420-Member_Register_Data_Sheet_(V2).xlsx](https://github.com/guyonroche/exceljs/files/1889724/1523272420-Member_Register_Data_Sheet_.V2.xlsx)

**Comment by salterok** [comment]
Seems that handling of "Defined Names" caused this issue.

Setter of `definedNames` model iterates over all `definedNames` ranges and as i can see initialize all named cells to their default values.

So in previously attached file there are several `definedNames` with a big range (e.g. $T$**14**:$T$**1048576**) so parser try to set default values for all cells in that range and spend a lot of time there and even more use a lot of memory (over 1.5 GB), which cause out of memory.

**Comment by holm** [comment]
We have run into this alos. I wonder if we really need to initialize the cells for a given "Defined Names", or they can just be left uninitialized.

**Comment by salterok** [comment]
@holm Don't know exactly, but we have patched this part of code and it works fine (note, that we do not use "defined names" feature and also only read files).

Here is the code that patch exceljs of version 1.1.2 to not initialize `Defined Names` if anyone interested.
```javascript
import * as DefinedNames from "exceljs/dist/es5/doc/defined-names";

(function patchDefinedNames() {
    const desc = Object.getOwnPropertyDescriptor(DefinedNames.prototype, "model");
    Object.defineProperty(DefinedNames.prototype, "model", {
        get: desc.get,
        set: noop
    });
    
})();

function noop() {}
```
