### ISSUE TITLE
How to write Date into an excel file in a specific format

### ISSUE THREAD

**Issue by pmaiya** [exceljs/exceljs#538]
I am trying to build an excel sheet which has date in a specific column. I am doing something like this:
`sheet.getCell('A6').value(new Date());`

when I generate the excel sheet, this gives me
`4/9/2018 `

I would like it to display this instead:
`4/9/2018  12:26:00 PM`

**Comment by zgriesinger** [comment]
As far as I know, this library only supports date format when reading in files.

There is a way you can write the format you want to a cell using a library like [moment](https://momentjs.com/). However this will not make the field a "Date" type in Excel, but it may be a quick fix.
` sheet.getCell("A1").value = moment().format("MM/DD/YYYY h:mm:ss a");`

**Comment by guyonroche** [comment]
@pmaiya - if you want to control how the date appears when loaded in Excel, then you need to use cell formatting:
```
sheet.getCell('A6').value = new Date();
sheet.getCell('A6').numFmt = 'm/d/yyyy\\ h:mm:ss\\ AM/PM'; // I think this is right ;-)
```

**Comment by nabeelz6** [comment]
@guyonroche - Should defining the numFmt like you did also work for column styles? I'm doing the following but still seems to show original date format (e.g. 8/1/18) instead of expected (e.g. 01/08/2018 for format below)
```
worksheet.columns = [
    { header: 'Id', key: 'id', width: 10 },
    { header: 'Name', key: 'name', width: 32 },
    { header: 'D.O.B.', key: 'DOB', width: 10, style: { numFmt: 'dd/mm/yyyy' } }
];

// Via streaming
worksheet.addRow({
   id: '1',
   name: 'my name',
   DOB: new Date()
}).commit();
```

**Comment by rnukala** [comment]
Hi,

I want to display milliseconds as well,  for which I have tried the format 'DD/MM/YYYY HH:mm:ss:SSS' and this does not work. What will be the correct format for milliseconds. Thanks in advance.

**Comment by mayurdhumal01** [comment]
just convert your date to string using .toString() method & your problem will solve

**like this**: if you are using moment to format date
 moment(cell.value).format("DD MMM YYYY hh:mm A")**.toString();**

**Comment by teunovic** [comment]
> just convert your date to string using **.toString()** method & your problem will solve
> 
> **like this**: if you are using moment to format date
> cell.value = moment(cell.value).format("DD MMM YYYY hh:mm A")**.toString();**
> 
> **& check this also**
> sheet.getCell('A6').value(**new Date().toString()**);

moment().format() returns a string, so moment().format().toString() is redundant.

**Comment by zdila** [comment]
`numFmt` doesn't work in streaming mode:

```js
worksheet.columns = [{ key: 'datetime', header: 'Date and Time', style: { numFmt: 'm/d/yyyy\\ h:mm:ss\\ AM/PM' } }];
const row = worksheet.addRow({ datetime: new Date() });
row.getCell(1).numFmt = 'm/d/yyyy\\ h:mm:ss\\ AM/PM';
row.commit();
```

**Comment by fmenis** [comment]
I also notice that numFmt doesn't work in streaming mode.
Can you please fix that?

**Comment by Siemienik** [comment]
please create new issue
