### ISSUE TITLE
请问是否支持导出2003版本的excel文件？

### ISSUE THREAD

**Issue by maimengdekedaya** [exceljs/exceljs#543]
如何设置才能让导出的excel文件是2003版本？谢谢

**Comment by mah110020** [comment]
我不认为Excel 2003是受支持的。只有2007年得到支持。如果你不能在2003年使用它，尝试找到一个转换工具。

**Comment by taoqf** [comment]
ha, nice translation. @mah110020

**Comment by maimengdekedaya** [comment]
有推荐的转换插件吗
