### ISSUE TITLE
showGridLines not working

### ISSUE THREAD

**Issue by unpollito** [exceljs/exceljs#546]
Apparently, the property showGridLines isn't working properly when added to a worksheet. This can be reproduced by running the following code on a browser after running `npm install file-saver exceljs`:

    <script type="text/javascript" src="node_modules/file-saver/FileSaver.js"></script>
    <script type="text/javascript" src="node_modules/exceljs/dist/exceljs.js"></script>
    <script type="text/javascript">
        window.addEventListener("load", function() {
            var wb = new ExcelJS.Workbook();
            var ws = wb.addWorksheet("Test", {properties: {showGridLines: false}});
            ws.getCell("A1").value = "Hello World!";
            wb.xlsx.writeBuffer().then(function(buffer) {
                saveAs(new Blob([buffer], {type: "application/octet-stream"}), "report.xlsx");
            });
        });
    </script>

While a workaround is mentioned in #408, the current behavior of the library is not consistent with the documentation, nor with user expectations. So while the workaround is enough for me, I am afraid that other people could stumble upon the same issue and lose time. Would it be possible to correct this behavior so that showGridLines works as intended?

**Comment by joyacv2** [comment]
Hi,

That is correct, #408 works perfect! The documentation needs to be updated! Also happens to me!
