### ISSUE TITLE
Streaming excel writer with very large file sizes, doesn't add hyperlinks

### ISSUE THREAD

**Issue by awitherspoon** [exceljs/exceljs#553]
So I employed the streaming I/O to save memory when writing 30mb+ excel files.  It always consists of multiple worksheets, but when I get the resulting workbook, worksheets that are excessively large do not have the appropriate hyperlink behind it.  The smaller worksheet does.

Here's the basic code being worked with:

```javascript
    const dataFilter = []
    const headers = []
    excelHeaders[filterType].forEach((header) => {
      dataFilter.push(this.headerList[header].key)
      headers.push(this.headerList[header])
    })
    const { hyperlink, currency, width } = excelHeaders[headerType]
    hyperlink.forEach((col) => {
      headers[col].style = excelHeaders.ColStyles.hyperlink
    })
    currency.forEach((col) => {
      headers[col].style = excelHeaders.ColStyles.currency
    })
    width.forEach((col) => {
      headers[col].width = 8
    })
    const ws = this.workbook.addWorksheet(title)
    ws.columns = headers
    ws.getRow(1).font = { underline: false, bold: true }
    ws.getRow(1).commit()
    this.data.forEach((obj) => {
      const filterHash = {
        CAT: true,
        Property: !obj.VIN && filterType === 'Property',
        Auto: !!obj.VIN && filterType === 'Auto',
      }
      if (filterHash[filterType]) {
        const row = {}
        Object.keys(obj).forEach((key) => {
          if (dataFilter.includes(key)) {
            row[key] = obj[key]
          }
        })
        ws.addRow(row).commit()
      }
    })
    ws.commit()
    return this
```

Ultimately, I assign specific styles (such as hyperlink) to specific columns.  The actual { text: x, hyperlink: y } is done at the point where the array of objects(rows) is being created.  Any thoughts on how I might get hyperlinks to work in, for example, a worksheet with 155,516 rows?

Edit: I should add that I am also getting an error on loading this spreadsheet in Excel, and it requires repair before it displays.  That could also be the reason the hyperlinks are broken, though for any spreadsheet created that isn't ridiculously oversized, it works just fine.

**Comment by t1hk** [comment]
There are general Excel limits of 66.530 hyperlinks per excel sheet. 
[Overview of Excel Limits](https://support.office.com/de-de/article/spezifikationen-und-beschr%C3%A4nkungen-in-excel-1672b34d-7043-467e-8e27-269d656771c3)
