### ISSUE TITLE
TypeError: worksheet.addRows is not a function

### ISSUE THREAD

**Issue by ningmengs** [exceljs/exceljs#569]
this is my code:
exceljs 1.4.6:
`var rows = [
    [5,'Bob',new Date()], // row by array
    {id:6, name: 'Barbara', dob: new Date()}
];
worksheet.addRows(rows);
`
error:TypeError: worksheet.addRows is not a function
do you deal it? help,help

**Comment by hankolsen** [comment]
@ningmengs I just installed 1.4.8 and it works as expected.
What does your worksheet object look like? How did you create worksheet?

**Comment by gauravcleartax** [comment]
Facing this issue in 3.4.0 version. Any solution?

**Comment by Siemienik** [comment]
https://github.com/exceljs/exceljs/blob/master/lib/doc/worksheet.js#L341

`addRows` function exists, maybe is `worksheet` null?

**Comment by joeldmyers** [comment]
Hey, so I ran into this and I think the confusing thing for me was that you have to: 

- Authenticate
then run `await doc.loadInfo();`

THEN (this is the part I missed initially), you have to specify the sheet within the worksheet. 
`const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id]` 

Then from there you can do `sheet.addrow({...});`

**Comment by amitbd1508** [comment]
update  google-spreadsheet to 3.0.8 or latest version 

This resolved my issue
