### ISSUE TITLE
TypeError: Cannot create property 'editAs' on string 'A1:E5'

### ISSUE THREAD

**Issue by HardikGlib** [exceljs/exceljs#570]
My Code is :
`let sheet2 = "/home/genesis/merge/CP-7 CHW ANALYSIS.xlsx";
let workbook = new Excel.Workbook();
workbook.xlsx.readFile(sheet2).then(function(data) {
    console.log(data);
}).catch(function(err) {
    console.log(err);
})`

My Excel file have 5 sheet, each have image on cell A1:E5 place with anchor tag.
Error is:
![selection_019](https://user-images.githubusercontent.com/33016366/40048967-23631c1a-5851-11e8-9a95-e5bd35497ae8.png)

if I remove the image from First Sheet, it will automatically read whole file.
How Do I read file without removing image?

**Comment by getsomecoke** [comment]
@HardikGlib can you please attach a sample file?

**Comment by HardikGlib** [comment]
No I can't attach sample file. @getsomecoke
