### ISSUE TITLE
Not display string value

### ISSUE THREAD

**Issue by alhassane85** [exceljs/exceljs#580]
Code
 try {
        var workbook = new Excel.Workbook();
        var worksheet = workbook.addWorksheet('My Sheet');

        worksheet.columns = [
          { header: 'Id', key: 'id', width: 10 },
          { header: 'Name', key: 'nom', width: 32 },
          { header: 'D.O.B.', key: 'dob', width: 10 }

        ];
        worksheet.addRow({id: 1, nom:  'jean', dob: new Date(1970,1,1)});
        worksheet.addRow({id: 2, nom:  'paul', dob: new Date(1965,1,7)});

        workbook.xlsx.writeFile('PP.xlsx').then(function() {
          console.log('file is written');
        });
      } catch(err) {
        console.log('OOOOOOO this is the error: ' + err);
      }

Output:

 
   |   | 
1 |   | 01/02/1970
2 |   | 07/02/1965

**Comment by getsomecoke** [comment]
Tried to reproduce, but seems to work for me

![output](https://user-images.githubusercontent.com/22377238/42142047-d5365454-7dca-11e8-9a40-35f23804ae7e.png)

Node version: 8.4.0
exceljs version: 1.5.1
