### ISSUE TITLE
Writing 'Grouped and Hidden' format

### ISSUE THREAD

**Issue by bhickey77** [exceljs/exceljs#585]
I am attempting to group and hide rows as opposed to just hiding rows. 

To be specific I would like to write a file that has cells grouped and hidden so that there is a plus button on the sidebar allowing you to hide the group of cells or expand the group of cells. I understand we have the ability to set the hidden property of a row to 'true'. Does anyone know if there is a way to do that with grouping and hiding? If not I would love to work on adding this functionality to the code base myself.

**Comment by sasapet** [comment]
Any luck with this? I also need this functionality!
