### ISSUE TITLE
Create hyperlinks whose visible values are stored as Numbers in Excel?

### ISSUE THREAD

**Issue by jgoris** [exceljs/exceljs#586]
Is there a way to create a hyperlink cell where the visible part is stored as a number in Excel?  I have created a spreadsheet that users want to run formulas and calculations on the visible values, but Excel treats them as "Numbers stored as Strings" in Excel.  Each cell gets a little red error or Warning <!> icon next to it when viewing it in Excel.  In order to access these values as numbers, users must manually convert them to Numbers.

For example, I have a "totals" hyperlink cell with a numeric value of 1234.56.  Users need the ability to click on the hyperlink cell to open a web page as well as use this value in a calculation.

From what I can see, the method available for creating a hyperlink cell in ExcelJS, is as follows:

value = 1234.56; // a number, but stored as a string in Excel
dataUrl = "www.github.com";
cell.value = { **text:** value, hyperlink: dataUrl};

but the cell value generated in Excel is always a Number formatted as a String.

I guess I'm hoping for "**text**" to use the data type of "value" and carry that forward into the created cell.

**Comment by xkill-9** [comment]
This issue is super old but i'll leave this here in case anyone runs into the same issue, the workaround i used is appending a blank character at the end, so in your example it would be something like:
```javascript
const value = 1234.56; // a number, but stored as a string in Excel
const dataUrl = "www.github.com";
cell.value = { text: ´${value}\t´, hyperlink: dataUrl};
```
The blank character won't show in excel and the warning message will be gone:
