### ISSUE TITLE
i can't copy worksheet with worksheet.model

### ISSUE THREAD

**Issue by honobono414** [exceljs/exceljs#591]
sorry

**Comment by POJOa** [comment]
i just copied worksheets using models assignment , and it seems to me that it's not a good approach.
i encountered merge data loss , too. how did you solve that?

**Comment by POJOa** [comment]
Okay i got it , but it's a stupid approach.but i really dont know how to copy a worksheet using public apis :)
wsGen is the destination while wsSub is the source sheet that need to be copied. 
```

            wsGen.model = wsSub.model
            wsGen.name = j.name

            for(let masterName in wsSub._merges){
                let dimensions =  wsSub._merges[masterName].model
                let master = wsGen.getCell(dimensions.top, dimensions.left);
                for (let i = dimensions.top; i <= dimensions.bottom; i++) {
                    for (let j = dimensions.left; j <= dimensions.right; j++) {
                        // merge all but the master cell
                        if ((i > dimensions.top) || (j > dimensions.left)) {
                            wsGen.getCell(i, j).merge(master);
                        }
                    }
                }
            }
```

**Comment by msedek** [comment]
solved the issue, get a copy of the sheet you want to clone then create a new sheet with a standar name, then copy the model then put the real name:
let sheetToClone = workbook.getWorkSheet("ID TO CLONE")
let copySheet = workbook.addWorkSheet("Sheet")

copySheet.model = sheetToClone.model
copySheet,name = "THE REAL ID/NAME YOU WANT FOR THIS SHEET"

//DO STUFF HERE



return workbook.xlsx.writeFile("your_file")

**Comment by POJOa** [comment]
@msedek I encountered merged region loss using method like this , is it okay for you ?

**Comment by msedek** [comment]
It does not works for New Brooks or at least to were I was able to to test,, so I have a template, read the file and then you can clone the New sheets from there, after you finish, save it with another name either in the same folder or another, but you can not clone from a template to a New book

**Comment by tinhnqjp** [comment]
#292, copy with merge cell

      var ws1 = workbook.getWorksheet('demo');
      let copySheet = workbook.addWorksheet('newdemo');

      copySheet.model = Object.assign(ws1.model, {
        mergeCells: ws1.model.merges
      });
      copySheet.name = 'new demo';

**Comment by aksharj** [comment]
Hi, i am facing a similar issue and copied rows do not have the same merged cells as the source file. I tried with 

```
          myworksheet.model = Object.assign(worksheet.model, {
            mergeCells: worksheet.model.merges
          });
```

Any help will be really great, Thanks.

**Comment by Siemienik** [comment]
1. @aksharj It is lack of `merges` property in a ws model. Please create a new issue for that (or even better PR).

Workaround: use `// @ts-ignore` in line above.

2. `Object.assign()` mutate 1st attribute (`worksheet.model`):

![image](https://user-images.githubusercontent.com/2893099/102348569-62d04400-3fa2-11eb-801c-38d21973271f.png)

```js
const origin = {a:1}

const copied = Object.assign(origin,{b:1}) //incorrect, mutates 1st attribut

console.log("copied",copied);
console.log("origin",origin); // origin changed

const copied2 = Object.assign({},origin,{ddd:1})

console.log("copied2",copied2);
console.log("origin",origin); // origin not changed - that's correct

const bySpread = {...origin, eee:1} //best option

console.log("bySpread",bySpread);
console.log("origin",origin); 
```

**Comment by aksharj** [comment]
@Siemienik, many thanks for your reply and many thanks for elaborating the correct way to use `Object.assign`. 

Sorry i did not fully understand by when you meant `use // @ts-ignore` in line above.

will my resulting code become like 

```
        const workbook = new ExcelJS.stream.xlsx.WorkbookWriter(writerOptions)
        const workbookReader = new ExcelJS.stream.xlsx.WorkbookReader(sheet.path, readerOptions);
        const myworksheet = workbook.addWorksheet('Sheet 1');
        workbookReader.read();
        workbookReader.on('worksheet', worksheet => {
         myworksheet.model = Object.assign(worksheet.model, {
            // @ts-ignore
            mergeCells: worksheet.model.merges
          });
          myworksheet.name = 'new demo';

          worksheet.on('row', row => {
            const r = myworksheet.addRow();
            Object.assign(r, row);
          });
        });
```

**Comment by AufarZakiev** [comment]
If someone needs to copy worksheet to another workbook, @msedek 's answer also works. 
In addition, if you need also pictures to be copied add following code to @msedek 's answer: 
```
originalSheet.getImages().forEach((image) => {
          //@ts-ignore
          const copiedImageId= copyWorkbook.addImage(temp.getImage(image.imageId));

          copyWorksheet.addImage(copiedImageId, image.range);
});
```

**Comment by fhero2030** [comment]
If someone is having trouble with sheet name duplication i solved it using this.

`
const sheetToClone = templateWorksheet.getWorksheet("Sheet_Template");
const copySheet = workbook.addWorksheet("Sheet");
copySheet.model = {
        ...sheetToClone!.model,
        name: "SHEET ",
      };
`
