### ISSUE TITLE
Cannot read property 'eachRow' of undefined

### ISSUE THREAD

**Issue by hazemsamoaa** [exceljs/exceljs#594]
Hi, 
I apply exactly the same APIs within the following code

var Excel = require('exceljs'); var inboundWorkbook = new Excel.Workbook(); inboundWorkbook.xlsx.readFile("Data/DataSet.xls").then(function() { var inboundWorksheet = inboundWorkbook.getWorksheet(1); //or name of the worksheet inboundWorksheet.eachRow({ includeEmpty: true }, function(row, rowNumber) { console.log("Row " + rowNumber + " = " + JSON.stringify(row.values)); }); });

but I got the error TypeError: Cannot read property 'eachRow'
I work in version exceljs@1.5.0, so I update eachrow function exactly like the documentation but still doesn't work

**Comment by bam-tbf** [comment]
+1 I am getting this error from time to time as well.

Could it be the result of trying to get a worksheet that has been deleted? If so, how can I be sure to access the first worksheet that has data in it?

**Comment by mkock** [comment]
This just happened to me in a production environment. I have this loop, which has worked until now:

```
  // Find first available worksheet.
  let sheetId: number = 0
  let worksheet: Excel.Worksheet | undefined
  do {
    sheetId++
    worksheet = workbook.getWorksheet(sheetId)
  } while (!worksheet)
```

For this particular file which contains exactly one worksheet named simply "Sheet1", it never finds the sheet, ie. `worksheet` always equals `undefined`, and the loop runs forever. Any solutions?

**Comment by mkock** [comment]
Update: as noted in this issue: https://github.com/exceljs/exceljs/issues/652, this happens when the workbook is stored in an older format, in this case, it's "Excel 97-2004 Workbook" format. I'm simply not able to fetch a sheet from those :-(

**Comment by Siemienik** [comment]
@hazemsamoaa @bam-tbf  @mkock 
It isn't required to worksheet has next id, so first one could have id=10, second one id=3 and the other id=1213.
To iterate through worksheets I recommend use array `worksheets`:
```
next = wb.worksheets[i++];
```

**Comment by VinodChugwani** [comment]
I got the error TypeError: Cannot read property 'eachRow'.

Please let me know the solution what should be there
