### ISSUE TITLE
Multiple worksheet not work with streaming 

### ISSUE THREAD

**Issue by shivshankar3578** [exceljs/exceljs#597]
Hi,
I'm trying to make a xls file have three worksheets as below

```
let wb = new Excel.stream.xlsx.WorkbookWriter({ filename: `./stats-${new Date().toLocaleString()}.xls` });
let dataWS = wb.addWorksheet("Raw Data");
let statsWS = wb.addWorksheet("stats report 1");
let deviceStatsWs = wb.addWorksheet("stats report 2");
dataWS.addRow(row).commit();
deviceStatsWs.addRow(item).commit();
statsWS.addRow(item).commit();
 wb.commit()
      .then(() => {
        app.log.info(`done`);
        process.exit(0);
      })
      .catch((err) => {
        app.log.error(err);
     })
```

but only first worksheet written. 
Is it possible by exceljs or not a feature

**Comment by BugsBunnyBR** [comment]
did you solve this? I have the same problem.

**Comment by shivshankar3578** [comment]
No i  didn't  work  further

**Comment by Wafel** [comment]
@shivshankar3578 

Could you provide more code? There is difference that you pass some variable called `row` and then you pass variable called `item`. `item` could be invalid.

**Comment by m90** [comment]
I'm running into the same issue. I can write multiple worksheets just fine and commit them when done, but when saved, the workbook will contain only a single sheet.

**Comment by m90** [comment]
The code to reproduce this can be as simple as

```
const workbookWriter = new Excel.stream.xlsx.WorkbookWriter({
  filename
})
const one = workbookWriter.addWorksheet('one')
one.addRow(['one', 'two']).commit()
one.commit()
const two = workbookWriter.addWorksheet('two')
two.addRow(['two', 'three'])
two.commit()
workbookWriter.commit()
  .catch((err) => console.error(err))
```

The written Excel file will only contain a single worksheet called "one".

**Comment by zonetti** [comment]
Same here. Any solution/workaround?

**Comment by zonetti** [comment]
@m90 Workaround for now: downgrade it to 1.4.10

**Comment by m90** [comment]
@zonetti So for me the situation is actually a little different:

- in the meantime I found out that ExcelJS will actually write multiple worksheets, yet LibreOffice does not display these. When opened in Excel or Google Docs, they will appear
- downgrading to 1.4.10 did not change anything in that regard

**Comment by m90** [comment]
@zonetti Really strange, I am on LibreOffice `6.0.6.2`. I'll let you know if I find out anything more.

Do you have any idea what the offending change is that made the library break after `1.4.10`

**Comment by zonetti** [comment]
@m90 Unfortunately, I don't. I got the idea of downgrading after using [another module](https://github.com/vikramthyagarajan/node-excel-stream/blob/master/src/excel-writer.js) for "xlsx write stream" which was using a really old version of `exceljs` and it worked.

**Comment by JefersonC** [comment]
Downgrade to 1.4.10 working for me.
