### ISSUE TITLE
Possible to embed Workbook_Open VBA Macro?

### ISSUE THREAD

**Issue by acefael** [exceljs/exceljs#605]
hi

can exceljs embed a VBA script into the workbook?
I would like to embed the Workbook_Open Method into an Excel file generated by exceljs,
to perform some postprocessing (formatting) on the file when first opened by a user.

cheers

**Comment by acefael** [comment]
This really hurts.  Can someone give a cue?

**Comment by TranBaVinhSon** [comment]
@acefael Did you find a solution?

**Comment by acefael** [comment]
@TranBaVinhSon: no I could not find a solution to my problem here.  I found another way to get what was needed.  The feature I wanted here might not be in scope for exceljs and I'd understand that.  For me it would be ok to close this issue with a "won't fix".
