### ISSUE TITLE
Offset Cell refererence

### ISSUE THREAD

**Issue by pmkroeker** [exceljs/exceljs#607]
Is there a way to select a cell by relative reference? I'm trying to find a cell then select the cell one column over programatically. 
`let cell = worksheet.getCell('B1').offset(1,0)
// cell.address == 'C1'`

Where offset takes a column and then row offset count.

**Comment by nevace** [comment]
If it's the same row, you can do:

```
const row = worksheet.getRow(1); // first row

row.getCell(2) // B1

row.getCell(3) // C1

```

**Comment by pmkroeker** [comment]
Yes I am aware of that. Its more of a convenience method than actually required, I have some something like this 

`const cell = ws.getCell('A1');
const newCell = ws.getCell(cell.row, +cell.col + 1) //B1`

I feel like having an offset from a cell that returns the new cell would be much easier, and more clear syntax wise.
