### ISSUE TITLE
Data validation to the whole column? 

### ISSUE THREAD

**Issue by mallagopi999** [exceljs/exceljs#614]
Trying to create a new excel template. The user will download the template, fill in the data and upload the sheet. In this case, I want to set the data validation to the whole column because the user can fill in n number of columns. Any help in this regard?

**Comment by ahouck** [comment]
I have the same use case

**Comment by abalter** [comment]
Me too!

**Comment by abalter** [comment]
@alubbe @Siemienik

**Comment by pavan612** [comment]
Any update @guyonroche

**Comment by swatantra1** [comment]
even i am facing the same issue

**Comment by swatantra1** [comment]
i have come up with a solution that might help

for( i =2; i< result.length; i++) {
      ws.getCell(`D${i}`).dataValidation = {
        type: 'list',
        allowBlank: true,
        formulae: ['"male, female, other"'],
        errorStyle: 'error',
        errorTitle: 'choose a gender ',
        error: 'must be male, female or other'
      };

    }

**Comment by Siemienik** [comment]
Resolved in: https://github.com/exceljs/exceljs/issues/1109#issuecomment-582592549
