### ISSUE TITLE
Tabs are not showing for multiple sheets

### ISSUE THREAD

**Issue by ashishbrst** [exceljs/exceljs#630]
When we create a workbook with multiple excelsheets, only 1 tab is showing and all other is hidden. There is a text at bottm  showing  number of sheets ie 'Sheet 1 of 20'. I am creating sheets dynamically 

`var workbook = new Excel.Workbook();
workbook.views = [
		 {
		x: 0, y: 0, width: 1000, height: 2000,
		firstSheet: 0, activeTab: 0, visibility: 'visible'
		}
];
							
							var date_created=moment(totalCryptofix.date_created).format('MM.DD.YYYY');
							_.forEach(totalCryptofix.prices,function(data){
								var worksheet = workbook.addWorksheet(_.toLower(data.currency));
								worksheet.state = 'show';
								
								worksheet.columns = [
									{ header: 'Currency', key: 'currency', width: 40,style: { alignment: { horizontal: 'left' }}},
									{ header: 'Price', key: 'price', width: 40,style: { alignment: { horizontal: 'left' }}},
									{ header: 'Date', key: 'date', width: 40,style: { alignment: { horizontal: 'left' }}}
								];
								
								var date=moment(totalCryptofix.date_created).format('YYYY-MM-DD');
								_.forEach(data.prices,function(price){
									worksheet.addRow({currency: price.currency, price: price.price, date: date});
								});
							});`

**Comment by mram888** [comment]
When creating the worksheet you should do it like this:
`var worksheet = workbook.addWorksheet(_.toLower(data.currency), {state: 'visible'});`
