### ISSUE TITLE
Heavily degrading performance in cell merges

### ISSUE THREAD

**Issue by unpollito** [exceljs/exceljs#637]
Hello,

I've been using ExcelJS to generate Excel files with lots of merged cells, around tens of thousands of merged cells. However, I've noticed that the performance degrades a lot the more merges I perform. I've noticed that these few lines of code inside the mergeCells function are eating up lots of execution time:

```
// check cells aren't already merged
_.each(this._merges, function (merge) {
    if (merge.intersects(dimensions)) {
        throw new Error('Cannot merge already merged cells');
    }
});
```

The issue here is clear: the first time I merge a cell, it doesn't need to perform any checks, but the second time, it needs to check against the first merged cell; the third time, there are two checks to be made... and the 10,000th time, there are 9,999 checks. So merging n cells requires 1 + 2 + ... + n-2 + n-1 ∈ O(n²) checks.

By simply commenting out the above lines, I reduced the generation time from above 5 minutes to just a few seconds, so the difference in performance is huge.

However, I haven't made a pull request yet because I am not quite sure about which would be the best solution here:

- Remove the check altogether: I'm not even convinced that the check is necessary (as it will only throw an exception, which is handy when starting out, but little more than that) - although I am not sure about the sort of exceptions that ExcelJS might throw if merge data is inconsistent, or whether the cause of such exceptions would be easy to track down.
- Add a flag, either in the whole document or as a parameter in mergeCells, which can be used to skip this check.
- Perform the check in a more efficient way. E.g., instead of iterating over all the merged cells, you may maintain an array telling you which merged cells belong in each row (e.g., if you merged A1 and A2, then arr[1] = ["A1"] and arr[2] = ["A1"]). That way, if I wanted to merge B2 and B3, I'd only need to check against the cells in row 2 (A1) and row 3 (none).

For the time being, as a workaround, I'm just commenting out these lines in my local version of the library, but of course I'd be happy to know which would be your preferred way to tackle this. :)

**Comment by hubyhub** [comment]
I am using exceljs 4.4.0 and I am also facing the same performance problems.

With  the before mentioned check `merge.intersects()` the application freezes and crashes, without the check the file is created within seconds.
My question is, what is the status of that issue? 

For the moment I would prefer your second solution, to have at least a flag, to be able to (temporary) disable the check. That would be simplest and safest way to solve the performance problems.
The issue is marked as "completed", but I cannot find the feature in version. 4.4.0.. or am I missing something?

**Comment by mvrikxix** [comment]
@Siemienik @unpollito - was there any update on this issue? The issue is marked as "completed" without any resolution maintained.
