### ISSUE TITLE
Protect Excel

### ISSUE THREAD

**Issue by jgtbz** [exceljs/exceljs#642]
How can i do this ?

>  Read Only in some cells
> 
>   Do not allow adding new rows
> 
>   Do not allow new sheets

**Comment by evelyn2584** [comment]
Same question

**Comment by felixOvianet** [comment]
I am also interested to know if theses features are non-existent or simply non-documented at the moment?

**Comment by karabaesh** [comment]
Issue resolved: https://github.com/exceljs/exceljs#sheet-protection

Please close @jgtbz
