### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by GuofuHuang** [exceljs/exceljs#657]
Environment: 
Meteor,
Angular 6

I'm trying to import exceljs with the code below:
 var Excel = require('exceljs');

But it always gives me this error:

Uncaught TypeError: Cannot read property 'prototype' of undefined

Any ideas?

**Comment by zgriesinger** [comment]
Try changing it to:
```javascript
var Excel = require('exceljs/dist/es5/exceljs.browser.js')
```

**Comment by sahilbhatt92** [comment]
Thanks @zgriesinger  it worked!
