### ISSUE TITLE
ExcelJS throws an exception in IE 11

### ISSUE THREAD

**Issue by Trinakriae** [exceljs/exceljs#658]
The component works perfectly in all the major browsers (Chrome, Firefox, Edge), however in Internet Explorer it throws an exception related to the JS method assign():

_Object doesn't support property or method 'assign'_

For my web application working in IE is a strict requirement. I know that the issue is not strictly related to the ExcelJS component but maybe somebody has any solution for this? Thanks

**Comment by Siemienik** [comment]
Just add this before your script: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill
