### ISSUE TITLE
Streaming support is genious. Any xml writing library doing the same?

### ISSUE THREAD

**Issue by Tilogorn** [exceljs/exceljs#660]
Just curious: I'm using exceljs to read a csv and write it to a xlsx-stream with nodejs. Takes less than **20MB** for **500k** rows. 
I need XML-Support too. But I can't find any xml writing library that supports committing single elements and writing them to disk (which leads to over **2GB** memory consumption).

Does the author of exceljs or anyone else know a xml-library that has the same genious streaming support as exceljs?

**Comment by vyava** [comment]
Hey,

Out of question.. May i get some example to write xls/xlsx file on nodejs? I was trying to do that with documentation but i just got zero byte files.

**Comment by Tilogorn** [comment]
You mean a simple example with File I/O?

```js
var Excel = require('exceljs');
var workbook = new Excel.Workbook();

var sheet = workbook.addWorksheet('My Sheet');
var cell = sheet.getCell('A1');
cell.value = 'Hello World';

workbook.xlsx.writeFile('testWorkbook.xlsx')
    .then(function() {
        console.log('File written');
    });

```

**Comment by vyava** [comment]
Actually my problem was little different. Now i have fixed. I just need to use "tempfile" library to create a file first, write on it after.. Thanks
