### ISSUE TITLE
How to download excel file from frontend without save it from folder first

### ISSUE THREAD

**Issue by muhammadbima20** [exceljs/exceljs#662]
hi, i have an issue about how to generate excel and return dowload file without save the file.

i use native JS in my frontend, and i generate the excel in my NodeJs Backend.
the way i generate, i think is normal : 
> /* Get Data Code Above */
>
> workbook.xlsx.write(res);
> res.end();

and in the frontend, i just using normal ajax call.

maybe you guys can help me with give me an example code in frontend to download, and how to return it from backend.

PS : 
- i've already tried using `Blob`, but they said, `Blob` is not available in NodeJs
- the download is already done but the excel file must be saved first in my folder.

any help will be appreciated.
thanks anyway;

**Comment by hewford** [comment]
Please help! I have the same issue. Using React though...

**Comment by JarvisQJ** [comment]
Same question!

**Comment by Siemienik** [comment]
@hewford @JarvisQJ 
https://www.npmjs.com/package/save-as used on frontend
