### ISSUE TITLE
Having issue the large size of item to the data validation on list with Exceljs

### ISSUE THREAD

**Issue by priyankhcrm** [exceljs/exceljs#667]
Having issue the large size of item to the data validation on list with Exceljs
This is working good
sheet2.getRow(2).getCell(1).dataValidation = {
type: 'list',
allowBlank: true,
formulae: ['"One,Two,Three,Four"']
};
but below is giving error and if we remove some of items from the array list then it is working fine
worksheet.getRow(2).getCell(m + 1).dataValidation = {
type: 'list',
allowBlank: true,
formulae:['"30W x 34L,31W x 34L,24W x 32L,XXXX-Small,25W x 32L,14-15 Years,18-24 Months,10,Free Size,12,14,Small,16,18,X-Large,0,2,3-6 Months,36W x 34L,38W x 34L,4,28W x 32L,6,30W x 34L,31W x 34L,24W x 32L,XXXX-Small,25W x 32L,14-15 Years,18-24 Months,10,Free Size,14,12"'],
};
Please help

**Comment by ert78gb** [comment]
Max 255 characters allowed in Excel when you define list validation with sting values. If you need bigger list then define the list on other sheet and reference to that range

**Comment by priyankhcrm** [comment]
Is there any paid service where we could take maximum characters

 

Thanks

Priyank Joshi

**Comment by SreekanthMekala** [comment]
@ert78gb @priyankhcrm How to get selected value from list?
Can you please share with us. Thanks

**Comment by ert78gb** [comment]
Based on the documentation
> // Specify list of valid values from a range.
// Excel will provide a dropdown with these values.
    worksheet.getCell('A1').dataValidation = {
        type: 'list',
        allowBlank: true,
        formulae: ['$D$5:$F$5']
};

or `formulae: ['LOOKUPS!$D$5:$F$5']` if you reference to other sheet

**Comment by SreekanthMekala** [comment]
@ert78gb Thanks, I tried with below code, No luck!!. Can you please review once.

workbook.xlsx.readFile('DAT_upload.xlsx')
    .then(function() {
        var worksheet = workbook.getWorksheet('COMP DATA');
        worksheet.getCell('C3').dataValidation = {
            type: 'list',
            allowBlank: true,
            formulae: ['LOOKUPS!$C$3:$J$3']
            };
        //console.log(cellData); 
        worksheet.eachRow({ includeEmpty: false }, function(row, rowNumber) {
          console.log("Row " + rowNumber + " = " + JSON.stringify(row.values));
        });
    });

**Comment by ert78gb** [comment]
In my last project I switched to `excel4node` because it support to set validation on range.

```javascript
sheet.addDataValidation({
      type: 'list',
      allowBlank: false,
      showErrorMessage: true,
      errorStyle: 'stop',
      errorTitle: 'Invalid value',
      error: 'Please select a valid value from the list',
      sqref: `B2:B100`, // range of the field that have to be validate
      formulas: ["=LOOKUPS!$A$2:$A$3"] // range that contains the valid list. The `LOOKUPS` is the name of the sheet
    });
```

**Comment by astak15** [comment]
> @ert78gb Thanks, I tried with below code, No luck!!. Can you please review once.
> 
> workbook.xlsx.readFile('DAT_upload.xlsx')
> .then(function() {
> var worksheet = workbook.getWorksheet('COMP DATA');
> worksheet.getCell('C3').dataValidation = {
> type: 'list',
> allowBlank: true,
> formulae: ['LOOKUPS!$C$3:$J$3']
> };
> //console.log(cellData);
> worksheet.eachRow({ includeEmpty: false }, function(row, rowNumber) {
> console.log("Row " + rowNumber + " = " + JSON.stringify(row.values));
> });
> });

Hi, is it not possible to do this anymore? I have a few columns in a table where I need to add formulae in list data validation but it looks like the dataValidation object is now readonly? 

If the devs did make the object readonly, they didn't provide another way to add a formula to list validation?

**Comment by yashsharma04** [comment]
@ert78gb can you share some example of how you would create that range and reference it ?

**Comment by ert78gb** [comment]
@yashsharma04 I created an example repo https://github.com/ert78gb/excel4node-range-validation

**Comment by PrashanthkumarR** [comment]
Even I faced this issue after a lot of circuses I found the solution we need to create two worksheets -
**const WorkSheet1 = await poSupplierWorkBook.addWorksheet('main');**
**const WorkSheet2 = await poSupplierWorkBook.addWorksheet('HugeList');**

WorkSheet2.addRow(['list1', 'list2', 'list3' etc ..]);  // here only mention your list to show in drop down
column.dataValidation ={
        type: 'list',
        allowBlank: false,
        formulae:['HugeList!A1:A500'],  // reference your worksheet and your list start and end
        showErrorMessage: true,
        errorStyle: "error",
        errorTitle: "Error",
        error: "Value must be in the list"
    }

**Comment by GirishAdvani** [comment]
@PrashanthkumarR  good pointer. for anyone looking working example, please check below link which I created based on Prashant's comment:

[https://stackblitz.com/edit/angular-8-export-dropdownlist-vetntu](https://stackblitz.com/edit/angular-8-export-dropdownlist-vetntu)

**Comment by kohaiy** [comment]
```JS
worksheet.dataValidations.add('E1:E1048576', {
    type      : 'list',
    allowBlank: false,
    formulae  : ['"One,Two,Three,Four"'],
});
```
