### ISSUE TITLE
Font Colors aren't Consistent

### ISSUE THREAD

**Issue by huntinghawk1415** [exceljs/exceljs#669]
I'm attempting to only change the font color of a row that is being passed into a function:

  ```
write(workbook, sheet, info, row_no, chart_path) {
    const worksheet = workbook.getWorksheet(sheet)
    const row = worksheet.getRow(row_no)
    const no_3 = info[2].slice(0, info[2].length - 1)

    row.font = {color: {argb: 'FFFF0000'}}

    row.eachCell({includeEmpty: true}, (cell, col_no) => {
      col_no === 1 && (cell.value = info[0])
      col_no === 2 && (cell.value = info[1])
      col_no > 3 && no_3.forEach((i, i_no) => {
        col_no - 4 === i_no && (cell.value = i)
      })
    })

    workbook.xlsx.writeFile(chart_path)
      .then(() => console.log('done'))
      .catch(error => console.error(error))
  }
```

Unfortunately when I run this it changes every row between an arbitrary number (i.e. rows 5-14) instead of just the row I specify. Any reason for this that someone can see, or is this a bug?

**Comment by Siemienik** [comment]
@huntinghawk1415 do you know now what was happen?

**Comment by huntinghawk1415** [comment]
@Siemienik Still no idea. The code is a little abrasive to look at to uncover the true cause after a while, so I decided to go with another option for editing the Excel file.

That said, if it helps, the last thing I was able to determine was it was only an issue with already existing Excel files. Files created using exceljs did not exhibit the same behavior and worked as expected.

**Comment by Siemienik** [comment]
@huntinghawk1415 could I please for example file?

**Comment by huntinghawk1415** [comment]
The file I was using contains sensitive data from my company, so I cant share that file. But when I have some time later today or tomorrow I can try to recreate the issue for you with a different file.

**Comment by Siemienik** [comment]
@huntinghawk1415  sure, thanks

**Comment by Siemienik** [comment]
pull request opened
@huntinghawk1415 thanks for details, it was really helpful ;)

**Comment by iva2k** [comment]
Perhaps it's happening due to use of simple assignment in the code of spliceRows(). Javascript assigns objects by reference, so simple assignment just reuses existing object. If later the object properties are changed, they affect all references of the original object. A fix would be a proper clone of the object instead of simple assignment.

**Comment by julimuchi** [comment]
THE SOLUTION: https://github.com/exceljs/exceljs/issues/2055
