### ISSUE TITLE
the default state value of sheet is "show" which not support by other lib, maybe "visible" is better

### ISSUE THREAD

**Issue by joeyzhao1023** [exceljs/exceljs#678]
openpyx in python
`ValueError: Value must be one of set(['visible', 'hidden', 'veryHidden'])`

xlrd in python
`KeyError: 'show'`

**Comment by naholyr** [comment]
:+1: and related to #648
Definitely a change to apply

Meanwhile you can call `workbook.addWorksheet(title, { state: 'visible' })`

**Comment by Siemienik** [comment]
PR: https://github.com/exceljs/exceljs/pull/621
