### ISSUE TITLE
[Streaming mode] Changing width after some rows was committed 

### ISSUE THREAD

**Issue by junaidinam** [exceljs/exceljs#686]
hi,

Initially, I was getting all the rows finding which row for each column has the longest length and setting column width based on that. it was working fine, but the problem occurred when I started committing each row.

I have noticed that when a row is committed, column width cannot be changed later on. 

Is there a workaround for that? I really appreciate all your help.

Keep up the good job

**Comment by junaidinam** [comment]
@Siemienik No. I think author is busy nowadays. If you like we can work on it together. I really like this library and would like to enhance its functionality. Please let me know!

**Comment by Siemienik** [comment]
@junaidinam nice to hear that, please make a pull request and add `@Siemienik`  in description, I promise to review it as quick it's possible, 

any way I don't know how often new versions will be published - I have no power to do that ;(

**Comment by Noitidart** [comment]
Hi guys, I tried setting with after streaming/comitting rows, but before comitting worksheet, but setting width is not having any affect. Is this feature not yet implemented?
