### ISSUE TITLE
Convert csv data to excel data in browser

### ISSUE THREAD

**Issue by ButuzGOL** [exceljs/exceljs#693]
I am using this library in browser
and i have variable with csv data like this
```
var csvData = `
Sally Whittaker,2018,McCarren House,312,3.75
Belinda Jameson,2017,Cushing House,148,3.52
Jeff Smith,2018,Prescott House,17-D,3.20
Sandy Allen,2019,Oliver House,108,3.48
`;
```
and want something like this ```.csvToExcel(csvData);```
is it possible or i should move csvData to array and then create excel based on array in loop or there some more simple way ?

**Comment by Siemienik** [comment]
@ButuzGOL,
i see 2 options:

1.     
```
workbook.csv.createInputStream()
 .fromString(csvData, {headers: false})
```
2. with [string-to-stream](https://www.npmjs.com/package/string-to-stream) package:
```
var workbook = new Excel.Workbook();
str(csvData).pipe(workbook.csv.createInputStream()))
```

let's try both and choose this one what is better for you ;)

**Comment by Folcon** [comment]
Is there an updated version of this?
#object[Error Error: `CSV#createInputStream` is deprecated. You should use `CSV#read` instead. This method will be removed in version 5.0. Please follow upgrade instruction: https://github.com/exceljs/exceljs/blob/master/UPGRADE-4.0.md]

I've been trying to use the example given, but I'm currently getting:
```
_stream_readable.js:905 Uncaught (in promise) TypeError: process.nextTick is not a function
    at resume (_stream_readable.js:905)
    at StringStream.Readable.resume (_stream_readable.js:895)
    at StringStream.Readable.on (_stream_readable.js:813)
    at StringStream.Readable.pipe (_stream_readable.js:677)
    at eval (exceljs.min.js:3)
    at new Promise (<anonymous>)
    at t.value (exceljs.min.js:3)
```
