### ISSUE TITLE
eachRow's row.values array, always has 'null' as its first entry

### ISSUE THREAD

**Issue by j0hnskot** [exceljs/exceljs#698]
Hello,

I'm wondering, Is the below behaviour normal?
I can't understand why "null" is added in the values array. Is this by intention or am I missing something?

``` javascript

   workbook 
        .getWorksheet(1) // has one row with values 1, 2, 3 on the first 3 cells
        .eachRow((row, rowNumber) => {
            console.log(row.values) // will output [null, 1, 2, 3]
        });
```

(using version ^1.0.0)
Thank you!

**Comment by Siemienik** [comment]
Hello @j0hnskot,
indexing in xlsx files starts from number 1 (eg. `A1` point to row `1` and collumn `1`)
setting `null` at the start is much easier than always recalculating from 0 based to 1 based indexing

**Comment by Samirun** [comment]
> Hello @j0hnskot, indexing in xlsx files starts from number 1 (eg. `A1` point to row `1` and collumn `1`) setting `null` at the start is much easier than always recalculating from 0 based to 1 based indexing

Hi, could you provide an example for your statement?
null at the start doesn't seem to resolve
