### ISSUE TITLE
Special cell value results invalid file

### ISSUE THREAD

**Issue by PRR24** [exceljs/exceljs#703]
```
In case of cell value "__proto__" exceljs creates invalid file.
Same happens also with CellHyperlinkValue.text = "__proto__"

Steps to repro:
1. Create new excel file and worksheet.
2. Add rows to the sheet:
        sheet.addRow(["Not good"]);
        sheet.addRow(["__proto__"]);
3. Save the file.

Expected result:
Excel file with two text cells with provided values.

Actual result:
LibreOffice shows the file, but second row data is invalid.
Excel claims that the file is invalid. If force-opened, shows [object Object] in second cell

**Comment by PRR24** [comment]
There are more weirdnesses, for example
sheet.addRow(["toString"]);
will appear as "Name" in the resulting file.

**Comment by wmizzi** [comment]
Having a similar issue. Doing the following:

`sheet.addColumn([ 'toString' ])`

results in a prompt from Excel saying: 

"We found a problem with some content in 'workbook.xlsx'. Do you want us to try to recover as much as we can?"

Selecting "Yes" results in the following cell value where "toString" should be:

`function toString() { [native code] }`

**Comment by Alanscut** [comment]
@PRR24 @wmizzi  I will use `object..create(null)` to resolve this error. I will submit a pull request as soon as possible.

## Screenshots

<img width="406" alt="bug1" src="https://user-images.githubusercontent.com/21104054/82009468-f60a6980-96a1-11ea-9223-4dd99f2dbad3.png">
<img width="475" alt="bug2" src="https://user-images.githubusercontent.com/21104054/82009474-fb67b400-96a1-11ea-9705-eaa5a8642095.png">


## Source code
```javascript
  // shared-strings-xform.js
  this.hash = {};
  addText(value) {
    let index = this.hash[value];
    if (index === undefined) {
      index = this.hash[value] = this.model.values.length;
      this.model.values.push(value);
    }
    this.model.count++;
    return index;
  }
```
