### ISSUE TITLE
Missing Worksheet outlineProperties

### ISSUE THREAD

**Issue by awn70** [exceljs/exceljs#710]
The outlineProperties are not part of the worksheet properties (index.d.ts). 
Setting them has no effect for the generated excel sheet.
Is this a bug?

**Comment by Siemienik** [comment]
@awn70 could You share with some example code ?

**Comment by awn70** [comment]
I want to set the summaryBelow property for the sheet:
`sheet.properties.outlineProperties = { summaryBelow: false };`

The outlineProperties are not available in the index.d.ts file.
