### ISSUE TITLE
LibreCalc / ODS support?

### ISSUE THREAD

**Issue by dandv** [exceljs/exceljs#716]
I'm a LibreCalc user, and would be interested to know if ODS support is within scope. Thanks!

**Comment by Siemienik** [comment]
lack of activity

**Comment by ZhenjaMax** [comment]
Any updates?

**Comment by Siemienik** [comment]
exceljs support only `xlsx` format at this time. If would you like discuss the future plans join to Discord: https://discord.gg/siema .

**Comment by jorgeperezlara** [comment]
This would be nice, to be honest

**Comment by trymeouteh** [comment]
Would like to see ODS support as well
