### ISSUE TITLE
Open Excel file not detecting any changes

### ISSUE THREAD

**Issue by johisco** [exceljs/exceljs#719]
Hi! Im working with ExcelJS in an electron application.

In my app I allow the user to drag and drop an excel file into the program .... the application thereafter manipulates and saves the modified excel file with the same name. I want the user to be able to have the excel file open (in Excel) and see the changes appear.

As of now when the file is saved I have to close the Excel app and reopen it again to see my changes take effect.

Is this possible? 
Or ..
Is there any thing I could do from the Excel file like allowing background refresh or something similar?

**Comment by Siemienik** [comment]
Hello @johisco,
as far as I know Excel locks opened files, so unfortunately it is not depended of this library :(

for what you want to achieve I'd try to use it:
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-overview

if You found any other solutions for this issue, please share it with us ;)
