### ISSUE TITLE
Project still maintained / looking for maintainers?

### ISSUE THREAD

**Issue by alubbe** [exceljs/exceljs#720]
Hi @guyonroche,

we've sent a couple of PRs your way that pass the test suite and are battle-tested on our production system. Our fork is growing more apart and we'd rather see the changes merged upstream, so that everyone can benefit.

On top of those open PRs that you haven't replied to we'd also like to send some more PRs your way - but are you still maintaining this project? We could also offer to help out as additional maintainers, if you're fine with that. The streaming excel reader is quite important for us and we'd like to give back to this library, if you let us ;)

**Comment by Siemienik** [comment]
Hello @alubbe , I notice the same problem with this wonderful library.. I wrote some changes with tests and all whats is needed, after that my pull request has stuck 
(https://github.com/guyonroche/exceljs/pull/702)

As long as it's required I am going to maintain this project as a fork here: https://github.com/p3rio/exceljs

I invite all interested in to write issues/pull request there

regards

**Comment by guyonroche** [comment]
@alubbe @Siemienik 
I must apologise for my lack of focus on this library. As I've mentioned I've been under heavy workload pressure from other projects and that's not likely to change soon. I know there is a great interest in the lib from yourselves and many others and I'd like to keep it going.
I think your suggestion to add maintainers is the way forward with this, would this be yourself or would you nominate an account?

**Comment by johnmalkovich100** [comment]
@alubbe @guyonroche that's right. But in this case add my main github account - @coldhiber, not this one (@johnmalkovich100)

**Comment by Siemienik** [comment]
@guyonroche nice to hear that You are alive :) I am interested too

I sent you invitation as a owner to exceljs organisation that I had create yesterday for this library, if it makes sense for You we may use it

**Comment by guyonroche** [comment]
@Siemienik that's great. Next question is, how to move the original repo into the org. The fork is missing all the PRs and issues

**Comment by Siemienik** [comment]
@guyonroche  shall you try to use  "transfer option" from settings?

**Comment by guyonroche** [comment]
@Siemienik done - it's all there
Would you mind terribly if I removed you and re-invited as a Member? I'd like to retain sole ownership if that's ok

**Comment by Siemienik** [comment]
@guyonroche sure, that's no problem for me ;)  it's Your project, so I have just removed myself, 
I want have only guarantee that this project doesn't stuck again because I am using it in some projects and have some ideas to put here

**Comment by Siemienik** [comment]
@guyonroche Did you create gitter under `/exceljs`, I can't access there and i cant create new one.

**Comment by guyonroche** [comment]
@Siemienik - sorry, turns out Members don't get full access to the repos. I've added you as collaborator on the repo now

**Comment by alubbe** [comment]
Awesome! I've noticed travis is still pointing at the old github repo, we should probably update that. And maybe have it run the tests on node 6, 8, 10 and 11.

Speaking of which, I see a lot of `var` in the files, but also arrow functions. So we are already requiring at least node v4. Would it be okay to refactor the entire code base, maybe file by file, to ES6? I'd suggest to make the changes without touching the tests, and then refactor the tests once the implementation is updated.

**Comment by guyonroche** [comment]
I updated Travis this morning but forgot to update the README - just did this now

Yeah, the code is a mish-mash of ES3 JavaScript and ES2015+
One of the things I wanted to do after adding Babel was to update the code-base to up-to-date JS.
I'm not overly happy with grunt any more - it's throwing up a lot of npm audit problems and there are better ways to build the code now - yet another thing that takes time

**Comment by alubbe** [comment]
@guyonroche we now have a number of PRs that we think can be merged - could you give us the rights to do so, or what's your plan on doing that? if you want to go through them yourself, should we schedule a time where we are all online and discuss the PRs together and do a release afterwards?

**Comment by guyonroche** [comment]
@alubbe sorry, I've been really busy (still). I assumed you would all have the rights to merge. Is this not so?
Which PRs were you interested in?

**Comment by guyonroche** [comment]
As for release checks, just the usual suspects...
* I try to add some kind of test for new features and especially for bug fixes.
* Travis should be green
* README.md should be updated - the New Features! section is copied to the Release History section (with appropriate version) and any changes documented
* I try to follow semver so new version will depend on those changes.

**Comment by alubbe** [comment]
yeah none of us have the rights to merge - would you mind granting us that?

regarding the PRs, I think it would be great if you could give your opinion on https://github.com/exceljs/exceljs/pull/702 and https://github.com/exceljs/exceljs/pull/722 as well as https://github.com/exceljs/exceljs/pull/736/files

then, I'd suggest to merge https://github.com/exceljs/exceljs/pull/727 - I will volunteer to update all remaining PRs by hand to avoid this causing any merge conflicts (it's really just checking out the branches and re-running prettier, no biggie).
