### ISSUE TITLE
How to insert data into merged cell of an existing Excel file?

### ISSUE THREAD

**Issue by e-ndrus** [exceljs/exceljs#726]
Is there a way to insert data into a merged cell of an existing Excel file?

I am trying to do something like this:

```
const workbook = new Excel.Workbook();

  workbook.xlsx.readFile('invoice А.xlsx')
      .then(function() {
          let worksheet = workbook.getWorksheet(1);
          let  row = worksheet.getRow(26);
          row.getCell(2).value = 15;
          row.commit();
          return workbook.xlsx.writeFile('newInvoice.xlsx');
      })
```

The error message is TypeError: Cannot read property 'getRow' of undefined.

**Comment by Siemienik** [comment]
@e-ndrus 
worksheet with id `1` doesn't exist

let's use `workbook.worksheets[0]` instead of `workbook.getWorksheet(1)`

It's possible to access id of first worksheet:
`console.log(workbook.worksheets[0].id)`

**Comment by e-ndrus** [comment]
@Siemienik, hm, unlike my code above the suggested solution doesn't create a new file with updated content from the old one. My code above works on a cell unless it is a merged cell. What am I missing?
