### ISSUE TITLE
append data to exising excel  with stream

### ISSUE THREAD

**Issue by duxy-ios** [exceljs/exceljs#729]
Hey ,

Nice to use exceljs, great job!
when i use stream writer, one million data used 2.5G RAM,  can i reduce memory by  commit multiple times ,Or do you have any other suggestions?
i had trying fs.createWriteStream with 'a' flag but finaly could not open the  Generated xlsx
```
    var writerStream = fs.createWriteStream('./streamed-workbook.xlsx', { 'flags': 'a', autoClose: false, encoding: "utf8" });
```

Thanks,

**Comment by Siemienik** [comment]
@duxy-ios , are You using `writerStream.end()`?

**Comment by alezzigo** [comment]
> @duxy-ios , are You using `writerStream.end()`?

Hi, I same your problem.
Can you help your sollution?
Thank!
