### ISSUE TITLE
Corrupt file on windows

### ISSUE THREAD

**Issue by Zoharyal** [exceljs/exceljs#732]
I'm writing on a blank xlsx file, created on windows. The file is corrupted on windows, i can open it on libreoffice on my  laptop, google sheets on google drive open it too. Only excel on windows cannot open it.

**Comment by Gildewarz777** [comment]
I seem to have the same problem [here](https://github.com/exceljs/exceljs/issues/739). What happens if you create a simple file with nothing on it, just a spreadsheet?

**Comment by starl441** [comment]
I have similar issues. Is this resolved and how?
