### ISSUE TITLE
Low Performance.

### ISSUE THREAD

**Issue by IgnatovDan** [exceljs/exceljs#742]
Hello,

Currently I am reviewing your library to see whether or not I can use it instead of my own implementation.

For now, I found the only issue with performance:
* [6-7s with our implementation, click the 'Click me to start DataGrid ExcelExport and wait 5-10 secs (there is no visual progress)' button](https://codepen.io/DanIgnatov/pen/qgxbXd)  to export [20000 x 50] array
* [15-20s with ExcelJS, click the 'Click me to start ExcelExport and wait 15-20 secs (there is no visual progress)' button](https://codepen.io/DanIgnatov/pen/vbdLjx?editors=1010) to export [20000 x 50] array

Click the [Click me..] button on each page and review the elapsed time in the shown alert dialog.

Do you have plans to improve it? There are no notes about performance in the [Backlog](https://github.com/exceljs/exceljs#backlog)

**Comment by Siemienik** [comment]
@IgnatovDan thank you for test, could I please You to give me repo with benchmark ?

**Comment by IgnatovDan** [comment]
Thank you for the reply.
I would like to help you to improve this scenario but it is not clear what is the 'repo with benchmark'?

Right now I created two simple pages at codepen.io (see my first comment):
* [6-7s with our implementation, click the 'Click me to start DataGrid ExcelExport and wait 5-10 secs (there are no visual progress)' button](https://codepen.io/DanIgnatov/pen/qgxbXd)  to export [20000 x 50] array
* [15-20s with ExcelJS, click the 'Click me to start DataGrid ExcelExport and wait 15-20 secs (there are no visual progress)' button](https://codepen.io/DanIgnatov/pen/vbdLjx?editors=1010) to export [20000 x 50] array

Click the [Click me..] button on each page and review the elapsed time in the shown alert dialog. I have simplified these pages and now there is the only button that shows the elapsed time in an alert dialog.

**Comment by alubbe** [comment]
Just did a quick check - datagrid seems to use a lower zip compression level, so exceljs is actually doing a lot more work. But I feel like when generating xlsx files on the client, we should favour cpu cycles over saving output size (4.2 MB vs 4.4 MB in this case). Maybe we can change the default compression to the lowest and fastet level and then provide an option to increase/change it for those who need it

**Comment by alubbe** [comment]
Okay so never mind, that's not it after all. The zip compression is the same, there must be something very inefficient in `workbook.xlsx.writeBuffer()` after all

**Comment by rogozind** [comment]
@alubbe , you are correct. In my tests I found xmlEncode() function takes 50% of write operation. This is because it uses a regexp to escape the text chunk. And there are a lot of chunks. My test case has 43K rows and 10 columns. That function is called roughly 6M times.  It takes 20secs to produce the file. 10 secs goes to writeBuffer() call. 

But in most cases the text passed in does not have any special characters and can be returned as is.  So I have created a patch to check if the text even needs an escaping and if not it returns the original:

```
xmlEncode(text){
     // Loop over and see if we have any "bad" characters
     for(var i=0; i<text.length; i++) {
        var c = text.charAt(i)
        if (c == '<' ||
            c == '>' ||
            c == '&' ||
            c == '\'' ||
            c == '"' ||
            c == '\x7F' ||
            c <= '\x08' ||
            c == '\x0B' ||
            c == '\x0C' ||
            ('\x0e' <= c && c <= '\x1F')) {
         // Found a char. Return escaped string
         return
            text.replace(/[<>&'"\x7F\x00-\x08\x0B-\x0C\x0E-\x1F]/g,function(c){switch(c){
                case'<':return'&lt;';
                case'>':return'&gt;';
                case'&':return'&amp;';
                case'\'':return'&apos;';
                case'"':return'&quot;';
                default:return'';
            }});
        }
      }
    // If we got here the string does not need escaping. Return the original.
     return text;
       }
```
This gave me 5sec back on my test.

I think it will be useful for very large files. Maybe there is a better way so you do not duplicate the characters twice. But you get the idea: fast check if escaping if even needed and return the original string if it is not.

Anyone cares to create a PR and incorporate this idea ?

**Comment by alubbe** [comment]
Thanks for investigating this! I used to build super-optimized version for pug (see https://github.com/pugjs/pug-runtime/blob/master/index.js#L187-L210), so could you try benchmarking with this one and share your results here or on the PR (https://github.com/exceljs/exceljs/pull/1476)?
```js
const xmlDecodeRegex = /[<>&'"\x7F\x00-\x08\x0B-\x0C\x0E-\x1F]/;
// ...
  xmlEncode(text) {
    const regexResult = xmlDecodeRegex.exec(text);
    if (!regexResult) return text;

    let result = '';
    let escape = '';
    let lastIndex = 0;
    let i = regexResult.index;
    for (; i < text.length; i++) {
      const charCode = text.charCodeAt(i);
      switch (charCode) {
        case 34: escape = '&quot;'; break;
        case 38: escape = '&amp;'; break;
        case 39: escape = '&apos;'; break;
        case 60: escape = '&lt;'; break;
        case 62: escape = '&gt;'; break;
        case 127: escape = ''; break;
        default: {
          if (charCode <= 31 && (charCode <= 8 || charCode >= 11 && charCode !== 13)) {
            escape = ''; break;
          }
          continue;
        }
      }
      if (lastIndex !== i) result += text.substring(lastIndex, i);
      lastIndex = i + 1;
      if (escape) result += escape;
    }
    if (lastIndex !== i) return result + text.substring(lastIndex, i);
    else return result;
  },
```

**Comment by alubbe** [comment]
Merged - thank you!
