### ISSUE TITLE
Internal Hyperlink generation is broken on Windows

### ISSUE THREAD

**Issue by jayden-chan** [exceljs/exceljs#749]
The following example works correctly on macOS/Linux, but not on Windows:

```javascript
const Excel = require('exceljs');
const wb = new Excel.Workbook();

wb.addWorksheet('TOC').state = 'visible';
wb.addWorksheet('Test Sheet').state = 'visible';

const ws = wb.getWorksheet('TOC');

ws.getCell('A1').value = {
  text: 'Test Hyperlink',
  hyperlink: `#'Test Sheet'.A1`
};

wb.xlsx.writeFile('output.xlsx');
```

For the hyperlink value I have tried:
```
* `#'Test Sheet'!A1`
* `#"Test Sheet"!A1`
* `#'Test Sheet'.A1`
* `#"Test Sheet".A1`
* `#\\"Test Sheet\\"!A1`
* `#\\'Test Sheet\\'!A1`
* `#\\"Test Sheet\\".A1`
* `#\\'Test Sheet\\'.A1`
```
and a few others. None work.

**Comment by jackchendong** [comment]
`#Test Sheet!A1`

You can try

**Comment by dosse** [comment]
Try with:
`hyperlink: '#\'Test Sheet\'!A1'`

Btw, the [hyperlink doc](https://github.com/exceljs/exceljs#hyperlink-value) is wrong as the syntax given there doesn't work.

**Comment by jayden-chan** [comment]
@dosse That doesn't work either. This is the same issue as #920. I'm confident it's a bug, I don't know how to fix it though.

**Comment by HarryW96** [comment]
Was there ever a fix implemented for this? I'm having the exact same issue as described. Documentation still seems to be incorrect on how this functionality works if it has been fixed too?

**Comment by Siemienik** [comment]
hyperlinks works good with URLs. I've never used them for internal links - probably, that hasn't implemented yet.

**Comment by Alanscut** [comment]
@jayden-chan I use the following code, the inline function works fine.
```
ws.getCell('A5').value = {text: 'Sheet2', hyperlink: '#\'Test Sheet\'!A1'};
```

**Comment by Troy96** [comment]
Hi, I'm facing issue of broken link. Can please somebody help me here?

![Screenshot 2021-04-20 at 10 54 56 AM](https://user-images.githubusercontent.com/24861825/115342274-a1cc0b80-a1c7-11eb-8004-1d855c1a26da.png)
![Screenshot 2021-04-20 at 10 57 54 AM](https://user-images.githubusercontent.com/24861825/115342284-a55f9280-a1c7-11eb-923a-90cf35d79b56.png)

**Comment by StraDIVar** [comment]
The bug still exists. The link is created but it doesn't work in Excel and other applications that open files (e.g. online Excel, Google Sheets, Numbers). For example, it is an error message in online version of Excel
![image](https://github.com/exceljs/exceljs/assets/1488722/4bc9d2bf-25b0-48a0-a4cd-59e53c784431)

**Comment by bah99** [comment]
To achieve this dynamically on Windows, you can use the following code snippet:

```typescript
const sheetName = 'Test';
const sheetRef =  `#'${sheetName}'!A1` ;
worksheet.getCell('A1').value = { text: sheetName, hyperlink: sheetRef };
```

This should work perfectly. Please note the importance of single quotes around the sheet name in `sheetRef`. Be cautious not to omit them for proper functionality.

**Comment by jessica** [comment]
None of the suggested approaches work for me in Numbers, google sheets, or excel. Has this issue been resolved yet?

**Comment by piscopancer** [comment]
google sheets does not transform xlsx inner links to use their crappy "gid" approach, wtf?

![Image](https://github.com/user-attachments/assets/a5c4ea52-3e8c-4109-b7ad-0aaf7c4c8e16)
