### ISSUE TITLE
Need one live demo

### ISSUE THREAD

**Issue by Ponvijaykumar** [exceljs/exceljs#751]
We need one live demo for exceljs (http://jsfiddle.net/ Or any other site demo)

**Comment by vchouhan** [comment]
@Ponvijaykumar here's a link to a demo code.
[https://repl.it/@vishwasc/ExcelJs-Example](https://repl.it/@vishwasc/ExcelJs-Example)

**Comment by Siemienik** [comment]
@Ponvijaykumar maybe my answer isn't best of all, but in my opinion the most valuable examples were placed in tests: (lots of examples with description and asserts ;) )

for example, here:

https://github.com/exceljs/exceljs/blob/master/spec/integration/worksheet.spec.js
