### ISSUE TITLE
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'toString' of undefined"

### ISSUE THREAD

**Issue by hzjump** [exceljs/exceljs#760]
why？？
![image](https://user-images.githubusercontent.com/37094919/53947230-539b4180-4100-11e9-91ea-ba54a5a42294.png)

**Comment by hzjump** [comment]
![image](https://user-images.githubusercontent.com/37094919/53947310-7decff00-4100-11e9-9b43-eb2e882f73d8.png)
Is my code wrong?

**Comment by hzjump** [comment]
Is this plug-in node using？

**Comment by zachariahtimothy** [comment]
I am getting the same in React

> hot-dev-client.js:131 Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (graceful-fs.js:63)
    at Object.../node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:279)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object.<anonymous> (index.js:8)
    at Object.../node_modules/archiver-utils/index.js (index.js:156)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object.<anonymous> (core.js:14)
    at Object.../node_modules/archiver/lib/core.js (core.js:906)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object.../node_modules/archiver/index.js (index.js:8)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object.../node_modules/exceljs/dist/es5/stream/xlsx/workbook-writer.js (workbook-writer.js:10)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Object.../node_modules/exceljs/dist/es5/index.js (index.js:11)
    at __webpack_require__ (bootstrap:788)
    at fn (bootstrap:149)
    at Module../components/UnfundedProjects/Dashboard/Table.tsx (Table.tsx:1)

I know it is because FS is not available in browser, and seems to actually be an archiver package issue. Will dig further into it.

**Comment by hzjump** [comment]
> I am getting the same in React
> 
> > hot-dev-client.js:131 Uncaught (in promise) TypeError: Cannot read property 'toString' of undefined
> > at Object. (graceful-fs.js:63)
> > at Object.../node_modules/graceful-fs/graceful-fs.js (graceful-fs.js:279)
> > at **webpack_require** (bootstrap:788)
> > at fn (bootstrap:149)
> > at Object. (index.js:8)
> > at Object.../node_modules/archiver-utils/index.js (index.js:156)
> > at **webpack_require** (bootstrap:788)
> > at fn (bootstrap:149)
> > at Object. (core.js:14)
> > at Object.../node_modules/archiver/lib/core.js (core.js:906)
> > at **webpack_require** (bootstrap:788)
> > at fn (bootstrap:149)
> > at Object.../node_modules/archiver/index.js (index.js:8)
> > at **webpack_require** (bootstrap:788)
> > at fn (bootstrap:149)
> > at Object.../node_modules/exceljs/dist/es5/stream/xlsx/workbook-writer.js (workbook-writer.js:10)
> > at **webpack_require** (bootstrap:788)
> > at fn (bootstrap:149)
> > at Object.../node_modules/exceljs/dist/es5/index.js (index.js:11)
> > at **webpack_require** (bootstrap:788)
> > at fn (bootstrap:149)
> > at Module../components/UnfundedProjects/Dashboard/Table.tsx (Table.tsx:1)
> 
> I know it is because FS is not available in browser, and seems to actually be an archiver package issue. Will dig further into it.
---------------
I've solved this problem.You need to annotate two things.
![image](https://user-images.githubusercontent.com/37094919/54003973-f3071580-418e-11e9-8052-4aa531c32406.png)
![image](https://user-images.githubusercontent.com/37094919/54003993-074b1280-418f-11e9-8eb2-a198470caee5.png)
error “toString”，You should delete it。like this 
old：
![image](https://user-images.githubusercontent.com/37094919/54004094-585b0680-418f-11e9-8930-fdab8aba5775.png)
new：
![image](https://user-images.githubusercontent.com/37094919/54004118-6ad54000-418f-11e9-9e61-b3ef63a3663f.png)
filename is 
![image](https://user-images.githubusercontent.com/37094919/54004145-79bbf280-418f-11e9-8945-1fe477acb481.png)

ok，Solved！！

**Comment by zachariahtimothy** [comment]
For anyone else landing here, I am using NextJS and was able to fix the issue with the following webpack config in next.config.js:
```
config.node = { fs: 'empty' };
config.resolve.alias['exceljs'] =
          path.join(__dirname, '../', `node_modules/exceljs/dist/es5/exceljs.${isServer ? 'nodejs' : 'browser'}.js`);
```
Excel JS is working great btw, thank you so much for this library!

**Comment by JamesChenX** [comment]
I have fixed the issue by using:
`import Excel from "exceljs/dist/es5/exceljs.browser";`
It works fine.

**Comment by bhartimehta15** [comment]
![Capture](https://user-images.githubusercontent.com/54262534/63245302-7750df00-c27d-11e9-85f0-cab2cdfa10f0.PNG)

**Comment by bhartimehta15** [comment]
help me for solving the error
