### ISSUE TITLE
RESOLVED: How to group the specified rows? Does it support?

### ISSUE THREAD

**Issue by dzk666** [exceljs/exceljs#769]
![图片](https://user-images.githubusercontent.com/8910671/54670405-8eed3580-4b2e-11e9-908b-fe0386813006.png)

**Comment by Siemienik** [comment]
I'm not sure, but probably that feature doesn't exists here

@dzk666 did you resolve this issue?

**Comment by dzk666** [comment]
@Siemienik Yes, I have resolved it by below method:
row1.outlineLevel = 1;
row2.outlineLevel = 2;
