### ISSUE TITLE
TS2371 in exceljs >= 1.9.0 (Typescript)

### ISSUE THREAD

**Issue by tsiegleauq** [exceljs/exceljs#773]
Version 1.9.0 introduced a new issue in `exceljs/index.d.ts.`

> ERROR in node_modules/exceljs/index.d.ts(787,17): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

In an Angular (7) project, install exceljs 1.9.0 and add the following to `tsconfig.json`
```
"paths": {
  "exceljs": ["../node_modules/exceljs/dist/exceljs.min"]
}
```
use ng serve and see `TS2371`

Downgrading to 1.8.0 solves the problem

**Comment by molant** [comment]
Having the same problem in https://github.com/webhintio/hint/pull/2158 😞

**Comment by mfulop** [comment]
I think line #789 of index.d.ts:
```
constructor(model: IAnchor|object = {});
```
should be:
```
constructor(model: IAnchor|object);
```

**Comment by yonaroshella** [comment]
use 
import * as Excel from "exceljs/dist/exceljs.min.js"; 
instead of import { Workbook } from 'exceljs';

and declare 
let workbook = new Excel.Workbook();

**Comment by molant** [comment]
That's a breaking change and the library should have been bumped to 2.0

**Comment by bhavivg** [comment]
@yonaroshella  Thank you this resolved the issue for me.

**Comment by alubbe** [comment]
I think we should merge https://github.com/exceljs/exceljs/pull/780 and publish a bugfix release - @guyonroche what do you think?

**Comment by graciano** [comment]
@yonaroshella's solution worked for me. My angular version is 4, a legacy project.

**Comment by graciano** [comment]
@molant I don't think it's a breaking change, but rather a bug that can be fixed

**Comment by molant** [comment]
Depends on the maintainers intentions with this change. If this was on purpose then it should have been a breaking. If it was a mistake then a fix version would be appreciated.

**Comment by astrobob** [comment]
Hi guys,
I'm using exceljs with nodejs in Typescript.
I tried import * as Excel from "exceljs/dist/exceljs.min.js"; and indeed the error was gone.
But,
wb.xlsx.writeFile() and wb.xlsx.readFile() doesn't work any more.
Do you have any clue solving this issue? It's quite blocking
Thank you in advance

**Comment by zhu110guang** [comment]
I use Exceljs like this : 
import * as Excel from "exceljs";
workbook = new Excel.Workbook();

but when i try to build my code ,  it throw Error like this : 
![image](https://user-images.githubusercontent.com/18319392/56343995-e98db600-61ee-11e9-94aa-b5f01bf6fd91.png)

**Comment by lkiii** [comment]
@guyonroche The issue is still present. Could you suggest how to manage it? Maybe you could consider @alubbe changes to be published?

**Comment by satya1432** [comment]
It's working for me just change exceljs file path extension  in tsconfig.json file exceljs.min to exceljs.min.js 

"paths": {
  "exceljs": ["../node_modules/exceljs/dist/exceljs.min.js"]
}

**Comment by tsiegleauq** [comment]
the current version should work like it was used to

**Comment by molant** [comment]
@tsiegleauq that's not the case for us. It is still failing with v1.9.1:

> error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

* [How we import `exceljs`](https://github.com/webhintio/hint/blob/0f70f6f773235cdab31d5811eaa5f0ff9be9650f/packages/formatter-excel/src/formatter.ts#L14) (`import * as Excel from 'exceljs';`)
* [PR with the update](https://github.com/webhintio/hint/pull/2275/files) 
* [Azure Pipelines output from the PR](https://dev.azure.com/webhint/webhint/_build/results?buildId=3582&view=logs&jobId=a76d2200-8b5d-5670-bd30-855ba389b65c&taskId=5cb11de7-248f-51fb-f42c-f9fc6c2fa06c&lineStart=237&lineEnd=238&colStart=1&colEnd=1)

**Comment by tsiegleauq** [comment]
I can try to confirm it on Monday. In that case, this issue should be either reponened or the documentation has to be adjusted
