### ISSUE TITLE
Get cells "effective" value

### ISSUE THREAD

**Issue by tim-field** [exceljs/exceljs#777]
For any given cell I would like its value as a native JS type.  i.e. a string, number or date object.

At the moment if I call cell.value I could get a different result based on the type.  If I have a formula then I get an object  with keys `sharedFormula` and `result` for other cells  I could get a plain string, a number or I could get a date object.

It's not clear to me how I should resolve these "values" down to a plain JS object, 

I see I can call cell.type or cell.effectiveType which returns an int, that corresponds to an internal enum value, but its not clear to me how I can export this enum type to my app in order to resolve a plain value, so I'm currently resorting to duck-typing.

```JS
const resolvedValue =
        cell.value && typeof cell.value === "object" && "result" in cell.value
          ? cell.value.result
          : cell.value
```
:-1: 

This must be a very common requirement ? I'm coming from xlsx-js which could simply return results into a two dimensional array `[rowIndex][colIndex]` = value, where value here is the resolved visible value in the spreadsheet.

P.S. the only way to tell what I can do on a cell is by reading the source, is there any API level documentation anywhere ?

**Comment by Siemienik** [comment]
@tim-field 
```
const resolvedValue =cell.text;
```
should works

https://github.com/exceljs/exceljs/blob/master/lib/doc/cell.js#L196
