### ISSUE TITLE
A parameter initializer is only allowed in a function or constructor implementation

### ISSUE THREAD

**Issue by pramodjaiswalapp** [exceljs/exceljs#779]
Why i am getting this error in node module.
node_modules/exceljs/index.d.ts:787:14 - error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

787  constructor(model: IAnchor|object = {});

**Comment by alubbe** [comment]
Duplicate of https://github.com/exceljs/exceljs/issues/773 - we're working on it
