### ISSUE TITLE
TS2345 when piping workbook data

### ISSUE THREAD

**Issue by Dormanil** [exceljs/exceljs#781]
The code as follows:

```ts
const workbook = new Excel.Workbook();
const excelStream = filesystem.createWriteStream(excelPath);
excelStream.pipe(workbook.xlsx.createInputStream());
```

`Argument of type 'Writable' is not assignable to parameter of type 'WritableStream'.
  Type 'Writable' is missing the following properties from type 'WritableStream': writable, write, end, addListener, and 14 more.ts(2345)`

Am I using the wrong version of Node or what?

**Comment by Estradiaz** [comment]
I guess its more  like  lazy type def: https://github.com/exceljs/exceljs/blob/c6ee7a14d5e0e5a07bf0e475aa4dd7b9a1e907f2/index.d.ts#L3
