### ISSUE TITLE
Get cell in row by column header/name.

### ISSUE THREAD

**Issue by MichaelGatesDev** [exceljs/exceljs#782]
I am working on a project now which uses ExcelJS and as of right now, there is a lot of hardcoding going on which would break if 1 column was inserted. To avoid this, I want to use column names/headers instead of numbers.

For example, I'm doing this right now:

```js
// while iterating over each row in the sheet...
name = row.getCell(1).text;
description = row.getCell(4).text;
```
Notice how I hardcoded column numbers 1 and 4. Instead, I would like to use the column header name like this:

```js
name = row.getCell('Name').text;
description = row.getCell('Description').text;
```

The reason being, I know the spreadsheet is going to add more columns but the column names will never change.

Is there a way to achieve this or does this go against best practices / the point of the library? 

See my project implementation [here](https://github.com/MichaelGatesDev/ccss-support-manual/blob/master/backend/data-helper.js#L30)

**Comment by MichaelGatesDev** [comment]
In the meantime, I've resorted to doing this:

```ts
import Excel = require('exceljs');

class WorksheetWrapper {
    private worksheet: Excel.Worksheet;
    private headers: string[];

    constructor(worksheet: Excel.Worksheet, headersRowIndex: number = 1) {
        this.worksheet = worksheet;
        this.headers = this.getHeaders(headersRowIndex);
    }

    private getHeaders(index: number) {
        let result: string[] = [];

        let row = this.worksheet.getRow(index);

        if (row === null || !row.values || !row.values.length) return [];

        for (let i: number = 1; i < row.values.length; i++) {
            let cell = row.getCell(i);
            result.push(cell.text);
        }
        return result;
    }

    public getCellInRowByColumnHeader(rowNumber: number, header: string) {
        let row = this.worksheet.getRow(rowNumber);
        let result: Excel.Cell | undefined;
        var self = this;
        row.eachCell(function (cell: Excel.Cell, colNumber: number) {
            let fetchedHeader: string = self.headers[colNumber - 1];
            if (fetchedHeader.toLowerCase().trim() === header.toLowerCase().trim()) {
                result = cell;
            }
        });
        return result;
    }
}

export {
    WorksheetWrapper
}
```

**Comment by Siemienik** [comment]
https://github.com/exceljs/exceljs/blob/master/lib/doc/row.js#L56

getCell by column key should work,

did you set columns? 

```
// Add column headers and define column keys and widths
// Note: these column structures are a workbook-building convenience only,
// apart from the column width, they will not be fully persisted.
worksheet.columns = [
    { header: 'Id', key: 'id', width: 10 },
    { header: 'Name', key: 'name', width: 32 },
    { header: 'D.O.B.', key: 'DOB', width: 10, outlineLevel: 1 }
];
```

or:

```
ws.getColumn(1).key='Name';
ws.getColumn(4).key='Description';
```

**Comment by MichaelGatesDev** [comment]
Thank you for that example. I did not know that I had to set the column keys myself . Works well now.

**Comment by skills-surendra** [comment]
Hi ,
I m getting the same issue,
My code is below: 
`
const optionsBestCompression = {
  filename  : filename,
  useStyles: true,
  zip: {
    zlib: { level: 9 },// Sets the compression level.
  },
};
const wb = new Excel.stream.xlsx.WorkbookWriter(optionsBestCompression);
const ws = wb.addWorksheet('blort');

// const style = {
//   font: utils.styles.fonts.comicSansUdB16,
//   alignment: utils.styles.alignments[1].alignment,
// };
ws.columns = [
  { header: 'Id', width: 10, key: 'id' },
  { header: 'Name', width: 10, key: 'name' },
  { header: 'Etc', width: 10, key: 'etc' },
];


ws.getCell('A1').font = {  bold: true};
ws.getCell('B1').font = {  bold: true};
ws.getCell('C1').font = {  bold: true};

// ws.getRow(2).font = utils.styles.fonts.broadwayRedOutline20;
ws.addRow({
  id: 1,
  name: '1.5',
  etc: 'someOtherDetail'
})



wb.commit().then(() => {
  console.log('Done');
});`




I m getting output like : 
![error](https://user-images.githubusercontent.com/40684316/67401209-71a0ae00-f5cc-11e9-9688-56130913fd73.png)

**Comment by Manish-Patidar01** [comment]
> In the meantime, I've resorted to doing this:
> 
> ```ts
> import Excel = require('exceljs');
> 
> class WorksheetWrapper {
>     private worksheet: Excel.Worksheet;
>     private headers: string[];
> 
>     constructor(worksheet: Excel.Worksheet, headersRowIndex: number = 1) {
>         this.worksheet = worksheet;
>         this.headers = this.getHeaders(headersRowIndex);
>     }
> 
>     private getHeaders(index: number) {
>         let result: string[] = [];
> 
>         let row = this.worksheet.getRow(index);
> 
>         if (row === null || !row.values || !row.values.length) return [];
> 
>         for (let i: number = 1; i < row.values.length; i++) {
>             let cell = row.getCell(i);
>             result.push(cell.text);
>         }
>         return result;
>     }
> 
>     public getCellInRowByColumnHeader(rowNumber: number, header: string) {
>         let row = this.worksheet.getRow(rowNumber);
>         let result: Excel.Cell | undefined;
>         var self = this;
>         row.eachCell(function (cell: Excel.Cell, colNumber: number) {
>             let fetchedHeader: string = self.headers[colNumber - 1];
>             if (fetchedHeader.toLowerCase().trim() === header.toLowerCase().trim()) {
>                 result = cell;
>             }
>         });
>         return result;
>     }
> }
> 
> export {
>     WorksheetWrapper
> }
> ```

can you please provide me the example , how to use this code? i have similar requirement.
