### ISSUE TITLE
How to implement multi headers?

### ISSUE THREAD

**Issue by mdmasumbillah** [exceljs/exceljs#785]
I want to header options is 

![Screenshot 2019-04-17 at 16 57 46](https://user-images.githubusercontent.com/17563505/56292714-7b42e800-6149-11e9-8918-05df5e6a2f5d.png)

1. Firstly header create header section.
2. And main sheet headers are under the section header.

**Comment by Siemienik** [comment]
As far as i know, currently the best way is do it manually;) 
https://github.com/exceljs/exceljs/issues/433#issuecomment-343955264
