### ISSUE TITLE
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

### ISSUE THREAD

**Issue by iggyZiggy** [exceljs/exceljs#79]
```
npm -v
3.3.12
```

```
node -v
v5.4.1
```

**Comment by apydo** [comment]
exceljs depends on unzip2 that seems unmaintained for a year. unzip2 has currently a dependency on an old version of fstream that depends on graceful-fs 3.
An updated version of fstream exists and depends on graceful-fs 4, however there is no answer from unzip2 author about that issue.

Any chance you can get rid of this outdated unzip2 dependency ?

BTW : exceljs is a nice work and I really appreciate it. The documentation is well written also.

**Comment by chenop** [comment]
I would like to create a PR for this issue since its failing my CircleCI CI.
Does anyone can advise for an alternative for unzip2?

**Comment by sveinburne** [comment]
Yes please provide a fix ; it's causing lots of problems with bundle tools, such as nexe and fuse-box.
![image](https://user-images.githubusercontent.com/3646758/34121798-8fbc593a-e42a-11e7-892b-725bf6d78b07.png)
