### ISSUE TITLE
Drop node v6 support

### ISSUE THREAD

**Issue by alubbe** [exceljs/exceljs#796]
With v6 out of LTS, should we refactor the code base to >= v8? This could mean trailing commas in functions, native Promises and async/await. I'd be highly in favour in doing this and releasing a new major version - do we have any other breaking changes we could also release or would it be just the node version upgrade?

**Comment by alubbe** [comment]
I just wanted to follow up with some more details about the improved debugging: https://v8.dev/blog/fast-async

And I've been asked about the performance impact of this. In v12, native async/await has caught up:
```
/bluebird $ ./bench doxbee

results for 10000 parallel executions, 1 ms per I/O op

file                                       time(ms)  memory(MB)
callbacks-baseline.js                           167       25.14
callbacks-suguru03-neo-async-waterfall.js       215       40.11
callbacks-caolan-async-waterfall.js             225       46.23
promises-bluebird-generator.js                  229       32.55
promises-bluebird.js                            263       49.07
promises-native-async-await.js                  269       54.89
promises-lvivski-davy.js                        280       89.95
promises-ecmascript6-native.js                  295       64.70
promises-cujojs-when.js                         303       59.53
promises-then-promise.js                        347       72.50
promises-tildeio-rsvp.js                        412       86.03
generators-tj-co.js                             491       62.53
promises-calvinmetcalf-lie.js                   499      139.76
promises-dfilatov-vow.js                        589      133.29
promises-obvious-kew.js                         635      114.16
streamline-generators.js                        687       90.89
promises-medikoo-deferred.js                    737      127.87
observables-pozadi-kefir.js                     799      153.48
streamline-callbacks.js                         945      118.20
observables-Reactive-Extensions-RxJS.js        1235      228.34
promises-kriskowal-q.js                        2762      484.91
observables-caolan-highland.js                 3158      455.48
observables-baconjs-bacon.js.js                4611      815.02

Platform info:
Darwin 18.5.0 x64
Node.JS 12.0.0
V8 7.4.288.21-node.16
Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz × 4
```

**Comment by alubbe** [comment]
Noone? :D

**Comment by alubbe** [comment]
@Siemienik you're clearly excited about this :)
@guyonroche would you be interested in releasing a major version bump to drop v6 support and introduce async/await?

**Comment by Siemienik** [comment]
You are right:)

**Comment by alubbe** [comment]
Should we still produce a transpiled version for node.js? If we do, adding async/await won't be a breaking change, since babel will add its runtime and some polyfills, right?

But I feel as if the standard `require`/`import` should point at our real code and the user should specify something special if they need a transpiled version. What do you all think?

**Comment by Siemienik** [comment]
LGTM if it keeps backwards compatibility

**Comment by Siemienik** [comment]
it's done for now
