### ISSUE TITLE
Impossible to use browser version in TypeScript application

### ISSUE THREAD

**Issue by Pr05p3ro** [exceljs/exceljs#804]
There is some sort of a workaround that allows to import browser build of exceljs
`const Excel = require('exceljs/dist/es5/exceljs.browser');`
but it does not work in a typescript application.
I've solved it for now by changing `"main": "./dist/es5/index.js",` to `"main": "./dist/es5/exceljs.browser.js",` in package.json in fork. In addition to it I had to add `load` method definition to `index.d.ts`. It works, but it is an ugly temporary solution.

I will try to solve this issue without breaking changes and contribute the solution if I succeed.

**Comment by vegarringdal** [comment]
you could add path to tsconfig
```
"paths": {
      "exceljs": ["node_modules/exceljs/dist/exceljs.min"]
    }
```

then load it like this:
`import Excel from "exceljs";`
