### ISSUE TITLE
Can't use this package on browser

### ISSUE THREAD

**Issue by macabeus** [exceljs/exceljs#810]
I'm trying to use `exceljs` on browser to read some XLSX files.
But, when I tried to import using

```js
import Excel from 'exceljs';
```

I received an error on build because can't resolve `fs` module:

```
ERROR in ./node_modules/exceljs/dist/es5/csv/csv.js
Module not found: Error: Can't resolve 'fs' in '/my-project/node_modules/exceljs/dist/es5/csv'
ERROR in ./node_modules/exceljs/dist/es5/utils/utils.js
Module not found: Error: Can't resolve 'fs' in '/my-project/node_modules/exceljs/dist/es5/utils'
ERROR in ./node_modules/exceljs/dist/es5/xlsx/xlsx.js
Module not found: Error: Can't resolve 'fs' in '/my-project/node_modules/exceljs/dist/es5/xlsx'
...
```

Searching about how is the correct way to import on browser, [I found this example](https://github.com/exceljs/exceljs/blob/master/spec/browser/exceljs.spec.js), and following it I tried importing using

```js
const ExcelJS = require('exceljs/dist/es5/exceljs.browser');
```

But this command also didn't work, returning the same errors.

[Also I found a related open issue about this problem.](https://github.com/exceljs/exceljs/issues/510)

Then.... is there a way to import `exceljs` on browser?

**Comment by zypA13510** [comment]
Not sure about ES6 import, but you can certainly use it via the global `ExcelJS` variable.
https://jsfiddle.net/zypA1310/k1h5qp6x/

**Comment by Siemienik** [comment]
https://github.com/exceljs/exceljs/issues/768#issuecomment-487388531

**Comment by Pr05p3ro** [comment]
Actually, my PR should solve your issue too: https://github.com/exceljs/exceljs/pull/806
One line in package.json allows to import browser version when project is built using webpack or any other tool that respects "browser" property. It is merged, but there were no new releases yet.

**Comment by kctang** [comment]
Using the latest release (`^1.11.0`), I am still getting the same error (can't resolve fs).

I am using this library with an Angular 7 project, and also tried with and without the tsconfig path approach:
```
// in package.json
    "exceljs": "^1.11.0",
    "@types/exceljs": "^0.5.3",

// in tsconfig.json
    "paths": {
      "exceljs": [
        "./node_modules/exceljs/dist/es5/exceljs.browser"
      ]
    }

// usage in code
import { Workbook } from 'exceljs'
const workbook = new Workbook()
console.log(workbook)
```

Any hints on how to get this working on a browser nicely for Angular projects?

I can fork and submit PR if you can provide some guidance on potential fix.

**Comment by charllie** [comment]
I solved this by adding:
declare const ExcelJS: any;

and in angular.json:
``
"scripts": [
   ...
   "node_modules/exceljs/dist/exceljs.min.js"
]
``

**Comment by abmj1979** [comment]
hi @charllie 

Where did you add this code to put the build to work?

`declare const ExcelJS: any;`

Best regards

**Comment by charllie** [comment]
You can put this in each component or file where you want to use ExcelJS (and remove for example ``import * as ExcelJS from 'exceljs'``)

**Comment by RRGT19** [comment]
Hi @charllie,
I have followed your advice but, didn't work for me yet. It works locally but not in production (inside a server, Amazon AWS).

I have:
```typescript
import {Injectable} from '@angular/core';

import * as Excel from 'exceljs/dist/exceljs.min.js';
import * as FileSaver from 'file-saver';

const EXCEL_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8';
const EXCEL_EXTENSION = '.xlsx';

declare const ExcelJS: any;

@Injectable({
  providedIn: 'root'
})
export class ExcelService {

  workbook: any;
  worksheet: any;

  constructor() {
    // Create workbook and worksheet
    this.workbook = new Excel.Workbook();

    // Set Workbook Properties
    this.workbook.creator = 'Web';
    this.workbook.lastModifiedBy = 'Web';
    this.workbook.created = new Date();
    this.workbook.modified = new Date();
    this.workbook.lastPrinted = new Date();

    // Add a Worksheet
    this.worksheet = this.workbook.addWorksheet('File');
  }

  public generateExcel() {

    // Title
    const title = 'Excel file example';

    // Add Row
    const titleRow = this.worksheet.addRow([title]);

    // Add blank Row
    this.worksheet.addRow([]);

    // Generate Excel File
    this.workbook.xlsx.writeBuffer().then((data) => {
      const blob = new Blob([data], {type: EXCEL_TYPE});
      // Given name
      FileSaver.saveAs(blob, 'download.xlsx');
    });
  }

}
```

Inside angular.json
`"scripts": ["node_modules/exceljs/dist/exceljs.min.js"]`

Any idea? What I'm doing wrong?

**Comment by abmj1979** [comment]
Change your import to ExcelJS, like this:

`import * as ExcelJS from 'exceljs/dist/exceljs.min.js';`

**Comment by RRGT19** [comment]
> Change your import to ExcelJS, like this:
> 
> `import * as ExcelJS from 'exceljs/dist/exceljs.min.js';`

Hi @abmj1979,
Thanks, it's working now. What I didn't understand is why the line `declare const ExcelJS: any;` should be there.

Also, why we need to add `exceljs.min.js` in **angular.json** if we are already using it as an import in our service.

**Comment by Dahman25** [comment]
Hello,
This work for me in production:
Angular 6, ExcelJS 1.10

import * as ExcelJS from "exceljs/dist/exceljs"

workbook: ExcelJS.Workbook;
 public async export()
{
this.workbook = new ExcelJS.Workbook();
await this.workbook.xlsx.writeBuffer().then((data) => {
                    const file= fileName + this.currentDate + EXCEL_EXTENSION
                    const blob = new Blob([data], { type: EXCEL_TYPE });
                    FileSaver.saveAs(blob, nomDeFichier);
                })
}

**Comment by AntonioEspinosa** [comment]
is it possible to use in  a browser to read a file with no angular, just a single html page referencning the js files?

**Comment by jonalxh** [comment]
@AntonioEspinosa  I have the same question. Could you do it?

**Comment by anl176** [comment]
I have a website that is wrapped in Electron (which uses Node.js apperently, still learning!). The website talks to Electron which uses Exceljs fine with `const Excel = require('exceljs/modern.nodejs');`. It does some work with Exceljs and gives it back to my website.

I want to remove this dependency and have the website use Exceljs itself but I am running into the following error.

![image](https://user-images.githubusercontent.com/53317810/65552434-3d58a580-ded9-11e9-998d-c352f4885a3f.png)

The code is the following

```
var fileName = "xxxxxx";
let workbook = new Excel.Workbook();
workbook.xlsx.readFile(fileName).then(callback);
```

I installed the library through yarn and am requiring it through a custom system. I for sure have `exceljs/dist/exceljs.js` though as the error comes from that file.

I tried the solutions in this thread such as including it via CDN and script from @jonalxh post but I get a `Uncaught Error: Mismatched anonymous define() module:...`. I've looked at other posts but haven't been able to find a solution yet. One person even stated there is no way to use this library outside of a node environment. Any help will be appreciated.

**Comment by kentuo** [comment]
> I have a website that is wrapped in Electron (which uses Node.js apperently, still learning!). The website talks to Electron which uses Exceljs fine with `const Excel = require('exceljs/modern.nodejs');`. It does some work with Exceljs and gives it back to my website.
> 
> I want to remove this dependency and have the website use Exceljs itself but I am running into the following error.
> 
> ![image](https://user-images.githubusercontent.com/53317810/65552434-3d58a580-ded9-11e9-998d-c352f4885a3f.png)
> 
> The code is the following
> 
> ```
> var fileName = "xxxxxx";
> let workbook = new Excel.Workbook();
> workbook.xlsx.readFile(fileName).then(callback);
> ```
> 
> I installed the library through yarn and am requiring it through a custom system. I for sure have `exceljs/dist/exceljs.js` though as the error comes from that file.
> 
> I tried the solutions in this thread such as including it via CDN and script from @jonalxh post but I get a `Uncaught Error: Mismatched anonymous define() module:...`. I've looked at other posts but haven't been able to find a solution yet. One person even stated there is no way to use this library outside of a node environment. Any help will be appreciated.
> 
> EDIT: Using the jsfiddle by @zypA13510 gives me ExcelJS to work with in that inspector. It still fails trying to do `workbook.xlsx.readFile(fileName).then(callback);`. It returns with an object with result `TypeError: e.exists is not a function at https://cdnjs.cloudfare.com/...`

---
because fs module do not in browser.

i only use this package to export xlsx (in Vue), but i think they are the same.
my solution is that,  use **buffer**
```
const wb = new ExcelJS.Workbook()
const ws = wb.addWorksheet('Sheet1')
// --- set ur wordbook content

wb.xlsx.writeBuffer()
.then(buffer => {
  // buffer --> blob
  const blob = new Blob([buffer], { type: "application/vnd.ms-excel" })
  let link = document.createElement('a')
  link.download = 'download.xlsx'
  link.target = 'blank'
  // blob --> url
  link.href = URL.createObjectURL(blob)
  link.click()
})
.catch(err => {
  throw err
})
```
i think u can read the file in buffer, too
```
var workbook = new Excel.Workbook();
workbook.xlsx.load(data)
  .then(function() {
    // use workbook
  });
```

**Comment by katikareddylava** [comment]
> Change your import to ExcelJS, like this:
> 
> `import * as ExcelJS from 'exceljs/dist/exceljs.min.js';`

I am gettting error like "ExcelJS" undefined

**Comment by ccruza** [comment]
Hello everyone. My app **is working** under this configuration:

![image](https://user-images.githubusercontent.com/41245212/75291512-5b139900-57f0-11ea-9907-03f725447daa.png)

![image](https://user-images.githubusercontent.com/41245212/75291564-78486780-57f0-11ea-9dfe-efc4efa2b272.png)

![image](https://user-images.githubusercontent.com/41245212/75291603-8a2a0a80-57f0-11ea-9194-d3526c51e510.png)

![image](https://user-images.githubusercontent.com/41245212/75291634-9910bd00-57f0-11ea-8eb0-d6df1054532e.png)

This is how I declare the workbook:

![image](https://user-images.githubusercontent.com/41245212/75291826-fd338100-57f0-11ea-92f6-f9bab5c3239c.png)


And if You want to download ... it's working with both ways:

![image](https://user-images.githubusercontent.com/41245212/75291734-c8272e80-57f0-11ea-82f9-30ac806e80fd.png)

**Comment by mateo2181** [comment]
@ccruza Could you share me your package.json? I have the same version of exceljs and file-saver but I got the error "Can't resolve fs in ...".
What version of @types/node are you using? Mine is ^12.0.7.

**Comment by ccruza** [comment]
Hello @mateo2181 
Sorry, I've been busy but here is my package.json

`"dependencies": {
    "@agm/core": "^1.0.0",
    "@angular/animations": "^8.2.6",
    "@angular/cdk": "^8.2.0",
    "@angular/common": "^8.2.6",
    "@angular/compiler": "^8.2.6",
    "@angular/core": "^8.2.6",
    "@angular/forms": "^8.2.6",
    "@angular/http": "^7.2.15",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.6",
    "@angular/platform-browser-dynamic": "^8.2.6",
    "@angular/router": "^8.2.6",
    "@asymmetrik/ngx-leaflet": "3.0.1",
    "@auth0/angular-jwt": "^4.0.0",
    "@nebular/auth": "^4.2.2",
    "@nebular/eva-icons": "^4.1.2",
    "@nebular/security": "4.1.2",
    "@nebular/theme": "4.1.2",
    "@swimlane/ngx-charts": "^10.1.0",
    "agm-direction": "^0.7.8",
    "angular-tree-component": "7.2.0",
    "angular2-chartjs": "0.4.1",
    "angular2-signaturepad": "^2.9.0",
    "angular2-toaster": "^7.0.0",
    "bootstrap": "4.3.1",
    "chart.js": "^2.9.3",
    "ckeditor": "4.7.3",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.1",
    "echarts": "^4.3.0",
    "eva-icons": "^1.1.1",
    "exceljs": "^1.12.0",
    "exif-js": "^2.3.0",
    "file-saver": "^2.0.2",
    "intl": "1.2.5",
    "ionicons": "2.0.1",
    "leaflet": "1.2.0",
    "mat-progress-buttons": "^8.0.7",
    "nebular-icons": "1.1.0",
    "ng2-ckeditor": "^1.2.4",
    "ng2-completer": "2.0.8",
    "ng2-smart-table": "1.3.5",
    "ngx-bootstrap": "^5.2.0",
    "ngx-echarts": "^4.2.1",
    "ngx-spinner": "^8.1.0",
    "node-sass": "^4.12.0",
    "normalize.css": "6.0.0",
    "pace-js": "1.0.2",
    "roboto-fontface": "0.8.0",
    "rxjs": "6.5.2",
    "rxjs-compat": "6.3.0",
    "socicon": "3.0.5",
    "sweetalert2": "^9.4.0",
    "tinymce": "4.5.7",
    "tslib": "^1.10.0",
    "typeface-exo": "0.0.22",
    "web-animations-js": "github:angular/web-animations-js#release_pr208",
    "xlsx": "^0.15.5",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.6",
    "@angular/cli": "^8.3.4",
    "@angular/compiler-cli": "^8.2.6",
    "@angular/language-service": "8.0.0",
    "@compodoc/compodoc": "^1.1.11",
    "@fortawesome/fontawesome-free": "^5.10.2",
    "@types/d3-color": "1.0.5",
    "@types/googlemaps": "^3.37.7",
    "@types/jasmine": "2.5.54",
    "@types/jasminewd2": "2.0.3",
    "@types/leaflet": "1.2.3",
    "@types/node": "6.0.90",
    "codelyzer": "^5.1.0",
    "conventional-changelog-cli": "1.3.4",
    "husky": "0.13.3",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "npm-run-all": "4.0.2",
    "protractor": "5.1.2",
    "rimraf": "2.6.1",
    "stylelint": "7.13.0",
    "ts-node": "3.2.2",
    "tslint": "^5.20.0",
    "tslint-language-service": "^0.9.9",
    "typescript": "3.4.5"
  }
`

**Comment by mateo2181** [comment]
Thanks @ccruza ! I solved it using exceljs 3.8.1 and @types/node 12.11.1.

**Comment by echobravo** [comment]
> @AntonioEspinosa It worked for me with this CDN:
> 
> `<script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/1.10.0/exceljs.min.js" integrity="sha256-NwTJQSOPRRgFqw5ol83SU70DgTvXvQ/dFdPcRJoCAFQ=" crossorigin="anonymous"></script>`

@jonalxh can you please provide a working example of reading an Excel file using a browser only with no Angular? I can't seem to get the readFile method to work with this setup.

**Comment by jonalxh** [comment]
Hi @echobravo, when I was using it I just used it to generate a XLSX file and it worked, not reading. In my project it was just with jQuery and the CDN was placed in an HTML file (the common script tag).

**Comment by Siemienik** [comment]
Did you try to use ES5 import version?
https://github.com/exceljs/exceljs/#es5-imports
