### ISSUE TITLE
List of images

### ISSUE THREAD

**Issue by gsanikidze** [exceljs/exceljs#812]
How can i render excel file with images in one column?

Problem is i can't define specific coordinates inside column.

### My Code:
![image](https://user-images.githubusercontent.com/15326244/57570451-18283680-7413-11e9-80d9-c02c8cf08b8f.png)

### Output File:
![image](https://user-images.githubusercontent.com/15326244/57570428-ddbe9980-7412-11e9-993b-a99add6896df.png)

**Comment by HTMHell** [comment]
@gsanikidze did you find a solution? If you did, I would really appreciate if you show a code sample
