### ISSUE TITLE
Distributed package (via NPM) misses modern.*.js files

### ISSUE THREAD

**Issue by daniele-orlando** [exceljs/exceljs#825]
Version: **1.11.0**

```
/modern.browser.js
/modern.nodejs.js
```

are not available when the library is downloaded with NPM
due to the fact that these files are not included in **package.json:files** section.

This means that it is impossible to bundle the library for modern browsers when installed through NPM.

**Comment by abmj1979** [comment]
Hi @daniele-orlando,

did you figure out any way to bundle? i'm stucked in a angular project.

Best regards

**Comment by daniele-orlando** [comment]
Unfortunately not.

**Comment by abmj1979** [comment]
@alubbe would you have some workaround to us for build, while the package don't go for publish?

best regards
