### ISSUE TITLE
Remove require('promish') for modern browsers

### ISSUE THREAD

**Issue by daniele-orlando** [exceljs/exceljs#826]
Version: **1.11.0**

What's the point of requiring *promish* when it is not used in modern browsers?

With the bad effect that the Promish library is bundled and sent to the client even if not used at all, resulting in an increased bundle size.

**Comment by alubbe** [comment]
@guyonroche I was actually wondering the same thing. For node, we don't need it since anything we support (>= v6) has its own Promise library, and for the browser, babel can insert its own polyfill (if necessary).

**Comment by guyonroche** [comment]
Native promises now used from v3.0.0 on
