### ISSUE TITLE
how to read xlsx file in browser with exceljs?

### ISSUE THREAD

**Issue by zlzdp** [exceljs/exceljs#832]
I tried many way, but not work.
help

**Comment by zlzdp** [comment]
I want read xlsx file and parse it in browser.

**Comment by zlzdp** [comment]
I can't find any demo.

**Comment by EliazTray** [comment]
1. get read files.
2. coerce the file object to `ArrayBuffer`(use FileReader)
3. use `workbook.xlsx.load` get workbook intance
4. traverse worksheet.

```html
// i use the vue template
<input type="file" @change="handleChange" />
```

```js
handleChange(e) {
  this.file = e.target.files[0]
},
handleImport() {
  const wb = new Excel.Workbook();
  const reader = new FileReader()

  reader.readAsArrayBuffer(this.file)
  reader.onload = () => {
    const buffer = reader.result;
    wb.xlsx.load(buffer).then(workbook => {
      console.log(workbook, 'workbook instance')
      workbook.eachSheet((sheet, id) => {
        sheet.eachRow((row, rowIndex) => {
          console.log(row.values, rowIndex)
        })
      })
    })
  }
}

**Comment by zlzdp** [comment]
thank you, it's working now.

**Comment by 152016726** [comment]
I get the same confusion. but I want to create a new xlsx and download in browser

**Comment by dm-ibtissam** [comment]
How to the same thing with a csv file please ?

**Comment by Siemienik** [comment]
https://github.com/exceljs/exceljs#reading-csv

**Comment by Olmectron** [comment]
@EliazTray solution isn't working anymore as of 3.7.0. It throws `Error: Chunk must be one of type String, Buffer or StringBuf.` at the `wb.xlsx.load(buffer).` line.

Is there anything to be done now if working on browser side?

**Comment by sohai** [comment]
Yeah there's a bug, sandbox to reproduce issue https://codesandbox.io/s/file-upload-in-react-7ibtx 
I will PR wit the fix

**Comment by beatlecz** [comment]
Which version works?

**Comment by sohai** [comment]
3.6 should work

**Comment by sorz** [comment]
Another approach: use [readable-web-to-node-stream](https://www.npmjs.com/package/readable-web-to-node-stream) to turn `ReadableStream` into `Steam`

```javascript
const file = event.currentTarget.files[0];
const stream = new ReadableWebToNodeStream(file.stream());
const wb = new Excel.Workbook();
await wb.xlsx.read(stream);
```

**Comment by Alfxjx** [comment]
we can use a Promise to wrap the FileReader so that the pipe will be easy to use
```javascript
const fileRes = event.currentTarget.files[0];
function readFile(fileRes) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.readAsArrayBuffer(fileRes)
    reader.onload = () => {
      resolve(reader.result)
    }
  })
}

// ...

const buffer = await readFile(e.target.files[0])
const workbook = new Excel.Workbook()
const file = await workbook.xlsx.load(buffer as Buffer)
const sheet = await file.getWorksheet(sheetName)
sheet.eachRow(function (row, rowNumber) {
  console.log(row.values)
})
```

**Comment by CarlosV-work** [comment]
For exceljs package in angular typescript for browsers
`import { HttpClient } from '@angular/common/http';
import { Workbook } from 'exceljs';
//...
constructor(
    private http: HttpClient
) { }
// ...
public obtenerPlantillaExcel(): void{
    const templateUrl = 'assets/plantillasExcel/plantillaVentas.xlsx';
    const wb = new Workbook();
    const reader = new FileReader();

    this.http.get(templateUrl, {responseType:'blob'}).subscribe({
      next: (data: Blob)=>{
        reader.readAsArrayBuffer(data);
        reader.onload = ()=>{
          const buffer: ArrayBuffer = <ArrayBuffer>reader.result;
          wb.xlsx.load(buffer).then(workbook=>{
            console.log('el load: ',workbook);
            workbook.eachSheet((sheet, id)=>{
              sheet.eachRow((row, rowIndex)=>{
                console.log(row.values, rowIndex);
              });
            });
          });
        }
      }
    });
}`

**Comment by MichaelSlowik** [comment]
Works if:

      const stream = (new ReadableWebToNodeStream(files[0].stream())) as unknown as import("stream").Stream;  
      const workbook:Workbook = new Excel.Workbook();      
      await workbook.xlsx.read(stream);

**Comment by s-light** [comment]
just adding a *modern* example:

```js

async function importFileXLSX_exceljs(file) {
    console.group("importFileXLSX_exceljs", file);
    const buffer = await file.arrayBuffer();
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(buffer);
    // the workbook is now filled...
    
    // fetch sheet by name
    const worksheet = workbook.getWorksheet("data");
    console.log("worksheet", worksheet);
    
    // read data
    worksheet.eachRow(function (row, rowNumber) {
        console.log(`row ${rowNumber}`, row);
        // Iterate over all cells in a row (including empty cells)
        row.eachCell({ includeEmpty: true }, function (cell, colNumber) {
            console.log(`cell ${colNumber} '${cell.value}'`);
        });
    });
    console.groupEnd();
}

```
