### ISSUE TITLE
Reading an xlsx file returns a TypeError

### ISSUE THREAD

**Issue by titivermeesch** [exceljs/exceljs#837]
Hi,

So I'm trying to read a xlsx file that is in the same folder as my Reactjs file, and here is what I got => 

`workbook.xlsx.readFile('data.xlsx').then(function() {
    console.log('File read')
})`

But then I got this error =>
Unhandled Rejection (TypeError): fs.exists is not a function

Can anyone help me with this please

**Comment by kigh-ota** [comment]
Hi @titivermeesch , 

I'm not sure, but maybe you use the js file for browsers by, for example, requiring 'excel.js' or 'dist/exceljs.js' directly.
