### ISSUE TITLE
Duplicate or copy row together with stylings and data

### ISSUE THREAD

**Issue by oalexandru** [exceljs/exceljs#839]
Hello,

Can anybody tell me how can I duplicate a row in a worksheet(I aim for identical rows, meaning stylings, borders, merged cells, data etc).I couldn't find a way.

P.S. What I actually want to achieve is duplicating a row in the middle of the spreadsheet, so that all the rows below are shifted by one row towards the bottom, but I could use only the duplication part, and I can carry on with the shifting afterwards.

Thanks:)

**Comment by dogusev** [comment]
@oalexandru 

https://github.com/exceljs/exceljs#rows

I think this is something you are looking for
```
// remove one row and insert two more.
// Note: rows 4 and below will be shifted down by 1 row.
var newRow3Values = [1,2,3,4,5];
var newRow4Values = ['one', 'two', 'three', 'four', 'five'];
worksheet.spliceRows(3, 1, newRow3Values, newRow4Values);
```

**Comment by Gricardov** [comment]
I'm having the same problem. I want to shift down the content without losing styles :(

**Comment by oalexandru** [comment]
Managed to copy the style, height, borders and values from one row to the other pretty easily with:

currentCell.style = cellToBeShifted.style;
currentCell.value = cellToBeShifted.value;
currentCell.height = cellToBeShifted.height;

but didn't find a way of copying the merging model, so I ended up removing all the merges from the document and applied merging manually after I did the shifting with

worksheet.mergeCells()
