### ISSUE TITLE
How to change worksheet views using the stream API?

### ISSUE THREAD

**Issue by MrHuds0n** [exceljs/exceljs#841]
I would like to add frozen views to a worksheet created using the stream API. However, the following code doesn't work.

```js
  const workbook = new Excel.stream.xlsx.WorkbookWriter({
    filename: 'output.xlsx',
  });

  const worksheet = workbook.addWorksheet('test');

  worksheet.views = {
    state: 'frozen',
    ySplit: 2,
    xSplit: 2,
  };

  worksheet.addRow([1, 2, 3]);

  worksheet.commit();
  workbook.commit();
```

While the row with numbers is added correctly, the worksheet is without any frozen columns.

**Comment by abmj1979** [comment]
Hi,

try assigning the property .view as an array, like the example:

`
views: [
        { zoomScale: 87, zoomScaleNormal: 100, state: 'frozen', ySplit: 4 }
      ]
`

i think you can do like this too:

`  let sheet = workBook.addWorksheet('Estoque', {
      views: [
        { zoomScale: 87, zoomScaleNormal: 100, state: 'frozen', ySplit: 4 }
      ]
    });`

**Comment by MrHuds0n** [comment]
Hi @abmj1979, the second way you listed works, thanks a lot for your help.
