### ISSUE TITLE
Exceljs don't work after build in Angular 7

### ISSUE THREAD

**Issue by abmj1979** [exceljs/exceljs#842]
I have an application built in Angular and it uses exceljs to export some data in .xlsx.

For some reason I do not know, when I generate a project build, exceljs stops working. I found this https://github.com/exceljs/exceljs/issues/825 that refers to a similar problem.

Is there any way to work around the problem until the version that includes the changes is released?

Best regards

**Comment by charllie** [comment]
In my case, exporting with ExcelJS worked in development but not in production (I think there are some issues around Buffer).

However, you can use this little trick to make it work: https://github.com/exceljs/exceljs/issues/810#issuecomment-496447076

**Comment by abmj1979** [comment]
@charllie 

It Worked!!! thanks for the tip!

**Comment by loganathansp** [comment]
Thanks.. work
