### ISSUE TITLE
Is it possible to add image with hyperlink?

### ISSUE THREAD

**Issue by faradaytrs** [exceljs/exceljs#845]
Is it possible to add image with hyperlink?

**Comment by svedbg** [comment]
No it's not possible. What you can do is to grab the remote image and convert it to base64, then insert it in the cell.

**Comment by pkjy** [comment]
Now exceljs can set a hyperlink to a cell, but it can't set a hyperlink on a image.

**Comment by Alanscut** [comment]
yes, it has supported this feature now. please see #1071 , and the usage is described in  [README](https://github.com/exceljs/exceljs#add-image-with-hyperlinks).
