### ISSUE TITLE
xlsx pipe from stream not working 

### ISSUE THREAD

**Issue by Coderwill** [exceljs/exceljs#851]
```
// pipe from stream
var workbook = new Excel.Workbook();
stream.pipe(workbook.xlsx.createInputStream())
.on('data', (data) => {
       // event not triggering...
          console.log(data)
})
```

**Comment by AkiOuma** [comment]
Hi, I met the same question just now, and I have solved it by transferring the stream into a buffer then load it successfully. You can see XLSX Streaming Reader is still in the backlog in readme, hope it can help.
