### ISSUE TITLE
TypeError: worksheet.addRows is not a function

### ISSUE THREAD

**Issue by microqiu** [exceljs/exceljs#86]
npm install exceljs
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
script@0.0.0 /home/linfeiyang/Documents/script
├── blueimp-md5@2.1.0  extraneous
├── exceljs@0.2.4  extraneous
├── moment@2.11.2  extraneous
└── xlsx@0.8.0  extraneous

i get this error when i use it.

**Comment by bluedge** [comment]
I had the same problem. 
I Checked the /lib I have in my node_modules got from npm install exceljs and the git here. On the local /lib/worksheet.js the "addRows" function is simply not part of the Worksheet.prototype .
Before a fix is found you can add this after line 174:
`addRows: function(value) {
    var self = this;
    value.forEach(function(row) {
      self.addRow(row);
    });
  }`

**Comment by ketansp** [comment]
Any updates on this?

**Comment by Reggino** [comment]
Bump, same here.

**Comment by mrdav30** [comment]
bump, i added bluedge's line of code to \exceljs\lib\stream\xlsx\worksheet-writer.js, however trying to stream it doesn't recognize the commit() method

**Comment by kevin-work** [comment]
How has this not been fixed yet?

**Comment by ningmengs** [comment]
i have the same problem,worksheet.addRows is not a function,do you deal it?

**Comment by edwardfelix** [comment]
Any Solutions for this issue?

**Comment by gauravcleartax** [comment]
Facing this issue in 3.4.0 version. Any solution?

**Comment by Siemienik** [comment]
https://github.com/exceljs/exceljs/issues/569
