### ISSUE TITLE
workbook.xlsx.writeBuffer() silently breaks since v1.11.0, only in production

### ISSUE THREAD

**Issue by barbalex** [exceljs/exceljs#871]
I have a hard time believing what is happening to me: After getting error complaints from users I found that exports are silently failing. Only in production. It works fine in dev mode!?

After some debugging I could narrow it down to the `await workbook.xlsx.writeBuffer()` line in this module of mine, as console.log nr. 5 is the last to appear in production:

```js
import * as ExcelJs from 'exceljs/dist/exceljs.min.js'

import getDataArrayFromExportObjects from './getDataArrayFromExportObjects'

export default async ({ data, store }) => {
  console.log('getXlsxBuffer 1')
  const dataArray = getDataArrayFromExportObjects(data)
  console.log('getXlsxBuffer 2', { dataArray })
  const numberOfColumns =
    dataArray && dataArray[0] && dataArray[0].length ? dataArray[0].length : 0
  const workbook = new ExcelJs.Workbook()
  console.log('getXlsxBuffer 3', { workbook })
  const worksheet = workbook.addWorksheet('Daten', {
    views: [
      {
        state: 'frozen',
        xSplit: 0,
        ySplit: 1,
      },
    ],
    autoFilter: {
      from: {
        row: 1,
        column: 1,
      },
      to: {
        row: 1,
        column: numberOfColumns,
      },
    },
  })
  worksheet.addRows(dataArray)
  worksheet.getRow(1).fill = {
    type: 'gradient',
    gradient: 'angle',
    degree: 0,
    stops: [
      { position: 0, color: { argb: 'FFD3D3D3' } },
      { position: 1, color: { argb: 'FFD3D3D3' } },
    ],
  }
  worksheet.getRow(1).font = {
    bold: true,
  }
  worksheet.getRow(1).border = {
    bottom: {
      style: 'thin',
    },
  }
  console.log('getXlsxBuffer 4')
  let buffer
  try {
    console.log('getXlsxBuffer 5')
    buffer = await workbook.xlsx.writeBuffer()
    console.log('getXlsxBuffer 6')
  } catch (error) {
    console.log('getXlsxBuffer, error:', error)
    return store.enqueNotification({
      message: error.message,
      options: {
        variant: 'error',
      },
    })
  }
  console.log('getXlsxBuffer 7', { buffer })
  return buffer
}
```

I then started rolling back versions and found that it works fine in v1.10.0 in production.

Some more info:
- my project: https://github.com/barbalex/apf2
- developed on windows 10, up to date
- Gatsby project
- hosted on zeit/now

**Comment by Galeups** [comment]
Hello. I am agreeing on this. But, why do you close this issue? this is don`t work in a new version 1.12.0.
Thank you @barbalex  it is helped me on my project. I downgraded this package to 1.10.0 version.

**Comment by barbalex** [comment]
@Galeups The closed issue is the one stating that exports did not work in our project. Rolling back exceljs solved that.

The issue with exceljs remains, so _this_ issue should remain open until the issue is resolved.

**Comment by mewild** [comment]
+1

writeBuffer works no problem in my dev environment, as soon as I build to production it breaks.

There is no error created either, the promise doesn't get resolved and the catch doesn't get triggered.

**Comment by drullo** [comment]
Confirmed... I'm having the same issue after updating to version 1.12.2

**Comment by jeff-1984** [comment]
+1
thanks

**Comment by wertie** [comment]
Still having the same problem with version 1.13.0 -- downgrading to 1.10.0 solved the issue. Thank you @barbalex !

**Comment by dooonabe** [comment]
+1
thaaaaaaaanks

**Comment by dooonabe** [comment]
when i use `ng build --prod --base-href /dc/` build my project,this problem occurs，And i use `ng build --aot --base-href /dc/` build my project, it works good.

**Comment by Michelangelo1984** [comment]
1.13.0 Still has this issue, downgraded to 1.10.0 and everything works fine.

**Comment by icaife** [comment]
version: 1.13.0   +1

**Comment by Senneseph** [comment]
I'm also having this problem with this library in Angular+CLI (8.2.0-next.0 atm).  I tried switching to 1.10.0, but I have the same problem.

I think it's a combination of Angular CLI's build process being broken and some quirk with this library.  Like the Promise library used by ExcelJS has been replaced by some kind of empty placeholder function.

Is there anything I can do to research this more on my own?  I'd also like to help get ExcelJS into a more modern module, one that can be tree-shaken by webpack.

**Comment by AriPerkkio** [comment]
I had the same issue on some browsers with version 1.12.0. Adding polyfill for Number.isNaN fixed this issue for me. 
`import 'core-js/features/number/is-nan';`

By comparing version 1.10 and 1.12, it seems that global isNaN was replaced with Number.isNaN for some reason. 
https://github.com/exceljs/exceljs/blob/v1.12.0/lib/csv/csv.js#L71
https://github.com/exceljs/exceljs/blob/v1.10.0/lib/csv/csv.js#L73

**Comment by Senneseph** [comment]
Good catch, @AriPerkkio 

It looks like the 1.12 authors are modernizing the codebase (note the `var`s becoming `const`s and `function` phat aero `() => {}`)

I will try the import this evening.

**Comment by dreamdevil00** [comment]
@AriPerkkio could you please make a pr?

**Comment by AriPerkkio** [comment]
@dreamdevil00 I could but this would require some changes to current eslint settings. Master branch contains 2244 eslint errors so I'd rather not do changes here.

**Comment by GunnerUjjwol** [comment]
The problem persists for me in version 1.13.0.
Will this be fixed in upcoming update?
So that,I dont have to specifically downgrade to 1.10.0

**Comment by jfhdevs** [comment]
Tested today, the problem persists for me in version 1.14.0. (New Features does'nt mention correction of #871).

**Comment by barbalex** [comment]
please solve this issue, I managed to update this dependency (as there is no good way to mark a dependency to not be updated in a package.json file), testing it in dev (works!) and getting error messages from users again :-(

**Comment by Dahman25** [comment]
Hi not working in production ! V1.10 Angular 6 :(

**Comment by matheusfajardo** [comment]
> Hi not working in production ! V1.10 Angular 6 :(

I solved this issue here ->> https://stackoverflow.com/questions/56996774/exceljs-not-working-in-production-in-angular-6

**Comment by Dahman25** [comment]
Hi @matheusfajardo 
When I keep  declare const ExcelJS: any; ! ERROR 
Error: Uncaught (in promise): ReferenceError: ExcelJS is not defined !
my code :
import * as ExcelJS from "exceljs/dist/exceljs.min.js"
declare const ExcelJS: any;

   await workbook.xlsx.writeBuffer().then((data) => {
                    FileSaver.saveAs(blob, fileName);
                })
Angular.json:
 "projects": {
    "Example-app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "sinistre",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "./scripts/libs",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/assets/i18n"
            ],
            "styles": [
              {
               ................
              },
              "src/styles.css"
            ],
            "scripts": [ "node_modules/exceljs/dist/exceljs.min.js" ]
          },...................................
tsconfig.json
   "exceljs": [
        "node_modules/exceljs/dist/exceljs.min.js"
      ]
..........
package.json
  "@angular/cdk": "^6.4.6",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
     "exceljs": "^1.10.0",
     "file-saver": "^2.0.2",

Thank you
Best regards.

**Comment by Dahman25** [comment]
Naw it working in production :
Relpace = > import * as ExcelJS from "exceljs/dist/exceljs.min.js" by  import * as ExcelJS from "exceljs/dist/exceljs"
commente this //declare const ExcelJS: any;

await workbook.xlsx.writeBuffer().then((data) => {
FileSaver.saveAs(blob, fileName);
})

**Comment by weelillad** [comment]
> please solve this issue: I managed to update this dependency (as there is no good way to mark a dependency to not be updated in a package.json file), testing it in dev (works!) and getting error messages from users again :-(

@barbalex You can use `"exceljs": "~1.10.0"` to keep it from updating past 1.10.

Reference: https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept

**Comment by barbalex** [comment]
@weelillad thanks, that helps

**Comment by barbalex** [comment]
Please address this issue. In my eyes it is very dangerous as it bites devs only in production

**Comment by barbalex** [comment]
Related issue: https://github.com/exceljs/exceljs/issues/883

**Comment by barbalex** [comment]
@AriPerkkio I spent two hours trying to install core-js and get `import 'core-js/features/number/is-nan` to work. Sadly it seems that I am not capable of getting this to work. So I will never know it that _would_ have helped

**Comment by AriPerkkio** [comment]
@barbalex You mean you are unable to install the polyfill?
Just run 
```js
npm install core-js
```

Then in your Javascript entrypoint, add
```js
import 'core-js/features/number/is-nan';
```
You can check if installation was success by running script below in IE. If it throws an error, installation was unsuccessful. 
```js
Number.isNaN(10)
```
If your users are using IE11 or below, they will definitely run into this error. Exceljs authors should inform developers about this requirement.

**Comment by barbalex** [comment]
@AriPerkkio yeah, that is what I tried. But I always got an error that `'core-js/features/number/is-nan'` could not be found and that I should `npm i core-js/features/number/is-nan`.

Maybe there needs to be the right configuration in webpack?

Anyway: The problem for me is not a missing shim as exceljs above v1.10.0 breaks for us in up to date chrome.

And thanks a lot for helping.

**Comment by barbalex** [comment]
After trying to update to v2.0.0 I had thought that had solved the issue. Then I ran into this: https://github.com/exceljs/exceljs/issues/948

**Comment by barbalex** [comment]
Closing this as I managed to solve https://github.com/exceljs/exceljs/issues/948. So updating to v2.0.1 works now.

**Comment by viettan66** [comment]
> khi tôi sử dụng `ng build --prod --base-href /dc/`xây dựng dự án của mình, sự cố này xảy ra ， Và tôi sử dụng `ng build --aot --base-href /dc/`xây dựng dự án của mình, nó hoạt động tốt.

Tôi đã thử và dự án của tôi đã hoạt động tốt. cảm ơn nhiều.

**Comment by jfhdevs** [comment]
Pourriez-vous traduire en français ou anglais ?
Would you please translate in french or english ?
