### ISSUE TITLE
how to place worksheet.columns in 2 row 

### ISSUE THREAD

**Issue by Harsimran247** [exceljs/exceljs#875]
I want to place column header in 2nd row and in 1st i want to add some other text.

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/60245378-15b06c00-98ef-11e9-9975-4be90311b9c4.png)

I'm using `worksheet.slice Rows`

**Comment by Harsimran247** [comment]
Hi !
Thanks for the help. I resolved this issue a bit differently. 
Refer this comment : https://github.com/exceljs/exceljs/issues/433#issuecomment-343955264.
This also works.

**Comment by gajus** [comment]
@Harsimran247 I think that suggestion was made before `spliceRows` existed. @yoyo837 suggestion is certainly less intrusive. Just do: `worksheet.spliceRows(1, 0, []);`.
