### ISSUE TITLE
Unable to write unicodes to excel files

### ISSUE THREAD

**Issue by aag035** [exceljs/exceljs#88]
I tried `worksheet.addRow(["John Doe"]).commit();` and it writes the string successfully to excel sheet but when i try `worksheet.addRow(["John Doe", utf8.encode("\u001a")]).commit();`, I get error while opening the excel sheet. Is there any tag or option value which when set, I can write unicodes to excel sheet?

**Comment by kylecannon** [comment]
I am having this issue too. Hoping to find a resolution.

**Comment by MarcusAhlfors** [comment]
Me too

**Comment by phatan** [comment]
Any progress?
