### ISSUE TITLE
bug: malformed comment crashes on write

### ISSUE THREAD

**Issue by aexei** [exceljs/exceljs#880]
My current program reads in an existing .xlsx that contains a few cells with a malformed comment. 

The lib crashes with

Cannot read property 'texts' of undefined
    at module.exports.render (exceljs/lib/xlsx/xform/comment/comment-xform.js:53:20)

I will send a PR with a fix

**Comment by redixhumayun** [comment]
Hi, is there any update on the status of PR? 
I am currently unable to write an XLSX workbook that contains comments. However, if I roll the version back to a stable 1.11.0, my comments are no longer saved when I write the workbook.

**Comment by aexei** [comment]
see #887

**Comment by guyonroche** [comment]
@redixhumayun and @aexei - fix published in v1.14.0 can you verify and close this issue if fixed?
