### ISSUE TITLE
Process doesn't exit < 8.12.0

### ISSUE THREAD

**Issue by murphyproject** [exceljs/exceljs#882]
I had issue closing my app with cmd+x (SIGINT).
The process doesn't close.

Could you please add a note in changelog. The problem appeares in version 1.9.1, because temp package got upgraded.

https://www.npmjs.com/package/tmp

Node Version: < 8.12.0
Package Version: > 1.9.0

Thanks a lot

**Comment by papandreou** [comment]
I also ran into this and brought it up here: https://github.com/exceljs/exceljs/commit/6f589b2557e41440d1632440d144965aee69531b#commitcomment-33747017

The workaround is to downgrade to exceljs 1.10.0 until https://github.com/raszi/node-tmp/pull/193 gets landed 🤷‍♂

**Comment by papandreou** [comment]
Ping @alubbe, given that the latest exceljs is affected, and that it seems to take a while to get that `tmp` issue fixed -- do you think there's anything we can do here? Do you think the cure is worse than the disease?

**Comment by alubbe** [comment]
Let's ask them - ideally, they merge the PR and we have the best of both worlds

**Comment by florianbepunkt** [comment]
This issue still persists. Using the module prevents using sigint signals. This prevents any sort of graceful shutdown procedures when using this module. Further, the node tmp module seems partially ambandoned as maintainers apparently have no permissions to push new versions to npm and there is a major security issue as well: https://github.com/raszi/node-tmp/issues/205

Is there any chance to switch to a different lib for creating tmp directories?

**Comment by ferm10n** [comment]
sub dependencies shouldn't be messing around with high level process lifecycle stuff.

Another workaround for those who want to avoid downgrading exceljs, is to remove the listener created by tmp:
```js
let _tmp$sigint_listener;
const sigintListeners = process.listeners('SIGINT');
for (let listener of sigintListeners) {
    if (listener.name === '_tmp$sigint_listener') { // this is the unique name of the listener function
        _tmp$sigint_listener = listener; // extract and save for later
        process.removeListener('SIGINT', listener);
        break;
    }
}
```

Then in your application's shutdown routine, you can call `_tmp$sigint_listener` whenever you like and are ready to exit.

**Comment by cduff** [comment]
v0.2.0 of tmp has been released which removes its SIGINT handler.

[https://github.com/raszi/node-tmp/blob/HEAD/CHANGELOG.md](https://github.com/raszi/node-tmp/blob/HEAD/CHANGELOG.md)

Should exceljs upgrade to this?

**Comment by alubbe** [comment]
Absolutely! https://github.com/exceljs/exceljs/pull/1234
