### ISSUE TITLE
Cannot export files on IIS Server

### ISSUE THREAD

**Issue by thuxeko** [exceljs/exceljs#883]
Hello.

I used Exceljs to read a file and then put the data in and pack it back to the user. My code is as follows:

`this.http.get('assets/Temp/demo.xlsx', { responseType: 'arraybuffer' })`
      `.subscribe(data => {`
        `var workbook = new Workbook();`
        `console.log('1');`
        `workbook.xlsx.load(data)`
          `.then(function () {`
            `console.log('2');`
            `var worksheet = workbook.getWorksheet("Demo");`
            `worksheet.addRows(lstData);`
            `workbook.xlsx.writeBuffer().then(buff => {`
              `console.log('3');`
            `});`
          `});`
      `});`

When I build the application on my computer, the code runs normally and returns the message in turn: 1-2-3. But when I put the build application on the IIS Server, only the message will appear: 1. There are no error messages displayed on the console screen. I don't know if I did something wrong. I hope everyone will help me. Thanks

**Comment by carolharry** [comment]
This post suggest to downgrade exceljs version to 1.10.0 https://github.com/exceljs/exceljs/issues/871
