### ISSUE TITLE
Macros not updated in the new file on reading and saving the file

### ISSUE THREAD

**Issue by mohanramegowda** [exceljs/exceljs#884]
I am using this package in Angular 7 application to download an excel file from the remote url and update it with some new data in one of the sheet of that file. I am saving the file using file-saver package. 

The file is getting saved with the updated data correctly, but the macros are missing in the saved file. Below is the code i am using:

import * as Excel from "exceljs/dist/exceljs.min.js";
import * as fs from 'file-saver';

createExcelWithExcelJS() {
    let workBook = new Excel.Workbook();
    let subscription = this.http.get("http://localhost:8081/samplefile.xlsx", { responseType: 'blob' })
    .subscribe(value => {
      let blob: Blob = value;
      let reader = new FileReader();

      reader.onload = function (e: any) {
        var contents = e.target.result;
        console.log(contents);
        workBook.xlsx.load(contents).then(data => {
          workBook.getWorksheet("Sheet 3").addRow(["new data", 1, 2, 3])
          workBook.xlsx.writeBuffer().then(data => {
            let blobUpdate = new Blob([data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
            fs.saveAs(blobUpdate, "samplefile.xlsx");
            console.log("Excel Exported successfully");
          });
        });
      };
      reader.readAsArrayBuffer(blob);
    });
  }

**Comment by joyacv2** [comment]
Hi,

Very interesting! Try to change the extension to xlsm, because the macros works this extension.
