### ISSUE TITLE
import Exceljs caused electron application error

### ISSUE THREAD

**Issue by hilanmiao** [exceljs/exceljs#885]
![image](https://user-images.githubusercontent.com/27052900/60582176-df755f80-9dba-11e9-872b-f593554fa289.png)

i used it on my electron appliction, if i use 'exceljs/modern.browser'，then electron-builder made a mistake.

![image](https://user-images.githubusercontent.com/27052900/60582553-a4bff700-9dbb-11e9-9f61-c72853d5bc49.png)

change it，work good。
```
    // import Excel from 'exceljs/modern.browser'
    import Excel from 'exceljs'
```

If you have time, please check this issue，thanks。

**Comment by liqiaolan** [comment]
一样问题
