### ISSUE TITLE
Cannot export excel file on server

### ISSUE THREAD

**Issue by carolharry** [exceljs/exceljs#886]
I have downgraded exceljs to 1.10.0 as suggested by other sites as the file is not download.  Now on the server I get " Bundles?v=lcqaclGHmBykQRmnuQ1uECa-_GIqnj5sIobWGGwpeFM1:1 Uncaught SyntaxError: Setter must have exactly one formal parameter."  The whole site doesn't load at it shows error somewhere related to excelworkbook.  Any help please?

**Comment by fahadjabbar8** [comment]
Use uncompressed file of exceljs rather than minified one and it wil work fine.
