### ISSUE TITLE
showGridLines for printing not working

### ISSUE THREAD

**Issue by qly01** [exceljs/exceljs#891]
I create a worksheet with this code: ` const worksheet = workbook.addWorksheet(sheetName, {
        pageSetup: {
          showGridLines: true,
          fitToPage: true,
          fitToWidth: 1,
          fitToHeight: 0,
          orientation: 'landscape',
          horizontalCentered: true,
          printTitlesRow: '1:1',
        }
      }
    );`
But when I print the excel downloaded, there are no gridLines.
I have tried with every showGridLine properties without success.

**Comment by qly01** [comment]
Nobody have the same issue ?

**Comment by JeeSky** [comment]
me too. it looks like the property "pageSetup" dosen't work well

**Comment by wishlog** [comment]
![image](https://user-images.githubusercontent.com/986511/64756071-122c9880-d560-11e9-9149-b34d2e3f7b7a.png)

This should be the option under Page Layout, not sure if it currently supported under pageSetup

**Comment by fghjfghj** [comment]
My result : the gridLines always showed.

**Comment by Alanscut** [comment]
if you want to control whether gridLines are showed in `View` mode, you should set it with `views`(array) property:
```javascript
var sheet = workbook.addWorksheet('My Sheet', {views: [{showGridLines: false}]});
// or
worksheet.views = [
  {showGridLines: false}
];
```
in `Print` mode, you should set it with `pageSetup`(object) property:
```javascript
var sheet = workbook.addWorksheet('My Sheet', {pageSetup: {showGridLines: false}});
// or
worksheet.pageSetup.showGridLines= false;
```

**Comment by Siemienik** [comment]
@Alanscut great response:)

**Comment by mehrshadFarzaneh** [comment]
this cod:
`worksheet.pageSetup.showGridLines = true;`
not work

> if you want to control whether gridLines are showed in `View` mode, you should set it with `views`(array) property:
> 
> ```js
> var sheet = workbook.addWorksheet('My Sheet', {views: [{showGridLines: false}]});
> // or
> worksheet.views = [
>   {showGridLines: false}
> ];
> ```
> 
> in `Print` mode, you should set it with `pageSetup`(object) property:
> 
> ```js
> var sheet = workbook.addWorksheet('My Sheet', {pageSetup: {showGridLines: false}});
> // or
> worksheet.pageSetup.showGridLines= false;
> ```
