### ISSUE TITLE
Is there any way to embed an image with hyperlink

### ISSUE THREAD

**Issue by pkjy** [exceljs/exceljs#899]
It seems like we can embed image and insert hyperlink.
![image](https://user-images.githubusercontent.com/14119424/61876888-7350cc00-af20-11e9-9586-2abf5db99273.png)

Is there any way to embed an image with hyperlink just like the example below:
![image](https://user-images.githubusercontent.com/14119424/61876593-d3933e00-af1f-11e9-948b-6800fab5d405.png)

**Comment by Alanscut** [comment]
@pkjy now it has supported add image with hyperlinks, please see [README](https://github.com/exceljs/exceljs#add-image-with-hyperlinks)
