### ISSUE TITLE
Unable to read excel file with latest excel js. File Not Found.

### ISSUE THREAD

**Issue by debojyoti19789** [exceljs/exceljs#90]
Unable to read excel file with latest excel js. File is not found.
Getting the following error while trying to read excel files.
I have double checked. The relative path provided is correct.

```
Unhandled rejection Error: File not found: ../TestData/TestData.xlsx
    at C:\Users\xxx\Documents\Eclipse\CSS_Sample\node_modules\exceljs\lib\xlsx\xlsx.js:60:17
    at tryCatcher (C:\Users\xxx\Documents\Eclipse\CSS_Sample\node_modules\exceljs\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xxx\Documents\Eclipse\CSS_Sample\node_modules\exceljs\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (C:\Users\xxx\Documents\Eclipse\CSS_Sample\node_modules\exceljs\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (C:\Users\xxx\Documents\Eclipse\CSS_Sample\node_modules\exceljs\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (C:\Users\xxx\Documents\Eclipse\CSS_Sample\node_modules\exceljs\node_modules\bluebird\js\release\promise.js:684:18)
    at Async._drainQueue (C:\Users\xxx\Documents\Eclipse\CSS_Sample\node_modules\exceljs\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (C:\Users\xxx\Documents\Eclipse\CSS_Sample\node_modules\exceljs\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate](C:UsersxxxDocumentsEclipseCSS_Samplenode_modulesexceljsnode_modulesbluebirdjsreleaseasync.js:16:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)
```

**Comment by RikRakRok** [comment]
I have the same problem.
What do we need to put in 'filename' only name ? Or path ?
Can we have an example ? 

Thanks

**Comment by piyush-sukhadiya** [comment]
I'm also facing same problem since last two days.
ExcelJs version : 0.4.12

**Comment by hemakumark** [comment]
Hi,
I am facing the same issue even though file present in the correct location. Any help is really appreciated.

**Comment by MJavedAli** [comment]
Hi , I am also facing the same issue : 

Code :  

 this.wb.xlsx.readFile('appConfig.xlsx').then(function(sheet){
 url= sheet.getWorksheet('Run_Config').getRow(2).getCell(2).toString();

ERROR :
(node:23852) UnhandledPromiseRejectionWarning: Error: File not found: ./ClientApp/e2e/src/Utils/appConfig.xlsx
C:\Users\xxxl\source\repos\Cert_Flow\Source\VCC.Leopard.Web\ClientApp\node_modules\exceljs\lib\xlsx\xlsx.js:60:17

**Comment by hassanQureshi22** [comment]
I am also having the same issue

**Comment by luiijoquiroz** [comment]
I have solved the problem as follows. 
`const exceljs = require('exceljs');
const fs = require('fs');
const path  = 'path/archive.xlsx'; 
const excel  = fs.realpathSync(path,{encoding:'utf8'});


const wb = new exceljs.Workbook;

wb.xlsx.readFile(excel).then(function(){

    //your code here


}).catch(error => {
console.error('Algo salio mal', error);
});`

**Comment by hassanQureshi22** [comment]
I solved it give the whole path of file

**Comment by ananthforu** [comment]
I too have the same issue and i can't use the absolute path since the script will run from build server behind TFS and the build folder will dynamically change. Any suggestions to provide relative path will help.
My project follows the default folder structure of Angular
Web/App
     -->node_modules
     -->test
              --> specs/module/spec.ts (where I need to pass the excel file path)
              --> data/excel file (where my excel file present)
ExcelJS version used: 1.13.0
Application is in Angular 8.
Note: Absolute path is working and looking for relative path to load the excel file.
Thanks in advance

**Comment by Siemienik** [comment]
```javascript
path.join(__dirname, './relative/path.xlsx');
```

**Comment by Akitektuo** [comment]
If someone has this issue on the client side (I am using React), this is how I solved the issue:
1. Place the static Excel file in the `public` folder
2. Fetch it from your own website
3. Parse the response as a blob to retrieve an array stream that can be used as a buffer
4. Load the stream into the package.

Below you can find a stripped-down version of my code:
```
export const fetchFile = async (url: string): Promise<ArrayBuffer> => {
    const response = await fetch(url);
    const blob = await response.blob();
    const buffer = await blob.arrayBuffer();

    return buffer;
}

export const loadExcel = async (path: string) => {
    const workbook = new ExcelJS.Workbook();
    const excelFile = await fetchFile(`${window.location.origin}/${path}`);
    await workbook.xlsx.load(excelFile);
    return workbook;
}

// Somewhere in the code, where you want the Excel to be loaded
const workbook = await loadExcel("data.xlsx");
```

_Why does this work?_

Placing files in the public folder makes them accessible by their path appended to your website's base URL. I am making use of this to achieve the loading of the excel file. Accessing _{YourApplicationURL}/data.xlsx_ will prompt the browser to download the file.

`window.location.origin` contains the base URL of your application, so in case you have routes, it will only take into account the base route.
