### ISSUE TITLE
Bold text inside cell

### ISSUE THREAD

**Issue by seppe-dalen** [exceljs/exceljs#900]
Is there a way to make a specific part of the a text/string bold?

Example: when giving the value input for a cell: "`<b>`Hello`</b>` World!" this would result in "**Hello** World!" in the given cell.

Some one knows a way to do this with Exceljs?

Thanks!

**Comment by chriscdn** [comment]
Have a look at the section on [Rich Text](https://github.com/exceljs/exceljs#rich-text).  In one example you can see how bold is set.

**Comment by sdd239** [comment]
Ah great! I missed that part.

Thanks

**Comment by chriscdn** [comment]
It seems to be a bit buggy, however.  I need to run more tests, but it seems if you apply bold to cell A1 it bolds everything on the sheet.
