### ISSUE TITLE
我想在浏览器里用，怎么办？

### ISSUE THREAD

**Issue by gezi666** [exceljs/exceljs#912]

**Comment by yoyo837** [comment]
https://unpkg.com/exceljs@1.14.0/dist/exceljs.min.js

`ExcelJS`

**Comment by yoyo837** [comment]
https://unpkg.com/exceljs@1.14.0/dist/exceljs.min.js

`ExcelJS`

**Comment by i365** [comment]
参考这个示例教程
[在浏览器里面使用ExcelJS解析表格文件](https://jstool.gitlab.io/zh-cn/demo/exceljs/)

the problem was resolved.
