### ISSUE TITLE
Travis not working?

### ISSUE THREAD

**Issue by alubbe** [exceljs/exceljs#924]
Hey everyone, is it just me or is travis no longer running/reporting when PRs are opened against this repo? Does anyone know what's causing this?

**Comment by alubbe** [comment]
So travis is actually still running things, but this repository does not seem to be integrated anymore. @guyonroche could you check the settings here on github, maybe the integration is broken?
See https://travis-ci.org/exceljs/exceljs

**Comment by guyonroche** [comment]
@alubbe  Looks ok to me: https://travis-ci.org/exceljs/exceljs/pull_requests
Last build was 3 hours ago from a PR
Just checked the settings and all the default switches are turned on.
Is this still a problem?

**Comment by alubbe** [comment]
yes I think so - all of these recent PRs do not display their travis results:
https://github.com/exceljs/exceljs/pull/933
https://github.com/exceljs/exceljs/pull/930
https://github.com/exceljs/exceljs/pull/929

**Comment by guyonroche** [comment]
Yeah - somewhere between github and travis they changed how all of that stuff integrates. It's now done through GitHub Apps. I've 'purchased' the Travis app for exceljs (free for open source) and hopefully it should start working now.
It's possible that the travis builds need rerunning to be seen in the PR. I'll work through them...

**Comment by alubbe** [comment]
I've started just adding the links manually ;)
Let's keep this ticket open until the next PR gets opened, if that has travis again, I will close this issue

**Comment by guyonroche** [comment]
I think it's all good now, soon as I restart each of the builds in Travis, the results appear in the PR

**Comment by alubbe** [comment]
indeed! thx for fixing this - can I poke you in this direction: https://github.com/exceljs/exceljs/pull/829 ? :D
Closing this issue!
