### ISSUE TITLE
exceljs安装报错，报错如下

### ISSUE THREAD

**Issue by liqiaolan** [exceljs/exceljs#928]
ERROR in ./node_modules/exceljs/lib/csv/csv.js
Module not found: Error: Can't resolve 'fs' in 'E:\tswork\node_modules\exceljs\lib\csv'

报 fs错误，但是依赖的包都安装了

**Comment by A1rPun** [comment]
https://github.com/exceljs/exceljs/issues/915

**Comment by ize8** [comment]
你可能用file-saver在网络浏览器下载文件!

**Comment by A1rPun** [comment]
# 浏览器

该库的一部分已经过隔离测试，可在浏览器环境中使用。

由于工作簿阅读器和工作簿编写器的流媒体特性，因此未包含这些内容。
只能使用基于文档的工作簿（有关详细信息，请参阅<a href="#create-a-workbook">创建Workbook </a>）。

例如，在浏览器中使用ExcelJS的代码，请查看github中的<a href="https://github.com/exceljs/exceljs/tree/master/spec/browser"> spec / browser </a>文件夹回购。
