### ISSUE TITLE
Reading comment/note from xlsx

### ISSUE THREAD

**Issue by mwoz123** [exceljs/exceljs#941]
I'm trying to read a comment (or rather note) from xlsx file. [There's seems to be a difference](https://support.office.com/en-us/article/the-difference-between-threaded-comments-and-notes-75a51eec-4092-42ab-abf8-7669077b7be3)

The field has expected values besides the comment/note.
I was trying to read it with:
`const comment = worksheet.getCell('A1').note` 
but it's undefined :(

Do I need to put any special option to make it work? Is it implemented?

exceljs version: 1.15.0

**Comment by yungcatx** [comment]
Bump. Looking for a solution too.

**Comment by guyonroche** [comment]
Should be fixed in v3.1.0

**Comment by RockMinsk** [comment]
Issue reproduced on v.4.4.0 - existing comments disappear after parsing xlsx file
