### ISSUE TITLE
Excel.js doesn't parse comments/notes. 

### ISSUE THREAD

**Issue by yungcatx** [exceljs/exceljs#944]
### Note screenshot
![image](https://user-images.githubusercontent.com/33134604/64099597-1c41e080-cd83-11e9-8ae1-6bbe649a355f.png)

I'm trying to get these type of comments. 
`worksheet.getCell(1).note`  doesn't work. Same for `cell._value.model.comments.texts`.

Could someone explain how to handle comments/notes with exceljs?

**Comment by mvelluet** [comment]
Same for me. If I add note or comments, my excel file is empty

https://codesandbox.io/s/commentsnote-exceljs-huc5z

**Comment by guyonroche** [comment]
Should be fixed in v3.1.0

**Comment by theodorDiaconu** [comment]
For me it's not working on 4.2.0

**Comment by dinesh761** [comment]
For me it's not working on 4.2.1, Please sort it out this kind of bugs

**Comment by RockMinsk** [comment]
For me it's not working on 4.4.0

**Comment by lyuboslav-lyubenov** [comment]
why is this closed? Im noticing the issue as well, latest version
