### ISSUE TITLE
when copy a sheet from old sheet, the merging style of cell is missing

### ISSUE THREAD

**Issue by lhf552004** [exceljs/exceljs#946]
Hi, I tried to copy the worksheet from an old one. I found the content is copied, but all merging of cell is missing. and some border line is missing, too.

```
const workbook = new Workbook();
workbook.xlsx.load(template).then(() => {
      const templateWorksheet = workbook.getWorksheet('Template');
      datas.forEach(data => {
          let worksheet = workbook.addWorksheet("Sheet");
          worksheet.model = templateWorksheet.model
          worksheet.name = data.bomHeader.number;
      });
      workbook.xlsx.writeBuffer().then((data) => {
          let blob = new Blob([data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });

         saveAs(blob, 'test file.xlsx');

        });
})
```
Here is the template sheet I copy from:
![image](https://user-images.githubusercontent.com/10030850/64325287-6d0f3e80-cffa-11e9-9858-3cd16a2ebd55.png)
And below is the sheet I copied to:
![image](https://user-images.githubusercontent.com/10030850/64325338-887a4980-cffa-11e9-8652-a3845e70cbe8.png)

How can I keep the same from template sheet? thanks

**Comment by tinhnqjp** [comment]
What did you fix this issue ?

**Comment by TranBaVinhSon** [comment]
How can I fixed this problem ?

**Comment by scorpiozj** [comment]
see #292
