### ISSUE TITLE
Cannot find module './lib/config/set-value'

### ISSUE THREAD

**Issue by freevital** [exceljs/exceljs#947]
`Error: Cannot find module './lib/config/set-value'` on version `2.0.0`

**Comment by kotmatpockuh** [comment]
Seems to be appearing only on v2.0.0
and yep... `const setConfigValue = require('./lib/config/set-value');` -> this file is missing

**Comment by kotmatpockuh** [comment]
@alubbe @Siemienik @guyonroche kinda blocker...

**Comment by guyonroche** [comment]
@kotmatpockuh - just pushed v2.0.1 which should fix this. Apologies, I'd forgotten about those files. Can you check and close this if good?

**Comment by guyonroche** [comment]
@freevital could you check whether 2.0.1 fixes your issue?

**Comment by kotmatpockuh** [comment]
> @kotmatpockuh - just pushed v2.0.1 which should fix this. Apologies, I'd forgotten about those files. Can you check and close this if good?

well... app can't start now too :)
I'm digging my code...

**Comment by kotmatpockuh** [comment]
@guyonroche  I guess all imports & usage remains the same as for v1?

**Comment by guyonroche** [comment]
@kotmatpockuh - yes, the main break/reason for major version is the removal of the Promise configuration and dependencies.

**Comment by kotmatpockuh** [comment]
@guyonroche found one more issue with babel... that's why my nestJs app won't start.
According to doc: https://babeljs.io/docs/en/babel-polyfill we should use `require("@babel/polyfill");`, otherwise with the old style `require('babel-polyfill');` app is not starting 😢

Other than that looks fine. Not sure if I have to create a separated issue?

**Comment by kotmatpockuh** [comment]
Would like to close the issue :) but @freevital should do this...

**Comment by freevital** [comment]
This issues was resolved in v2.0.1, but got new issue - https://github.com/exceljs/exceljs/issues/953
