### ISSUE TITLE
autofilter not work in my angular project

### ISSUE THREAD

**Issue by somkatiyar** [exceljs/exceljs#950]
Hey, I m using excel js package for exporting excel from angular application.
everything is work fine excepting one thing which is auto filtering.
When i use auto filter  it cant not work.
Please help me out .

let workbook: ExcelProper.Workbook  = new Excel.Workbook();

   sheet = workbook.addWorksheet(dataKey,
      { views : [
        {state: 'frozen', xSplit: 3}
        ],
        pageSetup: {fitToPage: true, fitToHeight: 5, fitToWidth: 7}
      });
sheet.autoFilter = 'A1:AY1';

**Comment by bleuscyther** [comment]
Install this: https://www.npmjs.com/package/@types/exceljs

**Comment by somkatiyar** [comment]
I m doing the same .Everything work fine in window and mac machine but when excel sheet downloaded on Linux machine, autofilter not work.

**Comment by bleuscyther** [comment]
Ah ok my bad,
i did not have my glass when i was reading i tought you were talking about auto-fill (auto-complete) in the IDE.
What software are you using on Linux to open the file?

**Comment by somkatiyar** [comment]
I m talking about auto filter not auto fill.I m using office libre to open
excell file. Actually i m using exceljs library to  export excel file.

**Comment by bleuscyther** [comment]
Okm another question what is the type of the data being filtered is it date?

**Comment by somkatiyar** [comment]
No its not date, the data which i filtered are string format like state,
district, city etc..
