### ISSUE TITLE
Add a warning that this library cannot work with large files

### ISSUE THREAD

**Issue by gajus** [exceljs/exceljs#956]
Add a warning to README.md that this library does not work with large excel files.

There are tons of related issues https://github.com/exceljs/exceljs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+memory

Finding this is out _after_ finishing is a huge bummer and a big waste of time.

**Comment by gajus** [comment]
For the record, I have migrated to https://github.com/DirtyHairy/node-libxl. It is paid extension. However, it generates large (50MB+) excel files within couple of seconds and with minimal memory footprint.

**Comment by Siemienik** [comment]
Probably using Stream API would approach that.
