### ISSUE TITLE
out of memory exception reading 997kb excel sheet. Pauses at addCellEx from cell matrix.js on readfile

### ISSUE THREAD

**Issue by essuraj** [exceljs/exceljs#967]
[1] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory                                    
00007FF63C63C6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506                                                                        
00007FF63C617416 node::MakeCallback+4534                                                                                                        
00007FF63C617D90 node_module_register+2032                                                                                                      
00007FF63C93189E v8::internal::FatalProcessOutOfMemory+846                                                                                      
00007FF63C9317CF v8::internal::FatalProcessOutOfMemory+639                                                                                      
00007FF63CB17F94 v8::internal::Heap::MaxHeapGrowingFactor+9620                                                                                  
00007FF63CB0EF76 v8::internal::ScavengeJob::operator=+24550                                                                                     
00007FF63CB0D5CC v8::internal::ScavengeJob::operator=+17980                                                                                     
00007FF63CB16317 v8::internal::Heap::MaxHeapGrowingFactor+2327                                                                                  
00007FF63CB16396 v8::internal::Heap::MaxHeapGrowingFactor+2454                                                                                  
00007FF63CC402BB v8::internal::Factory::AllocateRawWithImmortalMap+59                                                                           
00007FF63CC42C2D v8::internal::Factory::NewRawOneByteString+77                                                                                  
00007FF63CC41D99 v8::internal::Factory::NewStringFromOneByte+121                                                                                
00007FF63CC4E093 v8::internal::Factory::NumberToString+307                                                                                      
00007FF63CFD2C13 v8::internal::compiler::JSIntrinsicLowering::simplified+117347                                                                 
0000027B914DC5C1  

I cannot disclose the excel sheet.. Pauses when debugging.. if i continue it works fine.. but gives exception when i run it normally.. and crashes app

**Comment by essuraj** [comment]
non-reproducible i guess

**Comment by sambhav2612** [comment]
@essuraj how did you fix it?

**Comment by essuraj** [comment]
> @essuraj how did you fix it?

Seems like the excel file had some problems, I copied the data into a new file and didn't get any error anymore.
