### ISSUE TITLE
AutoFilter + merge giving an error

### ISSUE THREAD

**Issue by mvelluet** [exceljs/exceljs#970]
Hello,
## Current behaviour 😯
When I created a table and merge something in this table, I got an error when opening the excel file.  
```
Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
Removed Feature: AutoFilter from /xl/tables/table1.xml part (Table)
Removed Feature: Table from /xl/tables/table1.xml part (Table)
```
## Steps to Reproduce 🕹
https://codesandbox.io/s/merge-cells-it88r
In my example, I merge cells A1:A2
Click on the download button, open it and you will get the error

## Expected 🤔
First thing, it is possible to disable AutoFilter?   
If not I would like to disable it or use worksheet without `columns`

## My Environment 🌎
Tech | Version
-- | --
Excel| Microsoft Office Professional Plus 2016
React | 16.6

**Comment by ericklind** [comment]
I'm having this same issue on creating a table. I even tried using the example in the README. 
When I use the example, I get the following error:

```
Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
Repaired Records: Table from /xl/tables/table2.xml part (Table)
```
Anyone know how to get past this? I'd really like to use tables, but I can't even get a basic one to work properly.

**Comment by Alanscut** [comment]
@mvelluet Can you be sure that your excel supports cells in merged tables? My excel doesn't support it. And I disabled automatic filtering, but I also get an error when opening the excel file.

```
Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
Removed Feature: Table from /xl/tables/table1.xml part (Table)
```

### My Environment
|  Tech   | Version  |
|  ----  | ----  |
| Excel  | Microsoft Office Home and Student 2016 |

You can modify the table-xform.js file to disable AutoFilter for verification.

```javascript
// lib\xlsx\xform\table\table-xform.js
prepare(model, options) {
    // this.map.autoFilter.prepare(model);
    this.map.tableColumns.prepare(model.columns, options)
}

render(xmlStream, model) { 
    //  . . .
    // this.map.autoFilter.render(xmlStream, model);
    this.map.tableColumns.render(xmlStream, model.columns);
    this.map.tableStyleInfo.render(xmlStream, model.style);
}
```

**Comment by mvelluet** [comment]
@Alanscut I think you right, it's not supported by excel, at least with my version
Sorry I don't have time to verify your solution, because I changed the library, so I can't help more on this issues

**Comment by benedya** [comment]
hey @mvelluet I'm having a similar issue. Could you please share the library name that worked for you?

**Comment by mvelluet** [comment]
@benedya we use https://www.npmjs.com/package/xlsx-populate. It is not perfect neither but we have solve our use cases
