### ISSUE TITLE
Can not download file when set optimization=true in angular.json file

### ISSUE THREAD

**Issue by xiaosheyu** [exceljs/exceljs#975]
I am using exceljs and file-saver.js in my project, and it worked fine in my dev environment, but when I build in prod env, I could not download file anymore, does anyone help me?

When I set optimization=false in prod configuration, it worked fine.

angular.json

```
"configurations": {
        "production": {
           "fileReplacements": [
                 {
                    "replace": "src/environments/environment.ts",
                    "with": "src/environments/environment.prod.ts"
                 }
                ],
            "optimization": true,
            "outputHashing": "all",
            "sourceMap": false,
            "extractCss": true,
            "namedChunks": false,
            "aot": true,
            "extractLicenses": true,
            "vendorChunk": false,
            "buildOptimizer": true
        },
        "dev": {
            "fileReplacements": [
                 {
                    "replace": "src/environments/environment.ts",
                    "with": "src/environments/environment.dev.ts"
                  }
               ]
            }
        }
```

I find that workbook.xlsx.writeBuffer().then((data) => console.log(1)) i did not print 1 in console.

I want to know:

1. how to fix this problem? I think the config 'optimization' should be 'true';
2. if I set the optimization=false, what will happen?

Thanks very much!

**Comment by xiaosheyu** [comment]
solved：

use 

`import {Woekbook} from 'exceljs/dist/exceljs.js';` 

instead of 

`import {Woekbook} from 'exceljs/dist/exceljs.min.js';`

**Comment by Siemienik** [comment]
I reopen this issue because that case shouldn't happen, it looks like compilation bug
