### ISSUE TITLE
exceljs 3.0.1 and Angular 8 installation issue

### ISSUE THREAD

**Issue by elementalPRESS** [exceljs/exceljs#984]
I love exceljs and with version 2 it was no problem to get it to work with Angular. But after the upgrade to the new major release 3 I can't get it to work anymore. The compilation works fine, but it breaks on starting the application with:

```
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)

```
Does anybody has an idea or solution how this can be fixed so that it runs smoothly again?

Thx and regards,
Lars

**Comment by bleuscyther** [comment]
Same i down graded all my other packages i wasn't sure it was exceljs  until this morning.

**Comment by Siemienik** [comment]
#384 #511 #821 #348 ?

**Comment by elementalPRESS** [comment]
> #384 #511 #821 #348 ?

not really! The problem is a new one. As written in the original posting: exceljs v2.0.1 is working properly. The problem occurs since exceljs v3 (current 3.1.0).

**Comment by IsaacFilarski** [comment]
Is this fixed with release 3.2?

**Comment by noonhe** [comment]
I'm having the same issue with exceljs@3.3.0.
is there any solution?

**Comment by elementalPRESS** [comment]
> delete `import 'zone.js/dist/zone';` from `polyfills.ts`
> 
> append `import 'zone.js/dist/zone';` to `main.ts`. (PS: must the last line)

It might work, but is a really bad idea, because it can destroy angular regular working.

**Comment by noonhe** [comment]
It doesn't work for me.

**Comment by CranMalReign** [comment]
Having the same problem here.  Just started using exceljs and bombs when importing with the same error in ExcelJS 3.2.0

**Comment by elementalPRESS** [comment]
The error still exists with the latest release of ExcelJS 3.5 and all suggested solutions are not feasible. Is there any working solution/fix on the horizon?

**Comment by bleuscyther** [comment]
@elementalPRESS  can you confir m you tried this : https://github.com/exceljs/exceljs/pull/1030#issuecomment-565317523

**Comment by elementalPRESS** [comment]
> @elementalPRESS can you confir m you tried this : [#1030 (comment)](https://github.com/exceljs/exceljs/pull/1030#issuecomment-565317523)

Oh yes I tried, but without any success. BTW. from where comes this exceljs.bare? I have exceljs.min, only...

**Comment by bleuscyther** [comment]
It is in the latest exceljs (3.5.0).

**Comment by CranMalReign** [comment]
> > @elementalPRESS can you confir m you tried this : [#1030 (comment)](https://github.com/exceljs/exceljs/pull/1030#issuecomment-565317523)
> 
> Oh yes I tried, but without any success. BTW. from where comes this exceljs.bare? I have exceljs.min, only...

Same problem. I have installed 3.5 0 and, to the best of my knowledge, followed the linked instructions. I installed regenerator-runtime and made the same file updates listed in the linked comment. I continue to get regenerator-runtime is not defined. I'm using Angular 6.

**Comment by Siemienik** [comment]
anyone of You knows right sollution?

**Comment by CranMalReign** [comment]
I don't have an answer but my project is running out of time waiting for something to work. We need the functionality to add document headers/footers and need it to work in Angular in order to implement a customer critical feature. If we can't get this to work, we are going to have to move on soon.

**Comment by bleuscyther** [comment]
@CranMalReign  Please share your polyfill file and how do you import ExcelJs?  It should work even with Angular 6 with the correct imports and polyfill.js:
https://github.com/exceljs/exceljs/issues/1008#issuecomment-554830311

**Comment by garg10may** [comment]
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.push../node_modules/zone.js/dist/zone.js.Zone.assertZonePatched (zone.js:58)
    at new NgZone (core.js:24212)
    at getNgZone (core.js:24925)
    at PlatformRef.push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModuleFactory (core.js:24823)
    at core.js:24867
    at exceljs.min.js:3

Same, using exceljs : 3.5.0

**Comment by drullo** [comment]
@dim-sniffier's suggestion to move the zone.js import from pollyfills.ts to main.ts worked for me.  My app is an Angular 8.2.14 app.  While it might not be the best idea, as suggested by @elementalPRESS, it is a very minor modification so it's an acceptable work-around for me right now.  In general though, it seems like I always have struggles with excel.js each time I update the Angular version of my apps.  Excel.js seems to be pretty fragile in this regard.

**Comment by dmnrmr** [comment]
Just moving `zone.js` from `polyfills.ts` didn't work for me. I needed to import `exceljs` before `zone.js`. I also decided to pass `exceljs` to `platformBrowserDynamic` as a provided value to later `Inject` it where I need it.

```
import * as exceljs from "exceljs";
import "zone.js/dist/zone";

...

platformBrowserDynamic([
  { provide: "exceljs", useValue: exceljs }
]).bootstrapModule(AppModule);
```

```
...

export class AppComponent  {
  constructor(@Inject("exceljs") private exceljs: unknown) {}
}
```

**Comment by keatkeat87** [comment]
> Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise`

I get this error also in angular 9 and exceljs 3.8 and at the end solve it by few steps, just share here 

step 1 : tsconfig.json
![image](https://user-images.githubusercontent.com/8691013/76142638-86c53780-60aa-11ea-9293-9a7eebf3fa8d.png)
use bare.min, because it don't have dependency.

step 2 : install dependency
![image](https://user-images.githubusercontent.com/8691013/76142666-b8d69980-60aa-11ea-8ecb-1a65d3cc7a19.png)
add to package.json
![image](https://user-images.githubusercontent.com/8691013/76142669-c12ed480-60aa-11ea-89fa-e80437ff3e8d.png)
add to polyfills.ts
![image](https://user-images.githubusercontent.com/8691013/76142679-da378580-60aa-11ea-9758-538f028190c5.png)

step 3 
import in app.component.ts
![image](https://user-images.githubusercontent.com/8691013/76142690-f20f0980-60aa-11ea-9438-cc3926f34149.png)

git repo : https://github.com/keatkeat87/exceljs-angular-9-example

**Comment by ivanlopezmolina** [comment]
Hi @keatkeat87  I'm getting the following error: any idea:

> ERROR in ./src/polyfills.ts
> Module not found: Error: Can't resolve 'core-js/modules/es-promise' in 'C:\project-x\src'
> resolve 'core-js/modules/es-promise' in 'C:\project-x\src'
>   Parsed request is a module
>   using description file: C:\project-x\package.json (relative path: ./src)
>     Field 'browser' doesn't contain a valid alias configuration
>     resolve as module
>

**Comment by vese** [comment]
Moving `import 'zone.js/dist/zone';` to main.ts from polyfills.ts works for Development environment, but fails for Production environment.
For me for Production works next:
1) Add `import 'exceljs';` to polyfills.ts before `import 'zone.js/dist/zone';`
```
import 'exceljs';
import 'zone.js/dist/zone';
```
2) Import needed elements from exceljs and use them in component:
```
import { Workbook } from 'exceljs';
...
const workbook = new Workbook();
const worksheet = workbook.addWorksheet('Orders');
```

**Comment by elementalPRESS** [comment]
The new Version 4.0.1 has fixed the problem and now it seems now to work properly on Angular 9 again (without any changes in zone import etc.)

Thx to the developer for fixing this!

**Comment by keatkeat87** [comment]
v4.0.1 + angular 9 work properly now. thank so much !

**Comment by alubbe** [comment]
Great to hear that! Closing this issue
