### ISSUE TITLE
ERROR in node_modules/exceljs/index.d.ts(1661,34): error TS2503: Cannot find namespace 'NodeJS'.

### ISSUE THREAD

**Issue by aakashjangid** [exceljs/exceljs#997]
Code is failed to compile and giving below error - 
ERROR in node_modules/exceljs/index.d.ts(1661,34): error TS2503: Cannot find namespace 'NodeJS'.

Details - 
exceljs - ^3.3.0
@angular/cli - 7.3.9

I already tried each and every suggestion from everyone, but nothing worked for me.

Need this error to be removed so that code gets compiled successfully.

**Comment by langkydoanh** [comment]
The same issue:
ERROR in node_modules/exceljs/index.d.ts(1661,34): error TS2503: Cannot find namespace 'NodeJS'.
"@angular/cli": "~7.0.4", 
"@types/node": "~8.9.4",
"exceljs": "^3.3.0",

**Comment by srivishalsangepu** [comment]
Failed to compile.

node_modules/exceljs/index.d.ts(1661,34): error TS2503: Cannot find namespace 'NodeJS'.

**Comment by agamgupta6** [comment]
Same error for me 

"@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "exceljs": "^3.3.0",
    "file-saver": "^2.0.2",

**Comment by smithtaylorg** [comment]
I am getting the same error: ERROR in node_modules/exceljs/index.d.ts(1661,34): error TS2503: Cannot find namespace 'NodeJS'. I tried the suggestions in #971, but none of those worked for me. Anyone find a fix yet?  
"exceljs": "^3.3.1"
"core-js": "^2.6.10"
"@angular-devkit/build-angular": "^0.13.9",
"@angular/animations": "^7.2.15",
"@angular/cli": "^7.3.9",
"@angular/common": "^7.2.15",
@angular/compiler": "^7.2.15",
"@angular/compiler-cli": "^7.2.15",
"@angular/core": "^7.2.15",
"@angular/forms": "^7.2.15",
"@angular/http": "^7.2.15",
"@angular/language-service": "^7.2.15",
"@angular/platform-browser": "^7.2.15",
"@angular/platform-browser-dynamic": "^7.2.15",
"@angular/router": "^7.2.15",
"webpack": "^4.41.2"

**Comment by Roncy13** [comment]
same thing goes for me

**Comment by jeanfliu** [comment]
I tried to add `"node"` in _tsconfig.json_、_tsconfig.app.json_ .
![image](https://user-images.githubusercontent.com/17763012/68639665-3c8ada00-0540-11ea-872a-04a1de3e665a.png)

Then got the error:  
> ERROR in node_modules/exceljs/index.d.ts(1661,41): error TS2694: Namespace 'NodeJS' has no exported member 'TypedArray'

-> update `@types/node`

And referenced this https://github.com/exceljs/exceljs/issues/971#issuecomment-541751453, edited my code like below:
```
const Excel = require('exceljs');
const workbook = new Excel.Workbook();
```

It works for me !

**Comment by agamgupta6** [comment]
@jeanfliu Yes, it worked for me also but the drawback is you do not  have type suggestions in editor

**Comment by GustavDjavulen** [comment]
I erase the NodeJS.TypedArray from "index.d.ts" in de "node_modules/exceljs"

that works for me :)

![image](https://user-images.githubusercontent.com/54324708/69768131-f9865480-1144-11ea-8b1d-4b80b38aeb3e.png)

not the best form to fix it but works

**Comment by Alanscut** [comment]
Thanks for opening this request.
Please re-open if you still have issues.
Best of luck.
